### ISSUE TITLE
Review TheDeleteMethod.DeletesRepository test

### ISSUE THREAD

**Issue by shiftkey** [octokit/octokit.net#1002]
For some reason, this test is unable to delete the repository immediately after creating it (it gets a 404).

TODO:

 - is there some period of time we need to wait before we can delete the repository?
 - let's get this test passing again

**Comment by M-Zuber** [comment]
I would like to try this one.

**Comment by shiftkey** [comment]
@M-Zuber let me know what you find out!

**Comment by M-Zuber** [comment]
Lets start with Works On My Machine™...

**Comment by M-Zuber** [comment]
So of appveyor we have spoken. 
Of the rest of this issue we have not

**Comment by M-Zuber** [comment]
@shiftkey @tting you as I remembered to not rely on other notifications

**Comment by Anubhav10** [comment]
@shiftkey this test is passing in VS Tests. Also the repo is being created and deleted. Please give some more details about the problem.

**Comment by devkhan** [comment]
Its passing for me also. Should we un-skip it?

**Comment by shiftkey** [comment]
@Anubhav10 @devkhan if someone wants to submit the PR to unskip it I can verify and close this out.

**Comment by devkhan** [comment]
This should be :closed_lock_with_key: .

**Comment by ryangribble** [comment]
Resolved by #1135
