### ISSUE TITLE
Octokit.NotFoundException : Not Found

### ISSUE THREAD

**Issue by distantcam** [octokit/octokit.net#1010]
Yes thanks for that. Don't tell me what you didn't find.

**Comment by shiftkey** [comment]
This feels like our generic 404 exception (which the API typically returns when a repository doesn't exist) - do you have a snippet that I can use to explore this further?

**Comment by distantcam** [comment]
Yep, so after some digging I found the specific error was when trying to add a label to a repo with credentials that didn't have write access to that repo.

I can email you a script if that'll help.

**Comment by shiftkey** [comment]
@distantcam that'd be great. I can then generalize it and turn this issue into something we can improve more broadly...

**Comment by Haacked** [comment]
> Yep, so after some digging I found the specific error was when trying to add a label to a repo with credentials that didn't have write access to that repo.

So is the issue you want a specific exception?

A lot of our API endpoints return 404 to avoid information disclosure. So we can't tell you that it's an access denied necessarily. We could give an exception specific to the action such as `RepoLabelFailedException`. But I'm not sure that's all that valuable. You kind of know what you were doing, right?

**Comment by distantcam** [comment]
> So is the issue you want a specific exception?

Just a more specific message. `Not Found: 404 trying to retrieve resource https://api.github.com/...[specific endpoint]` would be useful.

> You kind of know what you were doing, right?

![Dog at keyboard with caption "I don't know what I'm doing"](http://ghk.h-cdn.co/assets/cm/15/11/640x480/54ffe5266025c-dog1.jpg)

**Comment by Haacked** [comment]
> Just a more specific message.

Kids these days. Always asking for useful relevant information in exception messages. IN MY DAY WE GOT "Unexpected error occurred" AND WE WERE GRATEFUL AN EXCEPTION EVEN OCCURRED!

:stuck_out_tongue:

**Comment by devkhan** [comment]
I dug through the code and found out that errors are handled in `Connection.HandleErrors()`, which just throws the an `ApiException` if the status code > 400. I can extend it to show a message based on the end-point.

Also, a possible solution is that we provide `HandleError()` with some info about what was requested so that it can throw a more informative message with the exception. Should I do it?

**Comment by ryangribble** [comment]
The ```ApiException``` class already has properties on it that provide the message, status code, array of errors etc.

eg from [ApiExceptionTests.cs](https://github.com/octokit/octokit.net/blob/master/Octokit.Tests/Exceptions/ApiExceptionTests.cs#L47)
``` csharp
[Fact]
public void CreatesGitHubErrorFromJsonResponse()
{
    var response = new Response(
        HttpStatusCode.GatewayTimeout,
        @"{""errors"":[{""code"":""custom"",""field"":""key"",""message"":""key is " +
                @"already in use"",""resource"":""PublicKey""}],""message"":""Validation Failed""}",
        new Dictionary<string, string>(),
        "application/json"
    );

    var exception = new ApiException(response);

    Assert.Equal("Validation Failed", exception.ApiError.Message);
    Assert.Equal("key is already in use", exception.ApiError.Errors.First().Message);
    Assert.Equal(HttpStatusCode.GatewayTimeout, exception.StatusCode);
}
```

**Comment by shiftkey** [comment]
@ryangribble @devkhan maybe we should verify that a 404 exception also has these details - I recall a PR where we were submitting some more information (the raw JSON payload) so let's see what we're getting currently before we close this out...

**Comment by shiftkey** [comment]
@devkhan nah, I don't think it's that complex - try accessing a repository that doesn't exist, for example

**Comment by devkhan** [comment]
Tried deleting a repo without access:

![image](https://cloud.githubusercontent.com/assets/8049092/13727328/19ae074c-e914-11e5-8ec1-16ed5086b192.png)

Tried accessing a repo which doesn't exists:

![image](https://cloud.githubusercontent.com/assets/8049092/13727329/3249dbd2-e914-11e5-8cbb-d031a02ac24c.png)

Should there be any more information?

@distantcam Is this similar to what your were getting or something else?

**Comment by ryangribble** [comment]
You're not actually calling the method properly there... They are async calls so you need to await the result, otherwise you're actually dealing with a ```Task<Repository>```

``` csharp
var result = await client.Repository.Get("octokit", "fake-repo") 
```

You'd need to wrap that in a try/catch then see what data you get on the thrown exception

**Comment by ryangribble** [comment]
Oops sorry I see you did try to say ```.Result``` on the call. I dont think you can really do such async stuff on console/immediate window, hence errors about tasks/no properties etc. 

it's easier to just write an integration test or something so you can execute the actual code fragment "properly"

**Comment by devkhan** [comment]
@ryangribble This is not command window, its `scriptcs` code, so I guess it is showing the correct response. Also, I tried a legit call and the response was correct, so this shouldn't be a problem. Or am I missing something?

**Comment by ryangribble** [comment]
Ah ok... Sorry am on my phone at the moment! 

I see now the first error you posted was saying .Result isn't a valid member...  that's because Delete actually isn't a Task<T> but just a Task. But yes it looks like the exception is still what you wanted to look at 

In both cases the exception you've received, you want to inspect the ApiError objects on it, to see what information is there on the .Message and .Errors (as per that unit test I posted earlier)

**Comment by shiftkey** [comment]
@devkhan @ryangribble The `AggregateException` raised is classic TPL behaviour. You want to have a look at what's set on it's `InnerException` - which seems to be the `404` you're interested in...

**Comment by devkhan** [comment]
Also, I think the `Not Found` is because the GitHub API gives just **"Not Found"** as message on 404.

So, what should be done next?
