### ISSUE TITLE
Review StopsMakingNewRequestsWhenTakeIsFulfilled test

### ISSUE THREAD

**Issue by shiftkey** [octokit/octokit.net#1011]
This seems to trigger for a lot of contributors and builds - most recently #995.

Example failures:

 - https://ci.appveyor.com/project/github-windows/octokit-net/build/0.17.39
 - https://travis-ci.org/octokit/octokit.net/builds/97097413

Let's see if we can understand:

 - why this is occurring
 - whether we can make the test more robust
 - if there's an alternative way to test this (integration test?)

**Comment by alfhenrik** [comment]
Isn't this a duplicate of #904?

**Comment by shiftkey** [comment]
@alfhenrik yes - oops!
