### ISSUE TITLE
Activity -> Events - unclear usage

### ISSUE THREAD

**Issue by shiftkey** [octokit/octokit.net#1016]
The [API docs](https://developer.github.com/v3/activity/events/) have these two events which seem similar, but aren't really:

```
# List repository events
GET /repos/:owner/:repo/events
# List issue events for a repository (issue events have different format)
GET /repos/:owner/:repo/issues/events
```

I can't see that the first resource has been implemented anywhere. The second resource has been implemented as `EventsClient.GetAllForRepository()`.

What I'd like to see done:
- implement the first endpoint as `EventsClient.GetAllForRepository`
- rename the second endpoint as `EventsClient.GetAllIssuesForRepository`
- verify the formats for both endpoints are deserialized correctly

**Comment by Haacked** [comment]
:+1:

**Comment by gabrielweyer** [comment]
I'll take a stab at this.

**Comment by prayankmathur** [comment]
@shiftkey 
@gabrielweyer 
What needs to be done here then ?
I followed your discussion [here](https://github.com/octokit/octokit.net/pull/1017) and since the method is implemented in a different class, do i need to remove it from there, or just have to add the new method in the **EventsClient** class or both ?

**Comment by shiftkey** [comment]
@prayankmathur that's an excellent point - I've called out the three tasks I think need to be done here https://github.com/octokit/octokit.net/pull/1017#issuecomment-166488913 but let me look at the current state of affairs and open fresh issues (rather than this vague one).

I'll leave this open until I have linked to the new tasks here.
