### ISSUE TITLE
Implement Enterprise - Management Console client

### ISSUE THREAD

**Issue by shiftkey** [octokit/octokit.net#1024]
New in GitHub Enterprise 2.4

https://developer.github.com/v3/enterprise/management_console/

```
/enterprise/management_console/
 - POST /setup/api/start
 - POST /setup/api/upgrade
 - GET /setup/api/configcheck
 - POST /setup/api/configure
 - GET /setup/api/settings
 - GET /setup/api/maintenance
 - POST /setup/api/maintenance
 - GET /setup/api/settings/authorized-keys
 - POST /setup/api/settings/authorized-keys
 - DELETE /setup/api/settings/authorized-keys
```

This has some additional security notes, for whoever ends up implementing this:

> You must explicitly set the port number when making API calls to the Management Console. If SSL is enabled on your Enterprise instance, the port number is `8443`; otherwise, the port number is `8080`.
> 
> If you don't want to provide a port number, you'll need to configure your tool to automatically follow redirects.

**Comment by devkhan** [comment]
@ryangribble I would also like to work on this, can I help?

**Comment by ryangribble** [comment]
Do you have access to a GitHub Enterprise environment (this is on premise version of github) ?

**Comment by devkhan** [comment]
I guess not. :cry:

**Comment by ryangribble** [comment]
Yeah if you have a look at the API docs linked above, there are some specific APIs that only the on premises "GitHub Enterprise" supports.  We use GHE at my work so I've been working on fleshing out the support for these.  Happy for anyone to help of course, but obviously there are a few barriers to entry - namely that you have a GitHub Enterprise license!
