### ISSUE TITLE
Implement Migration - Migrations client

### ISSUE THREAD

**Issue by shiftkey** [octokit/octokit.net#1029]
https://developer.github.com/v3/orgs/migrations/

I'm not 100% sure what this is all about, but it's in preview mode so it's not that urgent

[Update]
This API was moved out to a new location in a documentation update on.around the 19 February 2016 
https://developer.github.com/v3/migration/migrations/

**Comment by ryangribble** [comment]
> I'm not 100% sure what this is all about, but it's in preview mode so it's not that urgent

FYI :

https://help.github.com/enterprise/2.4/admin/guides/migrations/about-migrations/
> A migration is the process of transferring data from a source location (either a GitHub.com organization or a GitHub Enterprise instance) to a target GitHub Enterprise instance. Migrations can be used to transfer your data when changing platforms or upgrading hardware on your instance.

**Comment by shiftkey** [comment]
@ryangribble :metal: thanks!

**Comment by ryangribble** [comment]
Similar to #1024 you need to be on GitHub Enterprise to do this one :wink:

**Comment by devkhan** [comment]
@ryangribble Can I still help writing models, requests, tests, etc.?

I know I won't be able to to do integration tests, but still. I'll submit them to your fork.

**Comment by ryangribble** [comment]
Sure, feel free to create all the models classes interfaces and so on and let me know your branch etc.

I wasnt planning on doing this one for a while anyway, as im not really across what these migrations are about (migrating code from one github to another involving zips and files etc i think!) and dont really have a use for them at the moment...  Once I've done the #1024 this issue will be the last major Enterprise API missing, so for completeness sake I do want to do it... but definitely not as a priority

**Comment by ryangribble** [comment]
Implemented by #1141
