### ISSUE TITLE
IRepositoriesClient.Commits -> IRepositoriesClient.Commit

### ISSUE THREAD

**Issue by shiftkey** [octokit/octokit.net#1035]
This is a pluralized interface that we shouldn't really have:

https://developer.github.com/v3/repos/commits/

```csharp
var commit = await github.Repository.Commits.Get("octokit", "octokit.net", "master");
```

We should mark this property as obsolete and introduce a new property which is singular:

```csharp
var commit = await github.Repository.Commit.Get("octokit", "octokit.net", "master");
```

**Comment by M-Zuber** [comment]
:tanabata_tree:
