### ISSUE TITLE
IRepositoriesClient.RepoCollaborators -> IRepositoriesClient.Collaborator

### ISSUE THREAD

**Issue by shiftkey** [octokit/octokit.net#1036]
The prefix is unnecessary, and is a pluralized property that we shouldn't really have:

https://developer.github.com/v3/repos/collaborators/

```csharp
var collaborators = await github.Repository.RepoCollaborators.GetAll("octokit", "octokit.net");
```

We should mark this property as obsolete and introduce a new property which is singular:

```csharp
var collaborators = await github.Repository.Collaborator.GetAll("octokit", "octokit.net");
```

**Comment by M-Zuber** [comment]
I'll take this
