### ISSUE TITLE
IGitHubClient.GitDatabase -> IGitHubClient.Git

### ISSUE THREAD

**Issue by shiftkey** [octokit/octokit.net#1037]
We should align this API with the documentation:

https://developer.github.com/v3/git/

```csharp
var commit = await github.GitDatabase.Blob.Get("octokit", "octokit.net", sha);
```

We should mark this property as obsolete and introduce a new property which is abbreviated:

```csharp
var commit = await github.Git.Blob.Get("octokit", "octokit.net", sha);
```

**Comment by shiftkey** [comment]
Or should we name this `GitData` to match with the section header?

**Comment by M-Zuber** [comment]
Has this been an issue before (conflict of endpoint name in API and section header?)
If there is no precedence, my feeling is to stick with the actual api

**Comment by shiftkey** [comment]
> Has this been an issue before (conflict of endpoint name in API and section header?)

No, just me thinking out loud.

**Comment by RobPethick** [comment]
I'll take this. And implement as Git as I think matching the API is best.

**Comment by M-Zuber** [comment]
Glad someone agrees with me ;)

**Comment by elbaloo** [comment]
This can be closed.

**Comment by Haacked** [comment]
Thanks!
