### ISSUE TITLE
add some tests for Repository.Collaborator

### ISSUE THREAD

**Issue by shiftkey** [octokit/octokit.net#1045]
Reported here: https://github.com/octokit/octokit.net/pull/1040#issuecomment-166945235

> BTW I noticed that there seems to be no tests for this property. Is this on purpose?

It'd be nice to get some integration tests in here - mostly to verify that we're able to retrieve and deserialize details about the collaborators - as a regression test.

**Comment by M-Zuber** [comment]
I'll take this.
(only right as it's my fault it is here :stuck_out_tongue:)

**Comment by M-Zuber** [comment]
okay, so this seems to be quite complicated (and possibly the reason tests were not written previously)
You can not get collaborator data if you do not have push access to the repository.
@shiftkey what do you say?

**Comment by shiftkey** [comment]
@M-Zuber you might be right - from the docs:

>  Otherwise, only users with access to the repository are returned in the collaborators list.

I suspect `pull` wouldn't give you much data, but I haven't looked into it.

To test this out, you could use a newly-created repository and add/remove collaborators from there before tearing it down...

**Comment by M-Zuber** [comment]
Well I guess I am going to sacrifice my user to lots of notifications :) (or make yet another one :)
Hope to get to this soon
