### ISSUE TITLE
Tutorial on creating an issue?

### ISSUE THREAD

**Issue by wdhodges** [octokit/octokit.net#1046]
So I'm trying to use the Octokit.net API in my WPF application but for some reason I can't fully understand how to use the API. I've seen the documentation on creating an issue but I can't figure out how to get it to send, or even authenticate my account to create the issue. Does anyone know of a good tutorial to show this?

**Comment by naveensrinivasan** [comment]
https://github.com/octokit/octokit.net/tree/master/samples/linqpad-samples

https://github.com/octokit/octokit.net/tree/master/docs

These would probably help in getting started.

**Comment by shiftkey** [comment]
@wdhodges @naveensrinivasan the published version of the Getting Started guide is probably worth looking at: 

http://octokitnet.readthedocs.org/en/documentation/getting-started/

There's also a section about Issues 

http://octokitnet.readthedocs.org/en/documentation/issues/

If there's things that you don't find clear, let us know and we can refine them

**Comment by naveensrinivasan** [comment]
@shiftkey  Do we want to add the above link to `README.md`?

**Comment by shiftkey** [comment]
@naveensrinivasan it'll appear when the `documentation` branch has been merged: https://github.com/octokit/octokit.net/tree/documentation#documentation

**Comment by wdhodges** [comment]
Thank you guys for your speed replies!

**Comment by shiftkey** [comment]
As #948 has been merged and the README now has a Documentation section

https://github.com/octokit/octokit.net#documentation

I'm going to close this out.
