### ISSUE TITLE
Support for star creation timestamps

### ISSUE THREAD

**Issue by daveaglick** [octokit/octokit.net#1059]
[The API docs explain](https://developer.github.com/v3/activity/starring/#list-stargazers) that by passing a special `Accept` header (`Accept: application/vnd.github.v3.star+json`) you can have the stargazers list return star creation timestamps (same for getting the repositories starred by a user). This is useful if you're trying to see star behavior over time (I.e., to create a graph or sparkline).

Would there be any opposition to supporting this in Octokit? I'm assuming the best way to represent this would be similar to the result JSON by returning a wrapping object for each row of data that includes the starred at timestamp and the `User` as a property?

If this is a go, I can put a PR together...

**Comment by Haacked** [comment]
:thumbsup:

**Comment by shiftkey** [comment]
> Would there be any opposition to supporting this in Octokit?

No objections here  - and thanks for logging it as it's not something I thought about when doing the API audit!
