### ISSUE TITLE
New Parameters on "List Your Repositories"

### ISSUE THREAD

**Issue by shiftkey** [octokit/octokit.net#1065]
As per the [API documentation](https://developer.github.com/v3/repos/#list-your-repositories) the [RepositoryRequest class](https://github.com/octokit/octokit.net/blob/b9eeed3a8a9411cfe8ae79e2271c4ca9906e723f/Octokit/Models/Request/RepositoryRequest.cs) is missing some options.
The options missing are `visibility` and `affiliation`.

[Read this to get setup for contributing](https://github.com/octokit/octokit.net/blob/master/CONTRIBUTING.md)

Steps to implement:
- Add the following `enum`s
 - Visibility:
    - Public
    - Private
    - All
 - Affiliation: Some of the `Affiliation` enum members have to be decorated with the `Parameter` attribute so they are serialized properly
    - Owner
    - Collaborator
    - OrganizationMember:`[Parameter(Value = "organization_member")]`
    - OwnerAndCollaborator:`[Parameter(Value = "owner, collaborator")]`
    - OwnerAndOrganizationMember:`[Parameter(Value = "owner, organization_member")]`
    - CollaboratorAndOrganizationMember:`[Parameter(Value = "collaborator, organization_member")]`
    - All:`[Parameter(Value = "owner, collaborator, organization_member")]`
  
- Add properties to the `RepositoryRequest` class associated with the enums created earlier.

**Comment by M-Zuber** [comment]
Would you want these done as Enums or strings?

**Comment by shiftkey** [comment]
I'd prefer enums

**Comment by M-Zuber** [comment]
How do you feel about me trying to write this up so it is first-timer friendly?
Otherwise I would like to take it

**Comment by shiftkey** [comment]
I can expand on this - but I'm not sure we have a good example of "multiple enums" elsewhere in the codebase to point to...

**Comment by M-Zuber** [comment]
Don't to the work yet, give me till tomorrow and I'll try and post what I mean.

**Comment by shiftkey** [comment]
:thumbsup:

**Comment by M-Zuber** [comment]
[I made a gist](https://gist.github.com/M-Zuber/6c49f6ad1a77980cfec5). Will add some comments there.

**Comment by M-Zuber** [comment]
pinging @shiftkey

**Comment by shiftkey** [comment]
@M-Zuber those notes seem fine - want me to pull them into the issue description?

**Comment by M-Zuber** [comment]
+1.
Im thinking then we should delete the rest of the comment thread so there is less noise?

**Comment by shiftkey** [comment]
@M-Zuber done

**Comment by Sarmad93** [comment]
I will try to implement this.

**Comment by M-Zuber** [comment]
I realized that tests where not mentioned in this issue.
@shiftkey do you think they should be added as a requirement to the existing PR, or a separate issue opened up?

**Comment by shiftkey** [comment]
@M-Zuber let's see what we can do in the PR. If that doesn't progress, we can extract a task from that like we've done in the past.

**Comment by devkhan** [comment]
Can be closed now.
