### ISSUE TITLE
example of clone a repository

### ISSUE THREAD

**Issue by lbrader** [octokit/octokit.net#1066]
Simple example of cloning a repository to my local box.  

I have been going through the linq samples & integration test.  

Note, I have successfully worked in adding issues to a repository.  And working with repository on github, but I'm struggling in understanding how you do a simple clone in octokit.

thanks

**Comment by shiftkey** [comment]
Unfortunately Octokit is limited by what is available through the GitHub API - there are some Git operations there's no equivalent to "clone" available.

I'd recommend looking at [libgit2sharp](https://github.com/libgit2/libgit2sharp) which is a C# library for working with local repositories. Here's what the clone operation looks like in code:

```csharp
Repository.Clone("https://github.com/libgit2/libgit2sharp.git", "path/to/repo");
```

Or if you need to authenticate:

```csharp
var co = new CloneOptions();
co.CredentialsProvider = (_url, _user, _cred) => new UsernamePasswordCredentials { Username = "Username", Password = "Password" };
Repository.Clone("https://github.com/libgit2/libgit2sharp.git", "path/to/repo", co);
```

There's more examples in their [wiki](https://github.com/libgit2/libgit2sharp/wiki/).

**Comment by lbrader** [comment]
Thanks Brendan, quite helpful redirect.  I have public cloning operation working with libgit2sharp.

I do like Octokit and was quite successful in working directly on GITHUB.    But realized after working trying to branch, fork that I couldn’t get a local copy.

So am I wrong in thinking the rule of thumb is:

-        Use Octokit for manipulating GITHUB directly

-        Use libgit2sharp for manipulating your Local GITHUB Repository.

Larry

**Comment by shiftkey** [comment]
@lbrader that's a pretty accurate way to think about it

**Comment by AraHaan** [comment]
hmm I wonder if libgit2sharp has a way to push changes as well as commit them after adding all changed files ofc?
