### ISSUE TITLE
ReleaseAssetUpload Timeout doesn't work

### ISSUE THREAD

**Issue by onatbas** [octokit/octokit.net#1069]
Hi. 

I'm trying to increase the timeout of my ReleaseAssetUpload object like this:

```
var assetUpload = new ReleaseAssetUpload(
                    trimmed_filename,
                    content_type,
                    archiveContents, 
                    new TimeSpan(1,30,0)
                );
                // Upload the file to release.
                var asset = client.Release.UploadAsset(result, assetUpload).Result;

```

Afaik this means one and a half hours of timeout. Hoewever this doesn't work and my connection is disconnected after a couple of minutes, resulting in:

```
Unhandled Exception: System.AggregateException: One or more errors occurred. ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at GithubReleaser.Program.Main(String[] args) in d:\workspace\GithubReleaseCMD\GithubReleaseCMD\Program.cs:line 121
```

Any idea?

**Comment by naveensrinivasan** [comment]
This is an issue https://github.com/octokit/octokit.net/issues/963 . Here is a workaround https://github.com/fsharp/FAKE/pull/1048

**Comment by onatbas** [comment]
Thank you @naveensrinivasan for pointing me in the right direction. I just needed a quick commandline tool so what I did is that I just added a timeout to the default Http client in the HttpClientAdapter here. I know It's ugly (I had to turn off Code Analysis for that !) but it works for me.

https://github.com/octokit/octokit.net/blob/master/Octokit/Http/HttpClientAdapter.cs

Thanks.
