### ISSUE TITLE
Check if user is a collaborator on repo throws an exception

### ISSUE THREAD

**Issue by hahmed** [octokit/octokit.net#1070]
I am trying to check if a user is a collaborator on a repo.

https://developer.github.com/v3/repos/collaborators/#get

The code I am running is below:

````
var currentUser = await _githubClient.User.Current();

if (currentUser == null)
{
    return HttpNotFound("Current user not found");
}

vm.IsCollaborator = await _githubClient.Repository.RepoCollaborators.IsCollaborator(owner.Login, repository.Name, currentUser.Login);

Which translates to:
vm.IsCollaborator = await _githubClient.Repository.RepoCollaborators.IsCollaborator("octokit", "octokit.net", "hahmed");

````
Assume that I am getting the current user and the context of the code is:

https://github.com/hahmed/Sprint/blob/master/Sprint/Controllers/HomeController.cs#L58

I should get back false - as **hahmed** is not a collaborator on the Octokit.net repo, however I am getting a bad request exception.

````
Must have push access to view repository collaborators.
Exception Details: Octokit.ForbiddenException: Must have push access to view repository collaborators.
````

Even a curl gives me:

````
curl https://api.github.com/repos/octokit/octokit.net/collaborators/hahmed
{
  "message": "Requires authentication",
  "documentation_url": "https://developer.github.com/v3"
}
````

I may be doing the wrong call - but how can I check if a user is a collaborator on a repo? I can probably do something like the below, but that just does not seem right...

````
var allRepos = await _githubClient.Repository.GetAllForCurrent();
vm.IsCollaborator = allRepos.Any(x=> x.FullName == repository.FullName);
````

**Comment by Haacked** [comment]
I think that exception message tells you everything you need to know:

> Must have push access to view repository collaborators.

So unless you have push access to the repository (octokit/octokit.net), you can't view repository collaborators. Try changing the call to a repository that you have access to (such as one of your own) and see if the call succeeds.

**Comment by hahmed** [comment]
Thanks

Looks like I will have to use the code below to check if the current user is a collaborator.

````
var allRepos = await _githubClient.Repository.GetAllForCurrent();
var IsCollaborator = allRepos.Any(x=> x.FullName == repository.FullName);
````
