### ISSUE TITLE
PullRequest missing Milestone property

### ISSUE THREAD

**Issue by Eilon** [octokit/octokit.net#1071]
Related: https://github.com/octokit/octokit.net/issues/910

**Comment by shiftkey** [comment]
Likely an oversight. You can probably reuse the `Milestone` model we use for an issue if someone wants to add this in.

**Comment by Eilon** [comment]
Yeah working on a PR :smile: Had to update some VS stuff to try to get everything to compile (I didn't have the WP8.1 SDK or something).

**Comment by shiftkey** [comment]
> I didn't have the WP8.1 SDK or something

Seems plausible

**Comment by Eilon** [comment]
PR sent out: #1075
