### ISSUE TITLE
tracking TravisCI build issues

### ISSUE THREAD

**Issue by shiftkey** [octokit/octokit.net#1076]
Currently I'm just turning the TravisCI builds on and off again through the portal when something goes awry. That's not great.

Opening this to track these failures better so I don't need to do this as often.

**Comment by shiftkey** [comment]
Timeout? https://gist.github.com/shiftkey/777ce24a06cb1f4c60ca

**Comment by shiftkey** [comment]
"Got a SIGSEGV while executing native code." https://gist.github.com/shiftkey/ab637423fd610e1dc0ce

**Comment by ryangribble** [comment]
Here's a new one we hadn't seen before.  Perhaps just temporary issue communicating with nuget
**[Linux]** The command "nuget restore Octokit-Mono.sln" failed and exited with 139 during .
https://travis-ci.org/octokit/octokit.net/jobs/115926780

**Comment by ryangribble** [comment]
**[Linux]** Timeout

Same as [this one previously](https://github.com/octokit/octokit.net/issues/1076#issuecomment-178228432)

https://travis-ci.org/octokit/octokit.net/jobs/116884393

**Comment by M-Zuber** [comment]
[Linux] "Got a SIGSEGV while executing native code." https://gist.github.com/M-Zuber/7efea02cbf47fb310131982bbfcbd63b
https://travis-ci.org/octokit/octokit.net/builds/129625518

**Comment by dampir** [comment]
[MAC OS] 

> Assertion at metadata.c:3643, condition `ptr' not met

https://gist.github.com/dampir/b96ee54c5153d8b6f5aed65340ba6e9e

https://travis-ci.org/octokit/octokit.net/jobs/136667692

**Comment by shiftkey** [comment]
Nothing really changed in here since 2016 so I'm going to close this out.
