### ISSUE TITLE
Purpose of NewRepositoryWebHook class

### ISSUE THREAD

**Issue by M-Zuber** [octokit/octokit.net#1088]
[This class](https://github.com/octokit/octokit.net/blob/master/Octokit%2FModels%2FRequest%2FNewRepositoryWebHook.cs) does not seem to be used anywhere in the actual code.

Is there implementation missing somewhere? Or am I missing something?

cc'ing @alfhenrik as it seems that he was the contributor of that code.

**Comment by Haacked** [comment]
That's a helper class for when you're implementing a server side web hook target. For example, on gtihub.com you can configure a repository to request a URL every time a new repository is created.

Well, now you need to implement that endpoint. If you happen to be using ASP.NET MVC for example, you could add an action method that accepts this class (and use the JSON model binder) and receive the payload.

We should document this better. Or consider moving to its own library.
