### ISSUE TITLE
.\build FixProjects quirk

### ISSUE THREAD

**Issue by M-Zuber** [octokit/octokit.net#1092]
Somehow I ended up with the situation that the Mono\* projects had files, but the default did not.
Running the script does not fix it.

This may be a freak problem so not worth fixing.

**Comment by M-Zuber** [comment]
So here is the story:
I did a `git pull` on a computer that I had not done so for a while.
For some reason it updated all the `.csproj` files correctly - except for the default.
Weirder is that once I included the files manually - git told me that there were changes in the .csproj - namely lines not in the right place.

So it knew the files existed and where supposed to be included but VS did not.

Is it possible because I had VS open during this whole saga?
oh, btw I am not on Git for Windows fast loop so that should not be the problem #troll

**Comment by ryangribble** [comment]
So just a note on this topic, what ive found is FixProjects will add files from Octokit into all the other projects.  But if you then decide you want to remove that file, the FixProjects command doesnt REMOVE files from the sub projects.  It would be nice for FixProjects to remove files :grinning:

**Comment by Haacked** [comment]
@ryangribble That would be nice. So basically if the file isn't on disk, remove it? I'd love that.

**Comment by Haacked** [comment]
Which reminds me, I started a project called ProjectCop that could handle this. Someday I'll ship it.
