### ISSUE TITLE
Creating a branch

### ISSUE THREAD

**Issue by M-Zuber** [octokit/octokit.net#1098]
Currently (and this is per the API) there is no comfortable way to create a branch.
You have to do something like the following:
```c#
var master = await client.Git.Reference.Get(Helper.UserName, repository.Name, "heads/master");
await client.Git.Reference.Create(Helper.UserName, repository.Name, new NewReference("refs/heads/" + branchName, master.Object.Sha));
```

Is there room to consider creating a wrapper for this?

If so, is there also a way to cut down on the calls? Or would it just be for the users convenience?

**Comment by Haacked** [comment]
> Is there room to consider creating a wrapper for this?

Yes! Probably should be an extension method. That would be a good way to indicate that this is a wrapper and not a 1-1 mapping with an API call.
 
> If so, is there also a way to cut down on the calls? Or would it just be for the users convenience?

Not that I know of. It would be a nice convenience method.

**Comment by M-Zuber** [comment]
Is there a file for such extensions? 
If not where do I put it?

**Comment by Haacked** [comment]
In the `Octokit` project we have a `Helpers` directory. You'll notice we have extension classes in there. For example, in this case, perhaps call it a `ReferenceClientExtensions` or `ReferenceExtensions` or something like that.

**Comment by M-Zuber** [comment]
Where do I put the tests?
The `Helpers` folder in the integration tests projects seems to be for helpers for the tests, so do i just add a test to the file for the `IReferencesClient`?

**Comment by shiftkey** [comment]
@M-Zuber good point. I'm fine with putting them in there for now (we've done the same thing in `Octokit.Tests` but it also has some test classes which confuses things further). Let's keep going down that path and add a new test class for the extensions in `Helpers` for now, we'll clean it up later...

**Comment by M-Zuber** [comment]
@shiftkey [this code](https://github.com/octokit/octokit.net/blob/master/Octokit%2FModels%2FRequest%2FNewReference.cs#L49) could be useful in other places as well. 
Can I /Should I move it into the extension class, create a helper class, or duplicate it?

**Comment by shiftkey** [comment]
@M-Zuber did you mean to link to `GetReference`? If so, yes, I think that's useful to extract somewhere if you'd like to reuse it...

**Comment by M-Zuber** [comment]
:+1:
