### ISSUE TITLE
configure-integration-tests tries to remove a value right after I set it

### ISSUE THREAD

**Issue by shiftkey** [octokit/octokit.net#1104]
This flow around optional values seems counter-intuitive:

>
**[value] found as the configured application Secret
Want to change this? Press Y, otherwise we'll move on:** y
**Change the application Secret to use for the integration tests:** [new-value]
**Want to remove this optional value, press Y:**
```

If the user has pressed `Y` here, `Want to remove...` shouldn't be an option...

**Comment by Anubhav10** [comment]
I have fixed the issue. For an optional value it gives the option to change or remove the value, for a necessary value it doesn't give an option. this is how it looks like now.
![powershell](https://cloud.githubusercontent.com/assets/12119273/13553229/f966064a-e3a7-11e5-9984-c1fce612d8a8.png)

Please tell me if its what you wanted, and I'll send a pull request.

the files at the top has a TODO-" # TODO: this should indicate whether a variable is required or optional." It indicates if the property if required or optional when setting the value, where else should it indicate?

**Comment by shiftkey** [comment]
@Anubhav10 that sounds like it's on the right track - I'd love to review the work you've done here...
