### ISSUE TITLE
improve streaming behaviour of Observable endpoints

### ISSUE THREAD

**Issue by shiftkey** [octokit/octokit.net#1114]
Consider the following snippet:

```
static void Main(string[] args)
{
    Console.WriteLine($"Starting request at {Environment.TickCount}");

    client.PullRequest.GetAllForRepository("github", "gitignore")
        .Subscribe(
            next =>
            {
                Console.WriteLine($"Got #{next.Number} at {Environment.TickCount}");
            },
            () =>
            {
                Console.WriteLine("Done!");
            });

    Console.ReadLine();
}
```

As of Octokit 0.18 this is the resulting output (ticks are in milliseconds):

```
Starting request at 15183359
Got #1185 at 15187250
Got #1310 at 15187250
Got #1331 at 15187250
Got #1326 at 15187250
Got #1400 at 15187250
Got #1402 at 15187250
Got #1409 at 15187250
Got #1401 at 15187250
Got #1404 at 15187250
Got #1439 at 15187250
Got #1457 at 15187250
Got #1451 at 15187250
Got #1268 at 15187250
Got #1480 at 15187250
Got #1483 at 15187250
Got #1491 at 15187250
Got #1495 at 15187250
Got #1490 at 15187250
Got #1258 at 15187250
Got #1478 at 15187250
Got #1504 at 15187250
Got #1314 at 15187250
Got #1425 at 15187250
Got #1528 at 15187250
Got #1552 at 15187250
Got #1524 at 15187250
Got #1596 at 15187250
Got #1597 at 15187250
Got #1598 at 15187250
Got #1606 at 15187250
Got #1602 at 15188375
Got #1614 at 15188375
Got #1616 at 15188375
Got #1623 at 15188375
Got #1624 at 15188375
Got #1634 at 15188375
Got #1636 at 15188390
Got #1643 at 15188390
Got #1644 at 15188390
Got #1646 at 15188390
Got #1649 at 15188390
Got #1549 at 15188390
Got #1655 at 15188390
Got #1665 at 15188390
Got #1669 at 15188390
Got #1560 at 15188390
Got #1575 at 15188390
Got #1589 at 15188390
Got #1684 at 15188390
Got #1682 at 15188390
Got #1663 at 15188390
Got #1548 at 15188390
Got #1664 at 15188390
Got #1658 at 15188390
Got #1702 at 15188390
Got #1707 at 15188390
Got #1717 at 15188390
Got #1729 at 15188390
Got #1674 at 15188390
Got #1731 at 15188390
Got #1736 at 15189281
Got #1424 at 15189281
Got #1745 at 15189296
Got #1749 at 15189296
Got #1746 at 15189296
Got #1750 at 15189296
Got #1758 at 15189296
Got #1764 at 15189296
Got #1765 at 15189296
Got #1767 at 15189296
Got #1239 at 15189296
Got #1770 at 15189296
Got #1776 at 15189296
Got #1777 at 15189296
Got #1781 at 15189296
Got #1796 at 15189296
Got #1559 at 15189296
Got #1550 at 15189296
Got #1498 at 15189296
Got #1807 at 15189296
Got #1811 at 15189296
Got #1823 at 15189296
Got #1802 at 15189296
Got #1395 at 15189296
Got #1520 at 15189296
Got #1586 at 15189296
Got #1648 at 15189296
Got #1468 at 15189296
Got #1677 at 15189296
Got #1539 at 15189296
Got #1422 at 15190031
Got #1386 at 15190031
Got #1450 at 15190031
Got #1452 at 15190031
Got #1635 at 15190031
Got #1721 at 15190031
Got #1455 at 15190031
Got #1667 at 15190031
Got #1782 at 15190031
Got #1603 at 15190031
Got #1839 at 15190031
Got #1840 at 15190031
Got #1489 at 15190031
Got #1768 at 15190031
Got #1845 at 15190031
Got #1149 at 15190031
Got #1850 at 15190031
Got #1724 at 15190031
Got #1612 at 15190031
Got #1444 at 15190031
Got #1601 at 15190046
Got #1759 at 15190046
Got #1726 at 15190046
Got #1673 at 15190046
Got #1565 at 15190046
Got #1672 at 15190046
Got #1454 at 15190046
Got #1686 at 15190046
Got #1863 at 15190046
Got #1861 at 15190046
Got #1543 at 15190609
Got #1866 at 15190609
Got #1763 at 15190609
Got #1867 at 15190609
Got #1868 at 15190609
Got #1869 at 15190609
Got #1870 at 15190609
Got #1871 at 15190609
Got #1872 at 15190609
Got #1853 at 15190609
Got #1783 at 15190609
Done!
```

It's 131 results all up, and note the chunked intervals when receiving a value.

What's interesting here is that the time between starting the request and receiving the first value is **3891ms**, and then the time between the first value and the last value is **3359ms**. These numbers suggest that we're not streaming the results through to the client as we get them, but instead we're completing all the requests (for this scenario it's five pages of results) and then converting the full set of results into an observable.

This behaviour feels natural for the Task-based API we have, but as these are observables (and more friendly for doing asynchronous actions on) I'd like to see if we can refactor the behaviour in [GetPages](https://github.com/octokit/octokit.net/blob/1266ac0f3a366f033061d0c1cc0785bc3c9f5bd3/Octokit.Reactive/Helpers/ConnectionExtensions.cs#L25) to return results as they're received from the API, irrespective of the pagination behaviour of the endpoint.

**Comment by Haacked** [comment]
So the behavior you see is exactly what I'd expect because the API doesn't stream the response to us. What happens is we request page 1, when we get the response, we stream them to the subscriber and make request 2. When that request returns, we stream page 2 and make the request for page 3.

Notice that each timed chunk is 30 results. That's exactly the default page size.

**Comment by shiftkey** [comment]
@Haacked thanks for the extra update. It didn't quite match up with what I was seeing from the network traffic (the delay looked like the cumulative time spent fetching those requests), so here's me embedding some extra tracing against `master`:

<img width="508" alt="screen shot 2016-02-24 at 10 48 32 am" src="https://cloud.githubusercontent.com/assets/359239/13270744/348a0c98-dae4-11e5-92f5-34eb77edcc94.png">

I also felt I ran into this while doing #760 so I'll go back and test that again...

**Comment by Haacked** [comment]
> the delay looked like the cumulative time spent fetching those requests

If that were the case, we'd see a really long delay followed by _every_ item being printed with nearly the same timestamp. Instead, we're seeing timestamps chunked in groups of 30.

**Comment by shiftkey** [comment]
Just tested #760 and this behaviour remains the same. Closing it out as PEBKAC.
