### ISSUE TITLE
[META] Questions about HTTP Extensibility in Octokit

### ISSUE THREAD

**Issue by shiftkey** [octokit/octokit.net#1116]
This is a tracking issue for questions related to the proposal in #984.

You can see an initial proposal for how this might be achieved in #985, but you might have other ideas.

**Comment by shana** [comment]
#### GSoC Students

Make sure you read https://github.com/github/mentorships/issues/101 and http://write.flossmanuals.net/gsocstudentguide/what-is-google-summer-of-code/ and understand how the program works, how proposals are submitted, and all the milestones involved.

**Comment by devkhan** [comment]
Okay, I have read the mentioned issues, I understand about how things have been proceeded so far and agree with all of the points made by @shiftkey and @Haacked. I also get the type of abstractions has been planned. And after almost a week of reading docs, timing out tests, digging through the code, and following related issues transitively(there were too many), I had some thoughts about this particular topic. So, here I go: 

- Too many `ctor`'s - While I was going through the issues, I have seen @shiftkey expressing his views about having already so many `ctor`'s for `GitHubClient` and adding more is not going to help the situation. I think that **default(optional) parameters** can be a possible solution for this. We can something like this:

```csharp
public GitHubClient(
    ProductHeaderValue productInformation, 
    ICredentialStore credentialStore = null, 
    Uri baseAddress = "https://api.github.com",
    IConnection connection = null)
{
    if(credentialStore == null)
    {
         // Instantiate a CredentialStore.
    }
}
```

May be **named parameters** can help here. I don't know about the conventions to be followed here or does this even go well with the use cases.

- Per-request options - @distantcam once [mentioned](https://github.com/octokit/octokit.net/pull/985#issuecomment-163154415) about having per-request basis options. Can we use something a like an `ClientOptions` class which may have options for different types of API to be used, e.g. `Release`, `Gist`, `Issue`, which may have different timeouts and some other options to be passed on `HttpClient`. **Will it be feasible?**

- And there is a completely different thing in my mind. Can we use @paulcbetts [Refit](https://github.com/paulcbetts/refit) for delegating most of our tasks. As we are already talking about having a type of abstraction to de-couple the `HttpClient`, we can completely delegate the HTTP + Serialization work to `Refit`. [Square](square.github.io)'s [Retrofit](https://github.com/square/retrofit) uses a similar kind of abstraction (it uses OkHttp for it HTTP work. I don't know about the performance of `Refit`, maybe @paulcbetts can help. Or, we can fork `Refit` and decouple the HTTP and Serialization work and allow anyone to plug in their ISerializer too (which is also possible right now). 

Note: I know this may sound crazy, but it just occurred to me as I have worked with Retrofit and I really like how its structured.

---------------------
Please, be gentle with me, I am new to this project. I really respect this your opinion, these are just some of my crazy thoughts. And please, provide feedback on this.

**Comment by devkhan** [comment]
@shiftkey Can you please review this now?

**Comment by shiftkey** [comment]
@devkhan

Here's some of my thoughts on this:

- regarding "Too many ctor's" - I believe this we can resolve this as a side-effect of making `HttpClient` a first-class feature. There's a number of `ctor` dependencies in Octokit which we can (and perhaps should) delegate to the HTTP abstraction, such as:

  - `BaseAddress`
  - `Timeout`
  - perhaps even [`Credentials`](https://msdn.microsoft.com/en-us/library/system.net.http.httpclienthandler.credentials(v=vs.118).aspx)?

I wouldn't focus on this area first, but instead keep this in mind as you're exploring how we're using the HTTP stack inside Octokit. 

 - per-request options are still something we'll need to support - but I'd recommend keeping this as simple as possible. A `HttpClient` can set it's own `Timeout` which is applied to all requests (irrespective of what we try and set for each request) so I fear we'll have some issues here troubleshooting just what was set for a request.

 - switching over to Refit or Retrofit means we *might* be able to clean up some of our plumbing, but I don't think it will really help us out here. They use a different set of conventions for organizing things, and the work required to port things over would be orthogonal to this work around letting users provide their own `HttpClient` instance for our HTTP operations.

I guess the thing to bring this thread together is that we've had various requests in the past to be able to plug things into Octokit's HTTP stack, such as [custom caching](https://github.com/tavis-software/Tavis.HttpCache):

```csharp
var httpCache = new HttpCache(new InMemoryContentStore());
var cachingHandler = new HttpCacheHandler(httpClientHandler, httpCache);
var client = new HttpClient(cachingHandler);
...
```

We also introduced following HTTP redirects natively into Octokit in #808 after it became [a feature of the GitHub API](https://developer.github.com/changes/2015-07-21-automatic-redirects-for-renamed-repositories/), so we know we can customize our plumbing to suit - how we let others do the same is what I'd like to solve here...

Hope this helps!

**Comment by devkhan** [comment]
@shiftkey Can we also pull out the serialization part out of Octokit.NET and server as a separate packages? 

I know that users can still pass in an `IJsonSerializer` to provide their own serializer, but if we move the serialization work out of Octokit, others can also contribute community-powered Serialization packages for Octokit, e.g. [Nancy](https://github.com/NancyFx/Nancy/) has different NuGets for different serializers. 

Is it possible? Or is it outside the scope of this project?

**Comment by shiftkey** [comment]
@devkhan we've started a discussion in #1074 about that - the serializations are specific to Octokit's request/response models and the API itself, so I'd love to understand the scenarios and value that extracting it would permit...

**Comment by devkhan** [comment]
Thanks @shiftkey, I'll go through them first.

**Comment by devkhan** [comment]
on the topics of delegating things to `HttpClient`, should `ProductHeaderValue` be specified in the client or not? Since this should be added as a header to every request, I think its better to move in into the client. Users wanting to use other clients, can just add a custom header for this. `IGitHubClient` passes it on to `IConnection` anyways.

/cc @shiftkey

**Comment by shiftkey** [comment]
@devkhan 

> Since this should be added as a header to every request, I think its better to move in into the client.

This seems reasonable, however we need to ensure that [a User-Agent header is set](https://developer.github.com/v3/#user-agent-required).

> I want to discuss this project in detail, and long conversation might not be a good fit here. Can you chat on Gitter?

I'd rather do things publicly wherever possible, as there are others here who are familiar with Octokit and may be able to answer your questions - rather than myself being a blocker. But yes, I can keep an eye on Gitter...

**Comment by devkhan** [comment]
@shiftkey I looked at #985, and it seems like you have done much of the work, e.g. marking obsoletes, creating stubs, etc. So then, how much work is left in this project?

Sidenote: Why didn't you merged that PR?

**Comment by shiftkey** [comment]
> So then, how much work is left in this project?
> Sidenote: Why didn't you merged that PR?

Don't take my previous work as gospel here - I was exploring it and opened the PR to gather feedback. It didn't really get to the point where it was mergeable due to how much is involved with the HTTP stack, but hopefully the lessons learned help out with the work on this PR...

**Comment by devkhan** [comment]
That's good, cause it will be useful as a great reference. :+1:
