### ISSUE TITLE
Question: What is the use of the IJsonSerializer parameter in Connection.cs

### ISSUE THREAD

**Issue by devkhan** [octokit/octokit.net#1119]
I was going through the code, trying to understand the library, and encountered upon the `ctor`s of `Octokit.Connection` class and I'm unable to find any real usage of [this parameter](https://github.com/octokit/octokit.net/blob/master/Octokit%2FHttp%2FConnection.cs#L117), except just ensuring its not null. 

As I'm new to Octokit, can anybody tell me what's the use of it?

**Comment by M-Zuber** [comment]
My best guess is that it was meant to be passed on [here](https://github.com/octokit/octokit.net/blob/master/Octokit%2FHttp%2FConnection.cs#L136)
[That class](https://github.com/octokit/octokit.net/blob/master/Octokit%2FHttp%2FJsonHttpPipeline.cs) controls how serialization happens, but provides a ctor that sets a default implementation, so it seems not passing it on was overlooked.

**Comment by devkhan** [comment]
So, it should be passed on?
Should I open a PR?

**Comment by M-Zuber** [comment]
I would think so. 
A PR is probably a good way to get feedback. 
Worst case scenario you change the PR to remove the parameter from the ctor

**Comment by shiftkey** [comment]
@devkhan we have a large suite of tests which will help catch any unexpected behaviour, so please investigate and see if this can be cleaned up.

**Comment by devkhan** [comment]
@shiftkey @M-Zuber Please, take a look at the mentioned PR @ #1133.
