### ISSUE TITLE
update issue sample to not use octokit repository

### ISSUE THREAD

**Issue by shiftkey** [octokit/octokit.net#1130]
https://github.com/octokit/octokit.net/blob/master/docs/issues.md#create

The placeholders in the code snippet should be something like `"owner"` and `"name"` to indicate that they should be changed (or fail to complete successfully).

cc @rahutchinson who brought this to my attention

**Comment by shiftkey** [comment]
Fixed by #1131

**Comment by rahutchinson** [comment]
:+1:
