### ISSUE TITLE
IUserKeysClient.GetAll -> GetAllForCurrent()

### ISSUE THREAD

**Issue by shiftkey** [octokit/octokit.net#1136]
https://developer.github.com/v3/users/keys/#list-your-public-keys

This is currently marked as obsolete on `ISshKeysClient.GetAllForCurrent()` but has not been ported over. Should be easy to port for both the `ISshKeysClient` and `IObservableSshKeysClient`.

**Comment by ryangribble** [comment]
Is it not the same as this call?

https://github.com/octokit/octokit.net/blob/9e9de4ba74434f18f3ad0a8644ff1ee3f6cc9000/Octokit/Clients/UserKeysClient.cs#L28

**Comment by shiftkey** [comment]
@ryangribble ah, so there's a convention we use here to indicate when a method depends on the current user - we call the method `GetAllForCurrent()` and don't pass in any parameters...

**Comment by ryangribble** [comment]
ok cool, so this task can be simplified to simply renaming ```GetAll()``` to ```GetAllForCurrent()``` on
- ```UserKeysClient```/```IUserKeysClient```
- ```ObservableUserKeysClient```/```IObservableUserKeysClient```
- And the unit and/or integration tests for the above

**Comment by shiftkey** [comment]
@ryangribble looks good to me - I've updated the title to reflect the work necessary

**Comment by M-Zuber** [comment]
I'd like to take this one. Will do it now.
