### ISSUE TITLE
Documentation for getting API information from GitHubClient.

### ISSUE THREAD

**Issue by shiftkey** [octokit/octokit.net#1142]
Add a page to the documentation explaining how to access this. See https://github.com/octokit/octokit.net/pull/855 for the feature as it was implemented.

**Comment by SeanKilleen** [comment]
@shiftkey happy to write this up as I just used it and it seems pretty straightforward.

Do you have a preference for where it should live in the docs? Wasn't sure if it makes sense to devote an entire markdown doc to it or to throw it into `getting-started.md`.

**Comment by ryangribble** [comment]
Noticed this issue was fixed in #1524
