### ISSUE TITLE
Repository Contents API doesn't support Base64 content directly

### ISSUE THREAD

**Issue by shiftkey** [octokit/octokit.net#1143]
As raised in #925, we're making the assumption here that you're interested in publishing a UTF-8 string as your content when you create or update a file. That's not entirely true.

As raised in #925 there's a workaround which is to use the Git Data API - see sample here https://github.com/octokit/octokit.net/issues/925#issuecomment-147390168 - but I'll leave this open to indicate an area where we don't currently support it.

**Comment by laedit** [comment]
If that's ok I want to contribute on this one.

About how to do it,  I think that the simplest is to add an `EncodingType Encoding` property, potentially add the corresponding constructors and remove the `SerializeAsBase64` attribute on `Content` property.

And if you want to avoid any breaking change on this, deal with the base64 in the existing constructors.

What do you think?

**Comment by shiftkey** [comment]
@laedit go for it - there might be some things to catch when serializing/deserialzing but I'm happy to review things and ensure a smooth transition
