### ISSUE TITLE
Add ApiOption overloads to methods on IEventsClient

### ISSUE THREAD

**Issue by shiftkey** [octokit/octokit.net#1153]
As part of completing #760 a number of overloads need to be added to the client interfaces.

As an example, this has been added to [`IReleasesClient`](https://github.com/octokit/octokit.net/commit/03ea83148995711fc47148489e2123e65f33bd82)and [`IObservableReleasesClient`](https://github.com/octokit/octokit.net/commit/aa3ce0db9210b778414e290af7f17c4a646bdeec).

The checklist for porting each method is:

- Add an overload for this method on `IEventsClient` with a new parameter `ApiOptions`
- Implement the new method on the class which implements `IEventsClient`
- Add an overload for this method on `IObservableEventsClient` with a new parameter `ApiOptions`
- Implement the new method on the class which implements `IObservableEventsClient`

This needs to be done for each of these methods:

- [ ] `Task<IReadOnlyList<Activity>> GetAll()`
- [ ] `Task<IReadOnlyList<Activity>> GetAllForAnOrganization(String user, String organization)`
- [ ] `Task<IReadOnlyList<Activity>> GetAllForOrganization(String organization)`
- [ ] `Task<IReadOnlyList<Activity>> GetAllForRepository(String owner, String name)`
- [ ] `Task<IReadOnlyList<Activity>> GetAllForRepositoryNetwork(String owner, String name)`
- [ ] `Task<IReadOnlyList<Activity>> GetAllUserPerformed(String user)`
- [ ] `Task<IReadOnlyList<Activity>> GetAllUserPerformedPublic(String user)`
- [ ] `Task<IReadOnlyList<Activity>> GetAllUserReceived(String user)`
- [ ] `Task<IReadOnlyList<Activity>> GetAllUserReceivedPublic(String user)`

**Comment by devkhan** [comment]
Can be closed now.
