### ISSUE TITLE
Add ApiOption overloads to methods on IReferencesClient

### ISSUE THREAD

**Issue by shiftkey** [octokit/octokit.net#1168]
As part of completing #760 a number of overloads need to be added to the client interfaces.

As an example, this has been added to [`IReleasesClient`](https://github.com/octokit/octokit.net/commit/03ea83148995711fc47148489e2123e65f33bd82)and [`IObservableReleasesClient`](https://github.com/octokit/octokit.net/commit/aa3ce0db9210b778414e290af7f17c4a646bdeec).

The checklist for porting each method is:
- Add an overload for this method on `IReferencesClient` with a new parameter `ApiOptions`
- Implement the new method on the class which implements `IReferencesClient`
- Add an overload for this method on `IObservableReferencesClient` with a new parameter `ApiOptions`
- Implement the new method on the class which implements `IObservableReferencesClient`

This needs to be done for each of these methods:
- [ ] `Task<IReadOnlyList<Reference>> GetAll(String owner, String name)`
- [ ] `Task<IReadOnlyList<Reference>> GetAllForSubNamespace(String owner, String name, String subNamespace)`

**Comment by shiftkey** [comment]
Parking this one because of a bug with the API for `GetAllForSubNamespace`:

```bash
$ new_content=$(curl "https://api.github.com/repos/octokit/octokit.net/git/refs?per_page=5")
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1823  100  1823    0     0   1394      0  0:00:01  0:00:01 --:--:--  1393
$ jq length <<< "$new_content"
5
# note the namespace added here
$ content=$(curl "https://api.github.com/repos/octokit/octokit.net/git/refs/heads?per_page=5")
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5227  100  5227    0     0   3399      0  0:00:01  0:00:01 --:--:--  3398
# the pagination is ignored, everything is returned
$ jq length <<< "$content"                                                                  
14
```

**Comment by hnrkndrssn** [comment]
Just tested this again, and it seems that this bug is still around 😞

**Comment by eatdrinksleepcode** [comment]
Still there.

After 4.5 years, is there any chance of this bug being fixed? Is it worth implementing in the library anyway? It could still be useful.
