### ISSUE TITLE
Add ApiOption overloads to methods on IReleasesClient

### ISSUE THREAD

**Issue by shiftkey** [octokit/octokit.net#1169]
As part of completing #760 a number of overloads need to be added to the client interfaces.

As an example, this has been added to [`IReleasesClient`](https://github.com/octokit/octokit.net/commit/03ea83148995711fc47148489e2123e65f33bd82)and [`IObservableReleasesClient`](https://github.com/octokit/octokit.net/commit/aa3ce0db9210b778414e290af7f17c4a646bdeec).

The checklist for porting each method is:

- Add an overload for this method on `IReleasesClient` with a new parameter `ApiOptions`
- Implement the new method on the class which implements `IReleasesClient`
- Add an overload for this method on `IObservableReleasesClient` with a new parameter `ApiOptions`
- Implement the new method on the class which implements `IObservableReleasesClient`

This needs to be done for each of these methods:

- [x] `Task<IReadOnlyList<Release>> GetAll(String owner, String name)`
- [x] `Task<IReadOnlyList<Release>> GetAll(String owner, String name, ApiOptions options)`
- [ ] `Task<IReadOnlyList<ReleaseAsset>> GetAllAssets(String owner, String name, Int32 id)`

**Comment by dampir** [comment]
I guess here needed update only one method 

`Task<IReadOnlyList<ReleaseAsset>> GetAllAssets(String owner, String name, Int32 id)`

GetAll method is already implemented.

**Comment by shiftkey** [comment]
@dampir  :thumbsup:
