### ISSUE TITLE
Add ApiOption overloads to methods on IRepositoryForksClient

### ISSUE THREAD

**Issue by shiftkey** [octokit/octokit.net#1176]
As part of completing #760 a number of overloads need to be added to the client interfaces.

As an example, this has been added to [`IReleasesClient`](https://github.com/octokit/octokit.net/commit/03ea83148995711fc47148489e2123e65f33bd82)and [`IObservableReleasesClient`](https://github.com/octokit/octokit.net/commit/aa3ce0db9210b778414e290af7f17c4a646bdeec).

The checklist for porting each method is:

- Add an overload for this method on `IRepositoryForksClient` with a new parameter `ApiOptions`
- Implement the new method on the class which implements `IRepositoryForksClient`
- Add an overload for this method on `IObservableRepositoryForksClient` with a new parameter `ApiOptions`
- Implement the new method on the class which implements `IObservableRepositoryForksClient`

This needs to be done for each of these methods:

- [ ] `Task<IReadOnlyList<Repository>> GetAll(String owner, String repositoryName, RepositoryForksListRequest request)`

**Comment by dampir** [comment]
Can be closed now.

**Comment by dampir** [comment]
@shiftkey , @ryangribble 

It is hard to say why, but this client does not have ApiOptions overload at this moment. Please reopen it , I'll deliver ApiOptions overloads here as far as possible.
