### ISSUE TITLE
Add ApiOption overloads to methods on ISshKeysClient

### ISSUE THREAD

**Issue by shiftkey** [octokit/octokit.net#1179]
As part of completing #760 a number of overloads need to be added to the client interfaces.

As an example, this has been added to [`IReleasesClient`](https://github.com/octokit/octokit.net/commit/03ea83148995711fc47148489e2123e65f33bd82)and [`IObservableReleasesClient`](https://github.com/octokit/octokit.net/commit/aa3ce0db9210b778414e290af7f17c4a646bdeec).

The checklist for porting each method is:

- Add an overload for this method on `ISshKeysClient` with a new parameter `ApiOptions`
- Implement the new method on the class which implements `ISshKeysClient`
- Add an overload for this method on `IObservableSshKeysClient` with a new parameter `ApiOptions`
- Implement the new method on the class which implements `IObservableSshKeysClient`

This needs to be done for each of these methods:

- [ ] `Task<IReadOnlyList<SshKey>> GetAll(String user)`
- [ ] `Task<IReadOnlyList<SshKey>> GetAllForCurrent()`

**Comment by devkhan** [comment]
The mentioned methods are obsolete and marked for removal. And `User.Keys.*` are advised instead. Do we still need to add the ApiOptions overloads to these or #1183 will suffice?

**Comment by shiftkey** [comment]
@devkhan you're right, let's skip this
