### ISSUE TITLE
[META] Codecov Code Coverage Badge

### ISSUE THREAD

**Issue by devkhan** [octokit/octokit.net#1200]
Should we have a code coverage badge?

Example:

![image](https://cloud.githubusercontent.com/assets/8049092/13894323/817f92f6-ed8c-11e5-83dc-fd839efd443a.png)

The important thing: Is it really helpful for someone who reaches the repo homepage? Does it signify anything meaningful which is relevant to the library?

**Comment by shiftkey** [comment]
@devkhan I'm neutral on this.

On the one hand, I think code coverage is a questionable metric for code quality. Fowler [sums it up nicely](http://martinfowler.com/bliki/TestCoverage.html) in that it should be used to look for untested code, not as a general metric.

On the other, if someone thinks it's worth setting up, they are welcome to explore options and see how Octokit integrates with this. Ultimately I'm more interested in finding the code that isn't covered by tests, than the statistic itself.

**Comment by shiftkey** [comment]
Setting this to a meta discussion.
