### ISSUE TITLE
document usage of FormatCode in CONTRIBUTING.md

### ISSUE THREAD

**Issue by shiftkey** [octokit/octokit.net#1201]
From https://github.com/octokit/octokit.net/pull/1196#issuecomment-199249284

> And yeah, I hadnt actually seen the FormatCode build command until I was poling around the other day too... perhaps it should be added to the contributors.md. Not as a "you must run this" but more so as a "if you want to, here it is"

**Comment by Niyaroje** [comment]
Ccx

**Comment by Niyaroje** [comment]
Xvbj
