### ISSUE TITLE
Misspelt: docmentation

### ISSUE THREAD

**Issue by devkhan** [octokit/octokit.net#1202]
I know its not even a real issue, but just thought I should share:

![image](https://cloud.githubusercontent.com/assets/8049092/13943128/dddd1ff6-f01f-11e5-80ee-437451c5c94d.png)

`docmentation vs documentation`

This is just the code files, but when I searched in a text editor, it found results from non-code and generated files too. I didn't submit a PR as that may cause conflicts with many other PRs.

**Comment by shiftkey** [comment]
@devkhan nope, this is fine to log - I'll leave this as an easy contribution for someone to get started on...

**Comment by devkhan** [comment]
Let me take care of this. :smiley:
