### ISSUE TITLE
Provide uniform name for constructors test classes

### ISSUE THREAD

**Issue by dampir** [octokit/octokit.net#1231]
I found some inconsistency in naming of classes that tests client constructors. So,
30 tests uses "TheConstructor" class name for test client constructors.
37 tests uses "TheCtor" class name for test client constructors.
1 test use TheCtorMethod" class name for test client constructor in [ObservableCommitsClientTests.cs](https://github.com/octokit/octokit.net/blob/aa133286459612c32351cde75dca399b84e093ef/Octokit.Tests/Reactive/ObservableCommitsClientTests.cs).

In order to eliminate inconsistency in these cases, I propose put names in order and rename all such classes to "TheCtor" (as most popular class name at this moment).

**Comment by devkhan** [comment]
Can we add inconsistencies like this to be resolved in FormatCode command? Automating this will remove any inconsistencies introduced by humans. Is something like this possible?

**Comment by dampir** [comment]
@devkhan Guess after we choose name convention for these classes, we can add additional checks in Conventions test rather in FormatCode. Anyway, it would be very cool have such additional check.

**Comment by M-Zuber** [comment]
Checks like this are in theory possible, _but_ would require a lot of hard coding (not that that is a bad thing, just something to keep in mind).

And I second @dampir's suggestion that they go into `Conventions` and not `FormatCode`

**Comment by ryangribble** [comment]
Yep considering we aren't "making" people run the format code step, nor is there an easy way to enforce that, adding things to convention tests would be the preferred option

**Comment by shiftkey** [comment]
> Can we add inconsistencies like this to be resolved in FormatCode command?

There's no real project-specific rules defined in [`Octokit.CodeFormatter`](https://github.com/shiftkey/octokit.codeformatter) and writing Roslyn analyzers is a bit tricky if you're not familiar with the concepts.

> Guess after we choose name convention for these classes, we can add additional checks in Conventions test rather in FormatCode.

This feels a bit easier to add and will be caught earlier.

**Comment by shiftkey** [comment]
Closing this after the work done in #1246. Please open a new issue if there are further ideas about this.
