### ISSUE TITLE
unable to download PCLs for testing PRs on Travis

### ISSUE THREAD

**Issue by shiftkey** [octokit/octokit.net#1233]
```
127.34s$ curl -sS http://storage.bos.xamarin.com/bot-provisioning/PortableReferenceAssemblies-2014-04-14.zip > /tmp/pcl-assemblies.zip
curl: (7) couldn't connect to host
The command "curl -sS http://storage.bos.xamarin.com/bot-provisioning/PortableReferenceAssemblies-2014-04-14.zip > /tmp/pcl-assemblies.zip" failed and exited with 7 during .
Your build has been stopped.
```

@naveensrinivasan do you know what might have changed?

**Comment by naveensrinivasan** [comment]
I don't think we need PCL. Let me check that and get back. I have been really busy with work and haven't had a chance to look at these issues.

**Comment by naveensrinivasan** [comment]
@shiftkey The link is dead and there aren't any files. Could you try removing the pcl reference from the script and try it without that?
