### ISSUE TITLE
Implement Pull Request "Squash Commit" support (API preview)

### ISSUE THREAD

**Issue by ryangribble** [octokit/octokit.net#1236]
### Summary
Recently announced on this [blog post](https://developer.github.com/changes/#--preview-squash-support-for-the-pull-request-merge-api) the GitHub API now has preview support for the new "Squash Commits" Pull Request merge option.

API Docs [are here](https://developer.github.com/v3/pulls/#merge-a-pull-request-merge-button)

### Tips for Octokit Implementation
`IPullRequestsClient.Merge()` and `IObservablePullRequestsClient.Merge()` take a request model object `MergePullRequest` providing the input parameters for the merge action.  

There are now 2 new input parameters that need to be added to the request model
> `commit_title`	`string`	Title for the automatic commit message.
`squash`	`boolean`	Commit a single commit to the head branch.

Unit and Integration tests should also be updated to assert the new functionality works as expected!

Reminder that like all funcitonality in "preview mode" a custom accepts header needs to be specified (see `AcceptHeaders.cs`)
> To access the API during the preview period, you must provide a custom media type in the Accept header:
> `application/vnd.github.polaris-preview+json`

### Working on this issue
This issue has been flagged as `up-for-grabs` as it is a reasonably easy issue for a new contributor to pick up, and be guided through the process of contributing to octokit
(that said, if an existing contributor wants to work on this, by all means go for it!)

Please comment here if you want to take this issue.

Please read and follow the [CONTRIBUTING guide](https://github.com/octokit/octokit.net/blob/master/CONTRIBUTING.md) guide and if you need any help, just ask!  Don't be afraid to open a `[WIP]` (work in progress) Pull Request once you've started implementing the changes

**Comment by Sarmad93** [comment]
hi @ryangribble hope you are fine. this one looks easy i want to do this one :smile: 
but regarding the tests i will certainly bother you when i will implement this :grinning: 
and :+1: for clean and nice instructions.

**Comment by ryangribble** [comment]
:+1:

**Comment by shiftkey** [comment]
Implemented in #1245
