### ISSUE TITLE
Add custom exception for the HTTP 451 response (DMCA Notice)

### ISSUE THREAD

**Issue by ryangribble** [octokit/octokit.net#1237]
### Summary
As per this [blog post](https://developer.github.com/changes/#--the-451-status-code-is-now-supported) 

GitHub API will now return a HTTP 451 response (rather than a 403) when a repository or gist cannot be accessed due to a DMCA notice.

### Tips for Octokit Implementation
In octokit, some key HTTP exceptions are represented by specific named exceptions (eg `ForbiddenException`, which the `HandleErrors()` function in `Connection.cs` will throw when those HTTP response error codes are encountered.

- [ ] A specific exception class should be added for this new 451 response, and mappings added to the `HandleErrors` logic so it is thrown when encountered

- [ ] Unit tests should be updated/implemented, similar to `ForbiddenException`

### Working on this issue
This issue has been flagged as `up-for-grabs` as it is a reasonably easy issue for a new contributor to pick up, and be guided through the process of contributing to octokit
(that said, if an existing contributor wants to work on this, by all means go for it!)

Please comment here if you want to take this issue.

Please read and follow the [CONTRIBUTING guide](https://github.com/octokit/octokit.net/blob/master/CONTRIBUTING.md) guide and if you need any help, just ask!  Don't be afraid to open a `[WIP]` (work in progress) Pull Request once you've started implementing the changes

**Comment by devkhan** [comment]
Can be closed now.
