### ISSUE TITLE
[META] What should we do when preview API functionality becomes "official"

### ISSUE THREAD

**Issue by ryangribble** [octokit/octokit.net#1242]
As per this [blog post](https://developer.github.com/changes/2016-01-05-api-enhancements-for-working-with-organization-permissions-are-now-official/)

The accepts header for organizational permissions is no longer required and we can look towards removing it.

HOWEVER this does raise an interesting point around GitHub Enterprise.  

Generally speaking, GitHub Enterprise has a feature release (eg 2.3 2.4 2.5) every 2 or 3 months, and patch releases (2.5.1 2.5.2 etc) more frequently.  Typically my experience has been that introduction of API changes (and one can assume making such preview changes "official") come through in the feature releases.

If we remove the preview headers too early, the functions wont work even on the latest version of GitHub Enterprise.  Even if we wait until the latest GitHub Enterprise version is released and no longer requires the preview headers, we will still cause that feature not to work on previous versions of GiHub Enterprise where the preview headers were still required.

Perhaps the plan is to simply "never" remove the preview header?  It appears that it continues to be honoured (forever? not sure!).

Otherwise we'd need to do something like provide options for consumers to tell octokit to use the preview headers, or be smart about detecting GitHub Enterprise version and using appropriate headers where required.  All sounds pretty messy though.

I've only been involved with Octokit and using GitHub Enterprise for 6 months or so, this is the first time ive even seen a preview feature become "official".  It seems to often be the case that features are still in preview (or at leat them becoming official arent reported like the above blog post) even many months after they were introduced...

Interesting in what @shiftkey @Haacked and other GH staff think about this topic :grinning:

**Comment by pmn** [comment]
Outside of the larger conversation of when to stop sending the preview header, I chatted with a few folks about this here and verified that nothing will break if the preview header continues to be used after the feature has shipped. Any media type that is not supported or no longer supported will default back to `application/vnd.github.v3+json`. 

That being said, I'll leave the conversation around how to handle preview features in Octokit.NET to @Haacked and @shiftkey as they may have some preferences around that.

**Comment by ryangribble** [comment]
Useful info thanks. 

Perhaps we could treat it like obsoleting items where we remove things a number of releases after they are no longer supported/needed.  Eg we could decide the latest octokit will only support (for example) the last 2 GHE feature versions, and base such removals on that. 

Although I guess if there's no harm in sending them "forever" that gives the widest possible support with the least effort :grinning:
