### ISSUE TITLE
Deployment and DeploymentStatus API enhancements preview period

### ISSUE THREAD

**Issue by ryangribble** [octokit/octokit.net#1249]
### Summary
Recently announced on this [blog post](https://developer.github.com/changes/#--deployment-and-deploymentstatus-api-enhancements-preview-period) the Deployment API has some enhancements that are now in preview mode.

API Docs:
[Create Deployment](https://developer.github.com/v3/repos/deployments/#create-a-deployment)
[Create Deployment Status](https://developer.github.com/v3/repos/deployments/#create-a-deployment)

#### Deployment API
`IDeploymentsClient.Create()`
`IObservableDeploymentsClient.Create()`

The request model object `NewDeployment` providing the input parameters for the deployment creation which now has 2 additional parameters:
> `transient_environment`	`boolean`
`production_environment`	`boolean`

#### DeploymentStatus API
`IDeploymentStatusClient.Create()`
`IObservableDeploymentStatusClient.Create()` 

The request model object `NewDeploymentStatus` providing the input parameters for the deployment status creation has a number of changes:
- 2 new parameters need to be added to the request model
> `environment_url`    `boolean`
`auto_inactive`    `boolean`

- renaming a field
> `target_url` -> `log_url`

Note that the old field will need to be marked `[Obsolete]` at this stage - it will be removed after having been obsolete for at least 3 octokit releases

- Adding a new value to `DeploymentState`
> inactive

Unit and Integration tests should also be updated to assert the new functionality works as expected!

Reminder that like all functionality in "preview mode" a custom accepts header needs to be specified (see `AcceptHeaders.cs`)
> To access the API during the preview period, you must provide a custom media type in the Accept header:
> `application/vnd.github.ant-man-preview+json`

### Working on this issue
This issue has been flagged as `up-for-grabs` as it is a reasonably easy issue for a new contributor to pick up, and be guided through the process of contributing to octokit
(that said, if an existing contributor wants to work on this, by all means go for it!)

Please comment here if you want to take this issue.

Please read and follow the [CONTRIBUTING guide](https://github.com/octokit/octokit.net/blob/master/CONTRIBUTING.md) guide and if you need any help, just ask!  Don't be afraid to open a `[WIP]` (work in progress) Pull Request once you've started implementing the changes

**Comment by ErikSchierboom** [comment]
I'll try and have a go at this.

**Comment by ryangribble** [comment]
Fixed by #1365
