### ISSUE TITLE
GPG Key Administration API Preview

### ISSUE THREAD

**Issue by shiftkey** [octokit/octokit.net#1252]
### Summary

Recently announced on this [blog post](https://developer.github.com/changes/2016-04-04-git-signing-api-preview/) the User API has some enhancements that are now in preview mode.

### Notes on Octokit Implementation

This should be similar to our [`IUserKeysClient`](https://github.com/octokit/octokit.net/blob/master/Octokit/Clients/IUserKeysClient.cs)

#### GPG Keys API

 - [GetAllForCurrent](https://developer.github.com/v3/users/gpg_keys/#list-your-gpg-keys)
 - [Get(int id)](https://developer.github.com/v3/users/gpg_keys/#get-a-single-gpg-key)
 - [Create(NewGpgKey newGpgKey)](https://developer.github.com/v3/users/gpg_keys/#create-a-gpg-key)
 - [Delete(int id)](https://developer.github.com/v3/users/gpg_keys/#delete-a-gpg-key)

Reminder that like all functionality in "preview mode" a custom accepts header needs to be specified (see `AcceptHeaders.cs`)
> To access the API during the preview period, you must provide a custom media type in the Accept header:
> application/vnd.github.cryptographer-preview

#### Naming Things

So now we have two different sorts of keys to manage - Git SSH Keys (what we previously referred to as "Keys") and GPG Keys. This client should be named GpgKeys (or whatever naming style we're using for acronyms) and I'll open a separate task to rename `IUserClient.Keys`.

#### Testing Things

Testing with generated GPG keys may be tricky, but I'm open to ideas around this.

### Working on this issue

As this issue follows issue has been flagged as `up-for-grabs` as it is a reasonably easy issue for a new contributor to pick up, and be guided through the process of contributing to octokit
(that said, if an existing contributor wants to work on this, by all means go for it!)

Please comment here if you want to take this issue.

Please read and follow the [CONTRIBUTING guide](https://github.com/octokit/octokit.net/blob/master/CONTRIBUTING.md) guide and if you need any help, just ask!  Don't be afraid to open a `[WIP]` (work in progress) Pull Request once you've started implementing the changes.

**Comment by alfhenrik** [comment]
If no-one else has already picked this one up, I'll jump on it.

**Comment by alfhenrik** [comment]
OK, so the [blog post](https://developer.github.com/changes/2016-04-04-git-signing-api-preview/) specifies the preview header as `application/vnd.github.cryptographer-preview` while the [GPG Keys doco](https://developer.github.com/v3/users/gpg_keys/) specifies the preview header as `application/vnd.github.cryptographer-preview+sha`...so the question is, which one is correct? 

I'm going to go with the one from the doco for now to get started.

**Comment by shiftkey** [comment]
@alfhenrik both worked for me, but given History™ I'd recommend using `application/vnd.github.cryptographer-preview` here.

I'll speak to the team to confirm this is right and get the docs addressed.

**Comment by alfhenrik** [comment]
@shiftkey cheers, I'll update my PR later tonight
