### ISSUE TITLE
rename IUserClient.Keys to IUserClient.GitSshKeys

### ISSUE THREAD

**Issue by shiftkey** [octokit/octokit.net#1253]
As part of rolling out GPG Keys in the GitHub API, Keys was renamed to **Git SSH Keys**

<img width="329" alt="screen shot 2016-04-07 at 4 55 17 pm" src="https://cloud.githubusercontent.com/assets/359239/14366605/952572d0-fce1-11e5-9527-93b8348e72c0.png">

We should do the same in the client, and then mark the old property as obsolete.

**Comment by Andychochocho** [comment]
Hey there - I'm new to open source projects, but would like to take this on.

**Comment by shiftkey** [comment]
@Andychochocho sounds good!

**Comment by radu-matei** [comment]
What should be the course of action: adding a new property and modifying all references to it? (In this scenario, what happens with the old property?)

Or renaming `Keys` to `GitSshKeys` directly?

**Comment by caseycraig** [comment]
Because it's easier

**Comment by radu-matei** [comment]
@caseycraig I don't really understand your comment.
 
What is easier?

**Comment by shiftkey** [comment]
@radu-matei @caseycraig when it comes to deprecating properties and types we should follow this pattern:

 - mark the existing property or type as `[Obsolete]` so that it's easier to find all references
 - add in a new property or type with the correct name
 - update all usages internally to point to the new method 
 - add a comment to the `[Obsolete]` to indicate what needs to be done (i.e. use the new property)

This means we don't break existing consumers when they update, and we indicate what needs to be done to migrate...
