### ISSUE TITLE
Get Signature Verification When Viewing Git Data Tags

### ISSUE THREAD

**Issue by shiftkey** [octokit/octokit.net#1256]
API documentation: https://developer.github.com/v3/git/tags/#tag-signature-verification

An enhancement as part of the Commit Signing API is to surface the signature details in the tag.

It looks like these are the new properties:

```json
    "verification": {
      "verified": true,
      "reason": "valid",
      "signature": "-----BEGIN PGP MESSAGE-----\n...\n-----END PGP MESSAGE-----",
      "payload": "tree 6dcb09b5b57875f334f61aebed695e2e4193db5e\n..."
    }
```

These fields should be available on the `GitTag` response object (perhaps in a class called `Verification` or something), and the `TagsClient.Get` action should be updated to use the new `Accepts` header:

> application/vnd.github.cryptographer-preview+sha

I'd also like to see some new integration tests added to verify this behaviour is working as expected.

**Comment by mderriey** [comment]
Hey,

I'd like to give this one a shot.
From the looks of it, what has been done in #1398 can be reused.

Cheers

**Comment by shiftkey** [comment]
@mderriey sounds good!
