### ISSUE TITLE
Microsoft.Net.Http.Client -> System.Net.Http

### ISSUE THREAD

**Issue by ikourfaln** [octokit/octokit.net#1257]
Hi,

I think that you must remove reference to Microsoft.Net.Http.Client, this is obsolete now that CoreCLR has a functioning HttpClient. Microsoft.Net.Http should be used with traditional ASP.NET applications (MVC 5 for example) and does not work with .NET Core. So let ASP.NET Core developers be happy too.

**Comment by shiftkey** [comment]
Could you add a comment to #1115 about migrating that package, and any other details about why this package is considered obsolete? We've been talking about .NET Core support for a while, and that bit of information sounds useful to us...
