### ISSUE TITLE
Octokit.CompareResult does not include merge_base_commit field of the GitHub Api

### ISSUE THREAD

**Issue by kivancmuslu** [octokit/octokit.net#1258]
Hi, 

GitHub compare Api (https://developer.github.com/v3/repos/commits/#compare-two-commits) specifies the "merge_base_commit" field. Unfortunately, OctoKit.CompareResult (return value of await IGitHubClient.Repository.Commit.Compare(..)), does not contain a property for the "merge_base_commit" field. The closest it has is "MergedBaseCommit", however it always returns "null".

Are there any plans to properly fill this value and fix the naming convention?

Thanks,

**Comment by shiftkey** [comment]
I believe this is just a typo - note the `d` that's included on the C# property: 

> does not contain a property for the "merge_base_commit" field. The closest it has is "Merge**d**BaseCommit", however it always returns "null".

With Octokit we map properties using conventions, which would explain what happened (or didn't happen) here.

We have a bunch of tests around compare in [`RepositoryCommitsClientTests.cs`](https://github.com/octokit/octokit.net/blob/master/Octokit.Tests.Integration/Clients/RepositoryCommitsClientTests.cs) but I can't see us verifying this property explicitly...

**Comment by kivancmuslu** [comment]
I also thought it was something simple. Thanks for the quick response @shiftkey!

**Comment by shiftkey** [comment]
@kivancmuslu I can help to co-ordinate a hotfix release (currently there's a lot of new features on `master`) if someone is interested in tidying this up in a PR:

  - add the new property
  - mark the old one as obsolete
  - add a test to verify this behaviour

**Comment by kivancmuslu** [comment]
@shiftkey, no promises on the delivery time, but I will see what I can do during the weekend. 

Just a quick question: when the typo is fixed, does parsing (and the correct value filling in) happen automatically or do I need to update the parse logic as well?

I am an Octokit consumer, but am very new to how Octokit internally works. Sorry if the question is obvious.

**Comment by shiftkey** [comment]
@kivancmuslu 

> Just a quick question: when the typo is fixed, does parsing (and the correct value filling in) happen automatically or do I need to update the parse logic as well?

No need to worry about changing the parsing logic - for reference it's [this component](https://github.com/octokit/octokit.net/blob/master/Octokit/Http/SimpleJsonSerializer.cs#L24) that does the deserializing and [this is the magic rule for mapping properties from C# to JSON](https://github.com/octokit/octokit.net/blob/master/Octokit/Helpers/StringExtensions.cs#L81-L85)
