### ISSUE TITLE
improve documentation for interacting with Pages API

### ISSUE THREAD

**Issue by prayankmathur** [octokit/octokit.net#1263]
After having a discussion with @shiftkey and referring to the [docs](https://developer.github.com/v3/repos/pages/), we found that any normal integration tests won't be of any use as you need to be an authenticated owner of the repository to use the Pages API.

Refer to #1213 and especially conversation after this [comment](https://github.com/octokit/octokit.net/pull/1213#issuecomment-203437170) for more details.

**Comment by shiftkey** [comment]
This is mentioned in the docs: https://developer.github.com/v3/repos/pages/

> Information about the site and the builds can only be accessed by authenticated owners, even though the websites are public.
