### ISSUE TITLE
Obsolete attribute on interfaces and implementations

### ISSUE THREAD

**Issue by M-Zuber** [octokit/octokit.net#1270]
In the course of #1224 it was discovered that (in at least one place) a method was obsoleted, but the attribute was not added in both places.

Should such a check be added into the `Conventions` test project or somewhere else?

**Comment by shiftkey** [comment]
@M-Zuber I think this is a good thing to do, but I'll leave it up to someone who is brave enough (and knows enough reflection) to dive into this and make it work broadly (think methods versus properties and interfaces versus all implementations available).

**Comment by joaope** [comment]
Hi! I'm grabbing this one up if it's ok with you.
