### ISSUE TITLE
SearchUsers does not return Name and PublicRepos count

### ISSUE THREAD

**Issue by elv1s42** [octokit/octokit.net#1284]
The following code: 
```csharp
       [Test]
        public void Test()
        {
            var githubClient = new GitHubClient(new ProductHeaderValue("test"));
            var request = new SearchUsersRequest("EPAM Systems")
            {
                AccountType = AccountSearchType.Org,
                In = new[] { UserInQualifier.Username }
            };

            var res = githubClient.Search.SearchUsers(request);
            res.Wait();

            var user = res.Result.Items.First();

            var nl = Environment.NewLine;
            Console.WriteLine($"Org '{user.Name}' has {user.PublicRepos} public repos." + nl 
                + $"Org api url: '{user.Url}'" + nl
                + $"Org home url: '{user.HtmlUrl}'");
        }
```
does not return all information (user.Name and user.PublicRepos are empty). See this test run in VS 2015:

![screenshot](https://cloud.githubusercontent.com/assets/6689884/14818409/a5611094-0bc5-11e6-8c11-31d816a532e7.png)

API url (https://api.github.com/users/epam) returns correct data.
This issue can be reproduced in my project: https://github.com/elv1s42/gh-org-comparer/blob/master/OrgComparer/OrgComparerTests/Tests.cs

**Comment by ryangribble** [comment]
Hi, 

Thanks for reaching out... 

I haven't runtime tested this as I'm not at a computer currently, but if you have a look at the [API docs](https://developer.github.com/v3/search/#search-users) for the search user call and the example json response, it doesn't return a full `User` object (with the properties you are wanting), it only appears to return a smaller subset of information. 

Unfortunately if you need those fields it looks like you'll need to load the full User using the [`User.Get()`] (https://github.com/octokit/octokit.net/blob/f354d1bf00ff7606b46489e3a915e1428414bc47/Octokit.Tests.Integration/Clients/UsersClientTests.cs#L29) call, passing the `login` field from the search result.

**Comment by elv1s42** [comment]
@ryangribble thanks!
I did not notice that in API docs and expected to see full objects.

Looks like this is not an issue at all. 
I will try your approach, thanks.
