### ISSUE TITLE
Getting all the changed files from all the commits

### ISSUE THREAD

**Issue by dimitrisTim** [octokit/octokit.net#1293]
I am trying to get every file that has been changed in a repo, by every commit. Then I store the files in a list, so that I can count how many times every file has been changed.
Code:

```csharp
var commitsAll = await client.Repository.Commit.GetAll (Owner, Name);
foreach (var com in commitsAll) {
		var commit = await client.Repository.Commit.Get (Owner, Name, com.Sha);
		var files = commit.Files; //get changed files for every commit
		foreach (var f in files) {
			if (!fileNames.Contains (f.Filename)){
				fileNames.Add (f.Filename); //add the filename in a list
}
                 fileCounter [fileNames.IndexOf (f.Filename)]++;
}
}
```

However, if the number of commits is high (let's say 1000), this method is totally slow and useless. Any thoughts?

**Comment by shiftkey** [comment]
I'm not sure how we can optimize this "all files and then all commits" scenario but there's a few optimizations I can think of. Apologies if this doesn't compile, I'm writing it from scratch.

First, you can grab all the files which exist on a given branch like this:

```csharp
var tipCommit = await client.Repository.Commit.Get(Owner, Name, "master");
var allPaths = tipCommit.Files.Select(f => f.Filename);
```

Then, you can query for all commits associated with a given file:

```csharp
var stats = new Dictionary<string, int>();

foreach (var path in allPaths)
{
    var request = new CommitRequest { Path = "path/to/file.cs" };
    var commitsForFile = await client.Repository.Commit.GetAll(Owner, Name, request);
    stats.Add(path, commitsForFile.Length);
}
```

It's still time-consuming, but now the number of requests necessary is `(1 + file count)` instead of `(1 + commit count)`.

**Comment by dimitrisTim** [comment]
Thanks a lot. That was the other idea I had but didn't know how to implement. It works, with a change on how you get the file paths:

var files = await client.Git.Tree.GetRecursive (Owner,Name, "master"); 
var filePaths = files.Tree.Select (x => x.Path);
var stats = new Dictionary<string, int>();
			foreach (var path in filePaths)
			{
				var request = new CommitRequest { Path = path };
				var commitsForFile = await client.Repository.Commit.GetAll(Owner, Name, request);
				stats.Add(path, commitsForFile.Count);
			}

Thanks again for your help and fast response!!

**Comment by shiftkey** [comment]
Oh yes, silly me - the tip commit doesn't reflect the whole tree, just the files changed in that commit!

I'm glad the rest helped though!

**Comment by caseycraig** [comment]
It's an octodecimal hypermobius?
