### ISSUE TITLE
Add reactions to issue comments response payload

### ISSUE THREAD

**Issue by ja1984** [octokit/octokit.net#1295]
Github have added reactions to the issues, comments and pull requests. It would be a really cool feature to have, it's however opt in via header for now.

https://developer.github.com/changes/2016-05-12-reactions-api-preview/
https://developer.github.com/v3/issues/comments/#list-comments-on-an-issue

> An additional reactions object in the issue comment payload is currently available for developers to > preview. During the preview period, the APIs may change without advance notice. Please see the blog post for full details.

> To access the API you must provide a custom media type in the Accept header:
application/vnd.github.squirrel-girl-preview
The reactions key will have the following payload where url can be used to construct the API location for listing and creating reactions.

```
{
  "total_count": 5,
  "+1": 3,
  "-1": 1,
  "laugh": 0,
  "confused": 0,
  "heart": 1,
  "hooray": 0,
  "url": "https://api.github.com/repos/octocat/Hello-World/issues/comments/1/reactions"
}
```

**Comment by shiftkey** [comment]
@ja1984 I'd love to see this land with some preview support. As it looks like the reactions model are the same shape whether it is for issues, issue comments, pull requests or review comments we can roll this out gradually. The first PR can add the model, set the preview header and add some tests - and the others can follow.

I've renamed this task to focus on issue comments, and I'll open tasks for the other areas.

**Comment by alfhenrik** [comment]
I'd like to get back and involved with Octokit.net again (been too long since I was 😢 ), mind if I grab this one?

**Comment by ryangribble** [comment]
Hey @alfhenrik that's awesome! 

Just a heads up that some other related changes are occurring in #1335 (for creating and deleting the reactions)... For this issue you'd want to use the same `ReactionType` enum created there etc

**Comment by alfhenrik** [comment]
I'll get a start on this and add in a few `TODO`s to use the `AcceptHeaders.ReactionsPreview` property being introduced in #1335
