### ISSUE TITLE
Add reactions to issue response payload

### ISSUE THREAD

**Issue by shiftkey** [octokit/octokit.net#1296]
Link: https://developer.github.com/v3/issues/#preview-period-org-issues

Before we do this, let's get #1295 resolved as that will involve much of the groundwork.

After that, here's what I think needs to be done:

 - add `Reactions` property to `Issue` response model
 - include the preview header to methods in `IssueClient` which return issues:  `application/vnd.github.squirrel-girl-preview`
 - add tests to retrieve a known issue with reactions and verify it deserializes correctly

**Comment by maddin2016** [comment]
@shiftkey, i take this issue and #1297 and #1298 if this ok

**Comment by maddin2016** [comment]
Oops :see_no_evil: Of course!!! I didn't recognized that #1341 was merged. Thanks for the update
