### ISSUE TITLE
Delete a Reaction

### ISSUE THREAD

**Issue by shiftkey** [octokit/octokit.net#1303]
Link: https://developer.github.com/v3/reactions/#delete-a-reaction

As this is a standalone API not tied to specific resources, this should live in a new `IReactionsClient` (with an equivalent `IObservableReactionsClient` for Octokit.Reactive) as a property of the root `IGitHubClient`.

It only needs one method at this stage, which returns a `Task` (or `IObservable<Unit>`) but you'll need to send the new preview header along with it:  application/vnd.github.squirrel-girl-preview

 - `DELETE /reactions/:id`

**Comment by ryangribble** [comment]
fixed by #1335
