### ISSUE TITLE
Get all commits and details of those commits

### ISSUE THREAD

**Issue by joe307bad** [octokit/octokit.net#1309]
How do I get all commits of a repo, plus the details of those commits. This is the best I have come up with:
   
        var client = new GitHubClient(new ProductHeaderValue("joe307bad-commits"));

            var repository = await client.Repository.Commit.GetAll("joe307bad", "portfolio_wp");

            var commitsFiltered = repository.Select(async(_) =>
            {
                return await client.Repository.Commit.Get("joe307bad", "portfolio_wp", _.Sha);
            }).ToList();

            var commits = await Task.WhenAll(commitsFiltered);`

Is this the most efficient way to do this?

**Comment by shiftkey** [comment]
@joe307bad when you mean details, what exactly are you looking to get out of the API? 

Also, a similar question was asked in https://github.com/octokit/octokit.net/issues/1293 and we walk through some options there...

**Comment by joe307bad** [comment]
I had actually seen that question and formulated the above code based on that.

I am mainly looking to get the commit stats (which seems like a pretty small piece of data) without having to make a separate `Commit.Get` request for each individual commit returned from `Commit.GetAll`. This seemed like an inefficient way to get a small piece of data associated with all commits.

I thought my question differed from the one you referenced since that question is requesting to get deeper file information associated with every commit so it was understandable that a separate `Commit.Get` was required.

I came up with this question when I noticed the `GitHubCommit.Stats` property was `null` when accessing directly from the results of `Commit.GetAll`.

Thanks for the response!

**Comment by shiftkey** [comment]
> I came up with this question when I noticed the `GitHubCommit.Stats` property was null when accessing directly from the results of `Commit.GetAll`.

Yeah, unfortunately the response for `GetAll` doesn't have the stats or files changed in a commit - here's the [example payload](https://developer.github.com/v3/repos/commits/#list-commits-on-a-repository).

If you're aggregating the stats for a range of commits, what about if you were to compare two commits, like this?

```
var commits = await client.Repository.Commit.GetAll("joe307bad", "portfolio_wp");

var first = commits.First();
var last = commits.Last();

var result = await client.Repository.Commit.Compare("joe307bad", "portfolio_wp", last.Sha, first.Sha);

var files = result.Files;
var totalAdded = files.Sum(f => f.Additions);
var totalDeleted = files.Sum(f => f.Deletions);
```

This isn't as granular as checking each commit, but might work for your scenario...

**Comment by joe307bad** [comment]
That's an interesting approach. I am actually just looking to output a simple list of most recent commits and minor details on each commit. I felt the commit message, commit date, and commit stats would provide a good snapshot for a commit, which is why I was surprised commit stats were not in the commit payload you referenced. 

Thanks for the help.

**Comment by shiftkey** [comment]
@joe307bad the short version of the long story is that `GetAll` becomes expensive to execute when you have to dig into the underlying tree/s and blobs and work out the changes between it and the parent commit, for each commit in the range of history.

Closing this out for now. Best of luck!

**Comment by jjxtra** [comment]
Adding stats should be an option on the request, now I have to make a separate request for each commit, putting extra load on your servers and making my process slower... :(
