### ISSUE TITLE
Need to modify pull request commit message

### ISSUE THREAD

**Issue by ragnarok513** [octokit/octokit.net#1314]
I am working on migrating my code base to GitHub.  One of the requirements that I have is that I need to prepend the pull request commits with a specific string.  Does the GitHub API allow me to hook on to the pull request's "merge" event and modify the default commit message?

**Comment by shiftkey** [comment]
Not sure I understand the problem completely, but you have a couple of options:

 - the commits in a PR cannot be changed while under review - to change existing commits you need to rewrite the branch directly and push, which will then sync the PR on GitHub
 - when the PR is synced (aka updated) you could verify the commit messages for the commits to be merged, and then set a failed commit status for the tip of the branch - see [these docs](https://developer.github.com/v3/repos/statuses/#create-a-status)
 - you could programmatically merge a PR and specify the commit title/description - see [these docs](https://developer.github.com/v3/pulls/#merge-a-pull-request-merge-button)
 - there is a `pull_request` webhook event named `closed` that you can use to know when the PR was merged (it'll have a property `merged=true` set). But this even occurs after the merge.

**Comment by ragnarok513** [comment]
hi shiftkey,

Thanks for the quick response!  I understand the the commit message inside the PR can't be changes.  What I want to do is tack on a string to the pull request merge commit message.

Right now in GitHub website when I click on the merge pull request button my commit message for the merge is prepopulated with "Merge pull request #5 from ragnarok513/test".  If my branch name was named Bug-123-urgent_issue_with_homepage, I want to parse out the text "Bug-123-" and prepend it to my merge commit message so that my merge has this message "Bug-123-Merge pull request #5 from ragnarok513/test"

**Comment by ragnarok513** [comment]
Some context for you....

My users are going to be directed to use the Github website to initiate and complete pull requests.  I have a webhook that enforces that the pull request must also have my custom labels attached before merging.  I need to also enforce that the pull request commit message starts with something like "Bug-123".  I didn't find a capability to validate the pull request commit message so my alternate idea was to prepend the commit message with part of the branch name

**Comment by shiftkey** [comment]
Unfortunately that sort of web hook (enforce merge commit message) isn't available currently. I'm not sure of alternatives aside from what you've mentioned above...

**Comment by ryangribble** [comment]
one other suggestion i have is that by using the commit status API and protected branches features, you can effectively "stop" PR's from being merged if the status checks havent passed.  You could potentially set a status check as pending that will never be passed, thus stopping the users from merging PRs on github.com web site.  Then you provide them with your own tool/script/webUI that will set the required commit status to PASS and then merge the PR for them (customising the merge commit message to your requirements in the process)

**Comment by shiftkey** [comment]
@ryangribble I like that idea. Some people might not, but if you're looking for process then it's the easiest way to lock it down...

**Comment by ryangribble** [comment]
Yeah commit statuses and protected branches offer great flexibility from "carrot" based suggestions to "stick" based enforcement depending on individual teams/repos needs

**Comment by shiftkey** [comment]
Closing this out as I think we've covered a bunch of alternatives to the proposed requirements.
