### ISSUE TITLE
Do Contents support pagination?

### ISSUE THREAD

**Issue by dampir** [octokit/octokit.net#1315]
I guess that I've found a bug in Github API. I was implementing pagination support for IRepositoryContentsClient and found out that Contents do not support pagination.

This query

[](https://api.github.com/repos/octokit/octokit.net/contents?page=1&per_page=2)

return all contents of repo, but should return only 2 items.

/cc @shiftkey, @ryangribble

**Comment by shiftkey** [comment]
Let's not worry about this one - because of the nuance of serving up a directory versus serving up a file, I don't expect pagination to be added here anytime soon.
