### ISSUE TITLE
Incorrect order of parameters on IObservableRepositoryContentsClient.GetAllContentsByRef

### ISSUE THREAD

**Issue by dampir** [octokit/octokit.net#1318]
I've found out that method IObservableRepositoryContentsClient.GetAllContentsByRef ([here](https://github.com/octokit/octokit.net/blob/172b1a632ea8e64755128934d92d79ea068d4e8f/Octokit.Reactive/Clients/IObservableRepositoryContentsClient.cs#L107)) has incorrect order of parameters.

As is:

``` cs
public IObservable<RepositoryContent> GetAllContentsByRef(string owner, string name, string reference, string path)
```

As should be:

``` cs
public IObservable<RepositoryContent> GetAllContentsByRef(string owner, string name, string path, string reference)
```

/cc @shiftkey @ryangribble

**Comment by dampir** [comment]
I'm going to fix that, but I can't use standard approach "create new method, fix all usages, mark old methods by Obsolete attribute", because in this case type of parameters is equal (string). So it will be breaking change in this case. In what way it should be fixed?

**Comment by ryangribble** [comment]
So this is an inconsistency but not actually a "problem" currently right?  Because inside the Observable implementation it does pass the correct order of parameters through to the normal client.

Id be tempted to say that although inconsistencies are annoying, we shouldnt make a breaking change just to order the parameters in the observable client the same as the normal client...

**Comment by dampir** [comment]
Yeah, all worked :smile: ! I'm not insisting on fixing in any case, just I was wonder :scream_cat:  when I found it. And yes, breaking changes are very bad, but I thought that since version of Octocit.NET is far from 1.0 and maybe users are ready to breaking changes, so it can be fixed as far as it was located.

**Comment by shiftkey-tester** [comment]
Let's not break this yet. We've got a few things we should clean up that are far more urgent than this...

**Comment by dampir** [comment]
So I don't mind if it would be closed :+1:

**Comment by shiftkey** [comment]
@dampir I'm happy to leave it open.
