### ISSUE TITLE
Add or Update Team's Repository - missing permission parameter

### ISSUE THREAD

**Issue by ryangribble** [octokit/octokit.net#1320]
Related to the [Organisation/Team permission changes from last year](https://developer.github.com/changes/2015-06-24-api-enhancements-for-working-with-organization-permissions/#preview-period) 

When adding/updating a team's access to a repository, [there is a `permission` parameter](https://developer.github.com/v3/orgs/teams/#parameters-3) to control the level of access, we are currently not setting this.

In octokit this should be implemented as a request model object (eg `TeamRepositoryUpdate`) and an overload added to the `I(Observable)TeamsClient` interfaces `.AddRepository()` method

Other issues related to the changes introduced in that GitHub change: 
#1319 Missing permissions attribute on #repository collaborators and team's repositories calls
#1101 Add a user as collaborator with permission parameter

**Comment by maddin2016** [comment]
Hi @ryangribble, is there any option to try this out. Because i dont have access to github enterprise. And second question, is there someone still working on this issue?

**Comment by ryangribble** [comment]
This one doesn't require GitHub Enterprise (i take it you already realised that based on the strikethrough text)

I recently pushed up #1342 which addresses #1319, but I haven't done anything on this issue yet, so feel free to take this if you want!

**Comment by maddin2016** [comment]
:+1:
