### ISSUE TITLE
Download files in the Repo

### ISSUE THREAD

**Issue by k122085** [octokit/octokit.net#1327]
Is there any way of downloading complete repository from a given owner and repo. and store them in a local folder. just like git clone command in cmd.

**Comment by ryangribble** [comment]
I don't believe so... 

You can download an archive of the entire repository at any specified reference (branch, commit, tag etc)  in zip or tar format, using the [`client.Repository.Content.GetArchive()`](https://github.com/octokit/octokit.net/blob/master/Octokit/Clients/IRepositoryContentsClient.cs#L122) calls, but that's a copy at a point in time, not the entire repo including history and commits etc. 

If you want to do an actual git clone, I think you'd have to look into libgit2 or shell out to the git cmdline

**Comment by k122085** [comment]
Alright. Thank you for the response.

**Comment by shiftkey** [comment]
Seconding what @ryangribble said - it's not something Octokit or the GitHub API supports.
