### ISSUE TITLE
Support for multiple assignees

### ISSUE THREAD

**Issue by adamralph** [octokit/octokit.net#1334]
As per https://github.com/blog/2178-multiple-assignees-on-issues-and-pull-requests

This feature is amazeballs, and [we](https://github.com/Particular) want to start using it ASAP. Currently, we list all the assignees in a CSV string in the issue description (e.g.https://github.com/Particular/NServiceBus/issues/3342), and we have [some automation](https://github.com/Particular/PBot/blob/master/src/PBot/Issues/Pig.cs) to pull all of this out for each person to be able to see which issues they are involved in. We also include any issues to which someone is assigned. To allow us to gradually transition to using multiple assignees instead, we'd like this automation to understand multiple assignees too, but it looks like Octokit doesn't yet support this, would that be correct? I.e.

``` C#
public class RepositoryIssueRequest : IssueRequest
{
    public string Assignee { get; set; }
    public string Creator { get; set; }
    public string Mentioned { get; set; }
    public string Milestone { get; set; }
}
```

**Comment by adamralph** [comment]
The code I pointed is for the query, of course. I could also just retrieve all issues, and look through the list of assignees, but it seems like that list is also not yet exposed. `Octokit.Issue` only has a singular `Assignee` property.

**Comment by shiftkey** [comment]
@adamralph you are correct in that support isn't there.

I haven't had a chance to review all the areas where it's needed (I'm trying to wrap up the pagination release right now) but I'd love to see this happen.

cc @shana @paladique - we were discussing this just after it was made public.

**Comment by adamralph** [comment]
@shiftkey by chance, do you know if the API exposes it yet? I guess I could drop down to bare metal temporarily, depending on how you think Octokit might get his.

**Comment by shiftkey** [comment]
@adamralph I'll defer to @shana and @paladique to talk about their urgency for this being implemented, my focus is currently on other things at the moment...

**Comment by ryangribble** [comment]
Changes were only announced a few days ago so yeah, not implemented in octokit just yet! 😀 

These are the details of the API changes if it helps:
https://developer.github.com/changes/2016-5-27-multiple-assignees/

Listing and creating and editing issues has new "assignees" parameter but there isn't any mention of the search API behaviour although you would hope it would now return an issue where the user was among the multiple assignees. 

You need to set the custom accept header to enable the preview mode so hopefully once that's specified, the search query may work as you want. Otherwise you'd have to grab all (open?) issues then query over the assignees

**Comment by adamralph** [comment]
@ryangribble thanks very much for the info. Very useful. We don't have enormous urgency to support this in our automation so we may just wait for this to come out of preview (and be supported in Octokit) but in the meantime, if we do experiment with it, we'll report back and let you know how we get on.

**Comment by shiftkey** [comment]
@adamralph we're usually keen to get preview support into the APIs (we've not been burned by this yet) so expect it before GitHub drops the preview support and makes it part of the official API...

**Comment by ryangribble** [comment]
yeah sorry if that was misleading, from my observations such features sit in "preview" for a looooong time, so we definitely look to expose the preview functionality in octokit.net as soon as we can :grinning:

**Comment by shana** [comment]
Looks like @paladique will start working on this in the next few days so hopefully you'll have this very soon 😄

**Comment by adamralph** [comment]
@paladique @shana has any progress been made on this?

**Comment by shana** [comment]
@adamralph I believe so, there's an open PR by another contributor that adds this. I'm not sure what the status of it is, looks like it's bumped against some architectural issues and it's not finished yet. Work is ongoing at https://github.com/octokit/octokit.net/issues/1339.

**Comment by adamralph** [comment]
@shana looking back through this issue, I don't think I've been specific enough about my use case, and I'm not convinced that #1339 supports it.

I want to search for issues assigned to a particular user. Currently, using `RepositoryIssueRequest` an issue will only be returned if the user is the *first* assignee on the issue. If the user is the 2nd, 3rd, 4th assignee, the issue will not returned. Can you confirm that #1339 will fix this?

**Comment by shana** [comment]
@adamralph That is a very good question. I think it's best if you post this use case in #1339 so that everyone is aware of it.

**Comment by adamralph** [comment]
@shana thanks I did so https://github.com/octokit/octokit.net/pull/1339#issuecomment-231397033

Also, it turns out my immediate use case is solved already, without requiring changes to Octokit: https://github.com/octokit/octokit.net/pull/1339#issuecomment-231408854

**Comment by Eilon** [comment]
Per my latest comment at https://github.com/octokit/octokit.net/pull/1339#issuecomment-268691145, I think this should also include adding this for PullRequest (and not just Issue).
