### ISSUE TITLE
How do I get an Issue "closed_by" data?  

### ISSUE THREAD

**Issue by lbrader** [octokit/octokit.net#1350]
https://github.com/octokit/octokit.net/blob/master/docs/issues.md

I'm trying to retrieve an issue json with the "closed_by" data.  I can get a JSON value back, but it's missing the "closed_by" data.

**Comment by maddin2016** [comment]
That's right. `ClosedBy` Attribute is missing. @shiftkey, is there any reason why this attribute is missing. Otherwise we can added to `IssueClient.cs`.

**Comment by ryangribble** [comment]
No reason for it to be missing...  just historical really,and evidently nobody has raised it/needed it until now

**Comment by lbrader** [comment]
Thanks!  And great work on Octokit.
