### ISSUE TITLE
Missing Properties in Milestone Class

### ISSUE THREAD

**Issue by shaggygi** [octokit/octokit.net#1358]
Why doesn't the Milestone Class provide a HtmlUrl property similar to the Repository Class?  I noticed there is a Url property and the JSON returned includes a tag for html_url.  Is there another approach to get this information?

**Comment by ryangribble** [comment]
Any missing properties are not likely to be intentional, more so just historic or accidental. 

Would you be happy to send a pull request that adds the property?

**Comment by shaggygi** [comment]
Yes, I'll look into the PR.

**Comment by ryangribble** [comment]
Great!  Let us know if you need any help :+1:

**Comment by SeanKilleen** [comment]
I believe this was closed via #1489.
