### ISSUE TITLE
Deserialization error on Activity type

### ISSUE THREAD

**Issue by dampir** [octokit/octokit.net#1374]
When I've tried implement new integration tests for IEventsClient.GetAllIssuesForRepository I've found out that Activity class cannot be deserialized by SimpleJsonDeserializer, because of this part of code 
(https://github.com/octokit/octokit.net/blob/master/Octokit/Http/SimpleJsonSerializer.cs#L121 - https://github.com/octokit/octokit.net/blob/master/Octokit/Http/SimpleJsonSerializer.cs#L127):

```csharp
else if (jsonValue != null)
                {
                    if (type == typeof(Activity))
                    {
                        _type = jsonValue["type"].ToString();
                    }
                }
```

Type field not belongs to Activity JSON response. So, what we should do here? Maybe it is deprecated code and it can be removed for now?

/cc @shiftkey , @ryangribble

**Comment by shiftkey** [comment]
@dampir do you have a example of the failing test? I came across this a while ago, and I thought I wrote up an issue but perhaps I didn't...

**Comment by shiftkey** [comment]
Ah, I did: #1251

**Comment by shiftkey** [comment]
Closing this one in favour of #1251 - I'll add some notes in there about what I've found recently...
