### ISSUE TITLE
ApiValidationException failure when searching some repos for filename without a search term

### ISSUE THREAD

**Issue by dsplaisted** [octokit/octokit.net#1381]
I am using Octokit.NET to search GitHub repos for `project.json` files.  This means [searching for a filename without specifying a search term](https://github.com/octokit/octokit.net/pull/1338).  When I try to do this with some repos, I am getting an ApiValidationException, with the following response body:

```json
{
    "message": "Validation Failed",
    "errors": [{
        "message": "The listed users and repositories cannot be searched either because the resources do not exist or you do not have permission to view them.",
        "resource": "Search",
        "field": "q",
        "code": "invalid"
    }],
    "documentation_url": "https://developer.github.com/v3/search/"
}
```

An example repo I get this error for is [brandonlw/Psychson](https://github.com/brandonlw/Psychson).  [The same search](https://github.com/brandonlw/Psychson/search?utf8=%E2%9C%93&q=filename%3Aproject.json) is successful for me when searching via the web interface.  A repo I am able to search correctly is [dotnet/corefx](https://github.com/dotnet/corefx).  The value of the `X-GitHub-Request-Id` header for one of the failures is `836BA072:B215:326D768E:576049EB`.

Am I doing something wrong or trying to do something I don't have permission for?  Or why is this failing for me?

**Comment by shiftkey** [comment]
This HTTP request seems to work for me:

```
> curl https://api.github.com/search/code\?q\=filename:project.json+repo:brandonlw/Psychson
{
  "total_count": 0,
  "incomplete_results": false,
  "items": [

  ]
}
```

Which corresponds to this code with Octokit v0.20:

```
var request = new SearchCodeRequest
{
    FileName = "project.json",
    Repos = new RepositoryCollection
    {
        "brandonlw/Psychson"
    }
};

var results = await client.Search.SearchCode(request);
var count = results.TotalCount;
```

But both of these queries don't return results, which seems to be the same as the web result mentioned above. Swapping in `dotnet/corefx` for the repository entry then returns 571 results.

Not sure what I'm missing here @dsplaisted, let me know if I've missed something...

**Comment by dsplaisted** [comment]
OK, debugging a bit more, it looks like the issue is I'm actually searching the `adamcaudill/Psychson`.  The web interface redirects this to `brandonlw/Psychson`, but the API is giving the failure I describe.  Is there a way via the API to check if the user (or repo) ID has been changed?

**Comment by shiftkey** [comment]
Yep, I see the same failure now.

```
> curl https://api.github.com/search/code\?q\=filename:project.json+repo:adamcaudill/Psychson
{
  "message": "Validation Failed",
  "errors": [
    {
      "message": "The listed users and repositories cannot be searched either because the resources do not exist or you do not have permission to view them.",
      "resource": "Search",
      "field": "q",
      "code": "invalid"
    }
  ],
  "documentation_url": "https://developer.github.com/v3/search/"
}
```

> Is there a way via the API to check if the user (or repo) ID has been changed?

Octokit.net follows these redirects directly - but the search endpoints doesn't give us that context. If you hit the endpoint you should receive a 301 with a response like this:

```
> curl https://api.github.com/repos/adamcaudill/Psychson
{
  "message": "Moved Permanently",
  "url": "https://api.github.com/repositories/24504893",
  "documentation_url": "https://developer.github.com/v3/#http-redirects"
}
```

And then a GET gives you the new repository name:

```
> curl https://api.github.com/repositories/24504893
{
  "id": 24504893,
  "name": "Psychson",
  "full_name": "brandonlw/Psychson",
  "owner": {
    ...
  },
  ...
}
```

**Comment by shiftkey** [comment]
Closing this out as a limitation with the search endpoint (and not something we can fix in the client).

On the upside, [it's been acknowledged](https://twitter.com/pea53/status/742909469076529152)
