### ISSUE TITLE
Repository Invitations Changes

### ISSUE THREAD

**Issue by ryangribble** [octokit/octokit.net#1399]
### Summary
Recently announced on this [blog post](https://developer.github.com/changes/2016-06-14-repository-invitations/), Repository Invitations are now in preview in the GitHub API with changes in the following areas:

[Repository Collaborators](https://developer.github.com/v3/repos/collaborators/#add-user-as-a-collaborator) API
[Repository Invitations](https://developer.github.com/v3/repos/invitations/) API (new)

### Repository Collaborators
[Adding a collaborator](https://developer.github.com/v3/repos/collaborators/#add-user-as-a-collaborator) can now send an invite to the collaborator rather than directly adding them.  

In octokit.net this could be implemented by copying the [`Add()`](https://github.com/octokit/octokit.net/blob/26cc074d743612fc1f0c9268dad1e4c2a15c3fc4/Octokit/Clients/IRepoCollaboratorsClient.cs#L59) to create an `Invite()` function (and setting the new preview accepts header on the Http Post call in the `Invite()` call).

### Managing Invitations
A new `Invitations` API has been added to `Repositories`

In octokit.net this should be implemented as `IRepositoryInivtationsClient` and be a sub client of the `IRepositoriesClient` accessed by `GitHubClient.Repository.Invitation` with methods
- `GetAll()`
`GET /repositories/:repo_id/invitations`
- `Delete()` 
`DELETE /repositories/:repo_id/invitations/:invitation_id`
- `Update()` 
`PATCH /repositories/:repo_id/invitations/:invitation_id`
- `GetAllForCurrent()` 
`GET /user/repository_invitations`
- `Accept()` 
`PATCH /user/repository_invitations/:invitation_id`
- `Decline()` 
`DELETE /user/repository_invitations/:invitation_id`

Reminder that like all functionality in "preview mode" a custom accepts header needs to be specified (see AcceptHeaders.cs)

> To access the API during the preview period, you must provide a custom media type in the Accept header:
> `application/vnd.github.swamp-thing-preview+json`

### Working on this issue
This issue has been flagged as `up-for-grabs` as it is a reasonably easy issue for a new contributor to pick up, and be guided through the process of contributing to octokit
(that said, if an existing contributor wants to work on this, by all means go for it!)

Please comment here if you want to take this issue.

Please read and follow the [CONTRIBUTING guide](https://github.com/octokit/octokit.net/blob/master/CONTRIBUTING.md) guide and if you need any help, just ask!  Don't be afraid to open a `[WIP]` (work in progress) Pull Request once you've started implementing the changes

**Comment by maddin2016** [comment]
Hi @ryangribble , i would take this issue.

**Comment by maddin2016** [comment]
Hi @ryangribble @shiftkey i'm almost finished with this issue. There is one strange thing with this api. I have create an integration test to send an invitation. The callback from the api ist fine, but it sends no invitation (email). I have tested this also with a real example. Can you confirm this behavior?

**Comment by shiftkey** [comment]
@maddin2016 it'd be much easier to investigate the behaviour when the code is handy - let's look into that after opening the PR...
