### ISSUE TITLE
Impossible to use in ConsoleApp when ConsoleApp is running on .Net 4.6.1

### ISSUE THREAD

**Issue by tebeco** [octokit/octokit.net#1412]
Hi,
I've just created a new project on vs2015.3
Template used : Console Application
Framework : .net 4.6.1

I've just ran :
Install-Package Octokit

Then I tried to connect the Entreprise Github with this simple code to fect a user repository.
The Application Crash around the first "await" that call octokit code (a simple Repository fetch).

I've added the code to the "Octokit" Github solution to debug it, to find out that all the network connectivity is base on :
HttpClientAdapter, RedirectHandler, DelegatingHandler

and it seems that the "base.SendAsync" in this "RedirectHandler" crash the AppDomain.

I've tried to :
* surround it with try/catch (tried to catch Excetion/AggregateException)
* Suscribre to AppDomain UnhandledExcetion 
* Force Exception Settings to throw everything

nothing seems to affect the crash, there's just no way to get this exception and to use octokit.

But based on these class name I've tried to create a "WebApi" project instead, and it seems to work a bit better ... I'm still having other issues, (works on postman but not Octokit)
> await client.Repository.Create("myName", "MyNewRepo").ConfigureAwait(false)

**Comment by ryangribble** [comment]
Can you please post your example code here or in a gist or repo?

**Comment by tebeco** [comment]
Of course the code is copy pasted from :

https://github.com/octokit/octokit.net/blob/master/samples/linqpad-samples/6-create-repository.linq

Changes :
* ".Dump" method extension seems to comes from linqPad only so I've deleted lines
* I've replaced "client.GitDatabase.xxx" by "client.Git" since this is obsolete code.
* Used a new ProductHeaderValue
* used my Entreprise Account line 21
* replace line 27 with OAuth token : client.Cred = new Cred("tokenAsString");
* replaced line 30 with associated mail

**Crash on line 38**

**Comment by tebeco** [comment]
Ok so I just had a lucky Guess

Octokit is not compliant with ConsoleApp **if consoleApp is buit with 4.6.1**

It seems to crash a "MethodNotAllowed" exception if i'm targetting 4.5

**Comment by tebeco** [comment]
@ryangribble any idea for the MethodNotAllowed ?

Let's say that :
* my Entreprise expose Github on : https://corp.github.pouet/
* My account is on : https://corp.github.pouet/tebeco
* I created an OAuth token : a12345bcd

The generated request has the following params when it's rejected ::
(File Connection.cs line 543)

> request.BaseAdress : https://corp.github.pouet/api/v3
> request.EndPoint : {user/repos}
> request.Body : "{\"name\":\"SampleRepo\"}"
> request.Method : "POST"
> request.Parameters : Count = 0
> request.Headers[0] : {[Accept, application/vnd.github.quicksilver-preview+json;......]}
> request.Headers[1] : {[User-Agent, myProductHeaderValue]}
> request.Headers[2] : {[Authorization, Token a12345bcd]}

**Comment by shiftkey** [comment]
@tebeco there's documentation about enabling source debugging for Octokit here: http://octokitnet.readthedocs.io/en/latest/debugging-source/

This will mean you don't need to worry about referencing the source.

> Octokit is not compliant with ConsoleApp if consoleApp is buit with 4.6.1
> It seems to crash a "MethodNotAllowed" exception if i'm targetting 4.5

Could you confirm which version is the problem?

**Comment by tebeco** [comment]
wich version of what ?

I've cloned "Octokit" and added a console app INSIDE the solution
this consoleApp is using framework 4.6.1
And this project has a "Project reference" to the Octokit.net project

No tricks, then it will crash
My guess is that the framework 4.6.1 changed BCL for the stack octokit uses (from 4.5)

**Comment by shiftkey** [comment]
> wich version of what ?

Which version of the .NET Framework you are targeting - are you saying that both .NET 4.5 and 4.6.1 are affected?

These are the steps that I used in Visual Studio 2015 Update 3 to see if I can understand the issue as you see it:

 - create a new console application targeting .NET 4.6.1
 - In NuGet Package Console, run this command: `Install-Package Octokit`
 - replace the contents of Program with this:

```csharp
class Program
{
    static void Main(string[] args)
    {
        Run().Wait();
    }

    private static async Task Run()
    {
        var client = new GitHubClient(
            new ProductHeaderValue("Octokit.samples"), new Uri("https://corp.github.pouet/"));

        var owner = "tebeco";
        var reponame = "testing-repo-creation-" + Environment.TickCount;
        client.Credentials = new Credentials("a12345bcd"); // populate the whole token here

        // 1 - create a repository through the API
        var newRepo = new NewRepository(reponame)
        {
            AutoInit = true // very helpful!
        };

        var repository = await client.Repository.Create(newRepo);
    } // set a breakpoint here
}
```

 - set a breakpoint inside the closing bracket of the `Run()` method
 - `F5` to run the console app 

I tested this code against a version of GitHub Enterprise and didn't encounter an issue. **Could you confirm that these steps work for you?**

> No tricks, then it will crash
> My guess is that the framework 4.6.1 changed BCL for the stack octokit uses (from 4.5)

I couldn't find anything using the above repro steps, so I need more information to help troubleshoot further. Given you're not able to catch any sort of exceptions, I fear something isn't right with your installation of VS (or .NET).

What about if you had a console app that was just this? Does that also let you handle the error within the debugger?

```csharp
class Program
{
    static void Main(string[] args)
    {
        throw new NotImplementedException();
    }
}
```

**Comment by tebeco** [comment]
(just changed this issue title)
I'm redoing the steps you did above to double check
I'll delete this answer just after ^^

**Comment by tebeco** [comment]
So ...
The fact that I catch nothing is only happening if I use Octokit inside a 

ConsoleApp 461               KO
ConsoleApp is 4.5             OK
WebApi 461                       OK

I can catch any exception without issue in any configuration/plateform or whatever in any project BUT the configuration octokit + consoleApp 461
My guess is that there's a segfault or something like that. It seems that VisualStudio unload the AppDomain "the hardway".
And since octokit is using "Web" BCL classes and these one changed ... I think it comes from that

**FYI : the oldest framework supported is 4.5.1 and octokit uses 4.5
I've moved octokit to .net 4.6.1 it solves this crash**

**I strongly recommend the move to .net 461 to avoid this kind of behavior since there's been lots of changes in the BCL around httpClient & so on**

**Comment by tebeco** [comment]
For the "MethodNoAllowed" issue
It seems that :
> new ProductHeaderValue("Octokit.samples")
does not allow me to set a custom values ... it works perfectly until I change it with :

> new ProductHeaderValue("abc")

**Comment by shiftkey** [comment]
> I strongly recommend the move to .net 461 to avoid this kind of behavior since there's been lots of changes in the BCL around httpClient & so on

Thanks for the suggestion, but I'm very hesitant to drop this compatibility as I have an application that's been using Octokit targeting .NET 4.5 for 2+ years and I've not had any users encounter this issue.

> ... not always I really don't get it it's like there's a cache but when I got the exception, I play with the user agent and it seems to works again. Like there's a 50/50 chance

This is interesting, and not something I've seen before. Do you have a stack trace that illustrates the error when this occurs?

**Comment by shiftkey** [comment]
I'm going to close this out as I'm not sure what the next steps are to resolve this.
