### ISSUE TITLE
[Question] Fork repository with all issues, labels and assignees

### ISSUE THREAD

**Issue by shaggygi** [octokit/octokit.net#1424]
Is this possible or would you have to create each programmatically after forking?

**Comment by shiftkey** [comment]
@shaggygi you would have to repopulate the issues in the new repository after forking

**Comment by shaggygi** [comment]
I was able to do this as mentioned, but wasn't sure if there as a call that could do in one attempt instead of individually.  I also had to add the labels and assignees one at time, as well.  @shiftkey  Are you saying this is the case or is there a method to copy the entire issue(s) contents (body, labels, assignees, etc.) to new fork at one time?

Thanks again for the help.

**Comment by shiftkey** [comment]
@shaggygi unfortunately there isn't a method to do this all in one API call
