### ISSUE TITLE
[Question] Change repository name when forking

### ISSUE THREAD

**Issue by shaggygi** [octokit/octokit.net#1425]
Is there a way to change the name of a repository when forking another?  Meaning, if there is an original repository (e.g. organization/foundation) and I want to fork and rename to myuser/foundation-build, how would you rename when forking with Octokit?

Thx

**Comment by shiftkey** [comment]
@shaggygi I'm not aware of a way through the GitHub API to script forking repositories. However, if you've already created the repository you can rename it through the API.

This snippet from @M-Zuber is an example of doing the rename:

```csharp
private static async Task Rename()
{
  var apiClient = new GitHubClient(new Octokit.ProductHeaderValue("Issue-Managment")) /* Put credentials here */;
  var repoName = $"test-{DateTime.UtcNow.ToBinary()}";
  var repo = await apiClient.Repository.Create(new NewRepository(repoName));
  Console.WriteLine($"Created repo {repo.Name} under {repo.Owner.Login}");

  repo = await apiClient.Repository.Edit(repo.Owner.Login, repo.Name, new RepositoryUpdate { Name = $"{repo.Name} ll {repo.Name}" });
  Console.WriteLine($"Repo renamed to {repo.Name}");
}
```

**Comment by shaggygi** [comment]
That did the trick @shiftkey Thanks!
