### ISSUE TITLE
[Question] Enable issues in a fork

### ISSUE THREAD

**Issue by shaggygi** [octokit/octokit.net#1426]
Is it possible to enable issues with Octokit after creating a fork?  I notice you must go into the repository's settings > features section and check the Issues box before issues can be created in site or via Octokit.

**Comment by shiftkey** [comment]
Similar to #1425, you can set `HasIssues` when editing the repository through the API to change this behaviour...

**Comment by shaggygi** [comment]
Yes, just came across this property.  Thanks
