### ISSUE TITLE
Git LFS Support

### ISSUE THREAD

**Issue by bmd-benita** [octokit/octokit.net#1429]
Is there any way to download file from Git LFS?
I have tried to download text file from GitHub using this script, but the files from Git LFS cannot be convert to base64String:
`Dim blob = Await GitHubClient.Git.Blob.Get(Owner, Repository, fileSHA)
File.WriteAllBytes(DestinationFilePath, Convert.FromBase64String(blob.Content))
`
What should I do? What action should be taken to download dll, xml, and other file type?

Thanks.

**Comment by ryangribble** [comment]
Interesting question, there's nothing in the github API for git LFS specifically. I'd assume if you really need to do this you'd need to manipulate an actual git workspace using git cmdline or maybe libgit2 

As an aside I wouldn't expect dll or xml files to normally be setup to use LFS, it's normally only for huge files compared to typical dll or xml files

**Comment by shiftkey** [comment]
@bmd-benita what do you get back from the server when the file is GitLFS-enabled?

**Comment by bmd-benita** [comment]
The file itself. 
I have tracked .dat, .dat.gz, .xml, .dll for Git LFS. I want to get these files (download the files) to my local computer from the application using Octokit.

**Comment by rquackenbush** [comment]
Any update on this? I'm interested in doing the same thing.

**Comment by shiftkey** [comment]
I don't believe this has changed since I last checked. We're limited by what's available and supported in the GitHub API, so I recommend contacting [GitHub Support](https://github.com/contact) about the underlying issue.

If we see documentation about this we can then support it in Octokit, we can revisit this.
