### ISSUE TITLE
[Question] Markdown support with WPF app

### ISSUE THREAD

**Issue by shaggygi** [octokit/octokit.net#1430]
Anyone have examples of using GitHub Markdown with a WPF app?  Understanding, this is more of a GitHub question, I thought I would check here to see if someone came across the feature and possibly using it with Octokit.NET.  Thx

**Comment by shiftkey** [comment]
If you can render HTML in your WPF app (using the WebBrowser control or something like CefSharp), then you can just use Octokit.NET to generate the GitHub-flavoured Markdown directly:

```csharp
var github = new GitHubClient(/* setup */);
var html = await github.Miscellaneous.RenderRawMarkdown("This is a **test**");
```

I'm not aware of any libraries that support client-side rendering of GitHub-flavoured Markdown, but you can see an old [SO thread](http://stackoverflow.com/questions/8210974/markdownsharp-github-syntax-for-c-sharp-code) discussing some options.

I'll leave this open for a bit to see if anyone else has bright ideas here...

**Comment by khellang** [comment]
I think you should be able to tweak [Markdig](https://github.com/lunet-io/markdig) to render GFM pretty close to what GitHub itself does, if you want to avoid the roundtripping.

**Comment by shaggygi** [comment]
Came across this today, but is for UWP.
http://docs.uwpcommunitytoolkit.com/en/dev/controls/MarkdownTextBlock/

**Comment by shiftkey** [comment]
Closing this out due to inactivity.
