### ISSUE TITLE
[Question] How to upload avatar image

### ISSUE THREAD

**Issue by shaggygi97test** [octokit/octokit.net#1431]
Does Octokit.NET have the ability to upload an avatar image?  If not, is this something that must be performed in the user's bio?  Thx

**Comment by shiftkey** [comment]
@shaggygi97test unfortunately we can't set the avatar when [updating the user](https://developer.github.com/v3/users/#update-the-authenticated-user). This is still a manual task :cry:

**Comment by shaggygi** [comment]
Maybe one day.  Thx for the reply.
