### ISSUE TITLE
Cannot add labels to issue

### ISSUE THREAD

**Issue by martinnormark** [octokit/octokit.net#1438]
I'm trying to create an issue with labels, the below code is what I'm using:

```csharp
string token = "...";

GitHubClient client = new GitHubClient(new ProductHeaderValue("OctoBot"));
client.Credentials = new Credentials(token);

string title = payload.Issue.Title;

var createIssue = new NewIssue(title);
createIssue.Body = payload.issue.fields.description;
createIssue.Labels.Add("bug");
createIssue.Labels.Add("jira:sub-task");

var issue = client.Issue.Create("ORGNAME", "REPONAME", createIssue).Result;
```

I'm not getting any errors, and the issue is being created just fine. I just don't get the labels added to the issue. I have verified, and the labels already exists in the repo.

I tried sending an update to the issue adding labels via `AddLabel()` but that doesn't solve it.

Anything I'm doing wrong?

**Comment by ryangribble** [comment]
Do you have push access to the repository? The github API docs say that setting labels requires push access and if you don't have that, any labels (and assignees etc) are dropped

**Comment by martinnormark** [comment]
I do have push access. The token I'm using is a Personal Access Token - perhaps that is not enough?

**Comment by ryangribble** [comment]
Could be, depending on what scopes you've granted the personal access token You could also attempt user/pwd just to see if it changes anything 

Otherwise if you want to post your code sample we can take a look?

**Comment by martinnormark** [comment]
Doh, I messed up the permissions so in fact the user didn't have push access to the repo. Thanks for your input.
