### ISSUE TITLE
[Question] Add file to an Issue

### ISSUE THREAD

**Issue by shaggygi** [octokit/octokit.net#1439]
Could you explain how to add a file (e.g. Text.txt) to an Issue using Octokit.NET?  Thx

**Comment by ryangribble** [comment]
Are you referring to attachments on the issue? There doesn't appear to be any GitHub API method to do this, it seems only available through the webUI

**Comment by shaggygi** [comment]
Yes, I wanted to know if there was a way to attach a file via the API like you would when dragging/dropping on the Issue in GitHub website.  Basically, I want to programmatically create an Issue, add some markdown comments and attached a file.  It seems like there would be some type of method to do this.  If Octokit is currently not able to do so, do you know the next steps to take in determining if it possible?  Thx for the help.

**Comment by shiftkey** [comment]
@shaggygi I'm afraid this isn't currently supported, and I'm not sure of an ETA for it

**Comment by shaggygi** [comment]
@shiftkey Thanks for the info.  If I could ask one more question.... do you mean it is not supported in Octokit or it is not a supported feature in GitHub in general?  Meaning, you don't know of ETA coming with GitHub?  Thanks again.

**Comment by shiftkey** [comment]
@shaggygi it's not currently a supported feature of the GitHub API
