### ISSUE TITLE
migrate build scripts over to CAKE

### ISSUE THREAD

**Issue by shiftkey** [octokit/octokit.net#1440]
I've had some interest from various corners about moving our build scripts over to [Cake](https://github.com/cake-build/cake). The process seems very similar to what we're doing currently, so I'm not really going to stand in the way.

Things I'd like to verify are possible with Cake (mostly due to emulating our current flow for releasing things):
- use `dotnet` CLI tools to build, rather than MSBuild
- `AssemblyInfo` generation from our `ReleaseNotes.md` file
- SourceLink support (there's a nice helper for FAKE, but I gather there's a way to do it directly for our scenario)

Also note that these things in the current scripts will be made redundant by the migration to using the `dotnet` CLI, so I wouldn't worry about investing too much time in porting them over:
- generating NuGet packages (although we might need to do some manual unpacking/repacking to get it working with NuGet) 
- running xUnit tests

**Comment by ryangribble** [comment]
> SourceLink support (there's a nice helper for FAKE, but I gather there's a way to do it directly for our scenario)

Just on this point, I stumbled upon [GitLink](https://github.com/GitTools/GitLink) which sounds like it may do the same thing as what SourceLink currently does.  CAKE has [built in aliases](http://cakebuild.net/api/cake.common.tools.gitlink) for GitLink

**Comment by shiftkey** [comment]
@ryangribble if GitLink gives us the same end result, then I'm fine with switching. I forget the backstory and why they didn't team up way back in the day...

**Comment by ryangribble** [comment]
Hmmm so it turns out both SourceLink and GitLink dont support dotnetcore project.json and .xproj files which is a bit of a bummer in terms of our own dotnetcore move (which isnt strictly related to moving to CAKE however I was kind of intending to do it all at the same time)

GitLink [aren't planning on doing anything](https://github.com/GitTools/GitLink/issues/83) until project.json goes away (although Im not sure when that actually will occur), and SourceLink were [waiting for upstream depedencies](https://github.com/ctaggart/SourceLink/issues/121) as of a few months ago which are hopefully now in place so there could be hope there...

**Comment by ghuntley** [comment]
Yo @shiftkey I'd suggest using `gitversion` to automatically version your releases and generating release notes using `GitReleaseManager` which automatically builds RELEASENOTES.md from closed github issues + github tags. 

See https://github.com/reactiveui/ReactiveUI/blob/develop/GitReleaseManager.yaml  and https://github.com/reactiveui/ReactiveUI/blob/develop/GitVersion.yml

Doing `RELEASENOTES.md` is something I regret and am glad to :fire: in RxUI 7.0

**Comment by ghuntley** [comment]
Additionally, once netstandard migration is done you can move 100% to appveyor and get rid of travisci.

**Comment by ryangribble** [comment]
Yep all sounds good.  The cake stuff i was playing with already is using GitVersion [see here](https://github.com/octokit/octokit.net/pull/1476/files#diff-7ee6d77108fc6e231391468494148b63R76)

So far i mostly based my cake stuff off [Bddfy cake scripts](https://github.com/TestStack/TestStack.BDDfy) but I'll take a look at akavache

**Comment by ryangribble** [comment]
Closed by #1581
