### ISSUE TITLE
Implement Repository Traffic preview API

### ISSUE THREAD

**Issue by ryangribble** [octokit/octokit.net#1447]
As per [this announcement](https://developer.github.com/changes/2016-08-15-traffic-api-preview/) there is a new "Repository Traffic" API

I'll flesh this issue out later, but just logging it now so we don't miss it.

**Comment by maddin2016** [comment]
Hi @ryangribble, i would like to take this issue. I would create a new client `IRepositoryTrafficClient`!?

**Comment by ryangribble** [comment]
Yep, based on the [API structure](https://developer.github.com/v3/repos/traffic/) that sounds good, and it would be a child `Traffic` property under the existing `RepositoriesClient` so we would access it like `client.Repository.Traffic.GetAllReferrers()`
