### ISSUE TITLE
Add support for API change to update base branch of a PullRequest

### ISSUE THREAD

**Issue by ryangribble** [octokit/octokit.net#1449]
As per this [recent anouncement](https://developer.github.com/changes/2016-08-23-change-base/) the API now supports changing the base branch of an existing pull request (woohoo!!!).

The [Update a pull request](https://developer.github.com/v3/pulls/#update-a-pull-request) endpoint now accepts a `base` string field on the request to do this.

For octokit.net this is pretty simple - we just need to add the `Base` string property to our existing `PullRequestUpdate` request class and update a few tests

**Comment by M-Zuber** [comment]
If this is still open, I'd like to take it
