### ISSUE TITLE
Octokit Update

### ISSUE THREAD

**Issue by di48l069** [octokit/octokit.net#1451]
Hi,

Im using Octokit as a updater where it would download blabla.msi from my releases but my problem is my project is private how would I give it access to my private repro?

**Comment by ryangribble** [comment]
You would need to use credentials (personal access token) that has access to the private repository, which may not be desirable. 

If you are determined to use github release files as your file storage then perhaps another way would be to have a public repo that only contains a readme file and release notes etc that you could create/mirror your releases in and have your download msi there etc. You could also have issues turned on in that public repo so your users could raise issues with you

**Comment by di48l069** [comment]
@ryangribble Thank you

**Comment by di48l069** [comment]
@ryangribble Can I maybe invite you to my private repro can you give me a quick example on how to add credentials (personal access token) so I can download from my private repro

**Comment by shiftkey** [comment]
@di48l069 there's [an example](http://octokitnet.readthedocs.io/en/latest/getting-started/#authenticated-access) in the documentation about passing in a Personal Access Token

**Comment by di48l069** [comment]
@shiftkey Thanks just what i'm looking for!

**Comment by di48l069** [comment]
@shiftkey  Please see attachment is this best way to do token part?
[ReleaseInfo.zip](https://github.com/octokit/octokit.net/files/450606/ReleaseInfo.zip)

**Comment by shiftkey** [comment]
@di48l069 that seems fine
