### ISSUE TITLE
Construction of ReadOnlyCollection in RepositoriesClient.GetAllLanguages() method can throw null argument exception

### ISSUE THREAD

**Issue by aaronhoffman** [octokit/octokit.net#1465]
see here: https://github.com/octokit/octokit.net/blob/master/Octokit/Clients/RepositoriesClient.cs#L792

If this method is called and the API does not return a value, a null argument exception is thrown by the ReadOnlyCollection constructor.

example repo: vhf/free-programming-books  (id: 13491895)

Note: I'd like to contribute by opening a PR for this issue. I first need to investigate how "empty" results from the API are handled by other methods.

**Comment by shiftkey** [comment]
This seems plausible according to [the reference source](https://github.com/Microsoft/referencesource/blob/master/mscorlib/system/collections/objectmodel/readonlycollection.cs#L27-L32), but I'm not sure why this code shouldn't return an empty enumerable when there are no values in the response:

```csharp
data.Select(kvp => new RepositoryLanguage(kvp.Key, kvp.Value)).ToList()
```

**Comment by aaronhoffman** [comment]
I'll need to double check. I believe that was the exception and stack trace I was seeing, but I agree that the `.ToList()` should not return `null`.
