### ISSUE TITLE
Uploading new public key to user account

### ISSUE THREAD

**Issue by hbons** [octokit/octokit.net#1467]
I can't find the API for this function. Is it possible? If not, could Octokit.net support this? :)

**Comment by ryangribble** [comment]
Do you mean SSH key?  If so it's at `client.User.GitSshKey.Create()`

**Comment by shiftkey** [comment]
Alternatively, `client.User.GpgKey.Create()` is the other "key" that the GitHub API supports.

Closing this out as implemented.
