### ISSUE TITLE
Octokit.net supports repo traffic?

### ISSUE THREAD

**Issue by tang-jason** [octokit/octokit.net#1468]
Is the "[traffic](https://developer.github.com/v3/repos/traffic/#views)" supported or will be supported in the near future?

> 
> APIs for repository traffic are currently available for developers to preview. During the preview period, the APIs may change without advance notice. Please see the [blog post](https://developer.github.com/changes/2016-08-15-traffic-api-preview) for full details.
> 
> To access the API you must provide a custom media type in the Accept header:
`application/vnd.github.spiderman-preview`

**Comment by ryangribble** [comment]
@maddin2016 has done the work in PR #1457  which should be merged soon. It should be in the next release 👍

**Comment by tang-jason** [comment]
Awesome! Thanks for the update @ryangribble  👍
