### ISSUE TITLE
Mark RepositoryFormatException.GetObjectData with System.Security.SecurityCritical

### ISSUE THREAD

**Issue by khellang** [octokit/octokit.net#1471]
I'm getting this exception when trying to run a program using Octokit in .NET Fiddle:

> [System.TypeLoadException: Inheritance security rules violated while overriding member: 'Octokit.RepositoryFormatException.GetObjectData(System.Runtime.Serialization.SerializationInfo, System.Runtime.Serialization.StreamingContext)'. Security accessibility of the overriding method must match the security accessibility of the method being overriden.]
  at Program.<GetIssues>d__5.MoveNext(): line 57

> [System.AggregateException: One or more errors occurred.]
  at Program.Main(String[] args): line 16

I think `RepositoryFormatException.GetObjectData` should be annotated with `System.Security.SecurityCritical`, [like its base version](http://referencesource.microsoft.com/#mscorlib/system/exception.cs,548).

I'll PR this if no one beats me to it :smile:

**Comment by M-Zuber** [comment]
Beat you to it 😃
