### ISSUE TITLE
Support Projects preview API

### ISSUE THREAD

**Issue by ryangribble** [octokit/octokit.net#1472]
As per the [recent anouncement](https://developer.github.com/changes/2016-09-14-projects-api/) there is a new API for the Projects functionality

[API docs](https://developer.github.com/v3/repos/projects/)

There are 17 functions to be implemented around Projects, Columns and Cards.  It's also likely that there are `repositoryId` based versions of these functions as well

**Comment by maddin2016** [comment]
Looks like a nice project 😀 In the API they say that pagination is currently not supported. But i've tested with two projects and i can paginate (get the `Link` Header)!!??

**Comment by maddin2016** [comment]
So should we go on with pagination?

**Comment by ryangribble** [comment]
If it works then may as well include the `ApiOptions` overloads :+1:

**Comment by maddin2016** [comment]
Ok. I create PR for this

**Comment by shaggygi** [comment]
Any update on finalizing and when it will be added to NuGet package?  I'm looking forward to this feature.  Great work :+1:

**Comment by shaggygi** [comment]
@ryangribble thanks for working on this.  Do you know when this will be added to nuget package?

**Comment by ryangribble** [comment]
Putting together a new release is next on my list!  

In the meantime now this is merged to master, it will be in the nuget packages on our appveyor feed here: https://ci.appveyor.com/nuget/octokit-net

**Comment by shaggygi** [comment]
@ryangribble thank you
