### ISSUE TITLE
Is "GetReadmeHtml()" supported for subfolder readme?

### ISSUE THREAD

**Issue by tang-jason** [octokit/octokit.net#1478]
Sorry, I couldn't find anything that is related on how to get the readme in html form using `GetReadmeHtml()` in sub-folder structure. 

example: `https://github.com/tang-jason/test1/blob/master/subfolder/helloworld/README.md`

I can get `test1` readme using `Repository.Content.GetReadmeHtml(owner, name)` but how to drill down to sub-folder level to get the readme in html?

**Comment by shiftkey** [comment]
Unfortunately the [Get the README](https://developer.github.com/v3/repos/contents/#get-the-readme) endpoint doesn't support providing a path - that's the behaviour we're using in Octokit.

The [Get Contents](https://developer.github.com/v3/repos/contents/#get-contents) API supports providing a path, and looks like this in Octokit:

```csharp
var files = await client.Repository.Content.GetAllContents("octokit", "octokit.net", "docs/git-database.md");
var text = files[0].Content;
```

However we don't support providing a [custom media type](https://developer.github.com/v3/repos/contents/#custom-media-types) so you could get the rendered markdown. #593 is the open issue discussing that.
