### ISSUE TITLE
revisit RepositoryTrafficClient integration tests 

### ISSUE THREAD

**Issue by shiftkey** [octokit/octokit.net#1487]
I disabled some tests in 0f90d20e3015d7e405160f9348544c7dd5ac16b0 as my test account is not an administrator for the Octokit.net repository - and admin is necessary to see the repository traffic.

Instead, I'd suggest updating this test to use a user-generated repository so the API call doesn't fail. This probably means the deserialized response might not be as compelling, but I think verifying the endpoint works is a good first step.

**Comment by M-Zuber** [comment]
I'm working on trying to figure this out.

If we come up with something that works, there are a number of other tests that are currently skipped for the same reason of needing admin rights

**Comment by M-Zuber** [comment]
The main issue I am hitting is generating any sort of traffic.
Calling `new WebClient().DownloadStringTaskAsync(...)` does not seem to register as a hit.

I see two options:
1. Assert `referrers.Count` is 0
2. Create a browser object, navigate to url, ect, ect.

Is there another option I am missing?

**Comment by ryangribble** [comment]
one other way could be to create a "shared" octokit-test organisation and repo and user, then embed a personal access token for that user into our test code.  This could either be used to run those [RequiresOrgOwner] type tests under, or could also be used behind the scenes to add the user's configured test account to the organization as an owner, so the tests would then work

**Comment by M-Zuber** [comment]
I'm not sure how that is different then what we already have with the user, org, and access token set in environment variables?

**Comment by ryangribble** [comment]
A shared organisation and API key that all octokit contributors would be added to with appropriate permissions so the tests would work (and the data would be real since the repos are existing and not created just for the test)
