### ISSUE TITLE
Unable to add octokit.net package to Xamarin.iOS 10+ projects

### ISSUE THREAD

**Issue by jsauvexamarin** [octokit/octokit.net#1491]
When I try to add the octokit.net package to a Xamarin.iOS project, I get the following package manager output:

```
Attempting to gather dependency information for package 'Octokit.0.23.0' with respect to project 'MyProject.iOS', targeting 'Xamarin.iOS,Version=v1.0'
Attempting to resolve dependencies for package 'Octokit.0.23.0' with DependencyBehavior 'Lowest'
Resolving actions to install package 'Octokit.0.23.0'
Resolved actions to install package 'Octokit.0.23.0'
For adding package 'Microsoft.Net.Http.2.0.20505' to project 'MyProject.iOS' that targets 'xamarinios10'.
Install failed. Rolling back...
Package 'Microsoft.Net.Http.2.0.20505' does not exist in project 'MyProject.iOS'
Package 'Microsoft.Net.Http.2.0.20505' does not exist in folder '/Users/me/Projects/MyProject/src/packages'
Could not install package 'Microsoft.Net.Http 2.0.20505'. You are trying to install this package into a project that targets 'Xamarin.iOS,Version=v1.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
```

This seems to suggest that the package does not support Xamarin projects (or PCLs), even though the readme obviously claims that it does:
https://github.com/octokit/octokit.net#user-content-supported-platforms

Why would your nuget package not be able target Xamarin.iOS? 

Why is the dependency resolution choking on `Microsoft.Net.Http.2.0.20505` when the package config clearly contains a reference to version 2.2.29?: https://github.com/octokit/octokit.net/blob/master/Octokit/packages.Octokit-Portable.config#L5

**Comment by shiftkey** [comment]
@jsauvexamarin it's been a while since I've looked at our Xamarin Studio support (I'm pretty sure my license expired too), so I'm not quite sure how to proceed here.

We've had [Microsoft.Net.Http](https://www.nuget.org/packages/Microsoft.Net.Http/) as a dependency for a while - it's technically a PCL as well, so I'm not sure whether something has changed and we should target something else for the Xamarin platforms.

> Why is the dependency resolution choking on Microsoft.Net.Http.2.0.20505 when the package config clearly contains a reference to version 2.2.29?:

Check out [the nuspec](https://github.com/octokit/octokit.net/blob/master/Octokit.nuspec) as that should be more relevant to the issue here (we don't restrict to a certain version).

**Comment by jsauvexamarin** [comment]
I've actually already begun to take it upon myself to convert the csproj files over to supporting the unified Xamarin.iOS APIs. It's mostly just matter of swapping out the project type GUIDs in the csproj's, and then referencing the new targets.

I'm working on a fork. I should have a PR ready sometime in the next 24 hours. :)

**Comment by jsauvexamarin** [comment]
I'll make sure the entire solution is buttoned up before I submit

**Comment by jsauvexamarin** [comment]
@shiftkey, here's the PR: https://github.com/octokit/octokit.net/pull/1492

**Comment by Ygilany** [comment]
@jsauvexamarin were you able to fix this? I'd really appreciate it if you would point me to a solution or even a workaround for this.

**Comment by shiftkey** [comment]
Closing this out as we've now moved away from PCLs to targeting .NET Standard (we target .NET Standard 1.1).

If you are interested in seeing us support .NET Standard 2 or later, please open a fresh issue so we can discuss it further.
