### ISSUE TITLE
Admin Permission of Team lists out as Pull

### ISSUE THREAD

**Issue by goateey** [octokit/octokit.net#1496]
i'm Trying to get permissions of a team that is associated with the Repo of an org.
 The api lists out as "pull" for a team that has admin "role".  Not sure how to get around with this. Please let know 

private static async Task<string> BasicTest()
{
var ghe = new Uri("https://github.MyCompany.com");
var client = new GitHubClient(new ProductHeaderValue("TEST-APP"), ghe);
client.Credentials = new Credentials("USER-NAME", "PWD");
var repos = await client.Repository.GetAllForCurrent();
List<Report> reportList = new List<Report>();
List<Repository> reposlist = repos.ToList();
foreach (var repo in reposlist)
{
var teams = await client.Repository.GetAllTeams(repo.Id);
foreach (var team in teams)
{
reportList.Add(new Report() { OrgName = repo.FullName, RepoName = repo.Name, TeamName = team.Name, TeamRole = team.Permission.ToString() }); // for a admin team with admin role comes up as pull
}
}
return string.Empty;
}

**Comment by ryangribble** [comment]
Hey @goateey 

What level of access to the organisation/repo do the user credentials you are providing for the API call have?  In order to list out admins you would need to be an owner of the organisation I'm pretty sure

**Comment by shiftkey** [comment]
From the [docs](https://developer.github.com/v3/orgs/teams/)

> All actions against teams require at a minimum an authenticated user who is a member of the Owners team in the `:org` being managed. Additionally, OAuth users require the "read:org" scope.

**Comment by goateey** [comment]
The authenticated user is Site admin and owner of all orgs.. Github version is 2.6.9.... it worked before migrating from 2.4.3

**Comment by goateey** [comment]
The below curl gets me what i want but how can this be achieved via Octokit ?

 curl -u username:password https://github.MyCompany.com/api/v3/teams/<TEAM-ID>/repos -k

**Comment by ryangribble** [comment]
Yes the [API call you highlighted ](https://developer.github.com/v3/orgs/teams/#list-team-repos) is already implemented in octokit as `client.Organization.Team.GetAllRepositories()`

And the reason why the first call you mentioned doesnt work anymore is that the github API only returns limited team information on the "get teams for repo" call, as you can see in the [api docs here](https://developer.github.com/v3/repos/#list-teams).  I cant be certain but I think this all changed when the organization permissions were revamped [back in September 2015](https://developer.github.com/changes/2015-06-24-api-enhancements-for-working-with-organization-permissions/).

The interesting thing is that in GitHub Enterprise this change was in 2.4 so Im not sure why you weren't already running into this.  Perhaps it was only when those organization changes [came out of preview](https://developer.github.com/changes/2016-01-05-api-enhancements-for-working-with-organization-permissions-are-now-official/) and then whichever subsequent GHE release (2.5 or 2.6) that made it into?

Anyway try out the `Team.GetAllRepositories()` and let us know if that works for you?

**Comment by goateey** [comment]
@ryangribble  - thanks that worked.
we migrated recently from 2.4.3 to 2.6.9 and the contractor who was working on this task had his contract ended. So been pulled on to this task... 

Thanks a lot for the help... appreciate it!
