### ISSUE TITLE
Issue Comments - need an overload to take in optional arguments

### ISSUE THREAD

**Issue by shiftkey** [octokit/octokit.net#1500]
Documentation: https://developer.github.com/v3/issues/comments/#list-comments-in-a-repository

Existing methods: https://github.com/octokit/octokit.net/blob/master/Octokit/Clients/IIssueCommentsClient.cs#L36-L66

There should be overloads for each of these methods which accept an parameter which `IssueCommentRequest` and has those fields from the documentation.

**Comment by SeanKilleen** [comment]
I believe this is now closed via #1501.
