### ISSUE TITLE
GetLastApiInfo always returns null

### ISSUE THREAD

**Issue by 101shipit** [octokit/octokit.net#1509]
Using octokit v0.23.0 from nuget I am trying to capture rate limit information from github but whenever I call `gitHubClient.GetLastApiInfo()` it is returning null

**Comment by ryangribble** [comment]
`GetLastApInfo()` returns the `ApiInfo` from the last call that was made - are you making a regular Api call prior to calling it?

Can you provide a code sample reproducing the problem?  (Ive just run through [the integration tests](https://github.com/octokit/octokit.net/blob/master/Octokit.Tests.Integration/Clients/GitHubClientTests.cs#L16) locally and confirm they are passing)

**Comment by SeanKilleen** [comment]
I'm using the `GetLastApiInfo()` as part of a quick console app I'm writing and can confirm it works as expected (null on first call, populated for subsequent calls).

**Comment by Eilon** [comment]
Working just fine for me too, using 0.23.0 in an ASP.NET Core app.

**Comment by 101shipit** [comment]
mmmh, ok can't get it working, always just returns null. Assume it's something weird with my setup and dependency injection perhaps.
Will close this off anyway.

**Comment by SeanKilleen** [comment]
@101shipit if you're creating a new instance of the client per request, the client likely won't ever have the "last request". May want to look at how many instances you're creating within your DI setup.

**Comment by 101shipit** [comment]
Actually it seems to work fine for most client requests except for when calling the search api.
If calling `gitHubClient.Search.SearchIssues(search)` for example then gitHubClient.GetLastApiInfo() is returning null

**Comment by SeanKilleen** [comment]
@101shipit so to make sure I understand, the issue is basically:

| Action | GetLastApiInfo() Result | | 
| ------- | ------------------------- | - | 
| Non-search API call | null | ✅ |
| 2 non-search API calls | has result | ✅ | 
| Search API call | null | ✅ | 
| 2 search API calls | null | ❌ |

Is that correct?

**Comment by 101shipit** [comment]
yes

**Comment by ryangribble** [comment]
While looking at something else I found the reason for this!  

[This condition](https://github.com/octokit/octokit.net/blob/master/Octokit/Http/ApiInfo.cs#L63-L64) causes a null `ApiInfo` object to be stored as `LastApiInfo` if any of the various properties are null.  In my case I was debugging something and the Api response did NOT have an `ETag` header, which meant the `ApiInfo` object was then not attempted to be stored.  

The fix would be remove that condition and just guard against any of the sub elements being `null` but still clone as much of the `ApiInfo` object as is present.
