### ISSUE TITLE
watchers & watchers_count are incorrect

### ISSUE THREAD

**Issue by k0shk0sh** [octokit/octokit.net#1510]
As per the title says, the `watchers` & `watchers_count` are incorrect & always follows the `stargazers_count` I have seen this issue has been reported previously in #699 & that issue is reported back in 2015, now we are entering 2017 & this issue haven't been resolved. 

Steps to produce the issue:  using `("Accept","application/vnd.github.v3+json");`

1. Call Repositories API 
2. Validate the `watchers` & `watchers_count`  with the repo in **Github** 
3. Incorrect count.

Is there any workaround to overcome this issue for the meantime or at least when it can be solved?

**Comment by ryangribble** [comment]
Hey, if you have a read of #1470 there is some explanation there, but basically the fields you mentioned aren't the correct ones.  There was a `SubscribersCount` field which was correct but it was deprecated and replaced with a separate API call.  So the current official way to get this info is via a call to the `client.Activity.Watching.GetAllWatchers()` call.  

However as the `SubscribersCount` field was confirmed as being supported for the lifetime of the GitHub API v3, I actually suggested re-instating this field in PR #1473 which is not yet merged

**Comment by ryangribble** [comment]
#1473 should have resolved this with the `SubscribersCount` field
