### ISSUE TITLE
Rename PulRequest.Comment client to PullRequest.ReviewComment

### ISSUE THREAD

**Issue by ryangribble** [octokit/octokit.net#1511]
To better align with the [API docs](https://developer.github.com/v3/pulls/comments/), the access to the `PullRequestReviewClient` should be renamed from `client.PullRequest.Comment` to `client.PullRequest.ReviewComment` (also applies to the `Observable` versions of the client)

Normal octokit.net deprecation procedures should be followed (old variables being marked `[Obsolete]` for at least 2 releases before being deleted).

**Comment by bmeverett** [comment]
Is [this](https://github.com/bmeverett/octokit.net/blob/ca0011546b90674d079f03b6f9bcb317c059ef34/Octokit/Clients/IPullRequestsClient.cs#L19-L24) what you're looking for? And then should the tests be modified to use ReviewComment now?

**Comment by ryangribble** [comment]
Yeah pretty much, although the obsolete message wording should be more in line with other examples in the code base. It also needs to be done in both the interface definition and the concrete implementation and also for the `Observable` client/interface 

And yes updating any other test code should be done now, so that later on the removal of the deprecated endpoint is simple/surgical

**Comment by bmeverett** [comment]
Ok and just to be clear about the Observables. That would require changing  `IObservablePullRequestReviewCommentsClient.GetComment(long repositoryId, int number)` and `IObservable<PullRequestReviewComment> GetComment(string owner, string name, int number)` correct? 

And does anything need to be done with `Task<PullRequestReviewComment> GetComment(string owner, string name, int number)`?

**Comment by ryangribble** [comment]
What I actually meant was to make the same rename to the variable name in the observable API client structure...  But you are spot on that the internals of the observable methods will also need to be tweaked to call the new client's path

If you're keen to work on this just push up a PR with your progress and we can work through it there 👍
