### ISSUE TITLE
Organization Membership Preview API Changes - existing endpoints

### ISSUE THREAD

**Issue by ryangribble** [octokit/octokit.net#1514]
As per this [blog post](https://developer.github.com/changes/2016-11-28-preview-org-membership/) several changes are in preview for the Organization Membership API

This issue is to cover changes to existing endpoints

- The `default_repository_permission` and `members_can_create_repositories` settings for an organization can now be retrieved and set through the [Get an organization](https://developer.github.com/v3/orgs/#get-an-organization) and [Edit an organization endpoints](https://developer.github.com/v3/orgs/#edit-an-organization).

- The [Create team](https://developer.github.com/v3/orgs/teams/#create-team) endpoint now offers the `maintainers` parameter which will allow you to add team maintainers upon creation.

- You can now use the `affiliation` parameter with the [List collaborators](https://developer.github.com/v3/repos/collaborators/#list-collaborators) endpoint to filter a repository's collaborators by their affiliation type.

NOTE: A new preview accepts header needs to be specified `application/vnd.github.korra-preview+json` in `AcceptHeaders.cs`

**Comment by alfhenrik** [comment]
And while I'm in the area, I'd like to put my face on this one too

**Comment by hnrkndrssn** [comment]
> You can now use the `affiliation` parameter with the List collaborators endpoint to filter a repository's collaborators by their affiliation type.

There is already a `CollaboratorRequest` class that is used when creating/updating a collaborator to set their permissions and I don't think I can re-use this class for the `affiliation` parameter (looking at the code it'd add all the properties of the class to the query string)? 

Should I add a new class `ListCollaboratorRequest`(?) with the `Affiliation` property and use that for the List collaborators endpoint?

**Comment by ryangribble** [comment]
Yeah it looks like the naming conventions have been a bit out of whack with this one.  "normally" we would have `XxxRequest` on a `GetAll` endpoint, and `NewXxx`/`UpdateXxx` on any create/update endpoints... but in this case the `CollaboratorRequest` name has aleady been used 😬 

So yeah I would say :+1: to this
> Should I add a new class ListCollaboratorRequest(?) with the Affiliation property and use that for the List collaborators endpoint?
