### ISSUE TITLE
Search Repo by URL - Rate Limit Exception

### ISSUE THREAD

**Issue by l1salvatore** [octokit/octokit.net#1517]
Is not issue.
I take advantage of this "forum" of issues to ask how i search a repo by URL or by user/repo. 

And my other question is, how much time i have to wait to search repo again when the api throws me an Rate Limit Exception

Thanks

**Comment by ryangribble** [comment]
If you just want to ask a question you could use the gitter chat room also 

Documentation on rate limiting is here: https://developer.github.com/v3/#rate-limiting
