### ISSUE TITLE
Unable to check for multi-factor auth is enabled for each member of an org

### ISSUE THREAD

**Issue by damianh** [octokit/octokit.net#1518]
Howdy!

I would like to be able to:

    (await _gitHubClient.Organization.Member.GetAll(_organization)).Where(u => u.MfaEnabled)

... but alas there is no such `MfaEnabled` property on `User`. I can't find anything that look like that. Is this possible by other means? I swear I searched the entire API space first :)

Toodle-pip!

**Comment by damianh** [comment]
(await _gitHubClient.Organization.Member.GetAll(_organization, OrganizationMembersFilter.TwoFactorAuthenticationDisabled))

I hate when this happens.

**Comment by shiftkey** [comment]
I got you @damianh 

![](https://cloud.githubusercontent.com/assets/359239/21377136/5dc28db2-c78b-11e6-9b4e-d04c0e68ec2f.gif)

**Comment by damianh** [comment]
:)
