### ISSUE TITLE
Octokit.Tests.Integration.Helper fails due to unset environment variables around credentials

### ISSUE THREAD

**Issue by SeanKilleen** [octokit/octokit.net#1519]
Hi all,

I noticed that when I first pulled the project, a few tests failed. Looking into it, it appears to be because the `Helper` uses a `Lazy<Credentials>` that reads from environment variables. 

I'm thinking the solution for this is to mention it in the contributing guide; I'll submit the PR.

**Comment by SeanKilleen** [comment]
Annnnd nevermind -- it turns out the solution is to better **read** the contrib guide, which clearly mentions the powershell for the environment variables. Totally missed that somehow.

![](https://cdn.meme.am/cache/instances/folder265/500x/62529265.jpg)

**Comment by shiftkey** [comment]
@SeanKilleen I'm glad this was relatively easy to solve!

![](https://cloud.githubusercontent.com/assets/359239/21376811/009b0c8e-c788-11e6-80c6-7ea3c05f7c1d.gif)
