### ISSUE TITLE
PullRequest.Files array can return a null patch and a contents_url to follow

### ISSUE THREAD

**Issue by l1salvatore** [octokit/octokit.net#1521]
I have tried to get the patch of the following url https://github.com/dotnet/docs.de-de/pull/4/commits/05761c5864fff7dbbf5453b234e3fe581399ed24#diff-de8433d9825dcc2b06d9b079bc597e51 in the file ".filepath-state . But gives me a Nothing value, when the patch exists and is not empty.

Regards
Lucas

**Comment by ryangribble** [comment]
Hi @l1salvatore 

can you post some sample code to demonstrate what you're trying please?

**Comment by l1salvatore** [comment]
For num As Integer = 1 To _searchRepositoryResultList.Count Step 1
            Dim _PullRequests = Await github.Repository.PullRequest.GetAllForRepository(_searchRepositoryResultList.Item(num).Items(0).Id)
            For Each pull As Octokit.PullRequest In _PullRequests
                Dim PullRequestCommits = Await github.Repository.PullRequest.Commits(_searchRepositoryResultList.Item(num).Items(0).Id, pull.Number)
                Dim PullRequestFiles = Await github.Repository.PullRequest.Files(_searchRepositoryResultList.Item(num).Items(0).Id, pull.Number)
                Dim pullreq As New PullRequest(pull.Title + String.Format(" #{0}", pull.Number), pull.CreatedAt)
                pullreq.SetDescription(pull.Body)
                pullreq.SetLanguage(ParseLanguage(listarepos.Item(num).GetNombre))
                pullreq.SetAuthor(pull.User.Login)
                For Each com As PullRequestCommit In PullRequestCommits
                    If Date.Now.Subtract(com.Commit.Committer.Date.Date).Days <= max Then
                        Dim newcommit As New Commit(com.Sha)
                        newcommit.SetDate(com.Commit.Committer.Date)
                        newcommit.SetName(pull.Title)
                        For Each f As PullRequestFile In PullRequestFiles
                            If (Not fileNames.Contains(f.FileName)) Then
                               If f.Changes > 0 Then
                                    fileNames.Add(f.FileName)
                                    fileStatus.Add(f.Status)
                                    filePatch.Add(f.Patch)
                                    newcommit.AddFile(f.FileName, Parse(f.Patch), ParseNumLine(f.Patch))
                                    Debug.Print(ParseNumLine(f.Patch))
                                End If
                            End If
                        Next
                        pullreq.AddCommit(newcommit)
                    End If
                Next
                listarepos.Item(num).AddPR(pullreq)
            Next
        Next

**Comment by l1salvatore** [comment]
Sorry, i don't know how put entirely as code

**Comment by ryangribble** [comment]
https://help.github.com/articles/creating-and-highlighting-code-blocks/

**Comment by l1salvatore** [comment]
I have edited the text. So i have 3 collections: All repositories of a given list, All pull request for each repository, and all files for each pull request. 
There is a file in the collection that has as .patch the Nothing value. But the .patch is not empty, there is text.

**Comment by shiftkey** [comment]
`PullRequestCommit` won't have their `Files` entries populated. See #1522 for how to resolve those.

If you look at the [commit response](https://api.github.com/repos/dotnet/docs.de-de/commits/05761c5864fff7dbbf5453b234e3fe581399ed24) for that change, it appears to be a new feature of the GitHub API, likely related to how we're trying to defer our diff rendering wherever possible.

<img width="1134" src="https://cloud.githubusercontent.com/assets/359239/21410183/b449c026-c82e-11e6-9dd4-39921fca4132.png">

Instead of `patch` being defined, you have a `contents_uri` which if you follow, returns the Base64 encoded diff of the change:

<img width="1048" src="https://cloud.githubusercontent.com/assets/359239/21410214/e3863c52-c82e-11e6-82c6-c755ae7ece35.png">

Supporting this new field is probably easy to roll into an update, if someone wants to add it to the right response object.

**Comment by l1salvatore** [comment]
![error patch](https://cloud.githubusercontent.com/assets/14284586/21434186/dee58928-c851-11e6-8485-f3ba684e533f.jpg)
Sorry, i don't understad. Why gives me Nothing in the .patch field?

**Comment by shiftkey** [comment]
@l1salvatore because the `patch` property on the JSON isn't populated

**Comment by l1salvatore** [comment]
Reopen this issue and its possible solution and for example this content https://api.github.com/repos/Microsoft/azure-docs.ja-jp/contents/articles/virtual-machines/virtual-machines-windows-migration-classic-resource-manager.md?ref=08ba86851de2eac6f0f30e8953a8779aaa6db259 . How i do to access via Octokit? Sorry for a question in the issue thread. But in the chatroom nobody answer yet

**Comment by ryangribble** [comment]
The `ContentsUri` field needs to be added to `PullRequestFile` response class.  Then you would be able to get the Uri for the contents of these large diffs, and access it with a HTTP call
