### ISSUE TITLE
Commit not found from content sha

### ISSUE THREAD

**Issue by JohnGoldsmith** [octokit/octokit.net#1526]
I'm trying to get hold of the last commit object from the sha of a content object.  I can retrieve the sha for each content object, but I don't seem to be able to correlate this to a commit.  Here's an example using LinqPad:
```
async Task Main(string[] args)
{
	// https://github.com/githubtraining/hellogitworld/commits/feature_division/src/Main.groovy
	
	var owner = "githubtraining";
	var reponame = "hellogitworld";
	var targetBranch = "feature_division";
	var targetFolder = "src"; 

	var cred = new Credentials(Util.GetPassword("MyGitHubPassword"));
	var client = new GitHubClient(new Octokit.ProductHeaderValue("QuickQuery"));
	client.Credentials = cred;
	var contents = await client.Repository.Content.GetAllContentsByRef(owner, reponame, targetFolder, targetBranch);

	foreach (var c in contents)
	{
		$"{c.Name} - {c.Sha}".Dump();
		try
		{	        
			var ghCommit = await client.Repository.Commit.Get(owner, reponame, c.Sha);
			$"{ghCommit.User.Name}".Dump();
		}
		catch (NotFoundException ex)
		{
			ex.Message.Dump();
		}
	}
}
```

This results in the following:
```
Main.groovy - 55dcb458fcebd324d5344b5ac99c109ac694cc52
Not Found
Square.groovy - fde331951be7ee45857487ffff1ff50ad8c90d7d
Not Found
Subtract.groovy - 726e5252ccafd9d8fc661ed5ca5c665f24d4bc22
Not Found
Sum.groovy - 9f221918607d78c1db3f6c6d5afa68a66b1146a8
Not Found
```
...however none of these sha's match the ones found in the repo: https://github.com/githubtraining/hellogitworld/commits/feature_division/src/Main.groovy

Is anyone able to shed any light?

Thanks

John

**Comment by shiftkey** [comment]
@JohnGoldsmith unfortunately the `Sha` property here represents the blob of the file, not the commit where the file was last modified. That's why you're seeing the 404 Not Found.

> I'm trying to get hold of the last commit object from the sha of a content object.

I'm not quite sure of an easy way to get this data - you could walk through the commits starting from the tip of the branch, like this:

```
var request = new CommitRequest()
{
    Path = targetFolder,
    Sha = targetBranch
};
var commits = await client.Repository.Commit.GetAll(owner, reponame, request);
```

By default these aren't pre-populated, so you'd have to make a second call to get the changes in each commit.

**Comment by JohnGoldsmith** [comment]
That's great.  Thanks very much @shiftkey 

I've amended based on your help as follows:

```
foreach (var c in contents)
{
	$"\n{c.Name} - {c.Sha}".Dump();
	try
	{
		var request = new CommitRequest()
		{
			Path = targetFolder,
			Sha = targetBranch
		};
		var commits = await client.Repository.Commit.GetAll(owner, reponame, request);
		
		foreach (var cmt in commits)
		{
			var commitWithFiles = await client.Repository.Commit.Get(owner, reponame, cmt.Sha);	
			foreach (var f in commitWithFiles.Files)
			{
				if (f.Sha == c.Sha)
				{
					$"Found file {f.Sha} in commit {commitWithFiles.Sha}".Dump();
					$"Commit msg - {commitWithFiles.Commit.Message}".Dump();
					$"See commit - {commitWithFiles.HtmlUrl}".Dump();
				}
			} 
		}
	}
	catch (NotFoundException ex)
	{
		ex.Dump();
	}
}
```

...which results in the following:

```
Main.groovy - 55dcb458fcebd324d5344b5ac99c109ac694cc52
Found file 55dcb458fcebd324d5344b5ac99c109ac694cc52 in commit e650f374002f860d56ecad63b6fab7387a607642
Commit msg - Fixed a typo in a tested value of division (comment and actual didn't acgree)
See commit - https://github.com/githubtraining/hellogitworld/commit/e650f374002f860d56ecad63b6fab7387a607642

Square.groovy - fde331951be7ee45857487ffff1ff50ad8c90d7d
Found file fde331951be7ee45857487ffff1ff50ad8c90d7d in commit dc64fe4ab8618a5be491a9fca46f1585585ea44e
Commit msg - Refactored squaring into a separate class
See commit - https://github.com/githubtraining/hellogitworld/commit/dc64fe4ab8618a5be491a9fca46f1585585ea44e

Subtract.groovy - 726e5252ccafd9d8fc661ed5ca5c665f24d4bc22
Found file 726e5252ccafd9d8fc661ed5ca5c665f24d4bc22 in commit 3c9306fcc7c41a88a37514a1f4c8d43459eaf966
Commit msg - Added subtract feture
See commit - https://github.com/githubtraining/hellogitworld/commit/3c9306fcc7c41a88a37514a1f4c8d43459eaf966

Sum.groovy - 9f221918607d78c1db3f6c6d5afa68a66b1146a8
Found file 9f221918607d78c1db3f6c6d5afa68a66b1146a8 in commit 09b08e4b4d54a26653c847b88dfa8139826417ae
Commit msg - Added sum function and test call
See commit - https://github.com/githubtraining/hellogitworld/commit/09b08e4b4d54a26653c847b88dfa8139826417ae
```
I see the the [xml comment on Sha](https://github.com/octokit/octokit.net/blob/c9b2c1260bc87b7782d4fd9645d43a8885203923/Octokit/Models/Response/CommitContent.cs) says 'SHA of the last commit that modified this content' if I'm reading in the right place.  Should this be 'SHA of this content blob' or does it have different uses in other places?

Anyway, thanks again - it's a great help.

John

**Comment by ryangribble** [comment]
Yeah looks like that's an incorrectly documented field and should be fixed up... apologies for the bum steer!  😮

**Comment by JohnGoldsmith** [comment]
Well it's helped progress my git understanding so good things have come out of it :)

**Comment by shiftkey** [comment]
@JohnGoldsmith I'm glad you were able to workaround the issue! :sparkles:

Leaving this open for someone to address the suggestion that the comment on [this line](https://github.com/octokit/octokit.net/blob/master/Octokit/Models/Response/CommitContent.cs#L40) needs to be updated:

> I see the the xml comment on Sha says 'SHA of the last commit that modified this content' if I'm reading in the right place. Should this be 'SHA of this content blob' or does it have different uses in other places?

**Comment by JohnGoldsmith** [comment]
Hi, Have made the change in PR #1534

**Comment by ryangribble** [comment]
Comment clarified in #1534 - thanks!
