### ISSUE TITLE
List labels for repository

### ISSUE THREAD

**Issue by vmikeska** [octokit/octokit.net#1535]
I did my best, but cannot find how could I get list of labels for a repository. Is it already implemented ?

**Comment by ryangribble** [comment]
Hi @vmikeska , yes it should be implemented - something like the following should work:

``` csharp
var client = new GitHubClient(new ProductHeaderValue("LabelExample"))
    {
        Credentials = new Credentials(xxxxx /* add user/pwd or apikey as appropriate */);
    };

// Retrieve all labels available in a given repository
var labels = await client.Issue.Labels.GetAllForRepository("octokit", "octokit.net");
```

Please let me know if this is what you were looking for! 😀

**Comment by vmikeska** [comment]
Hi @ryangribble, yes, thank you very much, was exactly it!
