### ISSUE TITLE
How do I: add Credentials to a githubclient passed in via DI?

### ISSUE THREAD

**Issue by jennet** [octokit/octokit.net#1538]
I'm using GitHubClient in a .NET MVC controller. 

Before passing in IGitHubClient via DI I just used this:

    var client = new GitHubClient(new ProductHeaderValue("appname"))
            {
                Credentials = new Credentials(accessToken)
            };

where accessToken was the value saved in my user's Identity Claims (set there after the user has signed up via GitHub).

Now that GitHubClient is passed via DI from the application start, how do I set the Credentials when/before I want to use the client to get (for example) a list of repositories, which previously I'd just got simply using: 

`var repositories = await client.Repository.GetAllForCurrent();`

Thanks in advance, I'm sure this must be obvious but I'm having a very slow brain day today!

**Comment by M-Zuber** [comment]
What DI are you using?

You should be able to set the credentials in DI setup, and when it gets passed to the controller it is fully ready to use

**Comment by jennet** [comment]
Autofac in Startup.Services.cs in a standard MVC 5 app. 
A user will need to login before I can get at their access token.

**Comment by jennet** [comment]
I should have clarified that I'm using this in conjunction with an OWIN GitHub external login provider. So depending on the logged in user there will be different credentials

**Comment by M-Zuber** [comment]
I'm not that experienced in DI, but do you have an option of calling something like `container.GetInstance<IGithubClient>()`, registration of which is set to pull token from logged in user?

I know that it is not the cleanest solution, others may have a better one.

**Comment by jennet** [comment]
Not during application start. I need to add the Credentials after it's been passed to the controller

**Comment by M-Zuber** [comment]
I meant that instead of relying on injection into the controller, inject the Autofac container itself and call `container.Resolve`, which - if I understood correctly - can be registered to use dynamic values to create the instance.

There are a number of projects that might have useful code, when I get back I'll try and look for them.

**Comment by jennet** [comment]
That doesn't _feel_ like the right thing to do here, but if you can supply code/links then I'll take a look into that approach, for sure.

**Comment by M-Zuber** [comment]
My apologies, I remembered wrong.
The posts I had seen only dealt with the actual login, not how you would deal with using the combination of DI.
here they are anyways, in case they help you with something.
http://www.jerriepelser.com/blog/owin-oauth-provider-github/
http://www.jerriepelser.com/blog/using-aspnet-oauth-providers-without-identity/
http://haacked.com/archive/2014/04/24/octokit-oauth/

**Comment by M-Zuber** [comment]
@ryangribble might have something more helpful to add

**Comment by jennet** [comment]
I've just noticed in the GitHubClient code the comment to only use the Credentials getter/setter if you only use a single hard-coded credential. 

I'll read up on ICredentialStore.

**Comment by jennet** [comment]
I had a bit of a fail with ICredentialStore, but in amongst my googlings I saw [this blog post](http://blog.somewhatabstract.com/2015/10/28/octokit-and-the-authenticated-access/) which set the Credentials a slightly different way.

By setting the Credentials in this way (actually it's more long-winded than this for error checking but you get the idea) :
` _gitHubClient.Connection.Credentials = new Credentials(accessToken);`
my code works fine with the GHC passed to the controller via DI and then setting the credentials based on the logged in user in the controller method.


This may not be best practise (given that comment on GitHubClient.Credentials) so if anyone explain how to do it correctly that would be great. For now I'll get on with other work ;-)

**Comment by somewhatabstract** [comment]
I think the client is supposed to be one per credential rather than using the same one for multiple credentials. For that reason, I would expect the DI to be configured to create a new `GitHubClient` instance per injection request and probably, to have that require the credentials to be injected accordingly.

I'm not it makes sense to inject an `IGitHubClient` directly but instead to inject your own provider object that can create clients based on credentials you give it.

**Comment by ryangribble** [comment]
Yes, the way we tend to do it is create a Factory class which gets injected by DI, and that Factory class (which can be initially setup with your common values such as the AppName and the Url (if using GitHub Enterprise) etc) knows how to generate a client with the credentials you give it from your lower context...

eg 

``` csharp
using System;
using Octokit;

namespace Api.Providers.GitHub
{
    public class GitHubClientFactory : IGitHubClientFactory
    {
        private readonly string _serverUrl;
        private readonly string _apiKey;
        private readonly string _appName;

        public GitHubClientFactory(string serverUrl, string appName, string apiKey)
        {
            _serverUrl = serverUrl;
            _appName = appName;
            _apiKey = apiKey;
        }

        public IGitHubClient CreateClient()
        {
            return new GitHubClient(new ProductHeaderValue(_appName), new Uri(_serverUrl))
            {
                Credentials = new Credentials(_apiKey)
            };
        }
    }
}
```

**Comment by ryangribble** [comment]
CLosing this out as answered :+1:
