### ISSUE TITLE
patch is Nothing when the file is too large

### ISSUE THREAD

**Issue by l1salvatore** [octokit/octokit.net#1543]
Hi!
   Maybe i already asked this problem. When a file is too large, its .patch string is Nothing. For example: https://patch-diff.githubusercontent.com/raw/Microsoft/azure-docs.es-es/pull/13.patch

   Is a issue?

Thanks!

**Comment by ryangribble** [comment]
Yes you already asked this in #1521 and it looks like the `Patch` field is not provided on those responses (thus it is `null`).  There is discussion on that issue about another field that could be useful (but isnt currently supported in Octokit)

Let's continue discussions over on #1521 and close this duplicate issue
