### ISSUE TITLE
[.NET Core] - add GitVersion config file

### ISSUE THREAD

**Issue by mderriey** [octokit/octokit.net#1554]
This will have the benefit of making the configuration and behaviour explicit.

**Comment by mderriey** [comment]
@ryangribble any idea why this issue - and the other ones - didn't get closed? I thought putting the correct message in the PR description would do the trick. Or do you need to put it in the commit message when you squash the commits into one while merging the PR?

**Comment by ryangribble** [comment]
What you did should have worked 

Maybe it's the full stop at the end of the line?!
