### ISSUE TITLE
Getting Exception thrown: 'System.FormatException' in mscorlib.dll when deserializing type RepositoryTrafficView

### ISSUE THREAD

**Issue by pthivierge** [octokit/octokit.net#1558]
I am using the new API calls from Octokit .NET (3c818934 Release v0.24) , and I am getting a deserialization Exception:

System.FormatException occurred
  HResult=-2146233033
  Message=Input string was not in a correct format.
  Source=mscorlib
  StackTrace:
       at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
  InnerException: 

The method DeserializeObject fails at line 1401 of SimpleJson.cs:
return Convert.ChangeType(str, type, CultureInfo.InvariantCulture);

**str** contains: 
2017-02-08T00:00:00Z

**type** contains:
{Name = "Int64" FullName = "System.Int64"}

Values at line 165:

 return base.DeserializeObject(value, type);
**value**
{{"timestamp":"2017-02-08T00:00:00Z","count":2,"uniques":2}}

**type**
{Name = "RepositoryTrafficView" FullName = "Octokit.RepositoryTrafficView"}

It seems wrong to me that timestamp gets type of Int64.  I don't understand the code enought at this time to see what the problem is.

Thanks for your help.

**Comment by shiftkey** [comment]
@pthivierge can you provide a sample for what you're calling, so we can reproduce it on our end?

**Comment by ryangribble** [comment]
Hi @pthivierge it looks like the API response field for `timestamp`may now be a formatted  time string rather than the long value Unix epoch time that it used to be, back when [we implemented it]( https://github.com/octokit/octokit.net/pull/1457) 

Such is the nature of preview API features I guess! 

We should confirm this has changed on a few example repos and if so change the field type to `DateTimeOffset`

**Comment by pthivierge** [comment]
@shiftkey , below  is what I am calling.

@ryangribble, thanks for helping out, let me know if you need more details.

    public class PluginParams
    {
    	/// <summary>
    	/// The organization name to search for
    	/// </summary>
    	public string GitHubOwner { get; set; }
    	
    	/// <summary>
    	/// Application credentials token to use to connect to GitHub
    	/// <see cref="https://github.com/settings/tokens"/>
    	/// </summary>
    	public string GithubCredentialToken { get; set; }
    	
    	/// <summary>
    	/// Name of the product that is using octokit
    	/// </summary>
    	public string GitHubProductName { get; set; }
    
    }

    public static GitHubClient GetGitHubClient(PluginParams settings)
    {
    	var github = new GitHubClient(new ProductHeaderValue(settings.GitHubProductName));
    	github.Connection.Credentials = new Credentials(settings.GithubCredentialToken);
    	return github;
    }
                 
    var github = GitHubCommon.GetGitHubClient(settings);
    
    // Read repositories from GitHub
    var repos = github.Repository.GetAllForOrg(settings.GitHubOwner).Result;
    
    foreach (var repo in repos)
    {
	    var targetRepoElement = GitHubCommon.FindRepositoryById(orgElement, settings, repo.Id.ToString());
	    
	    // FAILS in those two methods
	    var clonesTask = github.Repository.Traffic.GetClones(repo.Id, new RepositoryTrafficRequest(TrafficDayOrWeek.Day));
	    var viewsTask = github.Repository.Traffic.GetViews(repo.Id, new RepositoryTrafficRequest(TrafficDayOrWeek.Day));`
	    
	    Task.WaitAll(clonesTask, viewsTask);
	    // do stuff here
    
    }

**Comment by pthivierge** [comment]
@ryangribble, where in the code may I change the type? Maybe I can test it... :)

**Comment by mderriey** [comment]
Indeed, it looks like both the [views](https://developer.github.com/v3/repos/traffic/#views) and [clones](https://developer.github.com/v3/repos/traffic/#clones) now use a formatted string. Good catch, @ryangribble.

Looking through the codebase, I could only find that timestamp pattern in 2 classes, [`RepositoryTrafficView`](https://github.com/octokit/octokit.net/blob/a57fb1278d1bca6375a6f80345da90c5dec5077f/Octokit/Models/Response/RepositoryTrafficView.cs) and [`RepositoryTrafficClone`](https://github.com/octokit/octokit.net/blob/a57fb1278d1bca6375a6f80345da90c5dec5077f/Octokit/Models/Response/RepositoryTrafficClone.cs).

I should be able to get a PR in.

**Comment by pthivierge** [comment]
Thanks a lot guys! Good job :)
