### ISSUE TITLE
How to get list of branches/tags that a given commitid is contained in?

### ISSUE THREAD

**Issue by xanthome** [octokit/octokit.net#1566]
https://github.com/{org}/{repo}/commit/{sha}
https://github.gaikai.org/core/core_konan/commit/25f8fa8544c89081818e70ada35fcec22fbdd59e

this blog posts mention it, how do I get it from my app?

https://github.com/blog/1451-branch-and-tag-labels-for-commit-pages

**Comment by shiftkey** [comment]
This is not available through the API.
