### ISSUE TITLE
Remove or fix warnings caused by the obsoleted default parameterless constructor of RepositoryUpdate

### ISSUE THREAD

**Issue by eriawan** [octokit/octokit.net#1568]
Hi guys,

Could we replace any referenced usages of obsoleted default (parameterless) constructor of RepositoryUpdate?

For example:

![image](https://cloud.githubusercontent.com/assets/8773147/24091335/11475a5a-0d7a-11e7-8eea-519f5a74b481.png)

As suggested, we could simply replace the default constructor with the constructor that has parameter `name`.

If this accepted, I will create a WIP PR on this. 🙂

**Comment by shiftkey** [comment]
Here's where we introduced the `Obsolete` rule: https://github.com/octokit/octokit.net/commit/e31ac8659a124079a696c84bfb22f67c759bd6d5

And this made it into the v0.23 release - https://github.com/octokit/octokit.net/releases/tag/v0.23.0

I think this is fine to remove from the next update @eriawan! :thumbsup:

**Comment by eriawan** [comment]
Thanks for the prompt response, @shiftkey 👍 

> I think this is fine to remove the ctor from the next update @eriawan! 👍

ok, so what do you think is the best? here are the solutions to choose:

1. Do you mean to remove the obsoleted parameterless ctor in the `RepositoryUpdate`? Then we will have many changes on the tests, although it is quite straightforward and it's easy to change. It is also easier to check all of the diffs on the PR, therefore it's easier to review.
2. Or we could do the otherwise, by changing the usages of all of parameterless ctor by replacing with ctor with 'name' parameter instead. Then we could mark the `ObsoleteAttribute` to always resolved as error instead of just compile warning, to really deprecate this constructor and to tell the consumer of this class to not to use it anymore. For example: `[Obsolete("Please use the ctor RepositoryUpdate(string name) as Name is a required field", true)]` (I prefer this solution 🙂 )

Let me know what you think, I'll create a PR for any one of those.

**Comment by ryangribble** [comment]
After the item ha been marked obsolete for a couple on releases its fine to remove it, so go with option 1 👍

**Comment by eriawan** [comment]
@ryangribble PR #1569  has been submitted.

cc @shiftkey
