### ISSUE TITLE
Authenticating Application without user input

### ISSUE THREAD

**Issue by nating** [octokit/octokit.net#1572]
Is there a way to authenticate an application so that it can have a higher rate limit, without web-flow? So that the application can just use its clientID & clientSecret to get a higher rate limit without any information about the user?

It seems that the only way to authenticate an app needs 'code' from the callback of the web-flow when a user permits access to the application.

![image](https://cloud.githubusercontent.com/assets/16880181/24424700/7c18b3d0-13f9-11e7-87a5-de6ddbdde32b.png)

**Comment by shiftkey** [comment]
Unfortunately not.

The [docs](https://developer.github.com/v3/oauth/#non-web-application-flow) for doing OAuth without the web flow involves signing in with basic authentication and creating an authorization on behalf of the user. But that still requires their input.

Alternatively, if the user can provide a personal access token you can use that for credentials - however it's not tied to your application.

**Comment by nating** [comment]
Thanks for getting back Brendan. That's unfortunate.

We are building a [chatbot](https://github.com/nating/gitbot) to interact with GitHub and were hoping it could scale to more than 60 queries per hour. Do you think creating a personal access key to be associated with the application so that it can have its higher rate limit would be a good idea?

**Comment by shiftkey** [comment]
> Do you think creating a personal access key to be associated with the application so that it can have its higher rate limit would be a good idea?

The OAuth token represents the relationship between a user and an application - that doesn't feel relevant here as it sounds like you don't need to have everyone authenticate against the application. Personal access tokens are great for testing and prototyping, but they are tied to a real account - combining whatever the real account has access to with [the scopes you give the token](https://developer.github.com/v3/oauth/#scopes). 

So there's a concept called "machine accounts" which I'll point out here. From the [Terms of Services](https://help.github.com/articles/github-terms-of-service/) page:

> A machine account is an account set up by an individual human who accepts the Terms on behalf of the account, provides a valid email address, and is responsible for its actions. A machine account is used exclusively for performing automated tasks. Multiple users may direct the actions of a machine account, but the owner of the account is ultimately responsible for the machine's actions. You may maintain no more than one free machine account in addition to your free personal account.

What I'd do to simplify things without having to worry about OAuth:

 - create a machine account, add it as a member of your organization and give it access to the appropriate teams and repositories it needs to get stuff done
 - generate a personal access token for the machine account, ensuring it has just the appropriate scopes set that it needs
 - set that token `GitHubClient.Credentials` whenever your chatbot needs to interact with the GitHub API

It avoids the whole OAuth application setup and management, but it doesn't sound like something you need here.

**Comment by rjk40** [comment]
Everything step in take i feel like I can't breath, friend or foe. I need a
professional opinion

**Comment by alfhenrik** [comment]
> create a machine account, add it as a member of your organization and give it access to the appropriate teams and repositories it needs to get stuff done

This is what we've done with our slack bot for releasing Octopus and it works well! 😄

**Comment by ryangribble** [comment]
Agree that a "machine account" with a personal access token sounds like the way to handle this.  We also have a release/helper bot that uses this approach.

Im going to close out this issue but feel free to comment further or re-open if you need to @nating

**Comment by nating** [comment]
Thank you all for your help. We set up a machine account for the application and are achieving our higher rate-limit.
