### ISSUE TITLE
Notifications.MarkAsRead() throws Octokit.ApiException

### ISSUE THREAD

**Issue by aalok05** [octokit/octokit.net#1578]
The method ` client.Activity.Notifications.MarkAsRead();` is throwing an exception. 

Type: Octokit.ApiException
HttpResponse Body:
{"message":"Problems parsing JSON","documentation_url":"https://developer.github.com/v3"}

**Comment by shiftkey** [comment]
Weird - [the source](https://github.com/octokit/octokit.net/blob/693cc29dd5f44646600c9e4759f800b31a1eca26/Octokit/Clients/NotificationsClient.cs#L190) looks rather mundane, and the endpoint also seems boring: https://developer.github.com/v3/activity/notifications/#mark-as-read

**Comment by aalok05** [comment]
yes it's definitely weird

**Comment by ryangribble** [comment]
Ive poked around with this, and it looks like the `last_read_at` parameter is required.  Not sure if this is a recent thing or it's always been like this, as there are no integration tests for this method currently.

For now, you can call the method using the following code and it should work OK (specifying no time in the `MarkAsReadRequest` passes null for the argument)

`await client.Activity.Notifications.MarkAsRead(new MarkAsReadRequest())`

**Comment by shiftkey** [comment]
>  Not sure if this is a recent thing or it's always been like this, as there are no integration tests for this method currently.

Sigh. I'll check it out. Thanks for digging into it @ryangribble!

**Comment by ryangribble** [comment]
I think this would be an uncommonly used method, so there's no telling how long it may have been like this for upstream (possibly forever?!)

**Comment by shiftkey** [comment]
@ryangribble If you PUT with an empty JSON object you get the correct behaviour without having to specify anything in the payload. And I'm pretty sure that PUT without a body isn't typical HTTP behaviour (the server may think "you haven't given me an entity to update, what am I supposed to do here?" and returning a 400 like it's doing here seems reasonable).

Anyway, #1579 should fix it
