### ISSUE TITLE
*Url response properties are inconsistent

### ISSUE THREAD

**Issue by shiftkey** [octokit/octokit.net#1582]
Before going 1.0 we should do a scan and ensure all response fields suffixed with `Url` are `Uri`s instead of strings.

@nickcraver pointed these examples out to me:

 - https://github.com/octokit/octokit.net/blob/master/Octokit/Models/Response/Author.cs#L38-L58
 - https://github.com/octokit/octokit.net/blob/master/Octokit/Models/Response/GitHubCommit.cs#L45
 - https://github.com/octokit/octokit.net/blob/master/Octokit/Models/Response/Account.cs#L99

**Comment by shiftkey** [comment]
Or maybe they should just go back to `string` if we're not getting anything from using `Uri` due to the increased allocations?

**Comment by NickCraver** [comment]
+1 on consistency, and a selfish +1 on strings (for performance reasons). I'd value consistency more overall, though.

**Comment by mderriey** [comment]
@shiftkey I'm happy to do this.
Would you rather have them as `string` or `Uri`?

So far, 43 classes have at least one property named or suffixed with `Url` that are not `Uri`. 27 classes have at least one property named or suffixed with `Url` that are all typed as `Uri`.

**Comment by shiftkey** [comment]
@mderriey I really don't think we're getting much out of returning `Uri`s - and they're boring enough that the caller can `new Uri()` the result if they need it explicitly.

Let's make them all `string`.

**Comment by ryangribble** [comment]
Sounds good. You could also add a convention test @mderriey,  to keep us consistent going forward :D

**Comment by mderriey** [comment]
Cool, will do!

**Comment by NickCraver** [comment]
\o/ thanks @mderriey and @ryangribble!
