### ISSUE TITLE
How get an folder from GitHub repository structure (tree)?

### ISSUE THREAD

**Issue by zlatibor** [octokit/octokit.net#1583]
Hello,

I am new in OctoKit and I need a little help.

I need to get an folder (and it's content) from (inside) GitHub repository. How to do that using OctoKit?

I suppose that I need to use this https://developer.github.com/v3/git/trees/ , but how in OctoKit?

Do I need to be owner of that repository to get folder using OctoKit? I am asking that because I am collaborator.

**Could you provide an short example in C#, please?**

Thanks!

**Comment by ryangribble** [comment]
You'll want to use the `RepositoryContentsClient` in octokit 
 
One good source  of sample code is the integration tests eg this one retrieves the contents of a folder: https://github.com/octokit/octokit.net/blob/master/Octokit.Tests.Integration/Clients/RepositoryContentsClientTests.cs#L95

**Comment by JoeyGarcia** [comment]
You want to use this call:  octokit.repos.getContents(dirContentsConfig);
Here is a reference to the documentation: https://octokit.github.io/rest.js/#octokit-routes-repos-get-contents

Here is some code that will print the files found in that directory.
`
        let dirContentsConfig = {
            owner: owner,
            repo: repo,
            path: `${pathToDirectory}/`,
            ref: branchName,
            branch: branchName
        }

            const dirContentsMetadata = await octokit.repos.getContents(dirContentsConfig);

            if (Array.isArray(dirContentsMetadata.data)) {
                for (let contents of dirContentsMetadata.data) {
                    console.log(contents.name)
                }
            }
`
