### ISSUE TITLE
Please support repository's license API

### ISSUE THREAD

**Issue by azubanov** [octokit/octokit.net#1586]
https://developer.github.com/v3/licenses/#get-a-repositorys-license

"license": {
    "key": "mit",
    "name": "MIT License",
    "spdx_id": "MIT",
    "url": "https://api.github.com/licenses/mit"
  },

**Comment by shiftkey** [comment]
From the [integration tests](https://github.com/octokit/octokit.net/blob/master/Octokit.Tests.Integration/Clients/MiscellaneousClientTests.cs#L49-L58):

```csharp
var client = new GitHubClient(/*...*/);
var licenses = await client.Miscellaneous.GetAllLicenses();
Assert.True(result.Count > 2);
Assert.Contains(result, license => license.Key == "mit");
```

Please let me know if there's anything more you want from this endpoint.

**Comment by azubanov** [comment]
Hello, shiftkey!
Yes there is no way to get license information about particular repository.
Please take a look at my link: https://developer.github.com/v3/licenses/#get-a-repositorys-license

**Comment by shiftkey** [comment]
It looks like we need to deserialize the `license` JSON as part of the [Repository](https://github.com/octokit/octokit.net/blob/master/Octokit/Models/Response/Repository.cs) response model.

@azubanov are you interested in contributing this change?

**Comment by ryangribble** [comment]
Indeed there are a couple of unimplemented calls that would be under `IRepositoriesClient` endpoint.

Would you be interested in making these modifications @azubanov  ?

Firstly, we could have license information included in existing calls that return `Repository` objects.  To do this we need to add the licenses preview API header (`AcceptHeaders.LicensesApiPreview`) in those calls (eg client.Repository.Get(owner, repo)) and then add a `License` property to the `Repository` response class.

Secondly there actually is a "Get a repository's license" call which you linked to.  This would be suitable as a new call in the `IRepositoriesClient` such as `Task<LicenseMetadata> GetLicense();`

**Comment by azubanov** [comment]
Hello ryangribble!
Sounds interesting :)
If this issue be still active in two weeks, I'll take a look.
