### ISSUE TITLE
LINQPad samples are requiring Reactive, but not actually using it

### ISSUE THREAD

**Issue by NickCraver** [octokit/octokit.net#1592]
Many of the LINQPad samples have this prompt:
<img width="399" alt="screen shot 2017-04-25 at 23 54 28" src="https://cloud.githubusercontent.com/assets/454813/25417522/a9839bda-2a12-11e7-9489-62af99f93421.png">

...but they don't *actually* use it. Since there's also a bug restoring Rx-Main right now, this creates a blocker for the user. I'll submit a PR soon as time allows cleaning up the samples and removing the extra namespace declarations where not needed if there are no objections.

**Comment by shiftkey** [comment]
Yeah, this is a convenience thing.

> Since there's also a bug restoring Rx-Main right now, 

Weird. Would love to hear more about this one - I gather it's because Rx-Main is unlisted and we haven't had a chance to land the migration to `System.Reactive`, but restore shouldn't be affected by that.

**Comment by NickCraver** [comment]
<img width="484" alt="screen shot 2017-04-25 at 23 55 56" src="https://cloud.githubusercontent.com/assets/454813/25417700/e46da884-2a13-11e7-8bbd-abfce4547106.png">
^ the LINQPad experience :)

**Comment by shiftkey** [comment]
Of course, because LINQPad doesn't know about specific versions...

![](https://cloud.githubusercontent.com/assets/359239/25417734/7cae2ffe-2a89-11e7-8860-2cfcf6dab5e3.gif)

Yep, burn those references to the ground @NickCraver  :fire: :fire: :fire: :fire: :fire: :fire:

**Comment by NickCraver** [comment]
Done: PR is #1593
