### ISSUE TITLE
Enumeration

### ISSUE THREAD

**Issue by Korporal** [octokit/octokit.net#1596]
Using C# in a (say) Console app, how can I 
* enumerate every repo in an org.
* enumerate every branch in a repo ordered by most recently updated (most recently commited to)

Thx

**Comment by shiftkey** [comment]
First one is easy:

```c#
var client = new GitHubClient(/* ... */);
var repos = await client.Repository.GetAllForOrg("org");
```

Second one is only partially possible:

```
var client = new GitHubClient(/* ... */);
var branches = await client.Repository.GetAllBranches("org", "repo");
```

The response returned for each branch doesn't give you much - just a link to the commit - and so you'll need to lookup that commit to find the timestamp.
