### ISSUE TITLE
Implement Protected Branches API Admin Enforcement Updates

### ISSUE THREAD

**Issue by M-Zuber** [octokit/octokit.net#1597]
Due to https://developer.github.com/changes/2017-03-22-protected-branches-admin-improvements/, the `BranchProtection` sub classes no longer should accept an `includeAdmins` param in the constructor.
In addition a top level property of `enforce_admins` needs to be added.

**Comment by M-Zuber** [comment]
@ryangribble I am working on implementing this, but there is a question of just how many constructors to add
![image](https://cloud.githubusercontent.com/assets/4746537/25613153/ec43710c-2f35-11e7-800b-82a9fea749f1.png)

Do we tell people that if they want to set `EnforceAdmins` they have to use the fullest ctor, or add another two?
(once this lands, #1523 is going to be adding a few more as well..)

**Comment by ryangribble** [comment]
Maybe just 1 ctor taking each single option and 1 ctor taking all options?

**Comment by M-Zuber** [comment]
so n+1 with n being the number of properties on the class? Sounds good to me.

An interesting item in the docs that @shiftkey might have some insight on is the fact that the `include_admins` property on some of the sub classes is marked as **`required`**, but in testing I've done, it does not effect the end result.
My personal vote is then to obsolete it as it can cause confusion.
