### ISSUE TITLE
fetch user from its mail id

### ISSUE THREAD

**Issue by ronaksharma8** [octokit/octokit.net#1601]
I am using Octokit.Reactive 0.21.1-alpha0001 and .net core application with User Identity . Now, my question how can i get user based on it email id i.e (User.Identity.Name = 'asd@asd.com' , get github user whose email id is 'asd@asd.com')

Below is my code

var client = new GitHubClient(new ProductHeaderValue("my-cool-app"));
var tokenAuth = new Credentials(access_token);
client.Credentials = tokenAuth;

var repositories = await client.Repository.GetAllForCurrent();

**Comment by shiftkey** [comment]
```
var users = await client.Search.SearchUsers(new SearchUsersRequest("asd@asd.com"));
```
