### ISSUE TITLE
Recent 413 Entity too large for gist creation

### ISSUE THREAD

**Issue by ferventcoder** [octokit/octokit.net#1605]
Recently have been seeing quite a few 413 request entity too large for our service that has been creating gists for choco community package testing results (running a year and a half now!). 

I have not had time to dig in just yet but I'm curious for the GitHub folks - have there been any changes recently limiting size of gist files?

**Comment by ferventcoder** [comment]
Apologies as well - prolly not the right place to file this

**Comment by shiftkey** [comment]
Looks like this isn't specific to Octokit.net - https://github.com/philschatz/octokat.js/issues/169

Gut feeling is something server-side has changed - I'll do some digging through the support channels and see if I can get an idea of what's changed recently.

**Comment by philschatz** [comment]
Thanks for taking a look into it!

/cc @SleepyBandit so they can track the progress of this issue

**Comment by shiftkey** [comment]
@ferventcoder a configuration fix has been deployed a few hours ago - are you able to see if that fixes the issue on your end?

**Comment by SleepyBandit** [comment]
I will confirm, this is fixed for me. Github support had me test it this morning and it worked for 3 different files of differing sizes above the 700KB threshold I was having issues with when it occurred.

**Comment by shiftkey** [comment]
@SleepyBandit thanks for confirming. I'll close this out for now.

@ferventcoder please let me know if you see any other issues.

**Comment by ferventcoder** [comment]
@shiftkey looks like things are rolling again - https://gist.github.com/choco-bot.

Note that the last noted time the service gave us an error was at 13:54 CDT:

~~~
2017-05-15 18:54:04,965 [42] ERROR chocolatey-package-verifier had error(s):
There are 2 exceptions of 'ApplicationException'.System.ApplicationException: Error creating Gist for bazel v0.5.0-rc4. The service will try to test the package again later. Until then enjoy this error log heartbeat. The service is still running, yay! ---> Octokit.ApiException: <html>


<head><title>413 Request Entity Too Large</title></head>
<body bgcolor="white">
<center><h1>413 Request Entity Too Large</h1></center>
<hr><center>nginx</center>
</body>
</html>

[..snip..]
~~~

Note that the bazel package testing gist creation was successful an hour ago - https://gist.github.com/choco-bot/e292af89f9d777d15348bc524ec03739

**Comment by shiftkey** [comment]
@ferventcoder yeah, that last error was before the update was deployed.

**Comment by ferventcoder** [comment]
@shiftkey fantastic customer service there. I def owe you a drink next time I see you!
