### ISSUE TITLE
Batch pull-request comments API is missing

### ISSUE THREAD

**Issue by PavelBansky** [octokit/octokit.net#1608]
I see at the documentation that submitting multiple pull-request comments is supported by the REST API, but I can't see any C# wrapper at Octokit?

Is that correct, or am I missing something?

**Comment by shiftkey** [comment]
@PavelBansky can you link to the documentation you are looking at?

**Comment by PavelBansky** [comment]
I'm looking at this:
https://developer.github.com/v3/pulls/reviews/#create-a-pull-request-review

Specifically:
comments | array of draft review comment objects

I would like to submit several pull request comments/review comments in batch. I don't want to trigger pull request comment event after every single comment, but rather when I'm done commenting.

**Comment by shiftkey** [comment]
Looks like we don't have that overload: https://github.com/octokit/octokit.net/blob/master/Octokit/Clients/PullRequestReviewCommentsClient.cs#L250

Given that was originally implemented a while ago and this feels like a new change, I guess it'd be nice to see if someone was keen to add this support in.
