### ISSUE TITLE
Octokit fails to install in a Xamarin.Android project

### ISSUE THREAD

**Issue by jamesqo** [octokit/octokit.net#1612]
Hi, I'm using VS2017 with the free Xamarin.Android tools. When I created a new Blank App, did some work, then tried running `Install-Package Octokit`, I got the following error in the Package Manager Console:

```
Installing Octokit 0.24.0.
Installing Microsoft.Net.Http 2.0.20505.
Install failed. Rolling back...
Package 'Microsoft.Net.Http.2.0.20505' does not exist in project 'Repository'
Package 'Microsoft.Net.Http.2.0.20505' does not exist in folder 'C:\cygwin64\home\james\code\cs\Repository\packages'
Executing nuget actions took 372.99 ms
Install-Package : Could not install package 'Microsoft.Net.Http 2.0.20505'. You are trying to install this package into a project that targets 
'MonoAndroid,Version=v7.1', but the package does not contain any assembly references or content files that are compatible with that framework. For more 
information, contact the package author.
At line:1 char:1
+ Install-Package Octokit
+ ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
```

It looks like `Microsoft.Net.Http 2.0.20505` is having issues installing. Can someone please take a look or advise me if I can do anything to work around this? Thanks.

**Comment by ryangribble** [comment]
Hey @jamesqo 

Maybe try our new dotnetcore (netstandard1.1) library and see if that works better. It's not an official release on nuget just yet, but a prerelease package is available if you specify Prerelease flag to get it. Or you could change your feed to our appveyor one

**Comment by jamesqo** [comment]
@ryangribble Thanks for the advice! I just tried installing the prerelease package and it works perfectly. :heart:
