### ISSUE TITLE
RepositoryContent.Content and other properties are null

### ISSUE THREAD

**Issue by jamesqo** [octokit/octokit.net#1615]
If you look at https://api.github.com/repos/jamesqo/Repository/contents/Repository.sln, you can clearly see the base64-encoded content is present in the response. Howevver, run the following app:

```cs
static void Main(string[] args)
{
    var client = new GitHubClient(new ProductHeaderValue(nameof(OctokitLab)));
    var contents = client.Repository.Content.GetAllContents("jamesqo", "Repository", "/").Result;
    var sln = contents.Single(c => c.Name == "Repository.sln");
    Debugger.Break();
}
```

View the variable `sln` in the debugger. You will be able to see that several important properties, including `Content`, `EncodedContent`, and `Encoding` are all null.

**Comment by jamesqo** [comment]
I looked into this a little bit. It seems that when you go to https://api.github.com/repos/jamesqo/Repository/contents, which corresponds to `GetAllContents` on the root directory, the content of each file will not be returned. However, passing in the file name to `GetAllContents` (I wasn't aware you could do that, I thought it only worked with directories) returns its content.

**Comment by ktundwal** [comment]
I am running into same issue. How did you pass in the file name to `client.Repository.Content.GetAllContents`? 

I tried following with no luck
```
var content = (await Client.Repository.Content.GetAllContents(RepoForTestingOwner, RepoForTesting, "/Readme.md")).First();
var content = (await Client.Repository.Content.GetAllContents(RepoForTestingOwner, RepoForTesting, "Readme.md")).First();
```
