### ISSUE TITLE
Repository Property is null on Issue objects

### ISSUE THREAD

**Issue by suchja** [octokit/octokit.net#1616]
Not sure what I'm doing wrong, but the following code always provides an `Issue` object where the `Repository` property is null.

```cs
var client = new GitHubClient(new ProductHeaderValue("Issue-Test-Client"));
var authToken = new Credentials(accessToken);

client.Credentials = authToken;

Issue completeIssue = null;
completeIssue = client.Issue.Get("lernmoment", "effort-calculator-bot", 1).GetAwaiter().GetResult();
```

Although I believe I have seen some cases to provide a non-null `Repository`, I can't reconstruct those case(s). I have tested the `client.Search.SearchIssues` feature, which also provides a "null - `Repository`".

Based on the discussion in #1243 I thought this will work.

**Comment by ryangribble** [comment]
Hi @suchja 

>Based on the discussion in #1243 I thought this will work.

The discussion in #1243 actually mentions the following:

> One thing to pay attention to is that requesting a specific issue will not return the repository key.

So it seems the upstream API response only includes the `Repository` information sometimes, and not when it is "already known" - eg when querying a single or multiple issues from a specified repository.  

Looking at the tests added in PR #1292 (the "fix" for #1243) it seems the only expected responses that do include `Repository` field are
- `GetAllForCurrent()`
- `GetAllForOwnedAndMemberRepositories()`
- `GetAllForOrganization()`

**Comment by suchja** [comment]
I see. I couldn't find any documentation about this. In case I can be of any help (meaning I would help to create some more documentation or fix existing) please point me to the proper process.

**Comment by ryangribble** [comment]
Hmm so typically we don't so document or note all of the cases where certain fields are or aren't included in API responses, but I can see in this case it would be helpful to do so. 

So in terms of documentation there is [this page]( https://github.com/octokit/octokit.net/blob/master/docs/issues .md) but I don't feel like it would be that discoverable there... 

Perhaps the best way to note that this field is not always returned  is to add a note in the xmldoc comment [here](https://github.com/octokit/octokit.net/blob/master/Octokit/Models/Response/Issue.cs#L143) saying something like the field is only included on queries that span multiple repositories, or something similar. Having it in the xmldoc text means it will show up in intellisense whenever a user is referencing the field in code

**Comment by KonH** [comment]
Unfortunately, I see null for Repository properties while running such request:
```
var request = new SearchIssuesRequest {
	Type   = IssueTypeQualifier.PullRequest,
	Author = userName
};
await _client.Search.SearchIssues(request)
```
Obviously, I don't have any repository context here and it is not clear how I can obtain it (except hacks like parsing some URLs in response objects).
Is any workaround exist here?
