### ISSUE TITLE
Dotnet core in AWS Lambda raises exception

### ISSUE THREAD

**Issue by aqwert** [octokit/octokit.net#1617]
**Issue:**
I took the code from dotnetcore, built and packaged as alpha so that I could use within my dotnet core project. This works fine as a stanad alone app but fails with the following if used within a serverless AWS [Lambda environment and ASPNet](https://github.com/aws/aws-lambda-dotnet/tree/master/Libraries/src/Amazon.Lambda.AspNetCoreServer).

```
at Amazon.Lambda.AspNetCoreServer.APIGatewayProxyFunction.<ProcessRequest>d__15.MoveNext()
PlatformNotSupportedException:
System.PlatformNotSupportedException: Operation is not supported on this platform.
at System.Runtime.InteropServices.RuntimeInformation.get_OSDescription()
at Octokit.Connection.FormatUserAgent(ProductHeaderValue productInformation)
at Octokit.Connection..ctor(ProductHeaderValue productInformation, Uri baseAddress, ICredentialStore credentialStore, IHttpClient httpClient, IJsonSerializer serializer)
```

The code to format the UserAgent checks the OS Description but the call is being rejected.

```
#if !HAS_ENVIRONMENT
                RuntimeInformation.OSDescription,
                RuntimeInformation.OSArchitecture.ToString().ToLowerInvariant(),
#else
```

I suspect that the OSArchitecture call may also fail. Would it be better to exclude this information or does the Github API require it?

Using dotnetcore 1.0

Other related (non Octokit) reports with the same error:
* https://github.com/StackExchange/StackExchange.Redis/issues/582
* https://groups.google.com/forum/#!topic/mongodb-user/l7bVlblY0hU
* https://forums.aws.amazon.com/thread.jspa?messageID=754848&tstart=0 (Dec 6, 2016) (There is code that suggests that RuntimeInformation is not possible in AWS, so returning just a plain old string value)

**Comment by ryangribble** [comment]
Hey @aqwert 

I'd be happy to use the approach they took in the StackExchange one you linked - catch the exception if thrown, and maybe just set the platform/architecture values to "unknown" in that case... 

It would be great if you wanted to fire a PR in to do this!

**Comment by aqwert** [comment]
thanks, I will see what I can do but it won't be for a while... off on holiday for a couple of weeks from tomorrow.

**Comment by ryangribble** [comment]
Just circling back on this one, is this still something you would be interested in contributing @aqwert  ?

**Comment by aqwert** [comment]
I will look at this tomorrow. Sorry for the delay

**Comment by ryangribble** [comment]
No need to apologise :grinning:

**Comment by ryangribble** [comment]
Hey @aqwert we were doing some work in this area in #1660 are you able to test whether that fixes the issue for you?  You can get the nuget packages for that PR from the appveyor feed
