### ISSUE TITLE
Pull Requests do not have a Review

### ISSUE THREAD

**Issue by nolanblew** [octokit/octokit.net#1618]
It seems that we are not able to access the "state" of a pull request review comment. Docs are here: https://developer.github.com/v3/pulls/reviews/

Would be good if we can get an enum for this.

Edit:

It looks like Reviews is a completely separate endpoint that doesn't seem to be supported yet. Can we add support for that endpoint?

**Comment by ryangribble** [comment]
Yeah, currently we have PullRequestReviewRequests and PullRequestReviewComments implemented, but not the actual PullRequestReview's themselves.

Ill mark the issue as "up for grabs", is it something you'd like to work on?

**Comment by nolanblew** [comment]
I'm out till July 10th, so if someone wants to take it before then be my guest!

**Comment by Sarmad93** [comment]
Hi @nolanblew  are u still out/busy...i would like to work on this one what do u say?

**Comment by nolanblew** [comment]
@Sarmad93 Yeah I'll take it on in my free time!

**Comment by nolanblew** [comment]
@Sarmad93 Sorry I misread your question - yes go ahead and take it!

**Comment by Sarmad93** [comment]
😄  i will open a pull request in coming weekend

**Comment by nolanblew** [comment]
@Sarmad93 Any progress updates with the branch?

**Comment by Sarmad93** [comment]
Quite busy with work in weekdays..will try my best to manage some time this weekend and start working on it.

**Comment by hartra344** [comment]
Sorry I noticed this hadn't had any traction in almost a month and started working on it yesterday for my own uses. I started a PR, only really need to finish writing integration tests

**Comment by Sarmad93** [comment]
@hartra344  👍
