### ISSUE TITLE
NewRepositoryWebHook ToRequest does not transmit all information

### ISSUE THREAD

**Issue by ctolkien** [octokit/octokit.net#1621]
Offending line:
https://github.com/octokit/octokit.net/blob/5ee4d6404628e43e5251eb68c85c31878b7d5b78/Octokit/Models/Request/NewRepositoryWebHook.cs#L124

As it's tossing away the existing instance and returning a new one, any of the other properties on the base `NewRepositoryHook` type that might have been set - like for instance, the `events` you'd like to receive are not persisted and never go over the wire.

I assume it does this because `Config` in `NewRepositoryHook` is `private set`, and as such this class cannot make modifications.

I don't really see any issue with making that property `protected set` but I'm not familiar enough with the code base. I can PR that change though if maintainers would prefer!

**Comment by ryangribble** [comment]
Isn't `Config` already `public` in the base `NewRepositoryHook` class?

Perhaps we just need to add a `ctor` on `NewRepositoryHook` that takes all the properties this class has (`Name`, `Config`, `Events`, `Active`) and use that from the `NewRepositoryWebHook.ToRequest()` ?

**Comment by ctolkien** [comment]
Is there an issue with making the `Config` `protected set` ? That would allow this descendent class to make changes to the config without needing to create a new instance.

**Comment by ryangribble** [comment]
Not specifically,  but a quick look indicated that the properties of NewRepositoryWebHook are actually put into the Config dictionary so it could get messy if that underlying field can be directly changed as well?

**Comment by ctolkien** [comment]
@ryangribble  - I'll put together a PR, can review from there.

**Comment by ctolkien** [comment]
@ryangribble  - care to review https://github.com/octokit/octokit.net/pull/1623 ?
