### ISSUE TITLE
Any way to retrieve file content of specific commit 

### ISSUE THREAD

**Issue by ghost** [octokit/octokit.net#1625]
I need a content of specific commit.
Like this command work:
git show sha:filepath
This command gives all content of the file for specific commit.
Is there any way to do this task?

**Comment by ryangribble** [comment]
Hi @patelhrp7 

How about [this overload](https://github.com/octokit/octokit.net/blob/master/Octokit/Clients/IRepositoryContentsClient.cs#L66) on RepositoryContentsClient?

**Comment by patelhrp7** [comment]
@ryangribble Thank you so much.Its work

**Comment by patelhrp7** [comment]
I want to do that scenario from local cloned repository, Is there any way to that?

**Comment by ryangribble** [comment]
Octokit.net is built you interface with github.com (programming github enterprise) API, it doesn't operate on local repos. You could look at libgit2 if you want to do local repo stuff
