### ISSUE TITLE
add documentation example about creating an issue and adding assignees

### ISSUE THREAD

**Issue by dvdstelt** [octokit/octokit.net#1626]
When creating a new issue and setting the `Assignee` property, I'm told the property is obsolete and I should use the `Assignees` property. The latter can't be set? Thank goodness for reference types! ;-)

This doesn't work. I get an obsolete warning and also get an error saying `You cannot pass both 'assignee' and 'assignees'. Only one may be provided.`
```
		var newIssue = new NewIssue("My Awesome Title")
		{
			Assignee = staffMember
		};
```

But this does work:
```
var newIssue = new NewIssue("My Awesome Title");
newIssue.Assignees.Add(staffMember);
```

**Comment by ryangribble** [comment]
Using the Add and Remove methods is the intended behaviour, similar to adding repositories to search criteria or labels to issues.   Yyou can see some implementations in the integration tests here https://github.com/octokit/octokit.net/blob/master/Octokit.Tests.Integration/Clients/IssuesClientTests.cs

**Comment by dvdstelt** [comment]
Possible, but at the very least update doco?! :)

**Comment by dvdstelt** [comment]
I'm okay to close this then, btw.

**Comment by ryangribble** [comment]
Actually there are `AddAssignee`,  `RemoveAssignee`  and `ClearAssignee` methods in `IssueUpdate` class too 

> Possible, but at the very least update doco?! :)

For sure, did you you find incorrect reference somewhere? Would you be able to send a PR to correct?

**Comment by shiftkey** [comment]
Looks like `NewIssue.Assignee` has been removed, but I'm going to leave this open as this feels like a good chance to include some example code for this scenario somewhere.
