### ISSUE TITLE
How to execute various Git commands

### ISSUE THREAD

**Issue by Korporal** [octokit/octokit.net#1627]
Does OCtokit allow me to write an app that can execute arbitrary commands against some repo? 

For example I've cobbled together some basic code that gets all our repos and for each of these gets all forks of them.

Now I want to run the equivalent of:

> git branch -r --merged

But have no idea how to accomplish this kind of thing.

Alternatively for my purposes, is there a way to see if some commit (i.e the latest commit on some branch) is present on another branch (i.e. "master")? Without enumerating all of the commits myself, explicitly?

I can see that I can use 

`IRepositoriesClient.Commit.Get()`

but there's no way I can pass in a branch name so cannot easily get what I need. If the commit is on _any_ branch I'll get it with the above call, but I want to know if I can get it on some named branch.

**Comment by khellang** [comment]
Octokit is only concerned about the GitHub API, which coincidentally exposes some primitive git metadata, but probably not at the level you're after. Sounds like you might want to use something like libgit2sharp for this. Possibly in combination with Octokit.

**Comment by ryangribble** [comment]
Thanks @khellang I'm going to close this issue out
