### ISSUE TITLE
DeleteEventPayload missing?

### ISSUE THREAD

**Issue by Norbo11** [octokit/octokit.net#1635]
Hey, I can't find a DeleteEventPayload anywhere, which means I'm unable to inspect such events using the Events API. Would it be possible to get it added? Also, do you know how I can work around this in the meantime?

**Comment by ryangribble** [comment]
I need to review how that code works but it would be great if you could send a PR to implement the missing payload class! 

in terms of a workaround you could obviously call the github API yourself or use the lower level octokit Connection Get method, but really the easiest way would be to implement the payload class and then use the nuget package from our appveyor feed, until the next official release to nuget.org

**Comment by ryangribble** [comment]
I poked a bit more into this and have proposed a workaround that will allow any unsupported event types to be accessed as Json...  please provide input on PR #1645

**Comment by ryangribble** [comment]
I've raised #1646 to cover the fact that there are various missing event payloads, so I'll close this issue.  If you feel like implementing the `DeleteEvent` please send a PR over!  There is some guidance in #1646 about how to implement a new payload
