### ISSUE TITLE
Check for existence of a commit

### ISSUE THREAD

**Issue by Korporal** [octokit/octokit.net#1641]
Is there a (simple) way to use Octokit to check whether a commit with a (truncated) commit ID exists in a repo?

I can get a Repository object but can't understand how to get that to search for a commit (on any branch).

Is this possible?

**Comment by Korporal** [comment]
OK I found a way, NP.

**Comment by ryangribble** [comment]
Hi @Korporal, glad you sorted it out yourself... did you want to post a code snippet of what you ended up with, so someone with the same question can see your solution?

**Comment by Korporal** [comment]
@ryangribble - Hi, I would but having confusing problems, see ticket 1642.
