### ISSUE TITLE
Expected behavior on a Get for a commit that does not exist.

### ISSUE THREAD

**Issue by Korporal** [octokit/octokit.net#1642]
I can't see what to expect when one attempts to get a non existent commit (e.g. using RepositoriesClient.Commit.Get(long, string)).

It seems from some crude debugging that the task hangs, never returns...

**Comment by Korporal** [comment]
Here's more detail

The code below is simply experimental

`        public void OnNext(Repository value)
        {
            var c = client.Commit.Get(id, commit+"777").Result;
        }
`

without the "777" appended it works, I get a real commit object back and its valid. When I append the "777" to force the reference to be a non-existent reference, it simply hangs, the .Result never materializes.

**Comment by shiftkey** [comment]
@Korporal I don't trust `.Result` in general because there's better ways to work with tasks these days, and this code works for me:

```cs
try
{
    var master = "cda714bef60d3c787ee3db2512025cde46d02dba";
    var commit = await client.Repository.Commit.Get("octokit", "octokit.net", master + "777");
}
catch (NotFoundException ex)
{
  // handle commit not found
}
```

**Comment by Korporal** [comment]
@shiftkey - Hi, thanks that's very helpful and works (although I actually get an AggregateExcedption but the inner exception is indeed NotFoundException.

**Comment by shiftkey** [comment]
@Korporal I'm not sure which version of the .NET Framework you're running on (this was with 4.5.2) but I think that's the root cause. Anyway, I'm glad you were able to handle the exception!

**Comment by ryangribble** [comment]
Yeah I was about to say the same thing, my repro gets the expected 404 (NotFoundException).  Using `.Result` is not great and depending on what your hosting app was it can cause infinite hangs.  Although that might mean we have a `.ConfigureAwait(false);` missing somewhere...

**Comment by rakeshvanga** [comment]
Trying out on .netcore 3.0 and seeing `Octokit.ApiValidationException` exception with an invalid commit id.  Should the code be updated to handle for 3.0?

**Comment by shiftkey** [comment]
> Trying out on .netcore 3.0 and seeing `Octokit.ApiValidationException` exception with an invalid commit id. Should the code be updated to throw NotFoundException for .netcore 3.0?

No, this is a different situation (we target netstandard these days).

Please open a fresh issue with details if you'd like us to investigate this.

**Comment by rakeshvanga** [comment]
Sure, opened #2026
