### ISSUE TITLE
Github confusing behavior (confirmed by Github staff)

### ISSUE THREAD

**Issue by Korporal** [octokit/octokit.net#1643]
I'm puzzled (and I've just reached out to Github) because I created a local commit, then I pushed it to my fork (only).

Then I interrogate Github (the organization that owns the original repo from which I forked) and query it for the commit and I get "true". If I create a URL in the browser that "pretends" the commit is in the base repo it works, its shows me the commit but gives no hint that the commit is really on a fork.

I'm trying to write code that will tell me if a commit is on the base repo, else on someone's fork, else not present at all (in Github) but because of this behavior ALL commits on all forks appear to be on the base repo even though no pull request has yet even been created!

**Comment by shiftkey** [comment]
@Korporal please provide a sample of the code you're using - the API is different to the website, so maybe there's some things that can be clarified when we're talking about the same code.

**Comment by Korporal** [comment]
@shiftkey - I'll try to get around to this later today. But Github confirmed that being able to see a commit that's only on a fork using a URL that targets the upstream is expected behaviour - at the browser/URL level anyway.

I am forming the opinion that forks are nothing more than "virtual views" of a repo, for the forks made by John and Mary, all existing branches get cloned as (for example) Mary.master and John.master. The Mary and John when perusing their forks are actually simply seeing their own branches but with the name prefix stripped away.

So there really is only one repo and the appearance of forks as distinct repos is illusory, but this is just what I think I don't know for certain.

**Comment by Korporal** [comment]
@shiftkey - Here, I just forked the Octokit repo and then manually added a simple commit to my "master" branch, however using this URL:

https://github.com/octokit/octokit.net/commit/550c9d405c24c162d43d20b1363b3c5b5fea30af

It appears that it's "in" the base repo, the one from which I forked !

**Comment by shiftkey** [comment]
> I'm hoping there's a programmatic way to get a "no" to the question "Is this commit (550C9D40) in the upstream repo?".

I don't think so. I think this behaviour came about because it was hard to find a commit within a network of repositories without knowing which fork had it - the exact opposite of what you'd expect.

What I'd do is compare two branches, like this:

https://github.com/octokit/octokit.net/compare/master...Korporal:master

This maps to the API as https://api.github.com/repos/octokit/octokit.net/compare/master...Korporal:master

And shows your new commit:

<img width="848"  src="https://user-images.githubusercontent.com/359239/28884952-5f671ebc-778a-11e7-9835-48b4701a1029.png">

**Comment by Korporal** [comment]
@shiftkey - Hi, well I'll consider what you suggested. But in my case I don't care about branches as such. I want to reliably know if the commit is anywhere within the main (which I call "principal") repo or in a fork of that repo. The behavior is counter-intuitive I think and it would be neat of Github would think about this and perhaps add a new API endpoint or option.

**Comment by ryangribble** [comment]
Since this isn't specifically an octokit issue I'd suggest you make sure your feedback is sent to github support (you could also ask them if there is a way you can tell if a commit is in the main repo or a fork via the API... It's not clear if you already did that or not :grinning:)
