### ISSUE TITLE
Imitation is flattery?

### ISSUE THREAD

**Issue by M-Zuber** [octokit/octokit.net#1644]
I want to create a generic template for building api wrappers such as this one, based off of Octokit.net
What do I need to do from a legal perspective to be properly legal?
@shiftkey ?

**Comment by shiftkey** [comment]
I Am Not A Lawyer, but I'd mostly say:

 - respect the license associated with the code
 - to avoid confusion with the Octokit group of libraries, a name change would be :gem:
 - attribution is always nice (but not required)

**Comment by M-Zuber** [comment]
Sounds good, 
Was planning on doing all 3, just wanted to see if I missed anything
