### ISSUE TITLE
Implement EventPayload models for the event types supported by GitHub API

### ISSUE THREAD

**Issue by ryangribble** [octokit/octokit.net#1646]
GitHub API has currently [37 event payloads](https://developer.github.com/v3/activity/events/types/) that the Activity API can return, and only 8 of these are implemented in Octokit.net!

To support these as first class objects, Octokit needs a response model class added [here](https://github.com/octokit/octokit.net/blob/master/Octokit/Models/Response/ActivityPayloads) for each one, and this [magic switch statement](https://github.com/octokit/octokit.net/blob/34d13743e5bdf70b7e2ab6b3e44531050f63ee26/Octokit/Http/SimpleJsonSerializer.cs#L159-L178) updated to suit.

We should also add a new [unit test](https://github.com/octokit/octokit.net/blob/master/Octokit.Tests/Clients/EventsClientTests.cs#L567-L833) and [integration test](https://github.com/octokit/octokit.net/blob/master/Octokit.Tests.Integration/Clients/EventsClientTests.cs) for each payload (although these may fail if they are uncommon events so maybe we can change to unit tests using hardcoded json content from the github api docs).

Related to #1635 (DeleteEvent not supported) and #1645 (proposed workaround to allow unsupported event payloads to be provided as a Json string)

List of [current event types](https://developer.github.com/v3/activity/events/types)
- [x] CommitCommentEvent
- [x] CreateEvent
- [x] DeleteEvent
- [ ] DeploymentEvent
- [ ] DeploymentStatusEvent
- [ ] DownloadEvent
- [ ] FollowEvent
- [x] ForkEvent
- [ ] ForkApplyEvent
- [ ] GistEvent
- [ ] GollumEvent
- [ ] InstallationEvent
- [ ] InstallationRepositoriesEvent
- [x] IssueCommentEvent
- [x] IssuesEvent
- [ ] LabelEvent
- [ ] MarketplacePurchaseEvent
- [ ] MemberEvent
- [ ] MembershipEvent
- [ ] MilestoneEvent
- [ ] OrganizationEvent
- [ ] OrgBlockEvent
- [ ] PageBuildEvent
- [ ] ProjectCardEvent
- [ ] ProjectColumnEvent
- [ ] ProjectEvent
- [ ] PublicEvent
- [x] PullRequestEvent
- [ ] PullRequestReviewEvent
- [x] PullRequestReviewCommentEvent
- [x] PushEvent
- [ ] ReleaseEvent
- [ ] RepositoryEvent
- [x] StatusEvent
- [ ] TeamEvent
- [ ] TeamAddEvent
- [x] WatchEvent

**Comment by Hollyw0od** [comment]
I can hop on this one.

**Comment by ryangribble** [comment]
Just noting that `StatusEvent` will be implemented in #1732
