### ISSUE TITLE
The client doesn't support for files raw content 

### ISSUE THREAD

**Issue by l1salvatore** [octokit/octokit.net#1651]
I didn't found any object that refers to all files of the repository. Could you please tell me if it is correct ? 

Thanks in advance!

Lucas

**Comment by shiftkey** [comment]
Are you looking for the [Content](https://developer.github.com/v3/repos/contents/) API, that lets you read directories or files in a repository?

```
var contents = await client.Repository.Content.GetAllContents("octocat", "Spoon-Knife");
```

This should give you a list of folders and files at the root of the repository.

**Comment by shiftkey** [comment]
Closing this out due to inactivity
