### ISSUE TITLE
Create New Issue with Assigned Project(s)

### ISSUE THREAD

**Issue by shaggygi** [octokit/octokit.net#1652]
How do you assign a project to a new issue?  I notice there are Labels, Milestone, etc... but no Projects.

Is there another method to use in the new Project APIs with preview package?  Thx

**Comment by ryangribble** [comment]
Project support ha been merged to master but isn't in an official build yet. If you grab the nuget package from our appveyor fed it should be there. 

What you want to do is create a project card for an issue - you specify the issue's id (globally unique id, not the repo issue number) as `ContentId` and `Issue` as `ContentType`.  I think you also need to specify the columnId the card will go into (there are separate API clients for getting the details of the configured columns for a project etc) 

``` csharp
var newCard = new NewProjectCard(issueId, ProjectCardContentType.Issue);
        var result = await client.Repository.Project.Card.Create(columnId, newCard);
```

**Comment by shaggygi** [comment]
@ryangribble as usual, that did the trick.  thanks for your help 😄
