### ISSUE TITLE
No mapping in between IssueComment and Issue

### ISSUE THREAD

**Issue by sxg611** [octokit/octokit.net#1666]
Hi, I am trying to pull all of the issue comments for a given repository then trying to map them to their given issues. Right now, if I use: 

var repoComments = await GitHubClient.Issue.Comment.GetAllForRepository(Owner, Name);

I get a list of IssueComments ordered by commentId, but they don't have any attribute mapping them to their parent issue. The only reference to the issue they belong to is given in the htmlUrl:

 "html_url": "https://github.com/octocat/Hello-World/issues/1347#issuecomment-1"

Since issue comments are heavily dependent on the context of the given issue, it would make sense to have an attribute explicitly linking both instead of having to parse the htmlURL. It would also be beneficial to add the ability to filter/sort by issue number through the IssueCommentRequest parameter

**Comment by shiftkey** [comment]
Sadly this is a limit of the payload that's returned from [the API itself](https://developer.github.com/v3/issues/comments/#list-comments-on-an-issue).

This is the entire payload we get:

```
[
  {
    "id": 1,
    "url": "https://api.github.com/repos/octocat/Hello-World/issues/comments/1",
    "html_url": "https://github.com/octocat/Hello-World/issues/1347#issuecomment-1",
    "body": "Me too",
    "user": {
      "login": "octocat",
      "id": 1,
      "avatar_url": "https://github.com/images/error/octocat_happy.gif",
      "gravatar_id": "",
      "url": "https://api.github.com/users/octocat",
      "html_url": "https://github.com/octocat",
      "followers_url": "https://api.github.com/users/octocat/followers",
      "following_url": "https://api.github.com/users/octocat/following{/other_user}",
      "gists_url": "https://api.github.com/users/octocat/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/octocat/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/octocat/subscriptions",
      "organizations_url": "https://api.github.com/users/octocat/orgs",
      "repos_url": "https://api.github.com/users/octocat/repos",
      "events_url": "https://api.github.com/users/octocat/events{/privacy}",
      "received_events_url": "https://api.github.com/users/octocat/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2011-04-14T16:00:49Z",
    "updated_at": "2011-04-14T16:00:49Z"
  }
]
```
