### ISSUE TITLE
[Question] Retrieve GitHub PR diff using application/vnd.github.v3.diff to find line position in diff

### ISSUE THREAD

**Issue by vishrutshah** [octokit/octokit.net#1684]
Hi There,

I was looking into the GitHub APIs to retrieve the PR diff but not sure which calls I am supposed to use. Basically, I am trying to auto generate line pointer into the PR diff. 

Basically, I know the PR URL like https://github.com/Azure/azure-rest-api-specs/pull/1737/files with the files and lines number but I want to generate URL like https://github.com/Azure/azure-rest-api-specs/pull/1737/files#diff-4e2918d5f8cd4a4461eca1d6da37eda1R2 which looks like  

`https://github.com/Azure/azure-rest-api-specs/pull/1737` - PR URL
+ 
`files#diff-4e2918d5f8cd4a4461eca1d6da37eda1` - files#diff-{someNumber}
+
`R2` - R{lineNumber}

I am not sure what APIs should I use to retrieve `4e2918d5f8cd4a4461eca1d6da37eda1` number to construct the complete URL. It'd be great if you can provide some pointers if any. 

Thanks in advance!

**Comment by ryangribble** [comment]
Im not sure where the `4e2918d5f8cd4a4461eca1d6da37eda1` comes from sorry!  There appears to be a different value for each file in the pull requestr.  Perhaps its a blob or tree SHA or something else you might be able to get at, via the [git data](https://developer.github.com/v3/git/) api?

**Comment by shiftkey** [comment]
@ryangribble @vishrutshah unless it's something that's available and documented via the https://developer.github.com/ site, it's not something that should be in Octokit.net.
