### ISSUE TITLE
Integration tests that rely on collaborators are failing

### ISSUE THREAD

**Issue by ryangribble** [octokit/octokit.net#1686]
GitHub changes have made it such that adding a collaborator is not effective until the collaborator accets the invitation.

There are number of integration tests that are now failing due to this... the following clients (and their observable counterparts) are affected:

`RepositoryCollaboratorClient`
`OrganizationOutsideCollaboratorsClient`
`PullRequestReviewRequestsClient`

We have a newer `[DualAccountTest]`  approach that can likely be used to fix most of them, but tests that involve 2 additional collaborators (in addition to the integration test user) will still be a problem.  Using a pre setup repository couldbe the answer in those cases.

![image](https://user-images.githubusercontent.com/5425163/31254193-055d2b14-aa6b-11e7-85ef-26cda45cf3af.png)

**Comment by Niyaroje** [comment]
Xchc

**Comment by hnrkndrssn** [comment]
I'll put my hand up to get this sorted

**Comment by hnrkndrssn** [comment]
Aaaand I ran into the _you are limited to sending 50 invitations to a repository per 24 hour period_ limit...

**Comment by ryangribble** [comment]
🎢
