### ISSUE TITLE
Is there any way to get repository insights/pulse via the GitHub Rest API v3?

### ISSUE THREAD

**Issue by sxg611** [octokit/octokit.net#1690]
I want to get statistics for the number of issues opened/closed for a repository during a specified period of time. I can view this information in GitHub by clicking the insights tab.

For example: https://github.com/nodejs/node/pulse

Can I pull any of this information via the GitHub Rest API v3/Octokit.net? I was looking through the documentation but couldn't find any information. Thanks in advance

**Comment by ryangribble** [comment]
I also can't find much in the REST API spec for this info.  The repo statistics are probably the closest thing?

https://developer.github.com/v3/repos/statistics/

**Comment by ryangribble** [comment]
I think most of the data for the other tabs (community, traffic,forks etc) is available in the API, but some of the sections like PULSE or NETWORK do not appear to be exposed directly in the API

https://developer.github.com/v3/repos/community/
https://developer.github.com/v3/repos/traffic/
https://developer.github.com/v3/repos/forks/

**Comment by shiftkey** [comment]
Also, keep in mind that any new features in the GitHub API are not going to be backported to v3.

I've been chatting with the other Octokit teams a bit about what this means for Octokit.net, and need to grab some time with @ryangribble, @mderriey and whoever else is interested to sketch this out further.

**Comment by sxg611** [comment]
Ok, seems like the information that is exposed doesn't fit what I need. Thanks for your help

**Comment by tejasa97** [comment]
@sxg611 https://github.com/tejasa97/github_traffic
You could have a look at my repo for functionality, drop a comment if you need help!
