### ISSUE TITLE
Error "One or more projects in the solution were not correct are loaded. "

### ISSUE THREAD

**Issue by it19862** [octokit/octokit.net#1700]
**Used**
Visual Studio 2015

**Open the file**
c:\UsersXadmin\Documents\Visual Studio 2015\Projects\prm\github\octokit.net\octokit.net_Projects_prm\Octokit.sln

I'm getting the message.
"One or more projects in the solution were not correct
are loaded. "
For more information, see "Output"

The **"Output"** window contains:
"**C:\Users\admin\Documents\Visual Studio 2015\Projects\prm\github\octokit.net\octokit.net_Projects_prm\Octokit\Octokit.csproj:**
	error: The default XML namespace for this project must be the **MSBuild XML** namespace.
		If the project is created in **MSBuild 2003** format,
			add xmlns = "http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element.
		If the project was created in the old 1.0 or 1.2 format, 
			convert it to **MSBuild 2003** format.
			C:\Users\admin\Documents\Visual Studio 2015\Projects\prm\github\octokit.net\octokit.net_Projects_prm\Octokit\**Octokit.csproj**

**C:\Users\admin\Documents\Visual Studio 2015\Projects\prm\github\octokit.net\octokit.net_Projects_prm\Octokit.Reactive\Octokit.Reactive.csproj:**
	error: The default XML namespace for this project must be the MSBuild XML namespace.
		If the project is created in MSBuild 2003 format,
			add xmlns = "http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element.
		If the project was created in the old 1.0 or 1.2 format, 
			convert it to MSBuild 2003 format.
			C:\Users\admin\Documents\Visual Studio 2015\Projects\prm\github\octokit.net\octokit.net_Projects_prm\Octokit.Reactive\Octokit.Reactive.csproj

**C:\Users\admin\Documents\Visual Studio 2015\Projects\prm\github\octokit.net\octokit.net_Projects_prm\Octokit.Tests\Octokit.Tests.csproj:**
	error: The default XML namespace for this project must be the MSBuild XML namespace.
		If the project is created in MSBuild 2003 format,
			add xmlns = "http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element.
		If the project was created in the old 1.0 or 1.2 format,
			convert it to MSBuild 2003 format.
			C:\Users\admin\Documents\Visual Studio 2015\Projects\prm\github\octokit.net\octokit.net_Projects_prm\Octokit.Tests\Octokit.Tests.csproj

**C:\Users\admin\Documents\Visual Studio 2015\Projects\prm\github\octokit.net\octokit.net_Projects_prm\Octokit.Tests.Conventions\Octokit.Tests.Conventions.csproj:**
	error: The default XML namespace for this project must be the MSBuild XML namespace.
		If the project is created in MSBuild 2003 format,
			add xmlns = "http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element.
		If the project was created in the old 1.0 or 1.2 format,
			convert it to MSBuild 2003 format.
			C:\Users\admin\Documents\Visual Studio 2015\Projects\prm\github\octokit.net\octokit.net_Projects_prm\Octokit.Tests.Conventions\Octokit.Tests.Conventions.csproj

**C:\Users\admin\Documents\Visual Studio 2015\Projects\prm\github\octokit.net\octokit.net_Projects_prm\Octokit.Tests.Integration\Octokit.Tests.Integration.csproj:**
	error: The default XML namespace for this project must be the MSBuild XML namespace.
		If the project is created in MSBuild 2003 format,
			add xmlns = "http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element.
		If the project was created in the old 1.0 or 1.2 format,
			convert it to MSBuild 2003 format.
			C:\Users\admin\Documents\Visual Studio 2015\Projects\prm\github\octokit.net\octokit.net_Projects_prm\Octokit.Tests.Integration\Octokit.Tests.Integration.csproj
"

**Question**
 Do the actions described in the "Output" window?
Or it is possible to solve a problem to another?

**Comment by ryangribble** [comment]
Hi @it19862 

We have upgraded to .NET Core project system so you will need Visual Studio 2017 to open the solution.  Alternatively you can use VSCode, or our CAKE build scripts, as mentioned in the [CONTRIBUTING](https://github.com/octokit/octokit.net/blob/master/CONTRIBUTING.md#running-builds-cross-platform) guide

I do notice we still have a mention of Visual Studio 2015 on that page - sorry!  We need to update this to say VS2017 😛

**Comment by it19862** [comment]
If to open in VS2017 I receive "an output"


C: \ Users \ admin \ Documents \ Visual Studio 2015 \ Projects \ prm \ github \ octokit.net \ octokit.net_Projects_prm \ Octokit.Tests.Conventions \ Octokit.Tests.Conventions.csproj: error: imported project "C: \ Program Files (x86) \ Microsoft Visual Studio \ 2017 \ Community \ MSBuild \ Sdks \ Microsoft.NET.Sdk \ Sdk \ Sdk.props "was not found. Verify that the path in the <Import> declaration is correct, and make sure that there is a file on the drive. C: \ Users \ admin \ Documents \ Visual Studio 2015 \ Projects \ prm \ github \ octokit.net \ octokit.net_Projects_prm \ Octokit.Tests.Conventions \ Octokit.Tests.Conventions.csproj

C: \ Users \ admin \ Documents \ Visual Studio 2015 \ Projects \ prm \ github \ octokit.net \ octokit.net_Projects_prm \ Octokit.Tests.Integration \ Octokit.Tests.Integration.csproj: error: imported project "C: \ Program Files (x86) \ Microsoft Visual Studio \ 2017 \ Community \ MSBuild \ Sdks \ Microsoft.NET.Sdk \ Sdk \ Sdk.props "was not found. Verify that the path in the <Import> declaration is correct, and make sure that there is a file on the drive. C: \ Users \ admin \ Documents \ Visual Studio 2015 \ Projects \ prm \ github \ octokit.net \ octokit.net_Projects_prm \ Octokit.Tests.Integration \ Octokit.Tests.Integration.csproj

picture [link](http://prntscr.com/h5llvy) 

**Question.**
How to be?
