### ISSUE TITLE
Search repository. How to extract README.md.

### ISSUE THREAD

**Issue by it19862** [octokit/octokit.net#1701]
I'm trying to make a code(**C#**) that looks for repositories in which README contains the necessary words.

```
 public async void searchReposit_GitHub() 
        {
            var client = new GitHubClient(new ProductHeaderValue("my-cool-app")); 
            var basicAuth = new Credentials("username", "password"); 
            client.Credentials = basicAuth;
            
            var request = new SearchRepositoriesRequest("mvc client side framework") 
            {   
                //  // or go all out and search the readme, name or description?
                 In = new[] { InQualifier.Readme, InQualifier.Description, InQualifier.Name },             
            };            
            var result = await client.Search.SearchRepo(request);
            for (int s = 0; s < 3; s++)
            {
                var vr = result.Items[s];                

                string readme_name = vr.Name;
                string readme_descript = vr.Description;                
                string readme_Html_url = vr.HtmlUrl; 
            }
		}
```

It turned out to be done only to search in the description.
![111](https://user-images.githubusercontent.com/18245828/32394083-009d5818-c0ed-11e7-8356-4ac261ee476a.jpg)

**Questions.**
How to make the code look in the text README?
How do I make the code extract the README text into a variable?
![112](https://user-images.githubusercontent.com/18245828/32394114-138d4136-c0ed-11e7-8013-f6c2f651d2a1.jpg)

**Comment by shiftkey** [comment]
@it19862 as the README isn't part of the returned search results, you'll need to make a follow-up query to read the [`README`](https://developer.github.com/v3/repos/contents/#get-the-readme) for a given repository.

I've tried to tweak your sample to illustrate this - hope it helps!

```
            var result = await client.Search.SearchRepo(request);
            for (int s = 0; s < 3; s++)
            {
                var vr = result.Items[s];
                var readme = await client.Repository.Content.GetReadme(vr.Id);
                var rawText = readme.Content;
            }
```
