### ISSUE TITLE
How do I make the repository search run within the topic?

### ISSUE THREAD

**Issue by it19862** [octokit/octokit.net#1704]
The code to search for "github.com" repositories:

	```
	 public async void searchReposit_GitHub() 
		        {
		
		            var client = new GitHubClient(new ProductHeaderValue("my-cool-app")); 
		            var basicAuth = new Credentials("username", "password"); 
		
		            client.Credentials = basicAuth;
		
		            
		            var request = new SearchRepositoriesRequest("mvc client side framework") 
		            {   
		                //  // or go all out and search the readme, name or description?
		                 In = new[] { InQualifier.Readme, InQualifier.Description, InQualifier.Name },
		             
		            };            
		
		            var result = await client.Search.SearchRepo(request);
		
		
		            for (int s = 0; s < 3; s++)
		            {
		                var vr = result.Items[s];
		
		                string readme_content;
		                string readme_name;
		                string readme_descript;
		                string readme_Html_url;
		
		                readme_name = vr.Name;
		                readme_descript = vr.Description;
						readme_Html_url = vr.HtmlUrl; 
						
						 try
		                {
		                    var readme = await client.Repository.Content.GetReadme(vr.Id);
		                    var rawText = readme.Content;
		                
		     				readme_content = rawText.ToString();
		                    richTextBox1.AppendText(" Сontent `readme` *** " + readme_content + " *** \r\n"); 
		                }
		                catch (Exception)
		                {
		                    richTextBox1.AppendText(" Сontent `readme` -  empty ххх" +  " \r\n"); // url
		                    // return;
		                    // throw;
		                }
						
		            }
				}
```
				

There is a theme https://github.com/topics/chrome-extensions

Question
How to make the code look inside: https://github.com/topics/chrome-extensions

**Comment by ryangribble** [comment]
Are you saying you want to access the "topics" for a given repo?

**Comment by it19862** [comment]
@ryangribble 
I'm sorry, I still do not understand the structure of "github.com".

How to understand the place github.com/topics/chrome-extensions

"Chrome extension" is the theme in which the repositories are located?
or
"Chrome extension" - a repository in which there are nested repositories?

"Chrome extension" contains 95 pieces of repositories.

Question
How do I search for the words I need in "README.MD" in 95 pieces of repositories that contain the "Chrome extension" (github.com/topics/chrome-extensions)?


For example.
Similar topic "API" (https://github.com/topics/api) contains 9039 pieces of repositories.

PS
Sorry if the question (answer) is difficult to perceive.
I do not know much English.
I use - translate.google

**Comment by ryangribble** [comment]
Hi @it19862 

"Chrome extension" is a TOPIC.

A Repository can have as many TOPICs as the owner wants.

BUT a TOPIC does not own a repository... it is like a tag or label on a repository, that can group repositories together that have similar topics.  Does that make sense?

Here is some information: 
https://github.com/blog/2309-introducing-topics
https://help.github.com/articles/about-topics/


Yes It is possible to search for repositories with a topic: https://help.github.com/articles/searching-repositories/#search-by-repository-topic


But we have not implemented TOPICS in octokit.net yet!

To implement this support we would need to:
- Add `Topic` field to `Repository` and use [preview header](https://developer.github.com/v3/previews/#repository-topics) to enable the field to be returned from the API
- Add `Topic` field to `SearchRepositoriesRequest` so you can search by topic
- Add `Topics` field to `SearchRepositoriesRequest` so you can search by number of topics

**Comment by ryangribble** [comment]
I've raised #1707 to cover implementing this support in Octokit
