### ISSUE TITLE
How repository search works by criteria: Readme, Description, Name?

### ISSUE THREAD

**Issue by it19862** [octokit/octokit.net#1705]
I tried several search options
Search phrase - api for github;
The number of search results is determined - result.TotalCount

Search result table

p_n | search type | Number of search results.     Try one | Number of search results     Trying two | Number of search results.     Trying three
-- | -- | -- | -- | --
1 | search on github.com | 2 733 | 2 733 | 2 734
  |   |   |   |  
2 | In = new[] { InQualifier.Readme, InQualifier.Description,   InQualifier.Name }, // result.TotalCount - 124 189 | 124 189 | 194 507 | 212 491
  |   |   |   |  
3 | In = new[] {InQualifier.Name }, // result.TotalCount -  18 | 18 | 18 | 18
4 | In = new[] {InQualifier.Description } // result.TotalCount   -  2 347 | 2 347 | 2 347 | 2 348
5 | In = new[] {InQualifier.Readme}, // result.TotalCount - 384   924 | 384 924 | 370 163 | 311 037

**Question.**
**1.** What is the search option for "octokit.net"?

Option 1 - uses the "AND" operator?
In = new [] {
InQualifier.Readme,
and
InQualifier.Description,
and
InQualifier.Name
}

Option 2 - uses the "OR" operator?
In = new [] {
InQualifier.Readme,
or
InQualifier.Description,
or
InQualifier.Name
}

Or other ways?

**2.** As search "octokit.net" uses the search words:
 - "api for github" - searches for the whole phrase?
 - "api" AND "for" AND "github" - uses the "AND" operator?
 - "api" OR "for" OR "github" - uses the "OR" operator?

**3.** How does the search for "github.com"?
I will assume: if the result "number 1" from the table is approximately equal to "number 4", then "github.com" searches for repositories by description
Did I understand correctly?

CODE
`
public async void searchReposit_GitHub() 
	        {
	
	            var client = new GitHubClient(new ProductHeaderValue("my-cool-app")); 
	            var basicAuth = new Credentials("username", "password"); 
	
	            client.Credentials = basicAuth;
	
	            
	            var request = new SearchRepositoriesRequest("api for github") 
	            {   
	               // or go all out and search the readme, name or description?
                                 In = new[] { InQualifier.Readme, InQualifier.Description, InQualifier.Name },
                               // In = new[] {InQualifier.Name}, // result.TotalCount -  18
                              // In = new[] {InQualifier.Description} // result.TotalCount -  2 347
	                 // In = new[] {InQualifier.Readme}, // result.TotalCount - 384 924     
	             
	            };            
	
	            var result = await client.Search.SearchRepo(request);
	            int i = result.TotalCount;
	
	            for (int s = 0; s < 3; s++)
	            {
	                var vr = result.Items[s];
	
	                string readme_content;
	                string readme_name;
	                string readme_descript;
	                string readme_Html_url;
	
	                readme_name = vr.Name;
	                readme_descript = vr.Description;
					readme_Html_url = vr.HtmlUrl; 
					
					 try
	                {
	                    var readme = await client.Repository.Content.GetReadme(vr.Id);
	                    var rawText = readme.Content;
	                
	     				readme_content = rawText.ToString();
	                    richTextBox1.AppendText(" Сontent `readme` *** " + readme_content + " *** \r\n"); 
	                }
	                catch (Exception)
	                {
	                    richTextBox1.AppendText(" Сontent `readme` -  empty ххх" +  " \r\n"); // url
	                    
	                }
					
	            }
			}

`

**Comment by ryangribble** [comment]
The API documentation for Repository search is here: https://developer.github.com/v3/search/#search-repositories

Answer to your questions:

1. Option 2

2. I believe the search keywords are "AND" logic by default.
`api github` is api AND github
`"api github"` is "api github" as a phrase

3. Github.com search by default searches Name AND Description.  https://help.github.com/articles/searching-repositories/#search-by-repository-topic
(but you can search in README as well by specifying the `in:` qualifier
