### ISSUE TITLE
Error "One or more projects in the solution were not correct are loaded. "

### ISSUE THREAD

**Issue by it19862** [octokit/octokit.net#1706]
**Used**
Visual Studio#  **2017**

Open the file
c:\UsersXadmin\Documents\Visual Studio 2015\Projects\prm\github\octokit.net\octokit.net_Projects_prm\Octokit.sln

I'm getting the message.
"One or more projects in the solution were not correct
are loaded. "
For more information, see "Output":
C: \ Users \ admin \ Documents \ Visual Studio 2015 \ Projects \ prm \ github \ octokit.net \ octokit.net_Projects_prm \ Octokit \ Octokit.csproj: error: imported project "C: \ Program Files (x86) \ Microsoft Visual Studio \ 2017 \ Community \ MSBuild \ Sdks \ Microsoft.NET.Sdk \ Sdk \ Sdk.props "was not found. Verify that the path in the declaration is correct, and make sure that there is a file on the drive. C: \ Users \ admin \ Documents \ Visual Studio 2015 \ Projects \ prm \ github \ octokit.net \ octokit.net_Projects_prm \ Octokit \ Octokit.csproj

C: \ Users \ admin \ Documents \ Visual Studio 2015 \ Projects \ prm \ github \ octokit.net \ octokit.net_Projects_prm \ Octokit.Reactive \ Octokit.Reactive.csproj: error: imported project "C: \ Program Files (x86) \ Microsoft Visual Studio \ 2017 \ Community \ MSBuild \ Sdks \ Microsoft.NET.Sdk \ Sdk \ Sdk.props "was not found. Verify that the path in the declaration is correct, and make sure that there is a file on the drive. C: \ Users \ admin \ Documents \ Visual Studio 2015 \ Projects \ prm \ github \ octokit.net \ octokit.net_Projects_prm \ Octokit.Reactive \ Octokit.Reactive.csproj

C: \ Users \ admin \ Documents \ Visual Studio 2015 \ Projects \ prm \ github \ octokit.net \ octokit.net_Projects_prm \ Octokit.Tests \ Octokit.Tests.csproj: error: imported project "C: \ Program Files (x86) \ Microsoft Visual Studio \ 2017 \ Community \ MSBuild \ Sdks \ Microsoft.NET.Sdk \ Sdk \ Sdk.props "was not found. Verify that the path in the declaration is correct, and make sure that there is a file on the drive. C: \ Users \ admin \ Documents \ Visual Studio 2015 \ Projects \ prm \ github \ octokit.net \ octokit.net_Projects_prm \ Octokit.Tests \ Octokit.Tests.csproj

C: \ Users \ admin \ Documents \ Visual Studio 2015 \ Projects \ prm \ github \ octokit.net \ octokit.net_Projects_prm \ Octokit.Tests.Conventions \ Octokit.Tests.Conventions.csproj: error: imported project "C: \ Program Files (x86) \ Microsoft Visual Studio \ 2017 \ Community \ MSBuild \ Sdks \ Microsoft.NET.Sdk \ Sdk \ Sdk.props "was not found. Verify that the path in the declaration is correct, and make sure that there is a file on the drive. C: \ Users \ admin \ Documents \ Visual Studio 2015 \ Projects \ prm \ github \ octokit.net \ octokit.net_Projects_prm \ Octokit.Tests.Conventions \ Octokit.Tests.Conventions.csproj

C: \ Users \ admin \ Documents \ Visual Studio 2015 \ Projects \ prm \ github \ octokit.net \ octokit.net_Projects_prm \ Octokit.Tests.Integration \ Octokit.Tests.Integration.csproj: error: imported project "C: \ Program Files (x86) \ Microsoft Visual Studio \ 2017 \ Community \ MSBuild \ Sdks \ Microsoft.NET.Sdk \ Sdk \ Sdk.props "was not found. Verify that the path in the declaration is correct, and make sure that there is a file on the drive. C: \ Users \ admin \ Documents \ Visual Studio 2015 \ Projects \ prm \ github \ octokit.net \ octokit.net_Projects_prm \ Octokit.Tests.Integration \ Octokit.Tests.Integration.csproj

picture [link](https://prnt.sc/h5llvy)

**Question.**
How to be?

**Comment by ryangribble** [comment]
Im not sure what the problem is, but the projects definitely work in VS2017 for other developers/contributors of this project, and myself on several different machines.

From your error message it sounds like you somehow don't have the .NET Core SDK installed
