### ISSUE TITLE
Add support for Repository Topics

### ISSUE THREAD

**Issue by ryangribble** [octokit/octokit.net#1707]
https://github.com/blog/2309-introducing-topics
https://help.github.com/articles/about-topics/

Response Class Support
- Add `Topics` field to `Repository` response class
- Specify new [preview header](https://developer.github.com/v3/previews/#repository-topics) on all calls that return `Repository` responses

New API Calls
- [List all Topics](https://developer.github.com/v3/repos/#list-all-topics-for-a-repository)
- [Replace all Topics](https://developer.github.com/v3/repos/#replace-all-topics-for-a-repository)

Support Search Repositories by Topic
https://help.github.com/articles/searching-repositories/#search-by-repository-topic
- Add `string Topic` field to `SearchRepositoriesRequest` and format search parameters accordingly
- Add `Range Topics` field to `SearchRepositoriesRequest` and format search parameters accordingly

See #1704

**Comment by MikhailTymchukDX** [comment]
Not implemented yet?

**Comment by ryangribble** [comment]
There is a work on progress PR #1721 but the contributors dropped off. I'm currently focusing on the checks API stuff so it would be wonderful if you could help on that PR if you've got a use case for the topics support @MikhailTymchukDX?

**Comment by BarbourSmith** [comment]
What is the status of this? [The documentation](https://octokit.github.io/rest.js/#api-Search-repos) implies that it is working, but it says "For example: " but the example has not been written yet

**Comment by ryangribble** [comment]
Hi @BarbourSmith , the documentation you are referring to is for octokit.js the javascript API client, whilst this is the c# client.  It looks like we still haven't had any traction on finishing that old PR #1721 off, so as of now Repository Topics are still not supported in the c# client unfortauntely 😞

**Comment by SeanKilleen** [comment]
Hey! I'd love this functionality in an app I'm building so I'm going to jump in and try to knock it out.

I will use #1721 as a reference.

**Comment by JustinGol** [comment]
@SeanKilleen, not sure Im missing something but I cant find the new method GetAllTopics on the RepositoryClient. Im using v0.50, double checked and decomplied. I saw in the release the commit for this is included. I can see it in the integration tests too so not sure whats happening. TIA

![image](https://user-images.githubusercontent.com/42610502/119305809-93807c00-bcac-11eb-9418-b8c213301b9e.png)
![image](https://user-images.githubusercontent.com/42610502/119305865-a72be280-bcac-11eb-8611-dc8aa5cdc1ca.png)

**Comment by SeanKilleen** [comment]
@JustinGol please file a new issue, tag me, and include an example of how you're attempting to use it. I'll do what I can to help. Thanks!

**Comment by JustinGol** [comment]
> @JustinGol please file a new issue, tag me, and include an example of how you're attempting to use it. I'll do what I can to help. Thanks!

Thanks Sean, its here: https://github.com/octokit/octokit.net/issues/2328. Appreciate your help on this.
