### ISSUE TITLE
Mergeable always null in Pull Request

### ISSUE THREAD

**Issue by joewstroman** [octokit/octokit.net#1710]
I'm calling `PullRequest.GetAllForRepository()` and I'm trying to check if the PR passed all the CI checks and can be merged (assuming CI checks are taken into account). But I call `hasValue()` since mergeable is Nullable type, and it always returns false for any of the pull requests. Also printing mergeable shows `<null>`. The rest of the data comes back as expected. 

Is this a bug or am I using the API incorrectly?

**Comment by ryangribble** [comment]
If you load a single PullRequest with `Get` operation, is the field populated then? 

Some response fields are only provided on a single record request and not on a `GetAll` request.

**Comment by joewstroman** [comment]
Using Get actually provides more fields, but now all the fields say true for Mergeable, even for PR's that say CI check has failed and says "Merging is blocked"

**Comment by shiftkey** [comment]
> Using Get actually provides more fields, but now all the fields say true for Mergeable, even for PR's that say CI check has failed and says "Merging is blocked"

The `Mergeable` field is compute-intensive, so it's only exposed on `Get` - see the details [here](https://developer.github.com/v3/pulls/#get-a-single-pull-request).

I think we have an old issue about differentiating `GetAll` from `Get` to make this clearer.

Also note that `Mergeable` is purely for whether the branch can be merged into the base branch. Things like [Commit Statuses](https://developer.github.com/v3/repos/statuses/#get-the-combined-status-for-a-specific-ref) should be used to look at the CI checks, and [Required Status Checks](https://developer.github.com/v3/repos/branches/#list-required-status-checks-contexts-of-protected-branch) to determine which need to pass before the branch can be merged.

**Comment by joewstroman** [comment]
So `Mergeable` only signifies if there are merge conflicts?

**Comment by ryangribble** [comment]
Yes. 

As @shiftkey outlined, if you want to check the commit status values you can do that with other API calls
