### ISSUE TITLE
netcoreapp1.0 support

### ISSUE THREAD

**Issue by adriangodong** [octokit/octokit.net#1712]
Octokit currently targets netstandard1.1 but did not specify a specific metapackage, so it defaults to NETStandard.Library 1.6.1. This metapackage is compatible only with netcoreapp1.1.

I'm trying to use this package in AWS Lambda, which only supports netcoreapp1.0.

The fix is simple, add `<NetStandardImplicitPackageVersion>1.6.0</NetStandardImplicitPackageVersion>` element to the package project file.

References:

- AWS Lambda limitation: https://github.com/aws/aws-sdk-net/issues/684
- Metapackage: https://github.com/dotnet/core/blob/master/release-notes/1.0/sdk/1.0-rc3-implicit-package-refs.md

**Comment by ryangribble** [comment]
Yes I ran into this myself and have a local build using that implicit package reference to get around it 

We don't actually target netcoreapp 1.1 intentionally, it's just that the newer build tools automatically use 1.6.1 netstandard library meta package (which aws lambda build tools detect and think you are netcoreapp 1.1)

I was hoping lambda would support 2.0 already

**Comment by adriangodong** [comment]
AWS policy is to support LTS version only, and 2.0 is current. 1.1 moved to LTS when 2.0 is out back in August, so I'm asking AWS as well for their timeline/commitment to add support for 1.1.

**Comment by ryangribble** [comment]
From what I saw the pretty much indicated they wouldn't be likely to support 1.1 eventhough it's now LTS 😝

I'll push up a PR for the local change I was using for my [octokit lambda demo](https://github.com/ryangribble/Octokit.Lambda.Demo)
