### ISSUE TITLE
Implement "Archiving Repositories" functionality

### ISSUE THREAD

**Issue by ryangribble** [octokit/octokit.net#1719]
As per [this recent blog post](https://developer.github.com/changes/2017-11-08-archiving-repositories/) there is new API functionality to archive repositories.

This touches on several areas of the API

- Add `Archived` field to `PullRequest` response model
- Add `Archived` field to the request model `UpdateRepository` used to edit a repository (and note that un-archiving a repo can not be done via the API!)
- Add `Archived` flag to the request model `SearchRepositoriesRequest` used to search repositories (should render as `archived:true` in the generated search string)
- WebHooks now have an `Archived` and `Unarchived` event, so we should check whether your activity classes need to have this added to `EventInfoState` enum (I think possibly not though, as this enum is maybe only used for Issue events and not Repository events)

**Comment by hnrkndrssn** [comment]
Looks like this was implemented in https://github.com/octokit/octokit.net/pull/1845

**Comment by ryangribble** [comment]
Thanks @hnrkndrssn 

Closed by #1845
