### ISSUE TITLE
SHA not supplied while creating new file

### ISSUE THREAD

**Issue by pizycki** [octokit/octokit.net#1725]
I'm trying to create file with Octokit.NET inside my repository

```F#
let user = "pizycki"
let repo = "testo-repo"
let branch = "Testo_" + DateTime.UtcNow.ToString("hhmmss")
let newFilePath = "file.md"
let createFileReq = new CreateFileRequest("Create file", """
        # Hello Octokit!
        ## Me gusta
        """, branch)
client.Repository.Content.CreateFile(user, repo, newFilePath, createFileReq).Result
```

but receiving the following error

```json
{"message":"Invalid request.\n\n\"sha\" wasn't supplied.","documentation_url":"https://developer.github.com/v3/repos/contents/#update-a-file"}
```

I checked with Fiddler the request sent to API and this is how it looks like
```
PUT /repos/pizycki/testo-repo/contents/file.md HTTP/1.1

{
  "content":"DQogICAgICAgICMgSGVsbG8gT2N0b2tpdCENCiAgICAgICAgIyMgTWUgZ3VzdGENCiAgICA=",
  "message":"Create file",
  "branch":"Testo_100809"
}
```

I checked this with [API Documentation](https://developer.github.com/v3/repos/contents/#create-a-file) and what is happening, according to docu, is ok (yet odd). Looks like API awaits for SHA parameter to update the file, not create a new one.

I'd expect the file creation to use `POST` instead of `PUT`.

I've tried changing it in .NET code, but using `POST` method gives me `404`.

**Comment by shiftkey** [comment]
@pizycki I think this might be related to the branch name - it looks like you're creating it from the current time, and if that doesn't exist the repository wouldn't know where to create the new commit from. What if you used a fixed branch name to confirm that the `PUT` is working as expected?

**Comment by pizycki** [comment]
I create branch with that name just before attempting to create new file. You can check my program right here https://github.com/pizycki/DevoWeek/blob/octokit/DevoWeek/Program.fs#L39

**Comment by shiftkey** [comment]
@pizycki I'm glad you were able to get to the bottom of it!

**Comment by bharatkale007** [comment]
I was searching for the same, got below solution.
repo = g.get_repo(repo_name)
file_path = 'myfilepathtocommit'
fc = open(file_path, 'r').read()
file_content = repo.get_contents(file_path)
repo.update_file("electricity.py", "commit message", fc, file_content.sha)
