### ISSUE TITLE
Extend authentication to support authenticating as installation

### ISSUE THREAD

**Issue by adriangodong** [octokit/octokit.net#1727]
Docs: https://developer.github.com/apps/building-github-apps/authentication-options-for-github-apps/#authenticating-as-an-installation

I can't find any issue, docs, or code related to this and I'm not sure if it is something that Octokit should do. From my initial research, it seems that the output of the flow is a valid "auth token" and can be used in place of PAT so the existing authentication mechanism can be used as-is, we just need to pass in a different token every time.

If anyone is working or worked on this, please chime in. I'm working on an implementation as well, and it would be great to not duplicate effort.

**Comment by ryangribble** [comment]
Hey @adriangodong, we haven't implemented any of the github apps stuff yet so definitely keen to see what you come up with

**Comment by adriangodong** [comment]
Awesome! I'm blocked on signing the JWT in .NET Standard, should be smooth sailing once that's out of the way. 🤞
