### ISSUE TITLE
Get the files modified in a commit ?

### ISSUE THREAD

**Issue by Xwilarg** [octokit/octokit.net#1728]
Hi,

I don't know if it's the right place, but I'm trying to get informations about the files changed in a commit.
I have a code who look like that:
```
foreach (GitHubCommit c in await p.clientGitHub.Repository.Commit.GetAll(r.Id))
{
    int added = 0;
    int changed = 0;
    int removed = 0;
    foreach (GitHubCommitFile cf in c.Files)
    {
        added += cf.Additions;
        removed += cf.Deletions;
        changed += cf.Changes;
    }
```
But c.Files is always null (even if the commit name is correct, so there should be some files that are changed).
Thanks in advance :).

**Comment by ryangribble** [comment]
Hi @Xwilarg 

The github API returns sparser results when getting "all" objects, compared to when getting a single object. 

If you load a single commit, the `Files` member should be present then

eg
`clientGitHub.Repository.Commit.Get(r.Id, c.Sha)`

Obviously this is inefficient to do this for many commits so ideally you can have some way to filter down on the commits you need to load first

**Comment by Xwilarg** [comment]
I'll try that, thanks.
My goal was to count how many changes each user did in one project, so I have to iterate through each files and commits..

**Comment by ryangribble** [comment]
Ouch, I'm not sure it's a good idea to try and do all that raw processing yourself

What about the repository statistics endpoints, maybe the contributor breakdown there would give you something useful? 

https://developer.github.com/v3/repos/statistics/#get-contributors-list-with-additions-deletions-and-commit-counts

**Comment by shiftkey** [comment]
Seconding using the repository statistics endpoints - this is supported in Octokit.net, and it will do the heavy lifting for you...

**Comment by hyan23** [comment]
hi, @ryangribble 
Can I apply pagination on a commit's files array in some way? Because there is cutoff on up to 300 files for each client.Repository.Commit.Get request, BTW the repository I am working on sometimes performs a large merge operation which results more than 10, 000 changed files, If I can't use pagination, Is there any other way to get the complete changed file list of a specific commit? Thanks.

**Comment by shiftkey** [comment]
@hyan23 this is not currently supported by the GitHub API, and so you might have to fall back to working with the Git repository via a local clone to get that information.

**Comment by hyan23** [comment]
that's exactly my plan B, and shall be working fine, thank you for your kindly response:)

获取 Outlook for iOS<https://aka.ms/o0ukef>

________________________________
收件人: Brendan Forster <notifications@github.com>
发送时间: 星期六, 十二月 29, 2018 8:46 下午
收件人: octokit/octokit.net
抄送: Haiyang Li (Wicresoft); Mention
主题: Re: [octokit/octokit.net] Get the files modified in a commit ? (#1728)


@hyan23<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fhyan23&data=02%7C01%7Cv-haiyli%40microsoft.com%7C06df8504743446d8a21b08d66d8b9e91%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636816843767894366&sdata=H8EIFES39piKFu9il6gy0XS6X0UlSPJAk%2BWg4%2BHat2M%3D&reserved=0> this is not currently supported by the GitHub API, and so you might have to fall back to working with the Git repository via a local clone to get that information.

―

**Comment by hyan23** [comment]
That's exactly my plan B, and shall be working fine, thank you for your kindly response:)

**Comment by DavidRawk-Blake** [comment]
Did this ever change?   
I cannot work with the repo locally because my apps don't run locally, and the server/docker image doesn't have git installed.
