### ISSUE TITLE
OauthClient.CreateAccessToken calls incorrect URL for Enterprise instances

### ISSUE THREAD

**Issue by grapehunter** [octokit/octokit.net#1729]
Another issue about enterprise address refer to #1724
[AS-IS]
`https://enterprise.url/api/v3/login/oauth/access_token`
[SHOULD-BE]
`https://enterprise.url/login/oauth/access_token`

By the way,please take serveral minutes to check all address of enterprise, it's a horrible disaster

**Comment by ryangribble** [comment]
Hi @grapehunter I've updated PR #1726 to fix the `CreateAccessToken` url, does that look good to you?


> By the way,please take serveral minutes to check all address of enterprise, it's a horrible disaster

Do you have any other examples? I use octokit against our GHE instance and haven't found any incorrect url's with the methods I'm calling...
