### ISSUE TITLE
Create first branch

### ISSUE THREAD

**Issue by davidobrien1985** [octokit/octokit.net#1736]
Hello,

trying to write a process that gets triggered via webhook whenever someone creates a repo via the web UI.

This process needs to then configure things like protected branch, reviewers, etc.
Problem is, if a user creates a repo without initialising it via the UI, then I need to create `master` branch.
For the life of me I can't figure out how to create that first branch, because creating a branch always requires a ref in the form of a SHA.

Anybody solved this before?

**Comment by ryangribble** [comment]
Hmmm our examples in integration tests often create new branches (create a git blob, then a tree, then a  then a commit, then a branch) 

https://github.com/octokit/octokit.net/blob/5e892325218600499a9943b4ff4ebd190e5a82ad/Octokit.Tests.Integration/Clients/PullRequestReviewRequestsClientTests.cs#L260

In those cases the repo already is initialised so the commit is created with a parent commit of the existing master branch commit, but checking the docs for [creating a commit](https://developer.github.com/v3/git/commits/#create-a-commit) says if you specify a blank parent sha it's written to the root of the repo. 

So hopefully you could try that?

**Comment by shiftkey** [comment]
Closing this out due to inactivity
