### ISSUE TITLE
Get Rate Limit By Calling it's API

### ISSUE THREAD

**Issue by mirsaeedi** [octokit/octokit.net#1737]
Currently, we need to call GetLastApiInfo() to get the status of our usage. This API uses the information from the last request it has sent. The problem with this approach is that in some cases we need to fetch this data from Github and the information which we have from the previous call is stale and not sufficient. What's the reasoning behind your implementation? If my argument is valid, can I send a pull request?

**Comment by ryangribble** [comment]
Hi @mirsaeedi the reasoning is simply that the remaining API rate limit is returned in the response headers of all calls, so we may as well provide a mechanism to access that information :)

It would be awesome if you wanted to send a PR to implement the actual [Rate Limit API](https://developer.github.com/v3/rate_limit/) though, then users can choose the method that is more appropriate for them :+1:

**Comment by mirsaeedi** [comment]
Actually, I found that [Rate Limit API](https://developer.github.com/v3/rate_limit/) has been implemented before. I will update the documentation.

`gitHubeclient.Miscellaneous.GetRateLimits();`

**Comment by ryangribble** [comment]
Fixed by #1742
