### ISSUE TITLE
GetAllForRepository and Rate Limit challenges

### ISSUE THREAD

**Issue by mirsaeedi** [octokit/octokit.net#1740]
Suppose I'm going to get all of the review comments from a project. However, because of the high amount of comments, this operation needs more than 5000 requests per hour. Can I use GetAllForRepository method in this kind of situations to get all of the comments? It seems I can't because this method will halt in case of  reaching the 5000/hour limit. So I think in some top hot repositories the GetAllForRepository is not applicable.

It would be good if Octokit was able to deal with rate limits in a more smarter fashion. If my argument is valid, please tell me to send you my suggestions as a pull request.

**Comment by shiftkey** [comment]
@mirsaeedi I'd recommend `GetAllForRepository` but also:

 - using the pagination API so you get more results per page:
 - using a local cache for past review comments and only querying for values since the most recent stored entry

```c#
var options = new ApiOptions { PageSize = 100 };

DateTimeOffset since =  /* */;

var request = new PullRequestReviewCommentRequest { Since = since };

var pullRequestComments = await _client.PullRequest.ReviewComment.GetAllForRepository("owner", "repo", request, options);
```

**Comment by mirsaeedi** [comment]
@shiftkey Thanks for your prompt reply. In some repositories, because of a large amount of data, even using pagination with big page sizes won't solve the above problem. besides that, I'm working on a research that I need to fetch all of the review related information from top repositories to analyze them afterward, so practically the second solution is not suitable for my scenario.

**Comment by shiftkey** [comment]
@mirsaeedi I would still recommend investing in a backing store (like a database) so that you can easily store the PR comments and work with them locally, so you can research as many repositories as desired while working within the API limits. 

The 5000 requests/hr limit is a server-side restriction of the GitHub API, and the Octokit client is not able to circumvent this.

**Comment by mirsaeedi** [comment]
@shiftkey, Of course, I'm using a backing store to save data. However, storing is a different concern from fetching data from servers. The problem is that practically GetAllForRepository is useless in scenarios where you need more than 5000 requests to fetch all of the data. 
A mitigation to this could be a change in GetAllForRepository to wait for a sufficient amount of time, in case of reaching the limit. And, automatically starting to fetch data again after that.

**Comment by shiftkey** [comment]
> A mitigation to this could be a change in GetAllForRepository to wait for a sufficient amount of time, in case of reaching the limit. And, automatically starting to fetch data again after that.

I'll defer to @ryangribble on this from an earlier thread: https://github.com/octokit/octokit.net/issues/1711#issuecomment-342463086

> we generally shy away from implementing higher order logic like making composite/multiple API calls on behalf of the consumer, or building in retry/throttling type behaviour in the library itself, because there are too many potential use cases to implement in a way that would suit everyone.

[The rate limiting API is available in Octokit.net, so that callers can handle this themselves](https://github.com/octokit/octokit.net/blob/8877eea1cbae447030f15a0b5c50dba7037283a2/docs/getting-started.md#too-much-of-a-good-thing-dealing-with-api-rate-limits).

**Comment by mirsaeedi** [comment]
@shiftkey The problem with current API is that when I call GetAllForRepository then I have no way to control its behavior by myself. Because when GetAllForRepository is running I don't have any access to GetLastApiInfo() method via events or callbacks. I should wait till I catch the Rate Limit Exceeded exception and act accordingly.

I'm really sorry to bother, your API is really awesome and I just wanted to make a contribution to improve it, based on the experience I had with it.

**Comment by ryangribble** [comment]
> Because when GetAllForRepository is running I don't have any access to GetLastApiInfo() method via events or callbacks

The `GetAllXXX()` methods will all have an override that takes an `ApiOptions` parameter, that allows you to specify the `StartPage` (amongst other pagination settings).  When you don't pass an `ApiOptions` to the call, octokit automatically retrieves all pages for you, which sounds like where you are going to run into trouble on large repositories.

But you can easily control this yourself by writing your own loop that uses `ApiOptions` to get 1 page, then check your remaining rate limit and either delay or go around the loop again.
