### ISSUE TITLE
Compare status of a fork branch with its origin branch

### ISSUE THREAD

**Issue by Korporal** [octokit/octokit.net#1746]
Hi,

Is there a straightforward way to compare a fork branch with the same named branch in the origin repo?

I'm developing a tool and one of the things I'd like to show is branches on user's forks that contain _additional_ commits over those in the same named branch in the origin repo,

One use for this info is to police team work so we can tell at a glance that some developer on a team has apparently contributed changes and pushed these to their fork but forgotten to create a pull request (for example).

I can of course compare the most recent commit on these branches but I'd also like to know if the fork is "ahead" of or "behind" the branch in the origin.

If a fork's branch is _simply_ behind the origin's branch (meaning that it just needs to fast forward) or completely in sync then this is a non problem scenario but otherwise we want to be alert to this and investigate.

However I do not know how we can use OctoKit to determine:

1. Fork is _simply_ behind origin
2. Fork is _simply_ ahead of origin
3. Fork is _both_ (meaning it has commits not in origin and origin has commits not in fork).

Thx

**Comment by ryangribble** [comment]
Hey @Korporal 

I do believe you are in luck 😄 

You can use the [Compare Commits](https://developer.github.com/v3/repos/commits/#compare-two-commits) call using branch names, and going across forks (see the note there about using USERNAME:branch` format for the fork branch)  and the response includes `AheadBy` and `BehindBy` summary info :+1: 

Something like this will hopefully work! 
`client.Repository.Commit.Compare(owner, repo, "master", "USERNAME:branch")`


Please let us know if this does the job for you

**Comment by Korporal** [comment]
@ryangribble - This is EXACTLY what I wanted and works like a dream!!

Now (of course) I have another question. If I want to know if the tip of some branch (a commit) is definitely present (merged into) some other like "master", is that easy too?

**Comment by ryangribble** [comment]
I'm thinking if you compared "master" to that "commit sha" and it HAD already been merged, then the comparison result would indicate `(BehindBy >= 0 && AheadBy == 0)`. However if you are talking about cherry picking commits or squash merges etc I don't think this would work

**Comment by Korporal** [comment]
@ryangribble - You're right and I do simply want to know if all of the branches commits are on master.

Thx

**Comment by ryangribble** [comment]
Glad it's working for you 👍
