### ISSUE TITLE
[Suggestion] GitHubClient.cs - clarify productInformation field in constructor

### ISSUE THREAD

**Issue by WeiseCreations** [octokit/octokit.net#1750]
Hello,

Going through the [GitHubClient.cs file](https://github.com/octokit/octokit.net/blob/c9b2c1260bc87b7782d4fd9645d43a8885203923/Octokit/GitHubClient.cs) I noticed the constructor takes a `ProductHeaderValue` named `productInformation` with the XML documentation comments [(XMLDOC tags)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/xmldoc/xml-documentation-comments) for this parameter as follows:

`The name (and optionally version) of the product using this library. This is sent to the server as part of the user agent for analytics purposes.`

Doing a tad bit of digging in the [Connection.cs file](https://github.com/octokit/octokit.net/blob/c9b2c1260bc87b7782d4fd9645d43a8885203923/Octokit/Http/Connection.cs) I see this is used for the User-Agent header. However I feel the XMLDOC tags on GitHubClient.cs don't clearly reflect the [Developer Documentation](https://developer.github.com/v3/#user-agent-required) for this field, as it can be your app name, your organization's name, or your username. Additionally, the comment states it's for analytics purposes, however the documentation states `This allows us to contact you if there are problems.`

I suggest modifying the XMLDOC, and if you're okay with it I don't mind opening the PR after doing the edit myself.

I recently went through making my own GitHub client rather than using octokit (for personal project involving building it from scratch), and recognized the difference immediately to the point of digging around and finding out where this field is used (which ultimately is for the User-Agent portion of the header when formatting the JSON) to determine if it was the User-Agent portion I thought, or something else.

Feel free to @ me if you'd like me to go ahead and open a PR for this change in documentation.

**Comment by ryangribble** [comment]
Sure, feel free to send a PR to clarify this field. You could also include a link to the official docs in a `Remarks` tag as well, similar to what we do on method calls

**Comment by WeiseCreations** [comment]
Working on it now, thanks
