### ISSUE TITLE
Determining ahead by and behind by files seperately

### ISSUE THREAD

**Issue by hgleaves-ncuadmin** [octokit/octokit.net#1752]
When I do a comparison between two branches we get a list of files. However these files are lumped together in the sense that we don't know which files constitute the BehindBy and which the AheadBy.

We could get these as separate lists if instead of comparing branch tips we compare branch tip with the common ancestor of the two branches.

Is it possible to get the common ancestor?

**Comment by Korporal** [comment]
@ryangribble Hi, imagine two branches that initially point at some common commit "root" then one one branch I add a file X1.txt and commit while on the other branch I add a file X2.txt and commit.

Now the compare between these two branches will show AheadBy = 1 and BehindBy = 1.

The files list will be X1.txt and X2.txt - this is current behavior.

However the file X1.txt appears ONLY on the first branch and the file X2.txt appears ONLY on the second branch.

That's what I'm seeking and I think I can get this from the common ancestor.

My motive here is to see what would be impacted if I were to merge one branch with another, by which I mean if I were to merge branch A into branch B, what on branch B would be impacted by such a merge.

Clearly only files modified on branch A would be impacted by such a merge, files modified on branch B that were not modified in branch A would not be impacted (by the merge).

**Comment by ryangribble** [comment]
In your example I'd expect x1.txt to have status `Added` and x2.txt to have status `Removed`

So I think you could still get this info from the files list (status field) of the compare result, rather than needing to resort together common ancestors and so on?

**Comment by ryangribble** [comment]
Actually I think I'm probably wrong on that, on my phone so can't verify right now

**Comment by Korporal** [comment]
@ryangribble - Hi,

The goal here (which is really what this is about) is to answer the following question:

**What files/folders would be changed in branch X if we were to merge branch Y into it.**

Nothing in branch X can influence the answer to this question. Branch X may contain several changes to some file, but if that file is not touched by branch Y then that file will not be impacted by a merge of Y into X.

The motive for the question itself is to answer another question like this:

**If we merge branch Y into branch X would that invalidate the testing of the apps we just did for the project on branch X?**

**Comment by ryangribble** [comment]
@Korporal perhaps reaching out to GitHub support is the best approach on this one too.  If you do, could you post the response?
