### ISSUE TITLE
Query commits by branch

### ISSUE THREAD

**Issue by Andrew-Hanlon** [octokit/octokit.net#1753]
I have a question similar to [issue #1293](https://github.com/octokit/octokit.net/issues/1293) regarding the commit history for a file. 

What I am unable to reconcile is how to query commits for a specific branch. It appears that the `CommitRequest` does not have a filter on the branch, and `Repository.Commit.GetAll` only queries the default branch.

Is there a alternative methodology to query commits from a specific branch?

Thank you kindly.

**Comment by ryangribble** [comment]
Hi @Andrew-Hanlon 

You can specify the branch name or any commit sha to start listing commits from, using the `CommitRequest`request model via [this overload]( https://github.com/octokit/octokit.net/blob/master/Octokit/Clients/IRepositoryCommitsClient.cs#L87) method

**Comment by Andrew-Hanlon** [comment]
Amazing, thank you @ryangribble - works like a charm. I hadn't realized the `Sha`  parameter in the `CommitRequest` could accept the branch name. Much appreciated!

**Comment by ryangribble** [comment]
Yeah we try to reflect the [upstream github API](https://developer.github.com/v3/repos/commits/#list-commits-on-a-repository) as much as possible, and that's definitely an oddly named parameter (probably historical reasons). In general github API seem to support a branch,  tag or commit sha in most of the places that want a commit so it's always worth trying

We also do try to bubble up these types of guidance/parameter info via [xml comments]
 (https://github.com/octokit/octokit.net/blob/master/Octokit/Models/Request/CommitRequest.cs#L14) which should appear as intellisense info inside any IDE that supports it, so you should be able to discover/explore these annotations as you are playing with the library 👍

**Comment by clarotech** [comment]
Sorry to drag this up again, so based on @ryangribble comment above is the following expected to work?
`                var request = new CommitRequest {
                    Path = "NamingSystems/NamingSystem-ODSOrganisationCode.xml",
                    Sha = "devt"
                };
                var commitsForFile = await client.Repository.Commit.GetAll(GHOwner, GHRepo, request);`

It throes an exception for me. Can the Sha part of the CommitRequest be the actual branch name?

**Comment by shiftkey** [comment]
> It throws an exception for me.

@clarotech what exception does it throw? Maybe the issue is not related to this specific problem...
