### ISSUE TITLE
Email "visibility" Field Missing

### ISSUE THREAD

**Issue by asapferg** [octokit/octokit.net#1754]
```
var client = GetGitHubClient(accessToken);
var emailAddresses = await client.User.Email.GetAll();
```
![dbg](https://user-images.githubusercontent.com/8890471/35870212-16786fba-0b2f-11e8-940a-1473e3ebf0a0.JPG)
![curl](https://user-images.githubusercontent.com/8890471/35870213-18555334-0b2f-11e8-9c27-20190ab6209d.JPG)

**Comment by ryangribble** [comment]
Hi @asapferg 
thanks for highlighting this, would you consider contributing a PR to fix this? 

It's very easy to add a field in octokit, just add the member to the response model with the right name `Visibility` and it will be populated.

**Comment by asapferg** [comment]
Sure thing, I'll give it a shot.
