### ISSUE TITLE
How to get the commit date of a commit

### ISSUE THREAD

**Issue by hgleaves-ncuadmin** [octokit/octokit.net#1755]
I'm looking a branch's Commit property but cannot see any trace a date/time for the creation of the commit, is this available some other way?

I actually have a set of branches and want to enumerate them in order of most recently updated  first.

**Comment by shiftkey** [comment]
@hgleaves-ncuadmin can you post up a snippet of the code you're using?

**Comment by hgleaves-ncuadmin** [comment]
@shiftkey - Hi

Here's a small part of it:

`            var principal_branches = client.Repository.Branch.GetAll(repo.Id).Result;
`
I'd like to enumerate that sequence in date order.

Thx

**Comment by shiftkey** [comment]
@hgleaves-ncuadmin the Branches API only includes the SHA of the commit associated with each branch, but this can be used to get the full commit information:

```c#
var branches = await client.Repository.Branch.GetAll(repo.Id);
foreach (var branch in branches)
{
    var result = await client.Repository.Commit.Get(repo.Id, branch.Commit.Sha);
    var authorDate = result.Commit.Author.Date;
    // these might be different values, in which case this will probably be later (and more accurate)
    var committerDate = result.Commit.Author.Date;
}
```

**Comment by hgleaves-ncuadmin** [comment]
@shiftkey - Much appreciated!

**Comment by markus-codechefs** [comment]
> @hgleaves-ncuadmin the Branches API only includes the SHA of the commit associated with each branch, but this can be used to get the full commit information:
> 
> ```cs
> var branches = await client.Repository.Branch.GetAll(repo.Id);
> foreach (var branch in branches)
> {
>     var result = await client.Repository.Commit.Get(repo.Id, branch.Commit.Sha);
>     var authorDate = result.Commit.Author.Date;
>     // these might be different values, in which case this will probably be later (and more accurate)
>     var committerDate = result.Commit.Author.Date;
> }
> ```

Though it seems clear from the comment its probably 
`result.Commit.Comitter.Date;`
