### ISSUE TITLE
Question - Can I ascertain if a PR (commit compare?) would or would not have conflicts?

### ISSUE THREAD

**Issue by Korporal** [octokit/octokit.net#1761]
Is there any way to do a compare to see if conflicts _would_ arise _if_ one were to create a pull request?

**Comment by ryangribble** [comment]
I cant seem to see anything telling in the API responses for comparing commits... and I'm not aware of anything else that could have this info, sorry 🤔 

@shiftkey anything i've missed?

**Comment by Korporal** [comment]
@ryangribble @shiftkey Hi,

I got this reply from Github:

Hi Korporal,

Thanks for reaching out. That's an interesting question -- I think there are two ways to do that currently:

1) create a pull request and then fetch the pull request via the API: https://developer.github.com/v3/pulls/#get-a-single-pull-request. The "mergeable" field will tell you if the pull request can be merged without conflicts (i.e. whether the two branches are mergeable in Git without conflicts)

2) create a temporary branch pointing at the same commit as the base branch (e.g. via https://developer.github.com/v3/git/refs/#create-a-reference) and then merge the head into the temporary branch via https://developer.github.com/v3/repos/merging/#perform-a-merge. If the merge succeeds -- then there were no conflicts. If the merge fails -- there were conflicts.

There's no endpoint specifically for the purpose you described as "to see if a pull request were created, would there be merge conflicts". 

Hope this helps.

Best,
Ivan


====================

Is the merge operation described above, supported by Octokit?

Thx

**Comment by shiftkey** [comment]
@ryangribble @Korporal yeah, those are the only two tricks I know about.

> Is the merge operation described above in 2.) , supported by Octokit?

Yes

```c#
var newMerge = new NewMerge("master", branchName) { CommitMessage = "merge commit to master from integrationtests" };

var result = await client.Repository.Merging.Create(owner, name, newMerge);
```

**Comment by ryangribble** [comment]
I'll close this out, given you've posted the response from github support
