### ISSUE TITLE
[Question] - Webhook support capabilities

### ISSUE THREAD

**Issue by Korporal** [octokit/octokit.net#1766]
I just wanted to get some idea whether Octokit.Net provides any programmatic support for creating and reacting to webhooks.

I'm trying to identify the key tasks needed for me to create a hosted service (for example something like Slack) which is sensitive to changes at Github on behalf of an organization.

Thx

**Comment by ryangribble** [comment]
Nothing specific at the moment. Webhook payloads are generally aligned with the activity event response classes but in terms of actually receiving a webhook, extractibg the event type from the http header and then deserialising the payload - octokit doesn't do that sort of thing. 

It also doesn't belong in the core library IMO however I think it would be appropriate to  have a wrapper/extension nuget package that provided this, similar to how its being done on the node.js octokit modules https://www.npmjs.com/package/@octokit/webhooks

**Comment by Korporal** [comment]
@ryangribble - Thanks, I'll probably write some kind of support stuff and perhaps share it here if I think its decent!

**Comment by ryangribble** [comment]
Sounds good!
