### ISSUE TITLE
Add MaintainerCanModify for PullRequest

### ISSUE THREAD

**Issue by Cyberboss** [octokit/octokit.net#1769]

**Comment by shiftkey** [comment]
@Cyberboss if you'd like to contribute this, the file you need to change is [here](https://github.com/octokit/octokit.net/blob/master/Octokit/Models/Response/PullRequest.cs) and I think all you need to do is add a new property:

```csharp
 public bool MaintainerCanModify { get; protected set; }
```

And then add an additional parameter to the second constructor:

```csharp
public PullRequest( /* ... */ , bool locked, bool maintainerCanModify, IReadOnlyList<User> requestedReviewers)
{
     // other code
     Locked = locked;
     MaintainerCanModify = maintainerCanModify;
     RequestedReviewers = requestedReviewers;
}
```
