### ISSUE TITLE
GitHub Apps and Endpoint availability

### ISSUE THREAD

**Issue by Korporal** [octokit/octokit.net#1773]
I stumbled upon [some posts](https://platform.github.community/t/request-support-for-additional-endpoints-for-integrations/426/5) recently at GitHub's [Platform Forum](https://platform.github.community/c/integrations).

I've reached out to GitHub here [in my own post](https://platform.github.community/t/github-apps-and-api-v3-endpoints/5100/1) but wanted to ask for information here too since you guys know far more about the API than I do!

So let me ask a few questions now that I've spent a weekend digging into GitHub apps and OAuth apps and so on.

1. Does Octokit "wrap" the entire v3 API as [defined here](https://developer.github.com/v3/)?
2. The API endpoint for [comparing commits here](https://developer.github.com/v3/repos/commits/#compare-two-commits) is **not** currently tagged as "enabled for GitHub apps" (as [this one](https://developer.github.com/v3/repos/commits/#get-a-single-commit) is) so what would happen if it _were_ to be called from a GitHub app?
3. Why am I able to easily write a Windows console app using Octokit, that **can** compare commits, yet that code (seemingly) would not be permitted/runnable in a GitHub app web app?
4. Is this ultimately about how the GitHub app has authenticated against GitHub? I know that such an app can authenticate server-to-server or user-to-server, is it all connected with this?

Thanks!

**Comment by ryangribble** [comment]
I'm not sure there is anything specific we can say here regarding octokit. 
We aim to wrap the upstream REST API, but of course some endpoints are not implemented yet 😁

It sounds like your queries are really related to how the github API works and the design decisions around github apps and which endpoints are enabled for apps or not... These are best directed at github support or the github platform forum
