### ISSUE TITLE
Support for various authentication types

### ISSUE THREAD

**Issue by Korporal** [octokit/octokit.net#1783]
Does Octokit provide any support methods for doing [this kind](https://developer.github.com/apps/building-github-apps/authentication-options-for-github-apps/#authenticating-as-an-installation) of authentication?

The steps there can of course be coded and raw web requests made etc, but I wanted to see if Octokit wraps these various token creation operations for us.

I've got code that generates the "JWT" but I now want to get the installation access token which seem to be done by calling some API endpoint (api.github.com/installations) is that endpoint exposed by Octokit?

Thx

**Comment by shiftkey** [comment]
@Korporal you probably want to follow along with https://github.com/octokit/octokit.net/pull/1738 and the original issue https://github.com/octokit/octokit.net/issues/1727
