### ISSUE TITLE
Label descriptions are not retrievable

### ISSUE THREAD

**Issue by CraigLager** [octokit/octokit.net#1786]
`Octokit.Label` does not expose Description and I can't see an exposed method to fetch it.

**Comment by ryangribble** [comment]
Hey @CraigLager 

It looks like this was a recently added feature last month: https://developer.github.com/changes/#--label-api-improvements-emoji-descriptions-and-search

As well as a `Description` field, there are also some other fields we are missing (`Id` and `Default` for example)...

Based on that feature announcement, the `NewLabel` and `UpdateLabel` requests can also be updated to add in the new `Description` field.

To enable this new field, we will have to add the preview header `application/vnd.github.symmetra-preview+json` to any calls returning, creating or updating labels

It would be wonderful if you were willing to contribute any of this support.  If you are, let us know... happy to give further guidance if you require :+1:

**Comment by jozefizso** [comment]
I think I will have time to implement this one.
