### ISSUE TITLE
Allow querying by milestones

### ISSUE THREAD

**Issue by mkArtakMSFT** [octokit/octokit.net#1787]
It seems it's not possible to query by `milestone` using `SearchIssueRequest`. Would be great to add support for it or at least some mechanism to specify custom set of parameters. I've tried to use the `Parameters` dictionary directly, but it is being overwritten every time it's accessed, based on the rest of the search request parameters.

**Comment by mkArtakMSFT** [comment]
Looking through the code I found the `Term` property. Will try to see whether this will do it.

**Comment by mkArtakMSFT** [comment]
So yes, passing the `term` as a constructor parameter to the `SearchIssueRequest` did it. Still, leaving this option as an ask to consider exposing `Milestones` property on the request.

**Comment by ryangribble** [comment]
Thanks @mkArtakMSFT, 

Just wondering did you just specify the milestone "foo" as the search term, or did you specify like "&milestone=foo"?

It should be easy to add the extra query option, would be great if you could send a pull request through?  :grinning:

**Comment by mkArtakMSFT** [comment]
Hi @ryangribble. I ended up using it as I would in GitHub search: `milestone: myMilestoneName`. It worked just fine. I'll try to submit a PR with the proposal.
