### ISSUE TITLE
[QUESTION] Is it possible to be notified of a new commit for a repository?

### ISSUE THREAD

**Issue by kristianjaeger** [octokit/octokit.net#1790]
Is it possible to be notified of a new commit for a repository, for a given branch?

I would like to do something like:
1) at a point in time get the list of commits
2) at a further point in time be notified if there is a new commit
2b) if there is a new commit do something like get the latest version of a file in that repo

Do I need to use a client.Repository.Commit.GetAll(...) call on a timer to poll for new commits?  Or use a git webhook or something?

Thanks.

**Comment by ryangribble** [comment]
Using Webhooks is preferable since github will notify you when something happens, rather than you having to poll for changes

You would need to setup a push event webhook, then filter for the branch yourself
