### ISSUE TITLE
Repository.GetAllTeams() for returns only parent team

### ISSUE THREAD

**Issue by MikhailTymchukDX** [octokit/octokit.net#1794]
I'm using Octokit 0.29.0.
When I try to get all teams for specific repo, for example:
```cs
var teams = client.Repository.GetAllTeams("DevExpress-Examples", "accessibility-how-to-skip-repetitive-navigation-links-t382165").Result.Select(t => t.Name);
```
only top (parent) team "ASP.NET" is returned.

Here is the structure of teams for this repo:
![image](https://user-images.githubusercontent.com/17080984/38614186-e626d2c8-3d94-11e8-936b-8691c4e187f7.png)

Is it octokit or API bug?

**Comment by ryangribble** [comment]
Hi @MikhailTymchukDX 

Nested Teams is currently a preview API feature which means we have to include a special accepts header in any calls which deal with teams. It looks like our initial implementation in #1682 only did this on the actual `TeamsClient` methods and missed these other calls in other API clients which deal with teams such as the [one you're using](https://developer.github.com/v3/repos/#list teams) (and possibly others?) 

It's a pretty simple fix, we just need to include the `AcceptHeaders.NestedTeamsPreview` on any other calls that deal with teams... It would be awesome if you wanted to tackle this and send a PR that fixes this!

**Comment by MikhailTymchukDX** [comment]
Hi @ryangribble 
I installed prerelease NuGet package `Octokit.0.30.0-PullRequest1798` to test these changes.
However, code behavior is not changed 😞 
Moreover, I found, that Octokit returns only bottom team for some repos (while still returning top parent team for the first case):
```cs
var teams = client.Repository.GetAllTeams("DevExpress-Examples", "custom-template-class-e1").Result.Select(t => t.Name);
```
Am I missing something?

I can provide you a sample project, but I don't want to expose my access token. Can I send the sample project to you in a secure way?

**Comment by ryangribble** [comment]
Hi @MikhailTymchukDX 

I've done some additional testing and it seems like this is the way the upstream API is behaving at the moment.  Eventhough we are now including the correct preview header, it seems to just make the response include the `parent` attribute on the team... but doesnt actually seem to include child teams of the parent team that has repository access.

I'll ask the folks at GitHub if this is intended behaviour or not

**Comment by MikhailTymchukDX** [comment]
Any update on this? Should I contact nyself with the support?

**Comment by ryangribble** [comment]
Sorry for not closing the loop on this, what I got from folks at GitHub was that they did have an internal issue about this, but also that the documentation does't actualy say this is how it should work...

But yes I would say you should also contact support yourself if you want to provide your feedback about this feature
