### ISSUE TITLE
[Help] Create a pull request from a forked repository

### ISSUE THREAD

**Issue by haouatmohamed** [octokit/octokit.net#1797]
Hello everyone,
I am using octokit library to automatically create pull requests. I get a ValidationApiException "Validation failed" when I try to create a pull request from forked repository.

```csharp
var uri = new Uri("https://github.com/");
githubclient = new GitHubClient(new ProductHeaderValue("dlala_project"), uri)
{
 Credentials = credentials
};

var pr = new NewPullRequest("testing api","haouatmohamed:master","master");

var pullRequestResult = githubclient.PullRequest.Create("octokit", "octokit.net", pr).Result;
```

Can anyone help me with this please ? what am I missing ?

**Comment by ryangribble** [comment]
The request code looks correct and is similar to working examples I use.

One thing I note is, when using github.com you don't need to provide a Uri argument to GitHubClient constructor (and actually the Uri should be the API address not the webUi). Although I don't think that would be your issue maybe try without doing that?

Other than that, does your fork's master branch contain valid commits that could be raised in a PR to the target you are specifying? 

As a final note, I noticed your test code is targeting THIS repository - we'd prefer if people didn't raise unnecessary PR's or issues in this repo for testing purposes please 😌 (you can create a test account and repo then fork that and use for your own testing).

**Comment by shiftkey** [comment]
I'd recommend checking these three things:

 - No need to provide the `uri` parameter when creating the `GitHubClient` for GitHub.com
 - Check there are new commits on the branch in the fork
 - Ensure you're using a real repository 

The latter two things are likely to trigger the "Validation failed" error from the server
