### ISSUE TITLE
How to know if you can create a public or private repository?

### ISSUE THREAD

**Issue by Disturbing** [octokit/octokit.net#1800]
I couldn't figure out the latest API to find out if my user has permission create private repos.

Any tips?

**Comment by shiftkey** [comment]
@Disturbing when you get the current user, there's a `Plan` property that contains the details:

```csharp
var user = await client.User.Current();

if (user.Plan.PrivateRepos > 0)
{
    Console.WriteLine("User has ability to create private repositories...")
}
```

**Comment by Disturbing** [comment]
What about the user's organization, because at the moment PrivateRepos is showing as zero.
