### ISSUE TITLE
new issue adding label doesn't work

### ISSUE THREAD

**Issue by ghiboz** [octokit/octokit.net#1803]
hi all!
i have this code:

```csharp
var newIssue = new NewIssue("Error creating issues");
newIssue.Body = "I have some error...";
newIssue.Labels.Add("Bug");

var issue = await github.Issue.Create("repo-owner", "repo-name", newIssue);
```

and the issue is created, but without the `Bug` label..

if I do this:
```csharp
var lbl = github.Issue.Labels.GetAllForRepository("repo-owner", "repo-name");
foreach (var item in lbl.Result)
{
    MessageBox.Show(item.Name);
}
```
the message shows the repo labels and in the list there's also `Bug` label.. so there is not a word error

thanks in advance

**Comment by shiftkey** [comment]
> ... Because only users with write access can assign labels to issues

I'm pretty sure it's this. Gonna close it out without more information.
