### ISSUE TITLE
A release to match the documentation

### ISSUE THREAD

**Issue by crhairr** [octokit/octokit.net#1815]
The latest documentation includes mentions of recently implemented support for GitHubApps, however the latest release doesn't have these features. This is very confusing. Either roll back the docs, or put out a new release. I vote for the latter.

**Comment by ryangribble** [comment]
sorry @crhairr , I didn't fully tweak to the fact that the docs site auto publishes from `master` whilst the nuget releases are only when I decide to cut a release...

I've been falling into the trap of "just waiting for that one last PR to be done" before cutting a release, but it's no excuse 😭 

I'll look to publish one over the weekend!

![](https://media3.giphy.com/media/B2TG4Rx3gPuMw/giphy.gif?cid=e1bb72ff5b22f03871485a6445076b70)

**Comment by crhairr** [comment]
I didn't mean to come off so pushy! I actually really like Octokit, and I was just hoping to use the GitHubApps features that were in the docs. Poking around the repo, I could see lots of good stuff, and the code looks to be in great shape, so I couldn't see a reason not to publish.

Thanks for a great tool!

**Comment by ryangribble** [comment]
All good, I need to release more frequently, particularly when there are doc changes that get auto published from master... 

I've pushed out a release, please give our GitHub App support a go, and provide any feedback!

**Comment by crhairr** [comment]
I just swapped out my code for handling the GitHub installation auth token generation for Octokit's and it works like a charm. Thanks!

**Comment by ryangribble** [comment]
Awesome! What method are you using to do the JWT creation out of interest?

**Comment by crhairr** [comment]
We are signing the IntegrationId using the pem-formatted private key generated by GitHub. It would be awesome if the complete JWT signature functionality was included in your API, but I can see why you might leave that part up to the user.

**Comment by ryangribble** [comment]
the fact we target `netstandard1.1` meant we couldn't easily pull in the crypto stuff necessary, but we did refer people to use the [`GitHubJwt`](https://www.nuget.org/packages/GitHubJwt/) library (and we infact use this in our [integration tests](https://github.com/octokit/octokit.net/blob/master/Octokit.Tests.Integration/Helper.cs#L75-L87) as well). 

Are you using a particular nuget package to do the JWT or just the crypto code in your app itself?  I'd also love to know details on what you're building as it'd be great to know what users we are catering to.  If it's not open source, feel free to DM me on [twitter](https://twitter.com/ryangribble_)

**Comment by crhairr** [comment]
We're using Org.BouncyCastle.Crypto for reading the PEM file and converting it into a valid key, and Microsoft.IdentityModel.Tokens for handling the JWT library. These are available in .NET Core 1.0.
