### ISSUE TITLE
GithubClient.Repository.GetAllLanguages throws Exception when the repo does not have a language

### ISSUE THREAD

**Issue by baonguyen96** [octokit/octokit.net#1820]
Example with this API endpoint: https://api.github.com/users/vinhhoa1/repos
Using the above  code will crash with this error for repository _RPG-ZombiesTCC_:

```
System.ArgumentNullException: Value cannot be null.

Parameter name: source

   at System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector)

   at Octokit.RepositoriesClient.<GetAllLanguages>d__84.MoveNext()
```

I think it would be better if _null_ value are marked as _""_ (empty) rather than throwing an exception here.

**Comment by ryangribble** [comment]
Hi @baonguyen96 

Can you provide the c# code that produced the error?

The API link you provided (getting all repos for a user) doesn't correlate to the the stack trace.  `RepositoriesClient.GetAllLanguages()` would correspond to `https://api.github.com/repos/vinhhoa1/RPG-ZombiesTCC/languages`

We definitely dont want an exception like this occurring, but I just want to get the repro code in this issue for completeness :+1:

**Comment by baonguyen96** [comment]
@ryangribble  Sure here is the link to the source code: https://github.com/baonguyen96/GitData/blob/dev/GitData/Storage/Repository.cs

Particularly, it breaks on line 41 (`language = await ....`) when I call the API to retrieve all languages and _any of the language is null_:
```c#
IReadOnlyList<Octokit.RepositoryLanguage> languages = null;
Task.Run(async () =>
{
                languages = await githubClient.Repository.GetAllLanguages(octokitRepository.Owner.Login, Name);
}).GetAwaiter().GetResult();
```

This exception does not happen when a repository has at least 1 language.

**Comment by ryangribble** [comment]
@baonguyen96 can you please take a look at #1831 and let me know if that would suit your needs?  Do you have a preference between returning an empty list or returning a `null`?  I went with empty list

**Comment by baonguyen96** [comment]
@ryangribble yes I definitely prefer the empty list to null. Thank you.
