### ISSUE TITLE
CS0104 Error: 'Application' is an ambiguous reference between 'Octokit.Application' and 'System.Windows.Application'

### ISSUE THREAD

**Issue by iamnotstanley** [octokit/octokit.net#1821]
Hello!

How can I fix this?

> CS0104 Error: 'Application' is an ambiguous reference between 'Octokit.Application' and 'System.Windows.Application'

[Visual Studio version and sample code in this gist](https://gist.github.com/iamnotstanley/3c83aa573b7b650b3b9ca84a0b021774)

Thanks,
Daniel Streba

**Comment by shiftkey** [comment]
@iamnotstanley I broke this line down so it wasn't so long, but it's that first line that should resolve the ambiguous reference:

```c#
var location = System.Windows.Application.ResourceAssembly.Location;
var versionInfo = System.Diagnostics.FileVersionInfo.GetVersionInfo(location);
currentVersion = Convert.ToString(versionInfo.ProductVersion).TrimStart('v'); // AssemblyInformationalVersion
```

**Comment by iamnotstanley** [comment]
@shiftkey Wow, thanks for the quick answer! That solved it.
