### ISSUE TITLE
github-apps.md too confusing

### ISSUE THREAD

**Issue by MartinDawson** [octokit/octokit.net#1823]
The [github app walkthrough](https://github.com/octokit/octokit.net/blob/master/docs/github-apps.md#github-app-walkthrough) is not clear on the steps to take at all.

It needs a numbered series of steps.

It says to use JWT tokens in one section but then in the next section no jwt token is used. I also have no idea where we put this stuff in our app? Is it on startup or on request.

**Comment by ryangribble** [comment]
Hi @MartinDawson , 

Thanks for the feedback, and sorry that the walkthrough hasn't managed to convey enough clear detail! 

We try to strike a balance between re-iterating what the official GitHub documentation says, but not wanting to include too much of their detail in case they change something and ours is then out of date or incorrect.  We therefore include several links to the official docs, and expect that Octokit users should familiarize themselves with those concepts first, before reading our walkthrough.  

Do you think we need to be more explicit in stating the expectations that users should be following the official doc links, before running through our walkthrough?  

Do you think we got the balance wrong, and need to include some more overall details about the relationship of PEM certificate => JWT Token => Installation Access Token (eventhough the official docs do cover that)?

I'll have a crack at reworking the doc, it would be great if you could review what I come up with and provide feedback! :+1:
