### ISSUE TITLE
Github Apps Trying to get current user installation repositories

### ISSUE THREAD

**Issue by MartinDawson** [octokit/octokit.net#1825]
I want to access the authorised repositories organisations and users so I can display them on my website. I install the app on my personal account and give it access to this repository:

- "MartinDawson/onboardor"

My github app has full read/write access set (just for testing).

Once the user installs the app they get redirected to my setup url: `/gitHubSetup`.

```csharp
Field<BooleanGraphType>()
    .Name("gitHubSetup")
    .Argument<NonNullGraphType<IntGraphType>>("installationId", "The installation id")
    .Argument<NonNullGraphType<StringGraphType>>("setupAction", "The action that is taking place")
    .ResolveAsync(async c =>
    {
        var client = new GitHubClient(new ProductHeaderValue(Env.GetString("APP_NAME")));
        var path = $"{_env.WebRootPath}/{Env.GetString("APP_NAME")}.pem";
        var appIntegrationId = Env.GetInt("GITHUB_APP_ID");
        var generator = new GitHubJwt.GitHubJwtFactory(
                new GitHubJwt.FilePrivateKeySource(path),
                new GitHubJwt.GitHubJwtFactoryOptions
                {
                    AppIntegrationId = appIntegrationId, // The GitHub App Id
                    ExpirationSeconds = 600 // 10 minutes is the maximum time allowed
        });

        var jwtToken = generator.CreateEncodedJwtToken();

        client.Credentials = new Credentials(jwtToken, AuthenticationType.Bearer);
        var installationId = c.GetArgument<int>("installationId");
        var response = await client.GitHubApps.CreateInstallationToken(installationId);
        var installationClient = new GitHubClient(new ProductHeaderValue($"{Env.GetString("APP_NAME")}-${installationId}"))
        {
            Credentials = new Credentials(response.Token)
        };

        var user = await installationClient.Repository.GetAllForCurrent();

        return null;
    });
```

But this line:
`var user = await installationClient.Repository.GetAllForCurrent();`

Is throwing this error:

code: `"FORBIDDEN"
location: "GraphQL.ExecutionError: Error trying to resolve gitHubSetup. ---> Octokit.ForbiddenException: Resource not accessible by integration
↵ `

Why doesn't this work? The current installation type is on a `User` (my personal account).

**Comment by ryangribble** [comment]
Hmm... I believe that endpoint requires being authenticated as a user, and you are not a user, you are an installation of a GitHub App.  When the app is installed by the user, they choose which repositories it can access (pick from a list, or choose "All").  

If you look at the API docs, there will be a little "i" indicating when the endpoint is accessible by GitHub App or not.

EG The "get current user's repos" is not enabled for GitHub Apps
https://developer.github.com/v3/repos/#list-your-repositories
![image](https://user-images.githubusercontent.com/5425163/41818851-f2f2a10e-77f9-11e8-8d34-ef25ceddb3db.png)

The "get a user's repos" is though... if you know what username is you want to check
https://developer.github.com/v3/repos/#list-user-repositories
![image](https://user-images.githubusercontent.com/5425163/41818866-0cef6416-77fa-11e8-9ff3-4513b98fad71.png)



But I think what you actually may be wanting to do, is get a list of repos the `Installation` has access to?  

If that's the case, then that would be [this endpoint](https://developer.github.com/v3/apps/installations/#list-repositories) but unfortunately we haven't got that implemented in octokit.net yet.  So far we have implemented the basic GitHubApp support such as authentication, listing installations and the various core response models...  You can still do plenty if you know you have access to a repo (eg you received a webhook from it) but we cant yet enumerate/determine all repositories the app can access until we implement those additional endpoints sorry 🙏 

Although we hope to get to it as soon as we can, we often tend to be driven by user needs and contributions - so it would be great if you were willing to have a crack at implementing this.  Even just as a headstart, contributions are very useful and appreciated!  :+1:

**Comment by tijdelijkeaccount** [comment]
Any update on this feature?
