### ISSUE TITLE
Supporting Interception

### ISSUE THREAD

**Issue by mirsaeedi** [octokit/octokit.net#1832]
Since some of the concerns such as throttling and having a retry policy are not supposed to be addressed by the core octokit library, please provide a way for third-party developers to be able to create wrappers or interceptors for octokit's clients (RepositoriesClient, RepositoryCommentsClient).

Implementing interceptors require all the methods to be _virtual_ while this is not the case with the current implementation and as a result, they are not interceptable. If you are open to this suggestion, I will send a PR for it.

**Comment by ryangribble** [comment]
Can you provide a small example of what you mean, as I'm not seeing how "marking all methods as virtual" really helps you that much, as then you would have to implement basically everything yourself. 

You already can use your own `HttpClient` with octokit - so that would be one place you could intercept and handle particular HTTP responses (such as throttling on rate limit exceptions, or automatically retrying).  

There are also fantastic libraries such as [Polly](https://github.com/App-vNext/Polly) that would enable you to wrap existing octokit calls with policy handlers to retry or delay things.

**Comment by mirsaeedi** [comment]
Yes, you are right! I forgot that I can solve it using DelegatingHandler of HttpClient. I planned to do it using [Dynamic Proxies](http://autofaccn.readthedocs.io/en/latest/advanced/interceptors.html).

**Comment by mirsaeedi** [comment]
following your suggestion, I implemented a mechanism to deal with rate limiting and possible http exceptions. I would be very happy if you could review my code. I shared it via [github gist](https://gist.github.com/mirsaeedi/e11f903b384861941624a49fa34ef3d5).

**Comment by ryangribble** [comment]
Nice one @mirsaeedi 

Obviously it's not ideal for you to have copies of the octokit source code in your repo though, so let's find a way to expose the minimum seams needed for you to be able to hook in your extensions.  I'd prefer not to just make all these things public or virtual, however Im sure we could come up with something.  Eg do you only ever need to respond to exceptions?  If so, perhaps we can add a hook into the "HandleErrors" section, allowing you to respond differently to the various exceptions at that point.

**Comment by mirsaeedi** [comment]
Thanks @ryangribble 

My main requirement is to have a retry policy to deal with exceptions such as timeouts, HTTP related errors, and GitHub related errors.

I don't know how adding a hook into the _HandleErrors_ can help us to implement a retry policy. In addition, timeouts and HTTP related errors happen before reaching the _HandleErrors_ method.

I thought a lot about this matter and I came to this point that having a custom [DelegatingHandler](https://github.com/mirsaeedi/octokit.net.Extensions/blob/master/src/octokit.net.Extensions/GitHubResilientDelegatingHandler.cs), maybe is the most practical way to achieve retry-able actions.
