### ISSUE TITLE
End of Line

### ISSUE THREAD

**Issue by Jericho** [octokit/octokit.net#1834]
When I commit a text file to my repo with octokit 0.30.0, I am expected to use the appropriate end of line, right? 

If so:
- how can I determine what the expected EOL is?
- Is it `\r`, `\n` or `\r\n`?
- Is it always the same value or does it vary per repo and/or per file?

**Comment by ryangribble** [comment]
git line ending configuration are super complex.  Git clients can have their own settings, repositories can specify their own settings via .gitattributes file, sometimes on a per file/pattern basis, and so on.  Clients can auto convert line endings locally and preserve linux line endings in the repo.

If you aren't going to use an actual git client to operate on a file system clone of a git repo (and thus get all the EOL logic for free) I would say you should just pick a line ending (linux format would be my reccomendation) and use that.
