### ISSUE TITLE
sparse checkouts

### ISSUE THREAD

**Issue by jlindner** [octokit/octokit.net#1835]
This really isn't an issue, but I cannot find a better place to ask this questions.

Does octokit support sparseCheckouts?  Where you can get one directory in a large git repository, instead of the whole repository?

The command line does, but I am hoping octokit also supports this.

https://stackoverflow.com/questions/4114887/is-it-possible-to-do-a-sparse-checkout-without-checking-out-the-whole-repository

**Comment by shiftkey** [comment]
@jlindner Octokit is for interacting with the GitHub API, rather than local Git repositories. If you want to do a local sparse checkout your best bet is the Git command line.
