### ISSUE TITLE
How to delete Tags?

### ISSUE THREAD

**Issue by rquackenbush** [octokit/octokit.net#1836]
I see that the api supports the deletion of tag refs:

https://developer.github.com/v3/git/refs/#delete-a-reference

Is there a way to delete tags with this client?

**Comment by shiftkey** [comment]
@rquackenbush 

```c#
await client.Git.Reference.Delete("owner", "name", "tags/some-tag-name-goes-here");
```

**Comment by rquackenbush** [comment]
Thanks! I hadn't noticed the .Git member.
