### ISSUE TITLE
Packaging error - Do not depend on SourceLink.Create.GitHub

### ISSUE THREAD

**Issue by matthid** [octokit/octokit.net#1839]
See https://github.com/fsharp/FAKE/pull/2011#issuecomment-401626376
This dependency introduces headache in downstream repositories.

Please consider un-listing that version (https://www.nuget.org/packages/Octokit/0.30.0)

**Comment by ryangribble** [comment]
Hi @matthid have already fixed in #1822 and will push a new release soon
