### ISSUE TITLE
Cancellation support using CancellationToken

### ISSUE THREAD

**Issue by FantasticFiasco** [octokit/octokit.net#1840]
I would propose supporting cancellation using cancellation tokens.

This issue relates to #744 but my proposal is not to specify a timeout as an argument, but instead allow the caller to optionally specify a CancellationToken that Octokit respects.

**Comment by shiftkey** [comment]
@FantasticFiasco given the broad API surface already supported, do you have any thoughts on how we'd support this through the internals? I guess we'd need to pass this all the way down to `HttpClient` but it'd be neat to confirm the impact of this on a single API function before moving ahead with this.

We have the ability to write convention tests to ensure things are consistent, but we should also figure out a migration path to transition to this before we got and introduce a change like this that will likely affect every API function.

**Comment by FantasticFiasco** [comment]
Without knowing the code base by hard, I guess that the implementation would start at the API surface, and the cancellation token would be passed down to the HTTP client where it would be used twice:

1. When the request is sent
2. When the response is read

I agree that a spike of the implementation could be done on a small subset of the API surface, but in an ideal world this would be implemented on the complete API surface.

**Comment by FantasticFiasco** [comment]
I would love to, but cannot truthfully commit to the implementation due to other priorities, at least for some months to come. Sorry.

**Comment by hnrkndrssn** [comment]
I'd like to take on something a little bit *chunkier* and more ***core*** to the library (to get a deeper understanding of it) and this feels like a well-scoped piece of work that fits that purpose.

My thoughts on a plan of attack *(based on the discussion in this issue)*:
- Spike out the cancellation code on a smaller piece of the API surface (a single `*Client` or perhaps even just a single method in a `*Client`)
- Once proved above and agreement has been made, expand the cancellation code to the rest of the API surface
- Create convention tests to ensure things stay consistent (might do this before expanding the cancellation code to the rest of the API surface as it would be the guide for that piece of work...)

Thoughts @shiftkey ?

**Comment by shiftkey** [comment]
@hnrkndrssn that seems like a fine approach

**Comment by kirsan31** [comment]
Hi guys. I am tring this code:
```cs
try
{
    IApiResponse<byte[]> resp;
    resp = await _client.Connection.Get<byte[]>(new Uri(Url), new Dictionary<string, string>(), "application/octet-stream", cancellationToken).ConfigureAwait(false);
    return resp.Body;
}
catch (TaskCanceledException)
{
    return null;
}
```

to download release binary and it's completely ignoring cancellationToken even when `IsCancellationRequested = true`.

**Comment by sommmen** [comment]
Would also love cancellation support!

**Comment by michael-hawker** [comment]
Should this issue be re-opened for tracking?

**Comment by Cyberboss** [comment]
Yes.

**Comment by soenneker** [comment]
Is anyone currently working on this?

**Comment by michael-hawker** [comment]
@soenneker I would assume not as it's a closed issue. Not sure if the maintainers are going to see the conversation on a closed issue. @shiftkey @nickfloyd for awareness, think you folks are the most active here?

**Comment by soenneker** [comment]
@michael-hawker I'd be willing to start chipping away at this if it gets a blessing from the maintainers.
