### ISSUE TITLE
Disposing the default HttpClient

### ISSUE THREAD

**Issue by FantasticFiasco** [octokit/octokit.net#1841]
From my understanding, if a create a default `GitHubClient::ctor(ProductHeaderValue)` there is no way for me to dispose the automatically created instance of `HttpClient` in `Connection`?

Am I perhaps better off to use the contructor `GitHubClient::ctor(IConnection)` instead to get full control of the HTTP client?

What is your suggestion?

**Comment by khellang** [comment]
I think this should be tackled with https://github.com/octokit/octokit.net/issues/984. It would also make it play nicer with the new ASP.NET Core `HttpClientFactory` 👍

**Comment by FantasticFiasco** [comment]
Close this issue if you think #984 will add support for disposing the HTTP client.

And you are correct, with the release of `HttpClientFactory` it seems that we now have enough guidance on how to the HTTP client in combination with Octokit .NET.
