### ISSUE TITLE
Cannot find event type in CreateEvent payload

### ISSUE THREAD

**Issue by totoroyyb** [octokit/octokit.net#1848]
I tried to use get activities by using `client.Activity.Events.GetAllUserPerformed` , and I can find the event type like "opened" "edited" in `IssuesEvent` and `IssueCommentEvent`.

However, when I tried to get the specific event type, such as "repository", "branch", or "tag", under `CreateEvent`, I cannot find anything in the payload. There are just several `null`, shown as the pic below.

![snipaste_2018-07-15_23-32-35](https://user-images.githubusercontent.com/30278896/42735481-7960315a-8887-11e8-802f-9fe199b26708.png)

Am I misusing anything? Any help are appreciated!

**Comment by shiftkey** [comment]
@totoroyyb are you able to share a runnable code sample of the issue? It looks like a deserialization issue but having the right steps to trigger it will significantly help with troubleshooting.

**Comment by ryangribble** [comment]
Yes a code sample will be useful however I'd say it's probably just that we don't have a payload class implemented for that particular event. Unfortunately this is an area where we have very sparse coverage (and it would be great if you wanted to help out, you could contribute any missing payload classes in a PR!)

These are the ones we have currently: https://github.com/octokit/octokit.net/tree/master/Octokit/Models/Response/ActivityPayloads

**Comment by totoroyyb** [comment]
Thanks for checking out. It seems Octokit just doesn't have a payload class for these.
I'd like to help out, and if there's anything I can help, I'll make a PR!
Thanks for all.
