### ISSUE TITLE
Git-Credential-Manager-for-Windows?

### ISSUE THREAD

**Issue by xied75** [octokit/octokit.net#1850]
https://github.com/Microsoft/Git-Credential-Manager-for-Windows

Say as a user I've logged in GitHub website via 2FA. The credential was stored on the Windows Credential Manager under "Windows Credentials" -> "git:https://github.com"

![image](https://user-images.githubusercontent.com/1682456/42830819-78765ee6-89e4-11e8-808f-21d44ea8d5a0.png)

Would it be feasible for octokit to grab secrets from here? Rather than asking username and password again?

**Comment by shiftkey** [comment]
@xied75 this isn't currently supported and I don't think we have plans for it, but there are existing solutions to interact with the Windows Credential Manager, like this https://stackoverflow.com/a/17747020/1363815

**Comment by xied75** [comment]
@shiftkey Thanks for the head up. 👍
