### ISSUE TITLE
New issue doesn't show the label

### ISSUE THREAD

**Issue by ghiboz** [octokit/octokit.net#1861]
hi all!
here is my code I use to add an issue:

```csharp
        public async void AddIssue(string title, string content, ISSUE_TYPE type)
        {
            var newIssue = new NewIssue(title);
            newIssue.Body = content;
            switch (type)
            {
                case ISSUE_TYPE.BUG:
                    newIssue.Labels.Add("Bug");
                    break;
                case ISSUE_TYPE.ENHANCEMENT:
                    newIssue.Labels.Add("Enhancement");
                    break;
                case ISSUE_TYPE.FEATURE:
                    newIssue.Labels.Add("Feature");
                    break;
                case ISSUE_TYPE.QUESTION:
                    newIssue.Labels.Add("Question");
                    break;
                case ISSUE_TYPE.DOCUMENTATION:
                    newIssue.Labels.Add("Documentation");
                    break;
            }
            
            var issue = await github.Issue.Create("gRally", "dev", newIssue);
            
            IssuesCreatedEvent?.Invoke(issue.HtmlUrl.ToString());
        }
```

these are the labels of the repository:
https://github.com/gRally/dev/labels
but all the issues comes with no label..

here is the debug issue I made:
![image](https://user-images.githubusercontent.com/446533/44787010-2a6c8800-ab96-11e8-8e11-acbc823f8373.png)

... and this is the issue: https://github.com/gRally/dev/issues/671

any ideas on this?

**Comment by ryangribble** [comment]
Hi @ghiboz 

Issues can be raised by anyone, but only users with write access can set labels on issues.

Do the credentials you're using have write access to the repository?

**Comment by shiftkey** [comment]
> Issues can be raised by anyone, but only users with write access can set labels on issues.

Yep, this is the issue. If you add `@gRally-Issues` as a collaborator to the `gRally/dev` repository this will work fine.

**Comment by ghiboz** [comment]
thanks! it works
