### ISSUE TITLE
Is it possible to create a pull request with a label?

### ISSUE THREAD

**Issue by stt106** [octokit/octokit.net#1862]
We have some system watching pull requests with specific labels; hence I am wondering whether it's possible to pragmatically create a pull request and attach a label to it?

**Comment by ryangribble** [comment]
Yes

**Comment by stt106** [comment]
@ryangribble thanks for the reply. Sorry but I am new to the package so not sure I fully understand you.
On the doc, I see I can add a label to a `NewIssue` like 
```
var myNewIssue = new NewIssue("Issue with dropdown menu");
myNewIssue.Labels.Add("bug");
```

I am creating a pull request using 

```
var github = new GitHubClient(new ProductHeaderValue(config.User), 
                                      new Uri("https://simhub.simcorp.com"),
                                      Credentials = Credentials(config.Password));
                                            
       var pr = github.PullRequest.Create("Foo", "Bar", 
            new NewPullRequest("PR title", branchName, "master"));
```
There is no `Labels` property on `PullRequest` hence unsure where/how to add the label to a pull request.

**Comment by ryangribble** [comment]
In github API terms, a pull request is actually a special type of issue (you 
may have noticed on github that the issue number and pull request number are shared/unique across issues and PR's! ) 

So you can actually use most of the issue API calls to do things to pull requests (get comments, set labels, milestones, assignees etc) 

so once you create the PR you can use the `IssueUpdate` request to update it and set the label

**Comment by stt106** [comment]
@ryangribble  thanks again for the reply. Just to confirm that I understand you correctly. Once I have a PR e.g. `pr`, then I will do something like this:

```
var issueUpdate = new IssueUpdate();
issueUpdate.Labels.Add("some label");
// pass in pr.Number below
gitHub.Issue.Update("owner", "repo name", pr.Number, issueUpdate);
```
I guess the key is passing `pr.Number` as the issue number in the `Update` method?

**Comment by ryangribble** [comment]
Yep! Let us know if you have any problems doing this

You can also see the official mention of this in the github docs here: https://developer.github.com/v3/pulls/#labels-assignees-and-milestones

**Comment by niteshkhannaupstart** [comment]
> owner

what does owner mean here? gitHub.Issue.Update("owner", "repo name", pr.Number, issueUpdate);

What value does it or it should hold?

**Comment by salvadorgonmo** [comment]
Is it possible to use issues to automatically assign a Project to a PR when it has an specific label?
