### ISSUE TITLE
Is there a way to get the date of creation of a specific commit?

### ISSUE THREAD

**Issue by NikosSyris** [octokit/octokit.net#1863]
I am using Repository.Commit.GetAll()  to get all the commits for a specific file and while i get a lot of useful info i don't see a createdAt field for each commit. Am i missing something or is there any other way to get it?

**Comment by shiftkey** [comment]
@NikosSyris this is not available from the GitHub Commit API because of how the Git object model works.

The closest approximation is looking at the commit timestamp (in most cases they should be the same) for the commit where this file was added to the Git repository:

```c#
var commit = await client.Repository.Commit.Get("octokit", "octokit.net", "master");

var authorDate = commit.Commit.Author.Date;
var committerDate = commit.Commit.Committer.Date; 
```
