### ISSUE TITLE
Issue.Repository is always null by default?

### ISSUE THREAD

**Issue by Dalmirog** [octokit/octokit.net#1870]
Hi there,

First time logging an issue here, so I'd like to start saying thanks for the awesome job :)

I'm going through a series of repositories, getting all their issues and processing them later on

```c#
 var allIssues = client.Issue.GetAllForRepository("OctopusDeploy", repositoryName, new ApiOptions { PageSize = int.MaxValue }).GetAwaiter().GetResult();
```

Is it expected that each issue in that collection has their `Repository` property set as `null`? I need the Repository info to get the comments for each issue using `client.Issue.Comment.GetAllForIssue()`

Client `0.32.0`

Thanks in advance!

**Comment by Dalmirog** [comment]
I noticed `Issue.CommentsUrl` does have a value. Perhaps I should be using that URL instead? I couldn't find a way to use it with the client in any of the repository's examples and tests.

Sorry for all my .NET noobness :(

**Comment by shiftkey** [comment]
@Dalmirog thanks for the details - I looked at the JSON payload being sent in [the API docs](https://developer.github.com/v3/issues/#list-issues-for-a-repository) and I don't see `repository` being populated, so I suspect this is just a limitation of us using the same class to where the API doesn't return everything.

Also, just a heads up: `new ApiOptions { PageSize = int.MaxValue }` will still only return a maximum of 100 items.

**Comment by ryangribble** [comment]
Heya @Dalmirog!

It's a pretty long history behind this, a pretty good description is in https://github.com/octokit/octokit.net/issues/1616 as well as the other PR's and issues referenced there

Long story short - only some API issue responses include the repository attribute but to avoid too much mess on our side we generally just have one response model
