### ISSUE TITLE
Get all issues is not returning all issues

### ISSUE THREAD

**Issue by WowItsDoge** [octokit/octokit.net#1871]
Hi,
does the `Issue.GetAllForRepository()` function not return all issues from the repository?

For example, the tensorflow repository has currently 1,567 open and 12,045 closed issues, which is writen on the github page.
When using the library function, to get all the issues, I only get 1,829 results.
Can anyone explain why not all issues are returned?

```cs
var issues = await client.Issue.GetAllForRepository("tensorflow", "tensorflow");
foreach (var issue in issues)
{
Console.WriteLine(issue.Title)
}
```

Regards,
Jan

**Comment by shiftkey** [comment]
@WowItsDoge please note that [the API docs](https://developer.github.com/v3/issues/#list-issues-for-a-repository) indicate this will default to `open` issues.

If you're doing queries that you know are going to return a lot of data, you should enable pagination:

```C#
var openIssues = await client.Issue.GetAllForRepository("tensorflow", "tensorflow", new ApiOptions { PageSize = 100 });
Console.WriteLine($"Issues found by default: {openIssues.Count}");
```

With this query I see 1827 issues, similar to your case.

If I change up the query to pass in a `RepositoryIssueRequest` object, like this:

```C#
 var allIssues = await client.Issue.GetAllForRepository(
    "tensorflow",
    "tensorflow",
    new RepositoryIssueRequest { State = ItemStateFilter.All },
    new ApiOptions { PageSize = 100 });
Console.WriteLine($"Issues found with filter set: {allIssues.Count}");
```

I now get 22333 open and closed issues. I'm not sure why the disparity between the stats on the website and the API, but I'll leave that as an exercise for you to figure out.
