### ISSUE TITLE
Add code coverage for mac/linux Travis builds

### ISSUE THREAD

**Issue by StanleyGoldman** [octokit/octokit.net#1875]
While developing #1866 

I attempted to setup code coverage for travis but I had issues determining the path of coverlet when installed with `dotnet install coverlet`. I decided to reduce my scope and not include Travis CI.

##### Commit where I attempted it
https://github.com/octokit/octokit.net/blob/8904a34237d644aedf3f4b3141808e4017548eb1/build/Tasks/CodeCoverage.cs#L24-L29

##### Builds

https://ci.appveyor.com/project/github-windows/octokit-net/build/0.33.0-PullRequest.1866+10.build.2870

https://travis-ci.org/octokit/octokit.net/jobs/426700235

```
========================================
CodeCoverage
========================================
Executing task: CodeCoverage
Executing Code Coverage Project Octokit.Tests...
An error occurred when executing task 'CodeCoverage'.
Error: Coverlet: Could not locate executable.
The command "./build.sh --linksources=true --verbosity=verbose" exited with 1.
```

https://travis-ci.org/octokit/octokit.net/jobs/426700236

**Comment by shiftkey** [comment]
Closing this out as unimportant given how .NET Core is cross-platform and the differences between the OSes is so minor these days. As long as _something_ is submitting code coverage stats I'm good.
