### ISSUE TITLE
How to download the latest version of the project?

### ISSUE THREAD

**Issue by it19862** [octokit/octokit.net#1878]
I usually download a project by reference (see screenshot)
How to programmatically download and save to a local disk:
- the format "zip"?
- in unzipped format?

![2018-09-28_17-11-31](https://user-images.githubusercontent.com/18245828/46213671-e4941280-c341-11e8-8464-5d4beb0a1046.png)

**Comment by ryangribble** [comment]
Hi @it19862 

There is a lot method to get repository contents in zip format but I don't believe the API had anything for unzipped (although you could loop through and download every file individually it would probably be better to just download the zip then extract it) 

https://github.com/octokit/octokit.net/blob/74dc51a6f567395d0c46d97f7270f959d671573e/Octokit/Clients/IRepositoryContentsClient.cs#L158

**Comment by it19862** [comment]
@ryangribble  Could you show a code example.
I try to do ... but I can't

**Comment by shiftkey** [comment]
@it19862 You should be able to just splat the archive bytes to disk:

```C#
var archiveBytes = await github.Repository.Content.GetArchive("octokit", "octokit.net", ArchiveFormat.Zipball);
System.IO.File.WriteAllBytes(@"C:\Temp\repository-archive.zip", archiveBytes);
```

If you want to programatically interact with the archive, there are many APIs out there like [System.IO.Compression](https://docs.microsoft.com/en-us/dotnet/standard/io/how-to-compress-and-extract-files) and [SharpZipLib](https://github.com/icsharpcode/SharpZipLib) that will accept the byte array you received from the GitHub API.

**Comment by perrylets** [comment]
This method returns null every time and I don't know why.
```cs
byte[] zipball = await gh.Repository.Content.GetArchive(user.ToLower(), repoName, ArchiveFormat.Zipball);
using MemoryStream stream = new MemoryStream(zipball);
using ZipArchive archive = new ZipArchive(stream);

if (!instalationPath.Exists)
  instalationPath.Create();

archive.ExtractToDirectory(instalationPath.FullName);
```

Maybe there's an error in my code after the call to `GetArchive` but it doesn't even get there because it always returns null. The repository is public.
