### ISSUE TITLE
How to get at least some data on the repository license?

### ISSUE THREAD

**Issue by it19862** [octokit/octokit.net#1881]
I search for repositories according to the documentation.
https://github.com/octokit/octokit.net/blob/master/docs/search.md
How to get at least some data on the repository license?
I mean get data from this page.

Or the content of the file - "LICENSE.txt"

I need information from any of the areas indicated in the figure.

![2018-10-02_14-44-56](https://user-images.githubusercontent.com/18245828/46346811-03e8b380-c652-11e8-820b-a46b95e00604.png)

**Comment by ryangribble** [comment]
Hi @it19862 

You should be able to access a repository license information using the `.License` property of a `Repository` class (returned from `client.Repository.Get()`) 
https://github.com/octokit/octokit.net/blob/74dc51a6f567395d0c46d97f7270f959d671573e/Octokit/Models/Response/Repository.cs#L109

And you should be able to get the license file contents using `client.Repository.GetLicenseContents()`
https://github.com/octokit/octokit.net/blob/74dc51a6f567395d0c46d97f7270f959d671573e/Octokit/Clients/IRepositoriesClient.cs#L562

**Comment by it19862** [comment]
@ryangribble 
Could you show a code example.
I try to do ... but I can't
```
var repoLicen = client.Repository.GetLicenseContents("octokit", "octokit.net");
var licen = repoLicen.li???
```

**Comment by shiftkey** [comment]
@it19862 it returns a `Task<RepositoryContentLicense>`, so you need to `await` on it to get the result:

```C#
var repoLicense = await client.Repository.GetLicenseContents("octokit", "octokit.net");
```
