### ISSUE TITLE
How to make a search query in multiple languages?

### ISSUE THREAD

**Issue by it19862** [octokit/octokit.net#1889]
How to make a search query in multiple languages?
```
var request = new SearchRepositoriesRequest("mvc client side framework")
{
   // how about we restrict the language the library is written in?
    Language = Language.CSharp,
    Language = Language.JavaScript // ???? !
}
```

**Comment by shiftkey** [comment]
@it19862 the GitHub API doesn't support searching for multiple languages, so it's not possible to do this search using the Octokit libraries.

**Comment by it19862** [comment]
@shiftkey  Can you recommend any other ways to get a multi-language collection of repositories?
Using another library?
Or filter the search results?

**Comment by shiftkey** [comment]
@it19862 "run multiple searches use the same search term with a different desired language" is the closest you're going to get to the desired behaviour, but you might also need to do some filtering and merging of results to prevent duplicates.
