### ISSUE TITLE
How to get repository tags?

### ISSUE THREAD

**Issue by it19862** [octokit/octokit.net#1890]
How to get repository tags?
I try using the code.
`var tags = client_cur.Git.Tag.Get(instanceRepo, "master");`

does not work

![2018-10-13_23-56-12](https://user-images.githubusercontent.com/18245828/46909956-d3ebbb00-cf43-11e8-8ce9-36ea7f7a275d.png)

**Comment by ryangribble** [comment]
Hi @it19862 those are called repository topics. We don't have support in octokit for them just yet, there was an in progress PR but it hasn't been completed. See #1707 

It would be awesome If you'd like to contribute by helping to complete that PR!
