### ISSUE TITLE
Is it possible to get html code "README.md"?

### ISSUE THREAD

**Issue by it19862** [octokit/octokit.net#1893]
I want to display the resulting code in the browser of my application.
To save pictures, code highlighting, links and other elements
Is it possible to get html code "README.md"?

![2018-10-16_20-50-23](https://user-images.githubusercontent.com/18245828/47036483-51ead480-d185-11e8-866d-fb3cc7eb2987.png)

**Comment by ryangribble** [comment]
Hey @it19862 ,

Yes you can do this using the `IRepositoryContentsClient.GetReadmeHtml()` method
https://github.com/octokit/octokit.net/blob/74dc51a6f567395d0c46d97f7270f959d671573e/Octokit/Clients/IRepositoryContentsClient.cs#L140

eg `var readmeHtml = await client.Repository.Content.GetReadmeHtml(owner, repo);`
