### ISSUE TITLE
How to call /Token API 

### ISSUE THREAD

**Issue by rukhsarahmadexpert** [octokit/octokit.net#1897]
i am using Token base Authentication in Web api with owing, i can call /Token api from ajax and in response i getting a token.
i want to call the same api and send
username,
password
grant_type and get token in c# MVC controller how can i do it.
i tried so many techniques but failed.

my ajax call working fine.
   $.ajax({
                            url: '/token',
                            method: 'POST',
                            contentType: 'application/json',                         
                            data: {
                                username: $('#txtUsername').val(),
                                password: $('#txtPassword').val(),
                               
                               grant_type: 'password'

                            },
                            success: function (response) {
                                sessionStorage.setItem('accessToken', response.access_token);
                                localStorage.setItem('Username', response.userName);
}

But want to call from MVC Controller and save return token in server session.

**Comment by ryangribble** [comment]
Hi @Itmolen1 , Im not quite following your question sorry... to do an OAUTH flow you need to redirect the user to interact with GitHub to provide authorization, then GitHub will hit your API back with a code which you can then exchange for an auth token.  
https://github.com/octokit/octokit.net/blob/master/docs/oauth-flow.md

Does that help or have I misunderstood your question?

**Comment by Itmolen1** [comment]
i want to show Product,Product Category, and then Variant in select 2 in option using jquery with MVC 5.
can someone help me ? i am new in jquery
