### ISSUE TITLE
Is it possible to get a list of languages in which the request is mentioned?

### ISSUE THREAD

**Issue by it19862** [octokit/octokit.net#1899]
Is it possible to get a list of languages in which the request is mentioned?
![2018-07-17_11-28-12](https://user-images.githubusercontent.com/18245828/47609220-711a1980-da43-11e8-8dcf-7e71483dd2d0.png)

**Comment by ryangribble** [comment]
Hi @it19862 

This information isnt returned by the underlying API (https://developer.github.com/v3/search) so it isn't possible for us to do this in Octokit.

It might be worth looking into the GraphQL API and seeing whether it has this information
