### ISSUE TITLE
[Question] How to Get labels for pull request.

### ISSUE THREAD

**Issue by masakaya** [octokit/octokit.net#1901]
I'm creating an application to create a report on Pull request.
How can I get the Labels set in Pull request?

For example
```
 return client.Issue.Labels.GetForRepository(owner,  repo, pull_request_Id);
```

Or is it included in the following?I could not find it :(
https://github.com/octokit/octokit.net/blob/master/Octokit/Models/Response/PullRequest.cs

thank you.

**Comment by ryangribble** [comment]
Hi @masakaya :wave:

In GitHub API terms, all pull requests are also issues.  So when it comes to things like assignees, labels, etc you can use the issues API calls to get those details for PR's as well.

Just make sure you use the `pullRequest.Number` field, when calling any issue related endpoint.

eg
``` csharp
var prNumber = 123;

// Get the labels for PR #123
var labels = await client.Issue.Labels.GetAllForIssue(owner, repo, prNumber);

// Labels are also returned as part of issue objects so get the whole "issue" record for PR #123
var issue = await client.Issue.Get(owner, repo, prNumber);

// And output the name of the first label
Console.WriteLine(issue.Labels[0].Name);
```

Hope that helps!

**Comment by masakaya** [comment]
Hi @ryangribble 

Thank to you  I got Label information as a pull request unit.

Thank you again.
