### ISSUE TITLE
Is it possible to get all pull requests which were part of a release?

### ISSUE THREAD

**Issue by AnoojNair** [octokit/octokit.net#1907]
As the heading suggests would it be possible to get all the pull requests which were part of the release?

**Comment by shiftkey** [comment]
There's no unified API for this, and what's in #1906 should support most of the cases:

 - Merge commits include the Pull Request number and look like this: https://github.com/desktop/desktop/commit/d841b98656245b0fbee07dcd6c0357f51138146f
 - Squashed pull requests also include the Pull Request number, but have a different format: https://github.com/octokit/octokit.net/commit/eb9c112c032449e9a0b42fdabf54d676cde7351a
 - Rebased pull requests will likely have their commits rewritten, so identify their source is likely even tricker (and not something I've explored)

**Comment by ryangribble** [comment]
You can also identify the merged PR using the issue events API, so the way I've done it in the past is to load all PR's for the equivalent date range, then select only those whose merge event is in the commit list from the comparison API

Code example we use for our release notes generation is here:

https://github.com/ryangribble/Octokit.ReleaseNotes/blob/master/ReleaseNotes.cs#L241

**Comment by shiftkey** [comment]
I'm going to close this out because it's not something currently provided in the GitHub API, and some workarounds have been suggested.
