### ISSUE TITLE
client.Repository.Release.GetAll(owner, name).Result returns 0 results

### ISSUE THREAD

**Issue by AnoojNair** [octokit/octokit.net#1908]
Hi,

I am trying to fetch all releases for a repository for example 

client.Repository.Release.GetAll("jashkenas", "backbone").Result 

but for some reason it always returns 0 results. Am i missing something here?

**Comment by shiftkey** [comment]
@AnoojNair because there aren't any releases listed in the repository - just the existing tags https://github.com/jashkenas/backbone/releases

You want to enumerate the [tags](https://developer.github.com/v3/repos/#list-tags) themselves, which supports pagination options:

```c#
const tags = await client.Repository.GetAllTags("jashkenas", "backbone");
```
