### ISSUE TITLE
client.Repository.Release.Get(owner, name, tag.Name) returns Not Found

### ISSUE THREAD

**Issue by AnoojNair** [octokit/octokit.net#1909]
Hi,

I am trying to get release details using the Tag Name, for few  releases for e.g below.

client.Repository.Release.Get("jorgebucaran", "hyperapp", "1.2.8").Result returns an exception with message "Not Found".

i can see that such a tag exists 
https://github.com/jorgebucaran/hyperapp/releases/tag/1.2.8

What could be the reason?

**Comment by shiftkey** [comment]
@AnoojNair the third parameter in `Release.Get` is the release ID, not the tag itself. The [API docs](https://developer.github.com/v3/repos/releases/#get-a-single-release) have more details about it.

If you want to get details about a specific tag you should use the [Tag API](https://developer.github.com/v3/git/tags/#get-a-tag):

```
var tag = await client.GitDatabase.Tag.Get("jorgebucaran", "hyperapp", "1.2.8");
```
