### ISSUE TITLE
Incorrect Tag name

### ISSUE THREAD

**Issue by AnoojNair** [octokit/octokit.net#1910]
Hi ,

I am trying to read all the tags of a repo using 

`var tags = client.Repository.GetAllTags("meteor", "meteor").Result;
            foreach (var tag in tags)
            {
                Console.WriteLine(tag.Name);
            }`

And the tag names that i are get are like this shown below whereas [here](https://github.com/meteor/meteor/tags) it is different.

windows-wrapper
v0.5.9
v0.5.8
v0.5.7.2
v0.5.7.1
v0.5.7
v0.5.6
v0.5.5
v0.5.4
v0.5.3
v0.5.2
v0.5.1

**Comment by shiftkey** [comment]
Offhand I'm not sure how they differ (I thought it'd be creation date but it doesn't look like that).

Please get in touch with [GitHub Support](https://github.com/contact) if you'd like a better answer, because Octokit doesn't have control over either list.
