### ISSUE TITLE
User.GetAll endpoint

### ISSUE THREAD

**Issue by acaly** [octokit/octokit.net#1915]
Hi,

I am working on a small project that does some statistics from GitHub data. I am so glad to find this library, which really helps me a lot. However I encountered some problems.

One thing I am trying to achieve is to sample some random users from GitHub, so I need an API to get a list of users. I know there are millions of users on GitHub and getting a full list in one API call is impossible, but I thing even a direct wrapper for the [original all users API](https://developer.github.com/v3/users/#get-all-users) would help.

From the implemented API and issue list I couldn't find such feature. Please let me know if I missed something. There is already a public repositories API so I believe there's no reason we can't add it. If you think it's OK to add it, I am very happy to spend some time to try to work on it and send a PR. 

Thanks,
Zhenwei

**Comment by shiftkey** [comment]
> I know there are millions of users on GitHub and getting a full list in one API call is impossible, but I thing even a direct wrapper for the [original all users API](https://developer.github.com/v3/users/#get-all-users) would help.

@acaly if you're interested in contributing that endpoint let us know, I'm not sure how we overlooked that.

**Comment by shiftkey** [comment]
Also, if you're wanting to work over public GitHub data I'd look at the BigQuery data set that's available: https://blog.github.com/2017-01-19-github-data-ready-for-you-to-explore-with-bigquery/
