### ISSUE TITLE
Search Issue Request is not authenticated

### ISSUE THREAD

**Issue by l1salvatore** [octokit/octokit.net#1916]
Hi,
    Is it possible that the SearchIssueRequest like
 ```
   // you can also specify a search term here
var request = new SearchIssuesRequest();

// or use a series of repositories
request.Repos = new RepositoryCollection {
    "aspnet/home",
    "dotnet/core"
};
```
  sends anonymous request? Because i have problems when i query the API with this class. I have the client authenticated:
` githubclient.Credentials = new Credentials(token);`
And i have a private repo that i can view with the acces token.
This succesfully returns the issues, but GetAllForRepository doesn't have all filter options that let me use this functionality.
` githubclient.Issue.GetAllForRepository(repo.Owner, repo.Name).Result;`
This is not working for me, it throws me "Validation Failed" even when i am authenticated.
`  githubclient.Search.SearchIssues(request).Result.Items`
So may be a problem of Search.SearchIssues that sends anonymous requests.

Thanks in advance!

Lucas

**Comment by shiftkey** [comment]
Closing this out due to lack of repro and inactivity. @l1salvatore if you're able to provide more information we're happy to investigate further.
