### ISSUE TITLE
Is there a way to get the Repository social statistics like Star and Watch etc?

### ISSUE THREAD

**Issue by AnoojNair** [octokit/octokit.net#1917]
Hi,

As the title suggests, is there a way to fetch the social statistics of a repository like the Watch, Star  etc

![image](https://user-images.githubusercontent.com/8334797/49307386-eb095b00-f539-11e8-98ec-44b0d5147b0b.png)

**Comment by shiftkey** [comment]
These are all available on the `Repository` API response:

```c#
var r = await client.Repository.Get(owner, repository);
Console.WriteLine($"Repository has {r.SubscribersCount} subscribers, {r.StargazersCount} stargazers and {r. ForksCount} forks");
```
