### ISSUE TITLE
Add missing login and allow_signup parameter to OauthLoginRequest

### ISSUE THREAD

**Issue by patriksvensson** [octokit/octokit.net#1918]
It would be great if the (optional) `login` and `allow_signup` parameters was present on the `OauthLoginRequest` class.

Documentation for this can be found here: https://developer.github.com/apps/building-oauth-apps/authorizing-oauth-apps/#parameters

I would be happy to submit a PR for this.

**Comment by ryangribble** [comment]
Hi @patriksvensson, some of these older endpoints or requests have had fields added to them over time which we've missed in octokit!

It would be awesome if you want to send in a PR. 

FYI our convention for optional fields is they should be nullable and should be set via object initialisation syntax (ie not via the `ctor`) if that helps! 🙏
