### ISSUE TITLE
How to get file's download_url

### ISSUE THREAD

**Issue by Dre-Tas** [octokit/octokit.net#1920]
Hi everyone,

I've been able to navigate to the files in one of my private repo doing this:
`
var codeSearch = new SearchCodeRequest()
{
    Extension = ".dyn",
    Repos = new RepositoryCollection
    {
        "ridleyco/DynamoRepo"
    }
};
`
and then if I loop through them
`
foreach (var item in codeResult.Items)
{
    apis.Add(item.Url);
    names.Add(item.Name);
}
`
I'm able to get a few properties including urls, but I can't find a way to get the url that I need, which is the **download_url**.
In this way I'd then be able to download the file using `WebClient.DownloadFile(address, fileName)`

Is there a way to get that download_url property?

Thanks!

**Comment by ryangribble** [comment]
Hi :wave:

Which download_url property are you referring to? 

The "search code" API response has various fields, which should all be implemented in the octokit.net response model. There is Url GitUrl and HtmlUrl 

https://developer.github.com/v3/search/#search-code

https://github.com/octokit/octokit.net/blob/master/Octokit/Models/Response/SearchCode.cs


Also if you want to get the content of files you can use octokit to do this using the `RepositoryContentsClient` client,

eg `client.Repository.Content.GetXXX()`

**Comment by Dre-Tas** [comment]
Thanks for your reply @ryangribble !

What I'm looking for is what I underlined in the image below:
![image](https://user-images.githubusercontent.com/36023527/49639061-15897580-fa5e-11e8-9e59-c80c8f0837d7.png)

That in the image is just a test from a public repo, but putting that url (underlined in red in the image) as the _address_ parameter in my `WebClient.DownloadFile` I'm able to download the actual file.
If I try to use Url, GitUrl or HtmlUrl I can't download the file.

Am I looking at the wrong thing / in the wrong place?

(I'm fairly new to programming so sometime I make very basic mistakes)

Thanks!

**Comment by ryangribble** [comment]
Ah ok, the API response in your screenshot is not from a "search code" query, which is what your octokit.net code is doing.

To make the request in your screenshot you would use the repository contents API, `client.Repository.Content.GetAlContents()` which returns a list of objects of type `RepositoryContent` which does have the `DownloadUrl` field you are looking for
https://github.com/octokit/octokit.net/blob/master/Octokit/Clients/RepositoryContentsClient.cs#L68

**Comment by ryangribble** [comment]
GetAllContents returns a list, so you'd need to access the items in the list using the normal ways you do that in c# (such as iterating the list in a loop, using an index or using c# linq queries like First() Last() Where() etc)

**Comment by Dre-Tas** [comment]
It worked!
![image](https://user-images.githubusercontent.com/36023527/49643722-8d5d9d00-fa6a-11e8-83d0-10938afa6ac9.png)

Thanks so much @ryangribble !!

**Comment by Dre-Tas** [comment]
It worked!!
![image](https://user-images.githubusercontent.com/36023527/49643822-d44b9280-fa6a-11e8-8799-cada074edd56.png)

Thanks so much @ryangribble !!

**Comment by ryangribble** [comment]
Nice one!

**Comment by ORESoftware** [comment]
how do I get it from the url?

```bash
mod_url="https://api.github.com/repos/cm/go-api/contents/go.mod?ref=master"
```

when I use the above, I get JSON, but I just want the raw file - how do I get the download_url without using JQ?
