### ISSUE TITLE
Why application/x-www-form-urlencoded used as default content-type?

### ISSUE THREAD

**Issue by SIkebe** [octokit/octokit.net#1922]
In octokit.net, default content-type is application/x-www-form-urlencoded.
https://github.com/octokit/octokit.net/blob/4fb325891124c8b2b4dfb7f065fd4a515d177f9f/Octokit/Http/Connection.cs#L397-L402

But from the GitHub REST API v3 link, I couldn't find the documentation that says default content-type is application/x-www-form-urlencoded.

The same page says
>For POST, PATCH, PUT, and DELETE requests, parameters not included in the URL should be encoded as JSON with a Content-Type of 'application/json':

https://developer.github.com/v3/#parameters

So why is application/x-www-form-urlencoded deafult?
Is there any easy way to use application/json instead?

**Comment by shiftkey** [comment]
@SIkebe the code that you've linked to was last updated in 2013, so I'm not surprised the docs are a bit out of sync with that. Is there some example code that isn't working as expected? It'd be great to start this discussion around something concrete.

**Comment by HEAVAYU** [comment]
Hello world
