### ISSUE TITLE
Tutorial lists line of code that doesn't work

### ISSUE THREAD

**Issue by POE-Addon-Launcher** [octokit/octokit.net#1923]
I was following along with the tutorial on:
https://octokitnet.readthedocs.io/en/latest/releases/

And it tells me to use:
var latest = releases[0]

To grab the most recent release, however, Visual Studio does not agree with this:
![image](https://user-images.githubusercontent.com/42203962/50400932-34407980-078b-11e9-8c32-784beee03258.png)

Please, advise?

**Comment by shiftkey** [comment]
You need to `await` on the previous line:

```
var releases = await client.Repository.Release.GetAll("octokit", "octokit.net");
```

I've opened #1924 to resolve this
