### ISSUE TITLE
Issue.Update remove milestone from issue no matter what

### ISSUE THREAD

**Issue by Eilon** [octokit/octokit.net#1927]
I have code like this:

```c#
            var issueUpdate = new IssueUpdate();
            issueUpdate.AddLabel("some label");
            await gitHub.Issue.Update("owner", "repo", issueNumber, issueUpdate);
```

But over the wire, this request body is sent:

```json
{"milestone":null,"labels":["some label"]}
```

As you can see, the `milestone` is being forced to `null`, even though I didn't explicitly do that.

This makes the Update operation cause data loss.

To work around this I have to get the issue's current milestone and set it in the Update to avoid it being cleared out.

**Comment by Eilon** [comment]
OK looks like I can call:

```c#
Issue.Label.AddToIssue(......);
```

To more easily do what I want. But the issue above still seems valid.

**Comment by Eilon** [comment]
Note: Looks like Issue.Labels.AddToIssue() doesn't work due to an Octokit bug (https://github.com/octokit/octokit.net/issues/1928), and also due to a GitHub issue anyway.

**Comment by Eilon** [comment]
Here's the code I have to do to work around this issue:

```c#
            var issue = await gitHub.Issue.Get("owner", "repo", issueNumber);

            var issueUpdate = new IssueUpdate
            {
                Milestone = issue.Milestone?.Number // Have to re-set milestone because otherwise it gets cleared out. See https://github.com/octokit/octokit.net/issues/1927
            };
            issueUpdate.AddLabel("some label");
            // Add all existing labels to the update so that they don't get removed
            foreach (var label in issue.Labels)
            {
                issueUpdate.AddLabel(label.Name);
            }

            await gitHub.Issue.Update("owner", "repo", issueNumber, issueUpdate);
```

**Comment by shiftkey** [comment]
@Eilon thanks for the report and the snippet - I've been able to get this into a integration test and see the behaviour for myself. This is down to the serializing of `IssueUpdate` sending a `null` Milestone rather than omitting the field from the JSON payload if it's not cleared by the user.

A cleaner workaround if you have the issue from the API would be to use `issue.ToUpdate()` which gives you the pre-populated milestone and issues ready for you to then augment, so you don't need to manually enumerate things yourself (Assignees are also caught up in this `null` issue, in case you're using that in these issues).

```c#
var issue = await gitHub.Issue.Get("owner", "repo", issueNumber);

var issueUpdate = issue.ToUpdate();
issueUpdate.AddLabel("some label");

await gitHub.Issue.Update("owner", "repo", issueNumber, issueUpdate);
```

**Comment by Eilon** [comment]
BTW I don't see the problem with Assignee: I tested it out by only setting milestone and labels, and the existing assignee(s) on the issue remained.

**Comment by rabuckley** [comment]
I just hit this too. I was updating issue descriptions and ended mass-removing issues from milestones. Are there plans for this to be fixed?

**Comment by miloush** [comment]
Could we use 0 as explicit request for removal?
