### ISSUE TITLE
Issue.Labels.AddToIssue() sending wrong body format

### ISSUE THREAD

**Issue by Eilon** [octokit/octokit.net#1928]
It's sending this in the POST body:

```json
["bug", "enhancement"]
```

But according to https://developer.github.com/v3/issues/labels/#add-labels-to-an-issue it should be:

```json
{
  "labels": ["bug", "enhancement"]
}
```

Note: Unfortunately, it looks like the API always returns a 404 anyway, even though everything else looks right, and it's otherwise following what the docs say. I sent manual requests using the exact documented pattern and it's always a 404.

**Comment by shiftkey** [comment]
@Eilon do you have a code snippet I can work with?

**Comment by gr2m** [comment]
FYI this was a recent change, both will work on api.github.com and GHE 2.16. Only the former will work on GHE 2.15 and below

**Comment by Eilon** [comment]
BTW sorry I haven't had a chance to make a full repro. I will try to find time to provide more info. And BTW I was using this with GitHub.com, not GHE. The support person who I reported the general problem to said they couldn't repro it using the documented API call, so I'm not sure what problem I had with that. Could be I was doing something bonkers.

**Comment by ryangribble** [comment]
> both will work on api.github.com and GHE 2.16. Only the former will work on GHE 2.15 and below

Based on this issue, It sounds like the "old" way (ie the raw array, current implementation in this library) is somehow not actually being supported on dotcom...

**Comment by ryangribble** [comment]
Actually, I just confirmed the integration tests that use this method are fine, so I think perhaps @Eilon you may have been onto something here 😝 
> Could be I was doing something bonkers.

![image](https://user-images.githubusercontent.com/5425163/52049398-6cf91d00-2599-11e9-99d3-88c71149efa1.png)

I'll close this issue but please re-open it if you do find something further on this...

As a separate concern, we should implement support for the newer API call schema, but it does look like GitHub Api is accepting the old array format (generally they are very good with backward compatibility and gating schema changes behind preview headers etc)
