### ISSUE TITLE
Detecting empty repositories

### ISSUE THREAD

**Issue by aurecchia** [octokit/octokit.net#1938]
I was wondering if there is a supported way to determine whether a repository is empty or not. At the moment I am checking the `size` field, it seems to work fine for the moment, but it is both deprecated and potentially inaccurate (as stated in https://github.com/octokit/octokit.net/issues/443).

Is there a cleaner way to do this?

**Comment by ryangribble** [comment]
Hi @aurecchia 

I assume you mean without making an additional "per repo" call?  I'm not aware of anything additional to the old conversation you've linked...

You could contact github support and see if they have anything else to suggest?

The graphQL API would also be an option to retrieve repos with commits/files/branches/refs provides some similar entity that helps determine if they're empty or not, without making multiple calls. You could check out https://github.com/octokit/octokit.graphql.net in that case...

**Comment by aurecchia** [comment]
Hi @ryangribble ,

Thank you for the quick reply. Yes, I was more interested in avoiding other requests. I assume that when you wrote "without making and additional call" you had the `contents` endpoint in mind, correct?

In any case this is just for an internal statistics tool, nothing that needs to run in production, and having empty repositories is an exception, so for now just checking the size should be  fine. 

I'll keep in mind that the graphQL API as an alternative, thanks for the suggestion.

**Comment by ryangribble** [comment]
I didn't have anything specific in mind but if you already had other reasons to make individual calls per repo then presumably getting commits, files refs or similar things would reveal the repo was empty

I'll close out this issue but do let us know if you have any further thoughts or findings
