### ISSUE TITLE
Octokit.PullRequest is missing labels

### ISSUE THREAD

**Issue by patriksvensson** [octokit/octokit.net#1942]
It looks like `Octokit.PullRequest` is missing labels associated with the pull request which according to the API documented is returned as part of the responses associated with pull requests.

Would you accept a pull request for this (no pun intended) 😓?

**Comment by khellang** [comment]
There's no need... https://github.com/octokit/octokit.net/pull/1926

**Comment by patriksvensson** [comment]
Oooh, that's a nice surprise! Thanks @khellang 😄
