### ISSUE TITLE
Implement the new Draft Pull Requests

### ISSUE THREAD

**Issue by guilhermemoschen** [octokit/octokit.net#1945]
Hello, at 2019-02-14, GitHub released a preview about the new draft pull request.
https://developer.github.com/changes/2019-02-14-draft-pull-requests/

I'd like to request an update include this new boolean flag at PullRequest.

Thanks!

**Comment by ryangribble** [comment]
Hi @guilhermemoschen 

it would be great to support this new feature, would you be keen to work on a PR to add it?

**Comment by guilhermemoschen** [comment]
Yes, I think I can try to do it ;)

**Comment by ShenLanJohn** [comment]
any update for this issue? Thanks!

**Comment by guilhermemoschen** [comment]
Is it possible to use `ApiConnection.Get<T>` to return the draft information if you define a new model. Something like `PullRequestWithDraft : PullRequest`.

So you can:
```cs
var pullWithDraft = apiConneciton.Get<PullRequestWithDraft>(...);
```

**Comment by ShenLanJohn** [comment]
Thanks Guilherme! will try!

**Comment by l1salvatore** [comment]
Hi all,
   any updates on this? Last version 0.32 in Nugget doesn't support Draft boolean and i want to use this.

Thanks

**Comment by l1salvatore** [comment]
On the other hand,, is there a way to build a filter instance of a class against Github API with this property?
At the moment i'm filtering issues and then look up the pullrequest with the same id and check the Mergeable State
