### ISSUE TITLE
Download whole folder/directory from repository

### ISSUE THREAD

**Issue by Dre-Tas** [octokit/octokit.net#1950]
Hey guys,

Is there a way to download an entire directory from my repository?

I'm able to go through the contents of my repositories using `GetAllContents()` and get all the files and folders in it.
I'm also able to download the files that are inside the different folders via:
`WebClient wc = new WebClient();`
`wc.DownloadFile(RepositoryContent.DownloadUrl, localPath);`
but I see that directories don't have the `DownloadUrl()` method.

Is there another way (without having to go through all the subfolders and getting the files)?

Thanks!

**Comment by shiftkey** [comment]
@Dre-Tas the only other example that comes to mind is downloading the entire repository as an archive (ZIP or TAR):

```
var archiveBytes = await client.Repository.Content.GetArchive("octokit", "octokit.net", ArchiveFormat.Zipball);
```

This will return a byte array which you can then stream to disk and work with locally to extract the files you need.

**Comment by Dre-Tas** [comment]
Thanks @shiftkey for your reply.

I'm afraid that downloading the whole repo wouldn't be too efficient in my case.

I just used a workaround for now, which is to load zipped folders in my repo. This means folders become files that can normally be downloaded through the `DownloadUrl` property and then, as soon as they get downloaded I'm able to unzip them and delete the original zipped folder.
Side benefit is also that it takes less space and less time to commit/push.

**Comment by shiftkey** [comment]
@Dre-Tas we're limited by what the GitHub API supports, so I'm going to close this out now that we've outlined the options available.
