### ISSUE TITLE
Easier way to get specific file commit date

### ISSUE THREAD

**Issue by Misiu** [octokit/octokit.net#1957]
Hi there,
I'm quite new to octokit.net, so this might be an easy one for veteran users 🙂
I'm trying to get file edit date (commit date) and a direct link to download it.
Currently I use this code:

```
var client = new GitHubClient(new ProductHeaderValue("Test_APP"));
var repo = await client.Repository.Get("51Degrees", "Device-Detection");
var request = new CommitRequest { Path = "data/51Degrees-LiteV3.2.dat" };
var commitsForFile = await client.Repository.Commit.GetAll(repo.Id, request);
var lastCommit = commitsForFile[0];//to get last commit
var commitDetails = await client.Repository.Commit.Get(repo.Id, lastCommit.Sha);
DateTimeOffset authorDate = commitDetails.Commit.Author.Date;
DateTime fileEditDate = authorDate.LocalDateTime;

var file = await client.Repository.Content.GetAllContents(repo.Id, "data/51Degrees-LiteV3.2.dat");
var downloadUrl = file[0].DownloadUrl;
```
is there an easier way? Especially to get specific file commit date?

**Comment by shiftkey** [comment]
I think that second request to `Commit.Get` is unnecessary, because `Commit.GetAll` will contain the details. But aside from that I can't get this down to fewer than 2 requests (because of how the data is organized).

Here's my tweaked sample, which also supports finding the file on a specific branch (without this, the default branch on the repository is used, which might be fine in your case):

```c#
var repo = await client.Repository.Get("51Degrees", "Device-Detection");

var path = "data/51Degrees-LiteV3.2.dat";
var branch = "master";

var request = new CommitRequest { Path = path, Sha = branch };

// find the latest commit to the file on a specific branch
var commitsForFile = await client.Repository.Commit.GetAll(repo.Id, request);
var mostRecentCommit = commitsForFile[0];
var authorDate = mostRecentCommit.Commit.Author.Date;
var fileEditDate = authorDate.LocalDateTime;

// get the download URL for this file on a specific branch
var file = await client.Repository.Content.GetAllContentsByRef(repo.Id, path, branch);
var downloadUrl = file[0].DownloadUrl;

Console.WriteLine($"File ${path} was last edited at ${fileEditDate} and has URL ${downloadUrl}");
```

**Comment by Misiu** [comment]
@shiftkey I didn't think about branches, thanks for the tip 🙂
Not sure about the internals, but ideally there could be a method to get the last commit for a specific file, something like so:

```
//gets the last commit details
var commitsForFile = await client.Repository.Commit.Get(repo.Id, request);
```
or
```
//gets the last commit details
var commitsForFile = await client.Repository.Commit.GetLast(repo.Id, request);
```
Currently this isn't available, but it would be usefull (idea is to query GitHub in such way that it would return only last commit data, not to filter data on client)

**Comment by shiftkey** [comment]
> Not sure about the internals, but ideally there could be a method to get the last commit for a specific file, something like so:

This library is just a wrapper around the [GitHub API v3](https://developer.github.com/v3/) and we've avoided implementing convenience methods that don't exist in the underlying API to keep things simple.

To make this a bit more performant most `GetAll` APIs support pagination using an `ApiOptions` parameter, so you can control how much data you get back. By default `GetAll` will follow pagination if there is more data to get, so this is a way to ignore data you don't need and save on network requests and downloads.

It won't change the API result (still an array of commits), but it becomes a bit easier to understand what data you are looking for:

```
var oneItem = new ApiOptions { PageSize = 1, PageCount = 1 };
var commitsForFile = await client.Repository.Commit.GetAll(repo.Id, request, oneItem);
var mostRecentCommit = commitsForFile[0]; //to get last commit
```

**Comment by Misiu** [comment]
@shiftkey this was exactly what I needed!
I've checked in Fiddler and the amount of data that is returned is much smaller.
I have a file that has almost 100 commits. With `ApiOptions` only data for the last commit is returned.

**Comment by shiftkey** [comment]
I believe this has been resolved, so I'm going to close it out

**Comment by Misiu** [comment]
@shiftkey yes, the problem is solved. There isn't a direct method but suggested workaround works perfect 🙂
