### ISSUE TITLE
404 on git tree recursive with slash in the branch name

### ISSUE THREAD

**Issue by joeharrison714** [octokit/octokit.net#1962]
When I try to do a git tree on a branch name that includes a slash (feature/whatever) I get a 404 back when using Octokit.net. I made the api request in postman and it worked fine. Any thoughts on what might be wrong?

**Comment by shiftkey** [comment]
> Any thoughts on what might be wrong?

The `/` could be encoded in the URL incorrectly? I'd look at a [Fiddler](https://www.telerik.com/fiddler) session when invoking Octokit and see what URL it's requesting...

**Comment by joeharrison714** [comment]
Nevermind! Sorry it was my mistake. I was accidentally doing a ToLower on the branch name and the only one that had uppercase also had a slash.
