### ISSUE TITLE
Exception when i want to commit in a branch

### ISSUE THREAD

**Issue by l1salvatore** [octokit/octokit.net#1963]
Hi guys, 
     I am trying to send a commit to a specific branch named B in a repository.
     Here is my code:

```
        var owner = Owner;
        var repo = Name;
        var branch = B;
 
        UpdateFileRequest upfr = new UpdateFileRequest(commitName,
                                                              newContent,
                                                              sha,
                                                              branch);

        var updateChangeSet = githubclient.Repository.Content.UpdateFile(
                                        owner,
                                        repo,
                                        filePath,
                                        upfr).Result;
```

The problem is that the filePath doesn't exist in live branch but it exists in the B branch. So the UpdateFile throws an exception named “Not Found”. 
Can you please help me? Because I think it shouldn’t make a difference whether it exists in live or not.

**Comment by l1salvatore** [comment]
UPDATE:

I checked the function of UpdateFile and it gets content of the live branch 
 _var updateUrl = ApiUrls.RepositoryContent(owner, name, path);_
```
public Task<RepositoryContentChangeSet> UpdateFile(string owner, string name, string path, UpdateFileRequest request)

        {

            Ensure.ArgumentNotNullOrEmptyString(owner, nameof(owner));

            Ensure.ArgumentNotNullOrEmptyString(name, nameof(name));

            Ensure.ArgumentNotNullOrEmptyString(path, nameof(path));

            Ensure.ArgumentNotNull(request, nameof(request));



            var updateUrl = ApiUrls.RepositoryContent(owner, name, path);

            return ApiConnection.Put<RepositoryContentChangeSet>(updateUrl, request);

        }
```

**Comment by l1salvatore** [comment]
One question:
   It is possible to add a commit to a forked repo? I've tried all ways and only i get is "Not Found" :/

**Comment by l1salvatore** [comment]
My idea is send commits automatically to a pull request made from a public forked repo

**Comment by shiftkey** [comment]
@l1salvatore I think you might have found a bug, but it's hard to say without a bit more context.

In theory the `request` payload should be converted to JSON, and if that branch name is set it should be on the payload here:

```
return ApiConnection.Put<RepositoryContentChangeSet>(updateUrl, request);
```

This is where we set `branch` in the library:

https://github.com/octokit/octokit.net/blob/74dc51a6f567395d0c46d97f7270f959d671573e/Octokit/Models/Request/CreateFileRequest.cs#L40-L43

Are you able to use a tool like Fiddler to inspect the HTTP traffic and see that we're sending the correct payload? There might be extra clues in the response to understand why it's returning `Not Found` (sometimes this occurs if the private repository is not accessible by the current user, but it seems like you're working from a fork which should be public by convention).

**Comment by l1salvatore** [comment]
Hi @shiftkey ,
    thanks for your answer. I have checked trying send http via curl the headers to Github API and it returns the same error "Not Found".
Basically, i have a repo **R** which there are a pull request coming from a public forked repo **R_f** in the branch **B**. The owner of **R_f** is other person **P**. So

`curl.exe -i -X PUT -H "Authorization: token TOKEN" -d "{\"message\":\"update\", \"content\": \"SG9sYSBtdW5kaWxsbwo=\",  \"branch\" : \"B\",  \"sha\" : \"SHA\"}" "https://api.github.com/repos/P/R_f/contents/File"`

should send a commit in the public forked repo. Moreover, i can make a commit in that repo in the Github front-end. But vía API it throws me "Not Found".

I have to investigate in that way
