### ISSUE TITLE
Can you pleaes give example to crate pull request and review request?

### ISSUE THREAD

**Issue by ShenLanJohn** [octokit/octokit.net#1968]
"{\"message\":\"Validation Failed\",\"errors\":[{\"resource\":\"PullRequest\",\"field\":\"base\",\"code\":\"invalid\"},{\"resource\":\"PullRequest\",\"field\":\"head\",\"code\":\"invalid\"}],\"documentation_url\":\"https://developer.github.com/v3/pulls/#create-a-pull-request\"}"

**Comment by ShenLanJohn** [comment]
I did not find any thing about pull request in( https://octokitnet.readthedocs.io/en/latest/search.html?q=NewPullRequest)

Thank you!

**Comment by Hekku2** [comment]
Following repository / file has a one example that creates a PR, or updates an old one with new commit. It might have some bugs, I'm currently investigating a possible memory leak issue which just surfaced.

See method `Fix`
https://github.com/protacon/repository-validator/blob/master/ValidationLibrary/Rules/HasNewestPtcsJenkinsLibRule.cs
