### ISSUE TITLE
DateRange formatted incorrectly

### ISSUE THREAD

**Issue by catmorgan** [octokit/octokit.net#1972]
#1904 

https://github.com/octokit/octokit.net/blob/9f005c438ee393f4f687edf0b9f22d0b38ae3a37/Octokit/Models/Request/SearchRepositoriesRequest.cs#L301

I believe that this may be a bug- I don't think there should be a space for the timezone, between "ss" and "zzz" 

This is the difference between filtering merged by with the formatted space:
https://github.com/octokit/octokit.net/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aclosed+merged%3A%3E2018-07-01T21%3A11%3A01+%2B00%3A00

without the space:
https://github.com/octokit/octokit.net/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aclosed+merged%3A%3E2018-07-01T21%3A11%3A01%2B00%3A00+

**Comment by patricknolan** [comment]
Hi @catmorgan is this causing incorrect results?

**Comment by patricknolan** [comment]
Hi @catmorgan just checking if you got my last message?

**Comment by catmorgan** [comment]
Hello! I am so sorry I missed your comments, I encountered this bug at my work and I just checked in on this- so happy to see it fixed! Thanks so much :D
