### ISSUE TITLE
Could you please help how can I know "All checks have passed" in octokit?

### ISSUE THREAD

**Issue by BingyuLiu** [octokit/octokit.net#1973]
![image](https://user-images.githubusercontent.com/19498851/60900477-17e4c580-a221-11e9-81bd-b974c7c812b9.png)

**Comment by BingyuLiu** [comment]
From checking, the Mergeable is "true", MergeableState is "Block" whatever all checks are passed or pending！

**Comment by BingyuLiu** [comment]
@shiftkey , could you please help? Thank you!!!

**Comment by BingyuLiu** [comment]
Ping, thanks!

**Comment by shiftkey** [comment]
@BingyuLiu the [Checks API](https://developer.github.com/v3/checks/) is only available to GitHub Apps. I'm going to cross-reference this in #1976 because we don't really have a better place to track it currently.

**Comment by shiftkey** [comment]
> From checking, the Mergeable is "true", MergeableState is "Block" whatever all checks are passed or pending！

@BingyuLiu please open a separate issue with a reproducible bug report if you'd like us to look at this problem.
