### ISSUE TITLE
How work with 2FA login?

### ISSUE THREAD

**Issue by MairwunNx** [octokit/octokit.net#1974]
I make an application for `GitHub`, and there was a problem when creating `Login view`, I would like to make it possible for a user to log in with his login and password or token, but if I have `2FA` enabled, then when I try to log in, program throw a `TwoFactorRequiredException` exception, I can process it and do something, but how can I interact with it in some way? There is nothing in the documentation with which I could send this token or choose `send to phone` or `send to application`.

Thanks.

**Comment by MairwunNx** [comment]
Please answer the problem from any of the contributors, because the creator of the repository on vacation.

**Comment by MairwunNx** [comment]
Когда я смотрел исходники `octokit.net` я нашел способ работать с `2FA`, и у меня получилось.

---
When I tried to log in with login and password I got the exception `TwoFactorRequiredException`, after that I’ve displayed in my `UI` the input field `verify code`.

When I clicked on the `Verify` button, I called the `Authorization.Create` method with the necessary arguments (`verifyCode` it `verify code` of the user):
```csharp
Authorization.Create(
    new NewAuthorization("note", new List<string>()),
    verifyCode
);
```
If the `verify code` is correct, then the `ApplicationAuthorization` instance returns to us with the `Token` property we need.

Then I just re-log in with the authorization type `AccessToken` passing that `Token` to the constructor `Credentials`.

Done, now I am authorized in the system! Please be kind @shiftkey and other contributors, add any of this to the documentation in the 2FA section. Thank.

I hope this helps someone.

**Comment by MairwunNx** [comment]
After working with this, I realized that Note should be unique, it confused me, many github clients who log in through 2FA, they somehow work differently with this.

В своем аккаунте во вкладке "безопасность" я заметил это: `oauth_authorization.create  – Personal access token (MagicianHub@2FA(Mairw:2019-07-15T21:24:11))` я использую дату и user name как уникальные данные для Note. 

In my account in the "security" tab I noticed this: `oauth_authorization.create  – Personal access token (MagicianHub@2FA(Mairw:2019-07-15T21:24:11))` I use the date and user name as unique data for Note.

I want to hear advice, can it be made easier and whether I am doing true authorization through 2FA?

**Comment by shiftkey** [comment]
Marking this one as `docs-and-samples` because this is a gap in the current documentation, and a decent sample for handling 2FA is necessary.

**Comment by hnrkndrssn** [comment]
I put together a quick LINQPad script to show how to handle 2FA login https://gist.github.com/hnrkndrssn/c40a4aba66a2680cac4e72d6d0fde4a1

**Comment by shiftkey** [comment]
@hnrkndrssn happy to help 👍
