### ISSUE TITLE
Question: GitHub integration support

### ISSUE THREAD

**Issue by Korporal** [octokit/octokit.net#1976]
Hi,

I was busy looking at Oktokit over a year ago when someone began to implement some support for GitHub integration (creating apps that integrate with GitHub).

I wanted to ask how far has that endeavor progressed? and are there any examples or anything that I can look at?

Thanks

**Comment by shiftkey** [comment]
@Korporal are you referring to GitHub Apps? If so, there are some outstanding issues that are up-for-grabs:  #1826 #1827 #1828

**Comment by shiftkey** [comment]
We had a request for supporting the Checks API in #1973, and that's something that's only available to GitHub Apps.
