### ISSUE TITLE
RepositoryCommitClient.GetSha1() returns full SHA

### ISSUE THREAD

**Issue by StupidChris** [octokit/octokit.net#1977]
Been trying to get the SHA1 of a commit in order to create a new tag and I can't seem to get it to work right.

The XML documentation on it is a bit fuzzy. I first assumed that the "reference" string was the full SHA. Tried with that, got the full SHA back from the method. At that point, I reread the doc comment and saw "repository reference". Thought this meant I had to supply "refs/head/branch". Tried that, get an API error out saying I supplied an invalid SHA.

So yeah, not sure what is up. Am I doing this wrong or is this really a bug?

**Comment by shiftkey** [comment]
@StupidChris can you show a code example of what you were trying to achieve? Using a public repository to test would also help us to reproduce what you're seeing.

**Comment by StupidChris** [comment]
Sure, here's a very small C# console app demonstrating this:
```csharp
using System.Threading.Tasks;
using Octokit;
using static System.Console;

namespace OctokitShaTest
{
    internal static class Program
    {
        private static async Task Main()
        {
            //Get branch info
            GitHubClient client = new GitHubClient(new ProductHeaderValue("OctokitShaTest"));
            Repository repo = await client.Repository.Get("octokit", "octokit.net");
            Branch branch = await client.Repository.Branch.Get(repo.Id, repo.DefaultBranch);
            string sha1 = await client.Repository.Commit.GetSha1(repo.Id, branch.Commit.Sha);

            //Print info
            WriteLine("Repository: " + repo.FullName);
            WriteLine("Branch: " + branch.Name);
            WriteLine("Branch SHA: " + branch.Commit.Sha);
            WriteLine("Branch SHA1: " + sha1);

            //Keep info on screen
            WriteLine("\nPress enter to quit...");
            ReadLine();
        }
    }
}
```

I'm getting the following output:
```
Repository: octokit/octokit.net
Branch: master
Branch SHA: 8fcb7313432b0c95e6713dd64bdf18d2e7631538
Branch SHA1: 8fcb7313432b0c95e6713dd64bdf18d2e7631538
```

**Comment by StupidChris** [comment]
Alright, I'm digging through the docs and I think I got it wrong on my end. I think what I expected was the *short* SHA of a commit. Guess that's what I get for working at 3am.

Trying to take that as a learning experience at least, I'm guessing GetSha1() is to do the opposite of what I'm trying to do? Send the short SHA and get the full one back, and I can just Substring(0, 7) to get the short? If that's the case can I suggest possibly clarifying a bit the XML comment on GetSha1? The `reference` parameter should probably be renamed `shortSha` along with it.

**Comment by shiftkey** [comment]
@StupidChris cool, so I think this is the part that need clarifying:

> Thought this meant I had to supply "refs/head/branch". Tried that, get an API error out saying I supplied an invalid SHA.

The GitHub API sometimes expects the fully-qualified ref (e.g. `refs/heads/master`), and sometimes the short ref is fine (e.g. `master`). Your sample works fine because you're passing in the commit ID, but if you want to find the branch name then I think tweaking the example like this is all you need to do:

```c#
using System.Threading.Tasks;
using Octokit;
using static System.Console;

namespace OctokitShaTest
{
    internal static class Program
    {
        private static async Task Main()
        {
            //Get branch info
            GitHubClient client = new GitHubClient(new ProductHeaderValue("OctokitShaTest"));
            var masterSha = await client.Repository.Commit.GetSha1("octokit", "octokit.net", "master");
            var branchSha = await client.Repository.Commit.GetSha1("octokit", "octokit.net", "audit-api-changes");

            WriteLine("Master: " + masterSha);
            WriteLine("Branch SHA: " + branchSha);

            try
            {
                var fullBranchSha = await client.Repository.Commit.GetSha1("octokit", "octokit.net", "refs/heads/audit-api-changes");
                WriteLine("Full Branch SHA: " + fullBranchSha);
            }
            catch (NotFoundException)
            {
                WriteLine("Fully-qualified ref throws");
            }

            //Keep info on screen
            WriteLine("\nPress enter to quit...");
            ReadLine();
        }
    }
}
```

I thought this would fail, but it's working fine:

```
Master: 8fcb7313432b0c95e6713dd64bdf18d2e7631538
Branch SHA: 0ebda0de8122ab6de4ec76728ab46a98f6b1b76e
Full Branch SHA: 0ebda0de8122ab6de4ec76728ab46a98f6b1b76e

Press enter to quit...
```

The other thing that is missing from the example script is that credentials are not provided. That could matter if you're trying to access a private repository.

**Comment by shiftkey** [comment]
@StupidChris this function is a wrapper on top of [this GitHub API](https://developer.github.com/v3/repos/commits/#get-a-single-commit).

It's intended to be a quick way to resolve a **ref** to the **commit id**, for situations where you don't have a copy of the repository locally.

**Comment by StupidChris** [comment]
@shiftkey yeah, that's the doc I was just looking at. I think I got this all wrong, apologies. I also tried using "refs/heads/branch", but I think I might've made a typo and that's why it crashed, tried again just now and had no issue. To clarify, I'm authenticated on my main app with a personal access token and full repo access, so credentials weren't the issue, it's really just me.

I think it's fine to close this. Mostly as big misunderstanding on my part. Looks like passing the first 7 characters of the sha works as I'm able to use it to grab the commit info again and create a tag.

**Comment by shiftkey** [comment]
@StupidChris yeah, if you're passing in untrusted input here (or it might not be a ref that no longer exists) I'd recommend ensuring you catch and handle any `NotFoundException` that comes from the GitHub API (it won't return `null`).

Good luck!
