### ISSUE TITLE
Partial Repository Archive

### ISSUE THREAD

**Issue by RedlineTriad** [octokit/octokit.net#1980]
It is not currently possible to only get a part of a repository using GetArchive, or if it is, it is not in the documentation.
This especially an issue for large repositories that also include images, sounds, and or video content.

(This is at the same time a question, since maybe there is a way but i haven't found it)

**Comment by shiftkey** [comment]
@RedlineTriad no, [`GetArchive`](https://developer.github.com/v3/repos/contents/#get-archive-link) is associated with a certain ref (or the default branch if not specified), and obtaining only a subset of the files is not currently supported.

If you only want to obtain a specific file or specific folder of files, [`GetContent`](https://developer.github.com/v3/repos/contents/#get-contents) might satisfy the requirements.
