### ISSUE TITLE
Question: Propper way to get all Repos for user that have file .xxx

### ISSUE THREAD

**Issue by BasHamer** [octokit/octokit.net#1990]
I want to display a lift for all repos for a user that has a file called .xxx in the root folder. I only want to list repos that this user has explicit access to, not public repos that they are unaffiliated with. I'm not just listing repos that are owned by the user they could belong to other users.

Is this the correct way to do this? I'm worried about the enumerating all repos for the user part.

```
            var repos = await client.Repository.GetAllForCurrent();

            var arg = new Octokit.RepositoryCollection();
            foreach (var repo in repos)
                arg.Add(repo.Owner.Login, repo.Name);

            var possibles = await client.Search.SearchCode(new Octokit.SearchCodeRequest
            {
                FileName = ".xxx",
                Repos = arg
            });

            var initialized = possibles.Items.Where(x => x.Name == ".xxx");
```

**Comment by hnrkndrssn** [comment]
Hi @BasHamer,

`var repos = await client.Repository.GetAllForCurrent()` will return only repositories that are **owned** by the current user so this would not return repositories where the current user is a collaborator. _Also, if the user has many, many repos the call to `client.Search.SearchCode` **could** throw an exception as the `Uri` would be too long._

From what I can see, there is no _easy_ way to find repos that the current user doesn't own but where they are a collaborator.

I've modified the code sample you have to search all repos **owned** by the current user (so you don't have to get all the users repos and iterate over them and possibly hit the max length for the `Uri` string) below:

```
var user = await client.User.Current();
var possibles = await client.Search.SearchCode(new Octokit.SearchCodeRequest
{
	Path = "/",
	FileName = ".xxx",
	User = user.Login
});

var initialized = possibles.Items.Where(x => x.Name == ".xxx");
```

I've explicitly included `path:/` so it only searches for files in the root folder (I couldn't find any docs mentioning if it'll search **everywhere** if `path` is not specified).

I hope that helps.

Cheers,
Henrik

**Comment by BasHamer** [comment]
I definitely get repos from other users when running 
`var repos = await client.Repository.GetAllForCurrent();`
For example, my bashamer login gets back the https://github.com/PossumLab/InternalTests repo that is used for testing. I don't know why bashamer does not show up as a contributor but does show up in the checkin history :/

using
```
            var possibles = await client.Search.SearchCode(new Octokit.SearchCodeRequest
            {
                FileName = ".possumlab",
                Path = "/",
                Repos = arg
            });
```
other weirdness that makes me nervous; 
it returns the `possumlab.md` file from that repo above. even if there is some regex magic happen the leading dot should still have prevented this :/

Adding the path did clean up some other matches, I appreciate the help w/ that.

**Comment by shiftkey** [comment]
@BasHamer 

> For example, my bashamer login gets back the https://github.com/PossumLab/InternalTests repo that is used for testing. 

This is probably because you were invited to be a collaborator on that repository in the past, which grants you access to this repository.

> I don't know why bashamer does not show up as a contributor but does show up in the checkin history :/

This API is for what the current user has access to, and doesn't consider contributions. If you don't care about being able to make changes to this repository, you can remove yourself from it by visiting https://github.com/settings/repositories, finding it in the list, and clicking "Leave"

**Comment by hnrkndrssn** [comment]
> This is probably because you were invited to be a collaborator on that repository in the past, which grants you access to this repository.
D'Oh, I was reading the code for that method [here](https://github.com/octokit/octokit.net/blob/master/Octokit/Clients/RepositoriesClient.cs#L299) which states that the method returns repos the user **owns**. But, the GitHub [docs](https://developer.github.com/v3/repos/#list-your-repositories) clearly state that it's any repo that the user has `read`, `write`, `admin` permissions too.

Sorry for the misinformation...

**Comment by shiftkey** [comment]
@hnrkndrssn no problem - one of the perks of spending _so much_ time with the GitHub API is that you can hear a behaviour and immediately be able to trace that back to what it's actually doing.

**Comment by hnrkndrssn** [comment]
> one of the perks of spending _so much_ time with the GitHub API is that you can hear a behaviour and immediately be able to trace that back to what it's actually doing.

yea, I've been out of the game for too long 😢 😃

**Comment by BasHamer** [comment]
oooh thank for the commit bug, yeah I'm not surprised that I mucked something up there and those are all done w/ code..

Also the relation between PossumLab and BasHamer is intended, this is the test data that I'm working with. I'm happy that the behavior is as expected.
