### ISSUE TITLE
Update documentation about auth tokens when working with private repositories

### ISSUE THREAD

**Issue by ianfixes** [octokit/octokit.net#2002]
Reopening the issue raised in https://github.com/octokit/octokit.net/issues/1775 as requested (also appears in https://github.com/octokit/octokit.net/issues/1891)

Please update this document with more information on setting up a personal access token.
https://github.com/octokit/octokit.net/blob/master/docs/getting-started.md

In particular, there should be some language around scope, especially the scary-sounding "Full control of private repositories".  

e.g. 

> To be able to see private repositories at all, you will need your oauth token to include the scope for "Full control of private repositories" (`repo`). Yes, it sounds over-inclusive; a better description would be "Access all aspects of public and private repositories", since your private repositories cannot even be listed without it.  GitHub doesn't currently allow anything more granular.
> 
> Note that you do not _need_ the top-level `repo` scope to be selected -- no errors will be raised -- but your queries for private repos will just return an empty array.

**Comment by ianfixes** [comment]
@shiftkey do you think this merits adding the `pinned` label, as the bot suggests?  Or has the underlying quirk about the `repo` scope been resolved upstream?

**Comment by shiftkey** [comment]
@ianfixes I'm no longer a maintainer on the project, but I'd suggest pitching the changes as a PR to that page. I also think basic authentication needs to be removed as it's [no longer supported by the API](https://github.blog/2020-07-30-token-authentication-requirements-for-api-and-git-operations/) so it's probably worth giving that page a refresh.

The [current docs for the REST API](https://docs.github.com/en/rest/guides/getting-started-with-the-rest-api#using-personal-access-tokens) also only mention tokens.
