### ISSUE TITLE
Draft PR - Difference between master branch in GitHub and Nuget package

### ISSUE THREAD

**Issue by boikomary** [octokit/octokit.net#2020]
https://github.com/octokit/octokit.net/blob/ce5ea644285b1b5cbc154bd838b600c0a2c43352/Octokit/Models/Response/PullRequest.cs#L42

this model contains Draft (please look into GitHub)
but when I use the latest Octokit version in the project. There is no Draft parameter

![image](https://user-images.githubusercontent.com/17644547/65963131-cbe19f80-e462-11e9-82e7-6a4449278bca.png)

**Comment by shiftkey** [comment]
You can see the commits on `master` that aren't in `v0.34.0` here: https://github.com/octokit/octokit.net/compare/v0.34.0...master

The PR with the draft PR changes #2009 hasn't been published to NuGet yet, but it it is available on our pre-release NuGet feed which is documented [here](https://github.com/octokit/octokit.net#beta-packages) if you wanted to start using it.

Gonna leave this open until I've published a new release to the main NuGet feed (later this week).

**Comment by boikomary** [comment]
many thanks 👍

**Comment by hnrkndrssn** [comment]
Draft PRs is now live and available in [v0.35](https://github.com/octokit/octokit.net/releases/tag/v0.35.0)
