### ISSUE TITLE
Support for negative qualifiers

### ISSUE THREAD

**Issue by ecarlson94** [octokit/octokit.net#2021]
GitHub API V3 has a functionality where a `-` can be placed in front of a qualifier to negate its function.
- `extension:sql` - Look in files with the `sql` extension
- `-extension:sql` - Look in file that are not `sql` files

I think this would be great functionality to have in `octokit.net`.

**Comment by hnrkndrssn** [comment]
As the `-` syntax works for all **string** based search qualifiers, should we add them all at the same time?

**Comment by shiftkey** [comment]
Before going too deep on this, I want to call out two things:

 - the work required to generate each search URL is already complex, and adding support for negation will potentially double the internals required e.g. 

https://github.com/octokit/octokit.net/blob/3e7c70cf4e38ea29fd778cdc7bfb65ea4f88e8b5/Octokit/Models/Request/SearchCodeRequest.cs#L160-L228

 - What should the user-facing API for this look like? We want to avoid breaking existing callers, if at all possible, but if breaking API changes are unavoidable I'd love to instead make this a new client API that we can experiment to then bake and figure out migration

**Comment by hnrkndrssn** [comment]
My initial (though quite brief) thoughts were to just add additional properties for qualifiers to exclude, e.g. `ExcludedExtensions` but after thinking about it a bit more **and** seeing the first of your thoughts I agree that it would add unnecessary complexity to an already complex implementation.
