### ISSUE TITLE
Suggestion: Endpoint / API for retrieving Team members

### ISSUE THREAD

**Issue by SeanKilleen** [octokit/octokit.net#2027]
Hey all,

It looks like this doesn't exist; I'd be interested in doing a PR to implement it. Let me know if it gets the green light.

## Goal

I'd like to be able to get a list of users that belong to a team. This is so that I can programmatically update a team with all of the members of the organization, and remove from teams any users who have been removed from the organization.

## Imagined Syntax

I'd like to do something along the following lines:

```csharp
var teams = await client.Organization.Team.GetAll(githubOrg);
var theTeam = teams.First(x =>string.Equals(x.Name, groupToPopulateWithAllUsers, StringComparison.InvariantCultureIgnoreCase));

// This syntax doesn't currently exist.
var usersInTeam = theTeam.Members;
```

Or:

```csharp
// These syntaxes don't exist
var teamMembers = client.Organization.Team.GetMembersFor("myOrg", "myTeam")
var teamMembers = client.Organization.Team.GetMembersFor(12345);
```

A few questions:

* Is this something you'd be interested in seeing added to the library?
* Is there a preferred syntax from a library standpoint for what users should call to get this information?

Thanks for considering!

**Comment by shiftkey** [comment]
@SeanKilleen apologies for the delay in following up. I think this all makes sense:

> Is this something you'd be interested in seeing added to the library?

Yes!

> Is there a preferred syntax from a library standpoint for what users should call to get this information?

We've got a number of conventions baked into the library that ensure things are consistent, and aside from that the syntax you've provided seems reasonable. Happy to revisit this as part of a PR review.
