### ISSUE TITLE
Newer Languages are missing

### ISSUE THREAD

**Issue by Dagizmo** [octokit/octokit.net#2030]
Acording to this list :
https://github.com/github/linguist/blob/master/lib/linguist/languages.yml

those are the languages in github.

On ocktokit serveral are missing such as "Jupyter Notebooks", how can more languages be added? since currently is only a enum but i don't know if it affects other parts.

**Comment by shiftkey** [comment]
I have an idea for keeping this in sync, but it requires some work to be more than a band-aid solution here:

 - add linguist as a submodule
 - write a script to check the list against the `Languages` enum, and identify any values that should be added or removed

https://github.com/octokit/octokit.net/blob/fd6bca910cce936d84af7fb264b516bff3904c57/Octokit/Models/Request/SearchRepositoriesRequest.cs#L502-L517

 - write an Action to periodically
   - update the submodule 
   - run the script that verifies the list
   - open a PR with the result and what a reviewer needs to do to manually address the issue
 
I think there's some extra work here (it'd be great for CI to also verify this) but for now I think this is a decent first step.
   -
