### ISSUE TITLE
Expose `triage` and `maintain` permissions

### ISSUE THREAD

**Issue by terrajobst** [octokit/octokit.net#2041]
It looks like there is currently no way to see whether a user has `triage` or `maintain` permissions because the API only exposes the three levels `pull`, `push`, and `admin`.

Affected APIs:

* `GitHubClient.Organization.Team.GetAllRepositories()`
* `GitHubClient.Repository.Collaborator.GetAll()`

**Comment by shiftkey** [comment]
I gather we're talking about https://developer.github.com/v3/repos/collaborators/#list-collaborators ? Or are you referring to the `permission` hash returned on https://developer.github.com/v3/repos/#get ?

I thought there might have been a preview API support for this, but it doesn't seem to be documented.

GraphQL supports this fine, FWIW:

```gql
query () {
  repository(owner: "owner", name: "repo") {
    collaborators(first: 50, affiliation: ALL) {
      edges {
        node {
          login
        }
        permission
      }
    }
  }
}
```

**Comment by terrajobst** [comment]
> I gather we're talking about https://developer.github.com/v3/repos/collaborators/#list-collaborators ?

Yes, and `GitHubClient.Organization.Team.GetAllRepositories()`. I've updated the description.

**Comment by hnrkndrssn** [comment]
Just so I don't go down the wrong 🐇 🕳 

I'm assuming that it's this class [RepositoryPermissions](https://github.com/octokit/octokit.net/blob/master/Octokit/Models/Response/RepositoryPermissions.cs) where these additional permissions would be added?

**Comment by terrajobst** [comment]
That's the only types I'm using, so I think this looks good.

**Comment by hnrkndrssn** [comment]
Cool 👍 PR incoming sometime this weekend 😁

**Comment by shiftkey** [comment]
Closing this out as it's not currently available as a preview API.

If this does make an appearance on https://developer.github.com/v3/previews/ then we can revisit it.

**Comment by fgarcia-cnb** [comment]
for what its worth, it looks like the REST API correctly shows triage and maintain permissions now (if you use "Accept: application/vnd.github.v3.repository+json" in the header: 
[https://developer.github.com/v3/teams/#list-team-repos](url)

and although the documentation only mentions being able to set pull/push/admin as permissions, triage and maintain does indeed work.

**Comment by shiftkey** [comment]
@fgarcia-cnb that sounds like its close, but I'm going to wait for this to appear as a documented preview API https://developer.github.com/v3/previews/

**Comment by terrajobst** [comment]
Seems a bit odd to close, rather than using it as a way to be periodically reminded to check the docs. FWIW, I’ve moved to graph APIs for these queries because they are much faster and expose that data already. But that also means that I’m unlikely to check back on this issue.

**Comment by shiftkey** [comment]
Looks like this one just went live: https://developer.github.com/v3/repos/#get-a-repository (check the JSON response)

**Comment by fredg02** [comment]
Any plans to add this to the library soon? Or does it still need to appear as a documented preview API first?

**Comment by shiftkey** [comment]
@fredg02 I believe this is just an additive change to the response, so I've marked it as `up-for-grabs` if someone wants to take a shot at adding it in.

**Comment by eatdrinksleepcode** [comment]
I started looking at this tonight, and would swear I saw the new values in the docs at https://developer.github.com/v3/repos/#get-a-repository. But after messing with the API for a bit, I couldn't find them in the response. So I went back and checked the docs again...and the values are gone!?

![image](https://user-images.githubusercontent.com/2099560/103146076-d0e6da80-4709-11eb-89ae-8c5c5fed7fa8.png)

I'm not quite sure what's going on...

**Comment by terrajobst** [comment]
Can this be reopened? Seems like a glaring omission now.

**Comment by TanukiSharp** [comment]
Bumping this, as the `ITeamClient`'s `AddRepository` method suffers the same problem.

https://github.com/octokit/octokit.net/blob/main/Octokit/Clients/ITeamsClient.cs#L247
https://github.com/octokit/octokit.net/blob/main/Octokit/Models/Request/RepositoryPermissionRequest.cs#L8
https://github.com/octokit/octokit.net/blob/main/Octokit/Models/Common/Permission.cs#L43

🙏
