### ISSUE TITLE
Search API: tags are not quoted

### ISSUE THREAD

**Issue by ChadNedzlek** [octokit/octokit.net#2044]
```csharp
var request = new SearchIssuesRequest()
{
  Labels = new[] {"With Space"},
};
SearchIssuesResult issues = await client.Search.SearchIssues(request);
```

This results in a search that looks like `label:With Space` which doesn't resolve, because the label needs to be quoted in the search string.

**Comment by shiftkey** [comment]
@ChadNedzlek thanks for the report. I believe this is the area of code that needs to be updated:

https://github.com/octokit/octokit.net/blob/f61654a74b4bee3bba59dce3b76dbe1bfd255f35/Octokit/Models/Request/SearchIssuesRequest.cs#L329-L332

And I think making changes here will require updating this test (and perhaps adding a new one for this case as well):

https://github.com/octokit/octokit.net/blob/f61654a74b4bee3bba59dce3b76dbe1bfd255f35/Octokit.Tests/Models/SearchIssuesRequestTests.cs#L111-L120

Marking this one as `up-for-grabs` as I think it's ideal for a new contributor to pick up.

**Comment by zHaytam** [comment]
Hello, may I take this issue if no one is working it?

**Comment by shiftkey** [comment]
@zHaytam go for it!
