### ISSUE TITLE
Expose whether a repo is a template repo

### ISSUE THREAD

**Issue by terrajobst** [octokit/octokit.net#2047]
In my case, I'm building a set of org policies and I want to exclude template repos from certain polices (e.g. that inactive repos should be archived).

**Comment by shiftkey** [comment]
@terrajobst the field you're looking for seems to be `is_template`:

```json
{
  "id": 1296269,
  "node_id": "MDEwOlJlcG9zaXRvcnkxMjk2MjY5",
  "name": "Hello-World",
  "full_name": "octocat/Hello-World",
  "is_template": true,
  ...
}
```

If someone was to add a new boolean field named `IsTemplate` to [`Octokit/Models/Response/Repository.cs`](https://github.com/octokit/octokit.net/blob/master/Octokit/Models/Response/Repository.cs) as well as a constructor parameter then I think this should all just work.

Marking as `up-for-grabs` as I think this is ideal for a quick external contribution.

**Comment by Flexburo** [comment]
@shiftkey 

Would adding that boolean to
Octokit/Models/Request/RepositoryUpdate.cs
Work the same way? So as to be able to edit repositories to be a template.
