### ISSUE TITLE
How to get organization list for a authenticated user?

### ISSUE THREAD

**Issue by Abdulsametileri** [octokit/octokit.net#2048]
Hello, 
I want to check a user belongs to specified organization or not? For example 

```
var orgs = user.OrganizationsBelongTo();
foreach (var org in orgs) {
    if (org == "specifiedOrganization")
        return true;
}
return false;
```

How Can I achive this functionality using this great library? 

I tried to use

```
var d = github.Organization.Get("specifiedOrganization");
var member = github.Organization.Member;
var isExistInOrganization = await member.CheckMember("specifiedOrganization", "specifiedUser");
```

Using CheckMember function returns currently available **public** users, I want to see also private users.

**Comment by shiftkey** [comment]
You're on the right track, but there's some limits to what you can see from `CheckMember` around seeing non-public membership:

 - you can only see your non-public membership if you have the `read:org` scope set on the token and are checking your membership
 - you can only see the non-public membership of others if you are an admin of that organization and have set the `read:org` scope on the org

**Comment by Abdulsametileri** [comment]
Solved adding read:org to scope. Thank you
