### ISSUE TITLE
Support for the newly announced Actions API?

### ISSUE THREAD

**Issue by JeffreyPalmer** [octokit/octokit.net#2078]
A kind soul at GitHub pointed me at this blog post announcing the launch of the Actions API beta: https://developer.github.com/changes/2020-01-28-actions-api/. This is super exciting, and I was wondering how this project would go about adding support for this API. I can see the general implementation patterns in the code for various other endpoints, and I would be happy to help with this effort. That said, I don't develop on Windows and am not sure if that makes my efforts more challenging than someone developing on Windows.

I guess I'm basically looking for guidance on some questions:

1) Is anyone already working on adding this API?
2) Am I misguided in thinking that developing this on a mac would be straightforward? My main concern would be that I would get 90% of the way through the implementation and then not be able to debug some test failure that I couldn't run, and the effort would stall out.
3) Would anyone be able to provide feedback during the implementation process if I have questions, etc.?

Thanks!

**Comment by shiftkey** [comment]
>  anyone already working on adding this API?

Not that I'm aware of.

> Am I misguided in thinking that developing this on a mac would be straightforward? My main concern would be that I would get 90% of the way through the implementation and then not be able to debug some test failure that I couldn't run, and the effort would stall out.

We're on .NET Core these days and I've been able to to work with the solution in VSCode on Linux (I'll drop to the command line mostly to run tests) but there's a bunch of patterns and conventions with how things are organized that means it should be easy to follow/borrow/steal from existing components in the library.

> Would anyone be able to provide feedback during the implementation process if I have questions, etc.?

I'm more than happy to help with reviewing.

**Comment by JeffreyPalmer** [comment]
I'll take a pass at it and see how it goes. Thanks!

**Comment by JeffreyPalmer** [comment]
Okay I have a first pass at the entire API. I am *definitely* going to need a lot of feedback, both because I am an F# programmer and this is my first *real* C# development, and also because I don't really know the preferred idioms for this project (although I have copied a ton!).

I'm going to try to clean things up a little and submit a WIP PR to provide an opportunity for directional feedback. Gonna try for tomorrow. 🤞🏻

**Comment by kentahikaru** [comment]
Hello,
is it still possible to implement this ? Or is anybody already working on this?
If i understand correctly , it is necessary to implement all of those 6 endpoints ?
https://developer.github.com/changes/2020-01-28-actions-api/

**Comment by martincostello** [comment]
I'm going to take a look at contributing the client bits for Actions, as I've been using it in some automation I've been building.

**Comment by Seichis** [comment]
Any news on this one?

Thanks!

**Comment by nickfloyd** [comment]
> Hello, is it still possible to implement this ? Or is anybody already working on this? If i understand correctly , it is necessary to implement all of those 6 endpoints ? https://developer.github.com/changes/2020-01-28-actions-api/

Hey @kentahikaru & @Seichis, it is possible; the only one who has worked on this is @martincostello - he's got a draft PR [here](https://github.com/octokit/octokit.net/pull/2429).  Ideally, all six endpoints should be implemented.  

If either of you has time, you might lend @martincostello a hand to get this over the finish line.  While getting these APIs knocked out is important, the core of the work we're in the middle of is still getting things in a healthy place so we can begin approaching model (and eventually endpoint) generation.

If y'all have time and want to contribute, please do!  Thank you for being part of the community ❤️

**Comment by martincostello** [comment]
I’d be happy to pick up the draft again soon and do more, but I was hoping for some initial review/feedback I was on the right track before I did anymore.

It turned out to be a lot more involved than I initially anticipated 😅
