### ISSUE TITLE
investigate whether linqpad samples can be run on non-windows builds

### ISSUE THREAD

**Issue by shiftkey** [octokit/octokit.net#2095]
We're currently using `lprun` from Linqpad v5 to test our samples, but v6 mentions that it works for .NET Core. Can we leverage that?

**Comment by hnrkndrssn** [comment]
I just downloaded LINQPad6 and it only include Windows binaries by the looks of things... 😢 

![image](https://user-images.githubusercontent.com/1035315/75100861-2dc3c100-561f-11ea-8834-332d51e242e3.png)

And it's built against `Microsoft.WindowsDesktop.App`...

> The framework 'Microsoft.WindowsDesktop.App', version '3.0.0' was not found.

**Comment by shiftkey** [comment]
@hnrkndrssn thanks for digging into that. Gonna close this out in that case.
