### ISSUE TITLE
Search.SearchRepo excludes private repos in GHE

### ISSUE THREAD

**Issue by lethall** [octokit/octokit.net#2098]
We have written an application using Octokit.net which permits the user to select a repo/branch/directory to execute test specifications found in that location. We authenticate as a GitHub App which is installed with read-only permissions to metadata and contents, plus read/write to issues.

This works perfectly for public repos and *temporarily* for private repos.  The duration of visibility of private repos is quite variable, spanning 30 minutes to about 20 hours.

Through much experimentation we have found that uninstalling the GitHub App and reinstalling it does temporarily make the private repos visible; but again, only temporarily.

Our company is using GitHub Enterprise Server 2.19.6, our app is built using Octokit.net 0.31.0 on top of Microsoft.AspNetCore.All 2.0.8

**Comment by shiftkey** [comment]
@lethall thanks for the report. I can't spot anything obvious about how to fix this with Octokit so I have some initial questions to help isolate where the problem lies.

> Through much experimentation we have found that uninstalling the GitHub App and reinstalling it does temporarily make the private repos visible; but again, only temporarily.

This makes me wonder if there's a bug in GHES about GitHub Apps and repository visibility, but the fact that it works initially and then stops working is fascinating. Your version `2.19.6` is only from last month, so I don't think an upgrade here will fix it. I checked the release notes for [`2.19.7`](https://enterprise.github.com/releases/2.19.7/notes) and [`2.20.0`](https://enterprise.github.com/releases/2.20.0/notes) and couldn't see anything obvious to indicate that this has been resolved. This might require your administrators who manage the GHES installation to contact [GitHub Enterprise Support](https://enterprise.github.com/support) and work with them to properly investigate the problem.

What happens if you use a personal access token instead - does that work as expected?

**Comment by lethall** [comment]
Thanks for your quick reply @shiftkey .  Given that the GitHub app works as expected initially, it will take some time to build experimental code using a personal access token and collect the results after a reasonable amount of time (>20 hr) has lapsed.  We will build such an experiment and report back after we know.

**Comment by lethall** [comment]
Seems a personal access token configured for repo read doesn't list private repos.  [Here's the simplified code example I created to experiment with this suggestion](https://github.com/lethall/SearchRepoExp)

Note that the "GitHub_app" branch of that repo is a stripped down version of what our production app is doing.

**Comment by shiftkey** [comment]
> Seems a personal access token configured for repo read doesn't list private repos.

I don't understand what "repo read" means here. I should have been clearer with what scopes the token needed - have you set the `repo` scope based on [these docs](https://developer.github.com/apps/building-oauth-apps/understanding-scopes-for-oauth-apps/#available-scopes)?

<img width="682" src="https://user-images.githubusercontent.com/359239/74589372-cda39e00-4fd2-11ea-8590-b9f783dfdcbc.png">

**Comment by lethall** [comment]
Giving full repo access to a personal token does, indeed, give visibility to my private GHE repo.  I'll check this again in a few hours, then again tomorrow.

Note that our use case is for our users to give our GitHub app read-only access.  It may be against policy to require them to provide a personal access token with full access.

**Comment by shiftkey** [comment]
> Note that our use case is for our users to give our GitHub app read-only access. It may be against policy to require them to provide a personal access token with full access.

Totally fine - just wanted to confirm this visibility issue is isolated to GitHub Apps.

**Comment by lethall** [comment]
Update:  private repos are still included when searching with the personal access token. In most observations, the private repos would have been skipped by now when authenticating as the GitHub app.  I will continue to monitor this as we've not yet reached the maximum failure duration.

**Comment by lethall** [comment]
Listings still include private repos after 20 hours.  At this point, I think it is safe to conclude that the problem with private repo visibility is isolated to GitHub apps.

**Comment by lethall** [comment]
I have contacted my employer's internal GitHub Enterprise administrative team asking them to open an issue with GitHub Enterprise Support.

**Comment by shiftkey** [comment]
> I have contacted my employer's internal GitHub Enterprise administrative team asking them to open an issue with GitHub Enterprise Support.

Excellent, that's the best option right now. I'm afraid there's not much I can do from the client side to resolve this, so I'm going to close this out as an Enterprise-specific issue to bring the issue tracker under control.

Feel free to update us with any additional information if it'll help.
