### ISSUE TITLE
Issue Label added datetime

### ISSUE THREAD

**Issue by apobekiaris** [octokit/octokit.net#2099]
how to get this information?

![image](https://user-images.githubusercontent.com/159464/74626763-4cc2de80-5159-11ea-9f4a-f9ab8c29fde8.png)

**Comment by hnrkndrssn** [comment]
Hey @apobekiaris,

You need to interrogate the events for the issue in question looking for `Labeled` events. I've put together a small LINQPad script below:
```
var gh = new GitHubClient(new ProductHeaderValue("LinqPad"));
var issueEvents = await gh.Issue.Events.GetAllForIssue("octokit", "octokit.net", 2099);
var latestLabeledEvent = issueEvents.Where(e => e.Event.Value == EventInfoState.Labeled && e.Label.Name.Equals("category: how do i do X?", StringComparison.OrdinalIgnoreCase)).LastOrDefault();
latestLabeledEvent.CreatedAt.Dump();
```

I hope that helps!

**Comment by apobekiaris** [comment]
excellent!
