### ISSUE TITLE
repository_dispatch event is not covered

### ISSUE THREAD

**Issue by justinyoo** [octokit/octokit.net#2100]
Hi, Team.

I'm heavily using GitHub Actions and just found that Octokit.NET doesn't have repository_dispatch event related logic, while rest.js does.

Would you please share your timeline to add this feature?

**Comment by shiftkey** [comment]
@justinyoo thanks for your interest!

Currently my bandwidth for addressing changes to the APIs is limited, so I can't commit to a specific timeline, but I'm also happy to make time for reviewing contributions to keep things moving.

Can you refresh my memory on the sample that you would like to work? That'll help me write up what changes need to be made to support this event.

**Comment by justinyoo** [comment]
@shiftkey Thanks for your reply!

I forked the repo and am in the middle of adding some logic for this, by changing `IRepositoriesClient`, `RepositoriesClient`, `IApiConnection` and `ApiConnection`. Once I complete my first draft, I'll send a PR for review.

**Comment by MindaugasLaganeckas** [comment]
Our company needs this feature as well.
@justinyoo: can I start working on this feature or do you plan to resume working on it?

**Comment by justinyoo** [comment]
@MindaugasLaganeckas Oh, that would be great! I’ve been fully stretched since this conversation. Thanks for your offer!

**Comment by MindaugasLaganeckas** [comment]
Unfortunately, our focus has changed for now. Everyone is welcome to take over.

**Comment by krokofant** [comment]
This is still missing. Could this be reopened?

**Comment by EvoTechMike** [comment]
@justinyoo Did you make the PR?  I am looking to trigger actions and cant find anything documented in library regarding it.

**Comment by jakub-lesniak-ikea** [comment]
This seems to be still missing after 4 years..
