### ISSUE TITLE
stop using full types in response where only subset of information is available from API

### ISSUE THREAD

**Issue by psiservices-rcocks** [octokit/octokit.net#2103]
I'm using Octokit version 0.4.0 through nuget and when I query pull requests with `GetAllForRepository`, the field `ChangedFiles` and similar other fields all report 0 for all PRs.

Manually querying the API through curl shows the correct number of changed files.

**Comment by shiftkey** [comment]
@psiservices-rcocks can you share the relevant JSON you are receiving from curl? Maybe we're not deserializing correctly due to some change from the API response?

**Comment by psiservices-rcocks** [comment]
My earlier description was not fully accurate, I was comparing octokit with an api request to the individual PR endpoint. 

However, the `/pulls` list endpoint does not list changed files at all.

I'm running the following linqpad script to reproduce this issue:

(With octokit added through nuget and namespaced in the linqpad properties).

```
async void Main()
{
	var client = new GitHubClient(new ProductHeaderValue(@"linqpad-github-test-client"));

	var options = new ApiOptions
	{
		PageCount = 1,
		PageSize = 1,
		StartPage = 1
	};

	var prReq = new PullRequestRequest()
	{
		State = ItemStateFilter.Closed
	};
	var pullRequests = await client.PullRequest.GetAllForRepository("octokit", "octokit.net", prReq, options);
	pullRequests.Take(1).Select(r => new { r.Number, r.ChangedFiles}).ToList().Dump();
	
	var pr = await client.PullRequest.Get("octokit", "octokit.net",2101);
	pr.Dump();
}
```

When queried as a batch, the ChangedFiles is zero, but the individual request matches the HTTP api which I was using to check against earlier.

**Comment by shiftkey** [comment]
@psiservices-rcocks this is a limitation of how we deserialize responses - we use the same type for `GetAllForRepository` and `Get`, but `GetAllForRepository` doesn't receive the same information as `Get`.

The fix for this would be to use a different response type, but I'd like to figure out how to do this across the entire codebase, rather than spot fixes like this.

**Comment by psiservices-rcocks** [comment]
Thank you for the quick response, I now understand the cause and limitation.
