### ISSUE TITLE
Support for transferring issues across repositories

### ISSUE THREAD

**Issue by nkolev92** [octokit/octokit.net#2117]
Looking at the APIs and docs https://octokitnet.readthedocs.io/en/latest/issues/#create, I am not sure what the recommended way to do this is. 

I know in theory, I can write a tool that closes an issue and then creates a new one in a different repo but it's not an equivalent experience.

**Comment by shiftkey** [comment]
Is there a documented API for Issue Transfers? I don't see it mentioned in https://developer.github.com/v3/issues/ or as a preview API https://developer.github.com/v3/previews/ ?

**Comment by nkolev92** [comment]
I haven't been able to find it either. 
Which I guess explains why it doesn't exist in the library itself.

**Comment by shiftkey** [comment]
For the moment I'm going to close this out as we're limited by what the GitHub API can suport.

If this does appear as a preview API in the future, we can revisit it then.
