### ISSUE TITLE
Build.ps1 hostfxr.dll does not support relative app dll paths.

### ISSUE THREAD

**Issue by bobbytreed** [octokit/octokit.net#2120]
A compatible installed .NET Core SDK for global.json version [3.1.101] from [C:\Users\user\Documents\ockokit.net\global.json] was not found
Install the [3.1.101] .NET Core SDK or update [C:\Users\user\Documents\ockokit.net\global.json] with an installed .NET Core SDK:
dotnet-install: .NET Core SDK version 2.0.3 is already installed.
dotnet-install: Adding to current process PATH: "C:\Users\user\Documents\ockokit.net\.dotnet\". Note: This change will not be visible if PowerShell was run as a child process.
Restoring global tools...
Tool 'sourcelink' (version '3.1.1') was restored. Available commands: sourcelink
Tool 'dotnet-format' (version '3.3.111304') was restored. Available commands: dotnet-format

Restore was successful.
Preparing Cake.Frosting build runner...
  Restore completed in 27.28 ms for C:\Users\user\Documents\ockokit.net\build\Build.csproj.
Running Cake.Frosting build runner...
dotnet run -- --configuration="Release" --linkSources="False" --dryrun="False" --target="Default" --verbosity="Normal"

----------------------------------------
Setup
----------------------------------------
Calculating semantic version...
The required library C:\Users\users\Documents\ockokit.net\.dotnet\host\fxr\2.0.3\hostfxr.dll does not support relative app dll paths.
Error: GitVersion: Process returned an error (exit code -2147450748).

**Comment by bobbytreed** [comment]
Installing the .net core 3.1 SDK fixed this, but your code that attempts to install dotnet under octokit won't work without setting DOTNET_ROOT. In PowerShell you probably also need to update $env:DOTNET_ROOT as environment variables are only loaded on new powershell session

**Comment by shiftkey** [comment]
@bobbytreed thanks for the heads up.

I'm not too familiar with how to properly configure PowerShell for working with .NET Core but I'm going to leave this open to remind myself to look at how setup docs and see if we can improve them at all.
