### ISSUE TITLE
preview support for enabling or disabling vulnerability alerts

### ISSUE THREAD

**Issue by shiftkey** [octokit/octokit.net#2145]
- https://developer.github.com/v3/repos/#enable-vulnerability-alerts
 - https://developer.github.com/v3/repos/#disable-vulnerability-alerts

**Comment by BlythMeister** [comment]
Can this also include listing if enabled using https://docs.github.com/en/rest/reference/repos#check-if-vulnerability-alerts-are-enabled-for-a-repository
