### ISSUE TITLE
Linked pr/issue

### ISSUE THREAD

**Issue by cotur** [octokit/octokit.net#2159]
Hi all,

How to get issues that closes by a pr from ```Octokit.PullRequest``` itself?
Or how to get prs that closes issue from ```Octokit.Issue``` itself?

**Comment by shiftkey** [comment]
@cotur are you referring to [this announced feature](https://github.blog/2020-02-06-get-more-information-at-a-glance-with-issue-and-pull-request-linking/)?

Unless there is a [documented API](https://developer.github.com/v3/) or a [preview API](https://developer.github.com/v3/previews/) underway then we are unable to supported it in the client API.

**Comment by cotur** [comment]
@shiftkey Thanks, I hope that feature comes early. :)
