### ISSUE TITLE
No option for checking (and activating) Read Only Data Collection

### ISSUE THREAD

**Issue by raphagibello** [octokit/octokit.net#2179]
Hello,

I'm trying to get some code to check for all repos in my organization for the option "Allow GitHub to perform read-only analysis of this repository" However I could not find in the docs or the go to definitions for that option and failed to find it. 

The option is this one: https://help.github.com/en/github/understanding-how-github-uses-and-protects-your-data/opting-into-or-out-of-data-use-for-your-private-repository

Is there any way to do this by using octokit or will I need to use selenium for a bot to activate it.

Thank you,

**Comment by shiftkey** [comment]
@raphagibello I don't believe this is currently available through the GitHub API.

Generally these sorts of features are exposed as a [preview API](https://developer.github.com/v3/previews/) first, so until that is available there's not much we can do from the Octokit side.
