### ISSUE TITLE
Releases returns empty on private repository

### ISSUE THREAD

**Issue by FelicePollano** [octokit/octokit.net#2190]
I'm using the following code to retreve releases from a repo:

```c#
client.Credentials = new Credentials(this.credentials.User,credentialService.DecodePwd(
                                                this.credentials.EncryptedPassword,
                                                this.credentials.Name
                                                ));

var all = await client.Repository.Release.GetAll(repoid);
```
but the returned list is empty. Repository id is correct ( It works for other apis ), code works if I pass the repository owner and name for a public repository, does not for mine.

**Comment by shiftkey** [comment]
@FelicePollano does the API work as expected if you pass the owner and name for the private repository?

**Comment by FelicePollano** [comment]
Unfortunately not, I have to say that the owner is an organization, don't know if it makes any difference

**Comment by shiftkey** [comment]
There's this caveat about [this API](https://developer.github.com/v3/repos/releases/#list-releases-for-a-repository) documented on GitHub:

> Information about published releases are available to everyone. Only users with push access will receive listings for draft releases.

Could that be relevant to what you're seeing?

**Comment by shiftkey** [comment]
Also note that tags may be listed in the Releases page for the repository, but they are not necessarily considered a release.

**Comment by FelicePollano** [comment]
Well I can see that I have releases in the github page by using the same user, I will try with the tags api instead...

**Comment by FelicePollano** [comment]
OPs, a separate tags api apparently does not exist in octokit, am I wrong?

**Comment by FelicePollano** [comment]
yes I'm wrong :)

**Comment by FelicePollano** [comment]
I can confirm, Tags works, ( and it is a good workaround for me ) for releases, I dont't really know if the problem is the caveat, should not because I can see on the page the releases, but I don't understand really.

**Comment by shiftkey** [comment]
For reference:

```c#
var all = await client.Repository.GetAllTags(repoid);
```

> I dont't really know if the problem is the caveat, should not because I can see on the page the releases, but I don't understand really.

I believe this is a historical thing on the website because of this workflow:

 - someone pushes a tag to the repository, and now wants to create the corresponding release
 - they go to the releases tab, and see the new tag alongside the current release
 - they click the tag, fill in the additional details for the release, and publish 

It saved having to go somewhere else to do this, but does introduce the "is a tag a release?" source of confusion in the UI.

Anyway, closing this out as resolved.

**Comment by FelicePollano** [comment]
Thanks!
