### ISSUE TITLE
Null SHA for NewTreeItem not allowed when it should be

### ISSUE THREAD

**Issue by Merlin04** [octokit/octokit.net#2191]
On the page https://developer.github.com/v3/git/trees/, it says under the parameter `sha`:

> The SHA1 checksum ID of the object in the tree. Also called tree.sha. If the value is null then the file will be deleted. 

However, when I set this to `null`, like this:

```csharp
NewTree newTree = new NewTree
{
    BaseTree = currentTreeSha
};
newTree.Tree.Add(new NewTreeItem
{
    Mode = "100644",
    Type = TreeType.Blob,
    Sha = null,
    Path = "testDeleteFile.txt"
});
await github.Git.Tree.Create(repoId, newTree);
```

I get an exception:

>  Octokit.ApiValidationException: Must supply tree.sha or tree.content

**Comment by chap-dr** [comment]
I'm sure you figured this out already, but just for anyone else finding this issue in search of a solution as to why they are unable to delete things, i found this issue: https://github.com/octokit/octokit.net/issues/1610 which was the fix for my problem at least..

**Comment by Sebu** [comment]
I have the same issue. Looking at the network traffic. neither sha not content are send. My guess v3 expects atually `"sha" : null` in the json of request but the .net implementation is likely omitting `null` properties.
