### ISSUE TITLE
CheckRun does not contain requested_action field

### ISSUE THREAD

**Issue by mitchdenny** [octokit/octokit.net#2195]
The following documentation on Webhook even payloads documents the ```requested_action``` field:

https://developer.github.com/webhooks/event-payloads/#check_run

However the ```Octokit.CheckRun``` type does not appear to expose this value. Is this just a missing feature (PR accepted?) or is it not there for a reason?

**Comment by shiftkey** [comment]
>  Is this just a missing feature (PR accepted?) or is it not there for a reason?

Likely an oversight. I can't think of a reason for excluding it.

**Comment by mitchdenny** [comment]
No worries. Submitted a PR to add it in!
