### ISSUE TITLE
Pinning an issue?

### ISSUE THREAD

**Issue by SeanKilleen** [octokit/octokit.net#2205]
I wasn't sure if Octokit (or indeed, the GitHub API) supports pinning issues.

I couldn't find any reference on how to accomplish a pinned issue via the API or Octokit.

Could someone please confirm whether this is possible? If it's possible but not a part of Octokit, I'd be interested in doing a PR for it.

**Comment by SeanKilleen** [comment]
Thanks for providing those reference points 👍 Feel free to close or label accordingly.

**Comment by shiftkey** [comment]
For the moment I'm going to close this out, but if this does appear as a preview API we can reopen it.
