### ISSUE TITLE
403 Access Forbidden 

### ISSUE THREAD

**Issue by shravan-prajapati** [octokit/octokit.net#2211]
I am trying to download Zip file from git hub repository.

I always get 403, but postman It is working and  get 302 and Location url for download.

var zipUri = $"https://api.github.com/repos/xyz/{repo}/zipball";
WebClient client = new WebClient();
                client.Headers.Add("Authorization", "bearer *****************************");
                client.Headers.Add("Accept", "*/*");
                client.Headers.Add("Accept-Encoding", "gzip, deflate, br");
                client.DownloadFile(zipUri, outputFileName);

Please suggest.

**Comment by shiftkey** [comment]
You need to specify a User-Agent header to interact with the GitHub API: https://developer.github.com/v3/#user-agent-required

**Comment by shravan-prajapati** [comment]
Hi It is Working with adding User-Agent.

client.Headers.Add("User-Agent", "Awesome-Octocat-App");

Thank you very much.
