### ISSUE TITLE
GET /user/issues returns empty collection unexpectedly

### ISSUE THREAD

**Issue by shiftkey** [octokit/octokit.net#222]
http://developer.github.com/v3/issues/#list-issues

We have a test here which is failing:

```
[IntegrationTest]
public async Task ReturnsAllIssuesForOwnedAndMemberRepositories()
{
    var newIssue = new NewIssue("Integration test issue");
    await _client.Create(_createdRepository.Owner.Login, _repoName, newIssue);
    var result = await _client.GetAllForOwnedAndMemberRepositories().ToList();

    Assert.NotEmpty(result);
}
```

I've logged the request ids here and scrubbed the other details - I'll do some digging in the morning cc @pengwynn 

**Creating a repository**

`POST /user/repos HTTP/1.1`
returns 
```
HTTP/1.1 201 Created
X-GitHub-Request-Id: 48B3241C:071D:29A25F:52844661
```

**Adding an issue**
`POST /repos/shiftkey-tester/public-repo-20131114034120284/issues HTTP/1.1`
returns
```
HTTP/1.1 201 Created
X-GitHub-Request-Id: 48B3241C:071D:29C855:52844681
```

**Querying for it**

```
GET /user/issues?filter=assigned&state=open&sort=created&direction=desc HTTP/1.1
```
returns
```
HTTP/1.1 200 OK
Content-Length: 2 // lol
X-GitHub-Request-Id: 48B3241C:071D:29C8E1:52844682
```

**Querying against the repository directly**

```
GET /repos/shiftkey-tester/public-repo-20131114034120284/issues HTTP/1.1
```
returns 
```
HTTP/1.1 200 OK
Content-Length: 1831
X-GitHub-Request-Id: 48B3241C:1D79:BA62D:52844712
```

**Comment by shiftkey** [comment]
Oh, this was fixed a long long time ago.

**Comment by nerocui** [comment]
I'm getting this bug with both the SDK and the raw API
My GitHub page
![image](https://user-images.githubusercontent.com/10738280/229476851-03b26864-c9ec-4b46-b9dc-eb836fa08072.png)

API returns empty
<img width="807" alt="image" src="https://user-images.githubusercontent.com/10738280/229477597-8921f36f-7551-4050-8e04-72a692030f65.png">

SDK returns empty
<img width="620" alt="image" src="https://user-images.githubusercontent.com/10738280/229477874-c4310cfa-3c9c-49a3-a8fa-e9e1e3ca9a1b.png">
