### ISSUE TITLE
Personal token :must have admin right

### ISSUE THREAD

**Issue by akanksha234** [octokit/octokit.net#2226]
Hi, I am trying to delete a repo created through API with a personal token which has the authority to delete the repo.

Although my user can do this through UI, and my account is the basic/standard account.

Why am I still getting this error?                   
![image](https://user-images.githubusercontent.com/11677994/88221063-886e5100-cc81-11ea-87b9-b857b78b9c10.png)

**Comment by akanksha234** [comment]
![image](https://user-images.githubusercontent.com/11677994/88221256-d420fa80-cc81-11ea-8e08-dd345a83a247.png)
delete repo is checked.

**Comment by shiftkey** [comment]
@akanksha234 please contact GitHub support, as this project is specific to the .NET client for Octokit: https://support.github.com/
