### ISSUE TITLE
How can I create a issue to specific repository with body, labels and title

### ISSUE THREAD

**Issue by christianrd** [octokit/octokit.net#2232]
I want to implements a bug report form on a website where any user can create issue without the github user. 

I have body (Markdown), title and 2 tags (created in existing repository).

I don't know how I can add the body, tags and title.

I think we need to create more examples like this ...

[octokit documentation: create issues](https://octokitnet.readthedocs.io/en/latest/issues/)

**Comment by shiftkey** [comment]
```C#
var client = new GitHubClient(....);
var createIssue = new NewIssue("title for issue");
createIssue.Body = "body for issue";
createIssue.Labels.Add("first");
createIssue.Labels.Add("Second");
var issue = await client.Issue.Create(owner, name, createIssue);
```
