### ISSUE TITLE
Issue active_lock_reason missing

### ISSUE THREAD

**Issue by broccolihighkicks** [octokit/octokit.net#2248]
Hello,

I am trying to get the value of

- `active_lock_reason` JSON 
- `activeLockReason` GraphQL

on the issue object.

Ive searched the C# source code but I do not think this property is accessible?

**Comment by shiftkey** [comment]
It seems like this hasn't been added to the API, both for `Issue` and `PullRequest` responses. 

Marking this as `up-for-grabs` in case someone wants to have a go at adding support.

**Comment by notauserx** [comment]
I would like to help out on this issue.
