### ISSUE TITLE
Support for GitHub Discussions

### ISSUE THREAD

**Issue by tomkerkhove** [octokit/octokit.net#2254]
Are there plans to provide support for GitHub Discussions? I'd love to use this to automate issue management to steer them to GitHub Discussions by locking issue and automatically creating related GitHub Discussion.

**Comment by shiftkey** [comment]
@tomkerkhove until there's a preview API announced from the team we can't support it in this project

**Comment by tomkerkhove** [comment]
Ha, I thought there was one already - Sorry!

I'll check when it's coming and circle back.

**Comment by tomkerkhove** [comment]
API is in preview: https://github.blog/changelog/2021-02-23-github-discussions-graphql-api-public-beta/

**Comment by tomkerkhove** [comment]
Any plans for this?

**Comment by shiftkey** [comment]
@tomkerkhove that's the GraphQL version. 

This library is for the REST API, and there's a sibling project for the GraphQL API in .NET here: https://github.com/octokit/octokit.graphql.net

Unless this becomes available as a REST endpoint, I can't see this becoming supported.

**Comment by brandonh-msft** [comment]
GH doesn't plan to put Discussions on the REST API - GraphQL is the path forward, apparently?
