### ISSUE TITLE
It does not look like this is possible right now: https://stackoverflow.com/q/59828577/206879

### ISSUE THREAD

**Issue by cecelias35** [octokit/octokit.net#2255]
It does not look like this is possible right now: https://stackoverflow.com/q/59828577/206879

_Originally posted by @gr2m in https://github.com/octokit/core.js/pull/32#issuecomment-576408646_

**Comment by shiftkey** [comment]
@cecelias35 this project is for the Octokit .net client, not the JavaScript client.

Closing this out as unrelated.
