### ISSUE TITLE
[META] Version 1.0.0?

### ISSUE THREAD

**Issue by Cyberboss** [octokit/octokit.net#2257]
Thanks for all the hard work you guys put into this project. My only concern is the continued use of major version 0.X.Y. I had to recently update an app from around 0.29.0 or so and had to clean up several breaking changes.

Are there any plans/targets to hit before a 1.0.0 version is cut? If not, I'd recommend going forward with it. Given how widely used this library is, just having proper [semver](https://semver.org) would be useful.

**Comment by IvanJosipovic** [comment]
This client is falling so far behind, I'd like to see a road map or something...

**Comment by shiftkey** [comment]
At the moment I have no bandwidth to catch up to what's currently supported as part of the v3 API. I did some analysis of the `octokit/routes` repository months ago to generate stats against the current release , that are hosted at https://octokit-status.shiftkey.dev/. That says we're at 56%, which wasn't unexpected.

I'd love to go back and explore generating the client code so this is no longer a manual process, but I haven't done .NET in my day-to-day work at GitHub for many years now. Even just handling the review pile on this project continues to get bumped down my priority queue by other urgent work.

Historically we get requests for preview API support as soon as features are available (e.g. Discussions #2254), and these new APIs are subject to change while in preview, so breaking changes may still be needed - so I'm not sure how to mesh with that aside from bumping the major version each time breaking changes are needed.

**Comment by IvanJosipovic** [comment]
Can you ask internally for additional help to maintain this repo? What about Microsoft?
If GitHub is not willing to allocate resources to keep this project going, you should make it clear and archive this repository.

**Comment by JonruAlveus** [comment]
@Cyberboss We’ve just hit v1 with a breaking change. I can’t say what’s going to happen in the future but it’s looking like semver had arrived!

**Comment by nickfloyd** [comment]
@IvanJosipovic we just posted an announcement on where we are and where we are headed:  https://github.com/octokit/octokit.net/discussions/2499 | please let us know if you have any questions or thoughts - we'd love to hear them.

**Comment by nickfloyd** [comment]
I am going to close this issue, but if you feel that your original question has not been answered or if there is more discussion needed here please feel free to reopen so that we can continue the discussion.
