### ISSUE TITLE
unsubscribe from issue

### ISSUE THREAD

**Issue by adamralph** [octokit/octokit.net#2262]
If I have a reference to an issue, can I use Octokit to unsubscribe from the issue?

**Comment by adamralph** [comment]
BTW, I wasn't lazy here. I spent quite some time digging through the API but I just couldn't find it. 🙂

**Comment by shiftkey** [comment]
I don't recall offhand how to correlate it to an issue, but what you want is the `Delete thread subscription` endpoint: https://docs.github.com/en/rest/reference/activity#delete-a-thread-subscription
