### ISSUE TITLE
NullReferenceException on retrieving forks 

### ISSUE THREAD

**Issue by sgmoore** [octokit/octokit.net#2265]
The following simple LinqPad script throws a NullException.
 
```
async Task Main(string[] args)
{
    var client = new GitHubClient(new Octokit.ProductHeaderValue("octokit.samples"));

    var forks = await client.Repository.Forks.GetAll("SamuelTulach", "VirusTotalUploader"); // throws NullReferenceException

    forks.Dump();
}
```

 This seems to occur because one of the forks has null for Owner (which Octokit copes with) and null for Archived which is what triggers this exception.

A simple workaround would be to change 

`public bool Archived { get; protected set; }
`

to

`public bool? Archived { get; protected set; }`

in the Repository.cs class (ie  ..\Models\Response\Repository.cs)

However, I am not sure whether that is the correct thing to do, or whether the offending fork should be excluded from the list altogether.

**Comment by shiftkey** [comment]
@sgmoore is this still occurring for you? I had a look at the raw JSON and I see all `archived: false` being returned, so I suspect this was just a bug with the actual API that's now been fixed.

Please let me know if you're still seeing this and I can dig into it further.

**Comment by sgmoore** [comment]
No, the exception is no longer being thrown. 
Unfortunately I didn't keep a note of which repo caused the problem.

Not sure what the deal is with https://github.com/RLlane2126/VirusTotalUploader, but this isn't causing me a problem.
