### ISSUE TITLE
LFS Batch API

### ISSUE THREAD

**Issue by github-dcl** [octokit/octokit.net#2273]
Is there support for LFS and the Batch Api at this point? I cannot locate it in the tests.

**Comment by shiftkey** [comment]
Unless it is documented in https://docs.github.com/en/rest or an upcoming preview https://docs.github.com/en/free-pro-team@latest/rest/overview/api-previews then we are unable to support it

**Comment by shiftkey** [comment]
Closing this out as I don't wish to track feature requests in this repository
