### ISSUE TITLE
How to delete a branch?

### ISSUE THREAD

**Issue by Jericho** [octokit/octokit.net#2281]
What is (are) the octokit.net call(s) necessary to reproduce the behavior of the `Delete Branch` button ?

![image](https://user-images.githubusercontent.com/112710/103157983-f534cc80-4786-11eb-8665-b78fb5331f16.png)

I'm working on a tool that will loop through all the branches in a given repo, check if there's an associated PR, determine if the PR has been merged and if so, delete the branch. There are several dozens such branches so it makes sense to automate this task.

**Comment by adamralph** [comment]
I'm also trying to do exactly this.

**Comment by adamralph** [comment]
FWIW, if I try and do:

```c#
await client.Git.Reference.Delete(repo.Id, branch.Name);
```

I get:

> Octokit.ApiValidationException: 'Reference does not exist'

😕

**Comment by shiftkey** [comment]
The Git references client supports removing references, not just branches, so there's some nuances here that I tried to capture in the docs:

https://github.com/octokit/octokit.net/blob/9e2618f6d1af590d1911bf6abeaa9425c5954c69/Octokit/Clients/ReferencesClient.cs#L345-L350

**Comment by shiftkey** [comment]
Something like this should do the trick:

```c#
await client.Git.Reference.Delete(repo.Id, $"heads/{branch.Name}");
```

I thought there was a high-level "delete branch" API but I couldn't spot it in the API docs...

**Comment by Jericho** [comment]
I had tried this already but it didn't seem to work:

```csharp
await client.Git.Reference.Delete(repo.Id, branch.Name);
```

I added the `heads/` prefix like in your sample and it now seems to be working as expected. Thanks for the tip.

**Comment by adamralph** [comment]
Thanks @shiftkey, that works for me!
