### ISSUE TITLE
Autogenerated issues not work (Not Found exception)

### ISSUE THREAD

**Issue by hoplik** [octokit/octokit.net#2282]
I can't overcome the Octokit library (0.48 for Visual Studio 2019) with interaction with the GitHub API. I make a test application, on the form one text field, one button to send the typed text. Returns the error: "Not found". What was not found is unclear. It seems that everything is done on the docks. The application without authorization is made on purpose, because the message can be sent by any user of the program, even unregistered on GitHub. The limit of 60 messages per hour is fine.

`
using System;
using System.Threading.Tasks;
using System.Windows.Forms;
using Octokit;

namespace WindowsFormsApp1
{
public partial class Form1 : Form
{
public Form1()
{
InitializeComponent();
}

    private void Button1_Click(object sender, EventArgs e)
    {
        _ = CreateGitHubIssue(textBox1.Text);
    }
    async static Task CreateGitHubIssue(string sent_issue)
    {
        try
        {
            GitHubClient client = new GitHubClient(new ProductHeaderValue("WindowsFormsApp1"));
            var createIssue1 = new NewIssue("Пожалуйста, исправьте ошибку")
            {
                Body = "Это автоматически сгенерированное сообщение. " + Environment.NewLine + sent_issue,
            };
            _ = await client.Issue.Create(owner: "hoplik", name: "Firehose-Finder", createIssue1);
        }
        catch (Exception ex)
        {
            MessageBox.Show(ex.Message);
        }
        MessageBox.Show("Отправили");
    }
}
}
`

![photo_2021-01-09_13-30-31](https://user-images.githubusercontent.com/60131631/104090518-5761f700-5288-11eb-97ce-34742d6555be.jpg)

**Comment by shiftkey** [comment]
> The application without authorization is made on purpose, because the message can be sent by any user of the program, even unregistered on GitHub. 

You need to authenticate the client to create issues against the GitHub API, as these need to be associated with a GitHub account.

> The limit of 60 messages per hour is fine.

This is 60 requests per hour.
