### ISSUE TITLE
Cannot create gist.

### ISSUE THREAD

**Issue by mr5z** [octokit/octokit.net#2283]
I'm trying to use this library to manage gist but got stuck at creating a simple gist.

Authentication part is already done.

I'm calling the API as below:

```cs
var result = await client.Gist.Create(new NewGist
{
    Files =
    {
        [gist.Name] = gist.Content
    },
    Description = gist.Description
});
```
Using the scopes: `user`, `repo`, `gist`

The returned error message was:

```js
{"message":"Resource not accessible by integration","documentation_url":"https://docs.github.com/rest/reference/gists#create-a-gist"}
```

And bot's enabled permissions:
![image](https://user-images.githubusercontent.com/6318395/104140061-6d87c880-53ea-11eb-8b2a-f9836acf7856.png)

It's probably due to the bot's permission, if so does anyone know which permissions to enable on GitHub Bots to manage gist? I can't seem to find any documentation regarding with this topic.

**Comment by mr5z** [comment]
Update: Tried to enable all possible permission, still getting same result. Completely lost where to go next.

**Comment by shiftkey** [comment]
GitHub Apps are only allowed to access these resources for a user, and Gists are not supported: https://docs.github.com/en/rest/reference/permissions-required-for-github-apps

Only OAuth apps are allowed to create Gists on behalf of a user, which is mentioned here https://docs.github.com/en/rest/reference/gists#authentication

As this is not something that Octokit can address, I'm going to close this out.

**Comment by mr5z** [comment]
@shiftkey Thanks for the reply! I missed that info.
