### ISSUE TITLE
Unable to use Repository functions | "RepositoryContentsClient.cs not found"

### ISSUE THREAD

**Issue by LeapsofFaith** [octokit/octokit.net#2287]
I'm trying to use octokit to programmatically view the information of the files in my own private repository, however no matter what I've tried the code always comes back with some form of "RepositoriesClient,cs not found" or "RepositoryContentsClient.cs not found". The error started when I reverted to a stashed copy of my files that had a working version of the package being used. The call that returns these errors are, respectively, `Repository repo = await client.Repository.Get(string owner, string name);` and `var binContents = await client.Repository.Content.GetAllContents(string owner, string name, string path);` (with client set as `var client = new GitHubClient(productInformation) { Credentials = credentials };`).
I have tried reinstalling the nuget package, clearing the cache, and searching for the files manually, however none of these have helped me get past these issues.

**Comment by shiftkey** [comment]
@LeapsofFaith there's not enough information here for me to understand the issue at hand.

Here's what would be great to investigate further:

 - as much details about the error you're seeing
 - a runnable sample project, that indicated what version of .NET you're using
