### ISSUE TITLE
Octokit should support Device Flow authentication (in C#)

### ISSUE THREAD

**Issue by palenshus** [octokit/octokit.net#2308]
Request for support of this flow: https://docs.github.com/en/developers/apps/authorizing-oauth-apps#device-flow

This is a big gap in the authentication functionality in Octokit. Currently we have to create all the REST calls and response objects ourselves which is a ton of boilerplate code that it would be nice to have abstracted away into the library, like it would if we were using the "web application flow."

I'd be happy to help with the implementation, as we already have it working in our app

**Comment by shiftkey** [comment]
@palenshus this flow is new to me, so I'd be open to reviewing contributions that add in this support if you're willing

**Comment by palenshus** [comment]
Sweet, I took a stab at it with the above PR. The calling pattern is different than for the web flow, so I wasn't sure exactly how to structure it. I settled on two new APIs, InitiateDeviceFlow, and CreateAccessTokenForDeviceFlow, which takes the response from InitiateDeviceFlow as an argument. Let me know what you think, thanks!

**Comment by palenshus** [comment]
@shiftkey , could you take a look? Thanks!

**Comment by dbalikhin** [comment]
Any updates? It looks like a very nice feature.
@shiftkey :point_up_2:

@palenshus Can you please try to make another commit / merge to rebuild it again?

**Comment by palenshus** [comment]
Good idea, done

**Comment by palenshus** [comment]
It's in!
