### ISSUE TITLE
Basic authentication not working

### ISSUE THREAD

**Issue by DrLeh** [octokit/octokit.net#2317]
I'm trying to run the following code to read data about private repos in my account, but the following code gives an error:

> Unhandled exception. Octokit.AuthorizationException: Requires authentication
```C#
var basicAuth = new Credentials("DrLeh", "<my password>", AuthenticationType.Basic);
var client = new GitHubClient(new ProductHeaderValue("GitScraper"))
{
    Credentials = basicAuth
};
var res = await client.Repository.GetAllForCurrent();
```

I didn't see anything in the [getting started](https://github.com/octokit/octokit.net/blob/main/docs/getting-started.md) mentioning anything more I need for this to work.

I do not have two factor authentication on my account, nor any other setting that I can tell might limit my API access for this login to not work. This is not going to be a production app, it's just a utility for me to quickly gather data about my repos, so I'd prefer to not have to set up a whole OAuth flow to do this. What am I missing?

**Comment by DrLeh** [comment]
I tried making a direct request via HttpClient and I got an error about it being forbidden because of admin rules, so sounds like it's an org setting forbidding this. Octokit just doesn't report it.

**Comment by alexandvvvvv** [comment]
I am having exactly the same issue

**Comment by shiftkey** [comment]
Basic Authentication with username/password using the GitHub API was deprecated back in November 2019:

https://docs.github.com/en/rest/overview/other-authentication-methods#via-username-and-password

Please create and use a Personal Access Token in place of your account password:

https://docs.github.com/en/rest/overview/other-authentication-methods#via-oauth-and-personal-access-tokens

**Comment by flcdrg** [comment]
@shiftkey Should the docs be updated to remove basic auth examples? https://octokitnet.readthedocs.io/en/latest/getting-started/
