### ISSUE TITLE
GetAllTopics on RepositoryClient is not available in v0.50

### ISSUE THREAD

**Issue by JustinGol** [octokit/octokit.net#2328]
@SeanKilleen, not sure Im missing something but I cant find the new method GetAllTopics on the RepositoryClient. Im using v0.50, double checked and decomplied. I saw in the release the commit for this is included. I can see it in the integration tests too so not sure whats happening. TIA

![image](https://user-images.githubusercontent.com/42610502/119305809-93807c00-bcac-11eb-9418-b8c213301b9e.png)
![image](https://user-images.githubusercontent.com/42610502/119305865-a72be280-bcac-11eb-8611-dc8aa5cdc1ca.png)

_Originally posted by @JustinGol in https://github.com/octokit/octokit.net/issues/1707#issuecomment-846786635_

**Comment by SeanKilleen** [comment]
@JustinGol do you have a code sample that isn't working? Are you using another part of the library with success or is this a new effort? Asking so I can keep that in mind as I look into this. (Not back at a computer yet to check).

**Comment by SeanKilleen** [comment]
Well @JustinGol I have good news and bad news. 😆 

The good news is, you're not wrong -- it is indeed in the integration tests and was merged in.

The bad news is, you're not seeing it in the wild because it's not yet been released. 

* #2246 was merged on Feb 25th.
* However, [the last release, v0.50](https://github.com/octokit/octokit.net/releases/tag/v0.50.0), was pushed out on Feb 21. 

I assumed it would be available by now but there hasn't been an additional release yet. I look forward to seeing it out there as well.

You can subscribe to releases by:

* Selecting "custom" under notifications:

> ![the notifications dropdown, showing a custom notification option](https://user-images.githubusercontent.com/2148318/119424809-2b459080-bcd4-11eb-917f-23bae5ab5dd0.png)

* And checking the box for releases:

> ![the custom notifications screen with the releases box checked](https://user-images.githubusercontent.com/2148318/119424856-44e6d800-bcd4-11eb-9ce8-f2a8cee5211b.png)


CC @shiftkey @ryangribble in case they'd like to take a whack at a release to get it out there. (if I can help, let me know.)

**Comment by SeanKilleen** [comment]
@JustinGol see my comment above and, if you agree, go ahead and close this issue. Thanks!

**Comment by JustinGol** [comment]
When I checked the release commits it was there, so not sure how that ended up like that.
![image](https://user-images.githubusercontent.com/42610502/119442694-a60dba80-bd6b-11eb-9499-c6525ec1e84c.png)

![image](https://user-images.githubusercontent.com/42610502/119442623-8b3b4600-bd6b-11eb-80eb-9d6c69b31bc0.png)

**Comment by JustinGol** [comment]
> Well @JustinGol I have good news and bad news. 😆
> 
> The good news is, you're not wrong -- it is indeed in the integration tests and was merged in.
> 
> The bad news is, you're not seeing it in the wild because it's not yet been released.
> 
> * #2246 was merged on Feb 25th.
> * However, [the last release, v0.50](https://github.com/octokit/octokit.net/releases/tag/v0.50.0), was pushed out on Feb 21.
> 
> I assumed it would be available by now but there hasn't been an additional release yet. I look forward to seeing it out there as well.
> 
> You can subscribe to releases by:
> 
> * Selecting "custom" under Watch:
> 
> > ![the notifications dropdown, showing a custom notification option](https://user-images.githubusercontent.com/2148318/119424809-2b459080-bcd4-11eb-917f-23bae5ab5dd0.png)
> 
> * And checking the box for releases:
> 
> > ![the custom notifications screen with the releases box checked](https://user-images.githubusercontent.com/2148318/119424856-44e6d800-bcd4-11eb-9ce8-f2a8cee5211b.png)
> 
> CC @shiftkey @ryangribble in case they'd like to take a whack at a release to get it out there. (if I can help, let me know.)

@SeanKilleen  Thanks for looking into this and for the detailed and quick reply.

**Comment by SeanKilleen** [comment]
@JustinGol in the view you showed in the screenshot, you were showing all the commits _since_ v0.50.0, because it was comparing against master. I think that's where the confusion came in.

But I'm glad someone else is looking to use the contribution! :)

**Comment by JustinGol** [comment]
> @JustinGol in the view you showed in the screenshot, you were showing all the commits _since_ v0.50.0, because it was comparing against master. I think that's where the confusion came in.
> 
> But I'm glad someone else is looking to use the contribution! :)

It would help if I actually read what came after the 8 commits, sorry for wasting your time. I searched the repo as well as I thought v0.50 had the latest master changes too. @SeanKilleen, appreciate your help with this, very keen to use this feature. I have almost 100 repo's I want to use this for and we want to leverage it for a tool in Slack we built for creating a new repo.

**Comment by Brend-Smits** [comment]
I actually stumbled on this issue because I thought this was already released. Is there any release planned?

**Comment by SeanKilleen** [comment]
I think @shiftkey may have been busy [building the future of GitHub](https://twitter.com/shiftkey/status/1407732284963311618?s=20) for a minute :) 

Brendan, these changes were merged Feb 25th, so just barely missed the Feb 21st release.

Is there a next planned release? Is there any way I could support that endeavor? I'm happy to onboard into that process if you would find it useful.
