### ISSUE TITLE
Get/Create/Update Environments

### ISSUE THREAD

**Issue by flcdrg** [octokit/octokit.net#2329]
I'd like to see support added for environments - https://docs.github.com/en/rest/reference/repos#environments

**Comment by semyon-p** [comment]
Hey! I've added Environments list Get feature.
How can I send a pull request?

**Comment by kfcampbell** [comment]
@semyon-p if you've forked the project and created the feature on your fork, you can find instructions on opening a PR [here](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork). If you haven't forked the repo yet, that's a good first step!

**Comment by semyon-p** [comment]
Thank you!
Created PR: https://github.com/octokit/octokit.net/pull/2613

**Comment by nickfloyd** [comment]
This has been fixed and merged  in: https://github.com/octokit/octokit.net/pull/2613

**Comment by danielshendfs** [comment]
Thanks a lot for the Get environment feature, is there any plan to add Create as well?

**Comment by mikebollandajw** [comment]
also looking to default setup environments
