### ISSUE TITLE
Value 'changes_requested' is not a valid 'PullRequestReviewState' enum value.

### ISSUE THREAD

**Issue by ch1seL** [octokit/octokit.net#2337]
I've tried to deserialize PullRequestReviewEventPayload and faced with this error:
```
System.ArgumentException: Value 'changes_requested' is not a valid 'PullRequestReviewState' enum value.
  File "/home/runner/work/octokit.net/octokit.net/Octokit/Models/Response/StringEnum.cs", line 146, col 17, in TEnum StringEnum<TEnum>.ParseValue()
  File "/home/runner/work/octokit.net/octokit.net/Octokit/Models/Response/StringEnum.cs", line 45, col 19, in TEnum StringEnum<TEnum>.get_Value()
```

I think there is a little problem with `review.state` value.
In Rest API is in uppercase: https://docs.github.com/en/rest/reference/pulls#list-reviews-for-a-pull-request--code-samples
In Webhooks events is in lowercase: https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#webhook-payload-example-33

Suggested solution:
Ignore case for the value of ParameterAttribute of PullRequestReviewState

**Comment by shiftkey** [comment]
Webhook support has never been a priority for this, and https://github.com/octokit/octokit.net/issues/407 was an early request to support this:

https://github.com/octokit/octokit.net/blob/356588288e2d07fb4844911f6e03ef129540b124/Octokit/Models/Response/PullRequestReview.cs#L88-L104

Not sure when this will get fixed, and I'm not sure if we can adapt that parsing to ignore the casing of a match (`StringEnum<T>` was designed for relaxed parsing, and [the docs](https://github.com/octokit/octokit.net/blob/356588288e2d07fb4844911f6e03ef129540b124/docs/working-with-enums.md#stringenumtenum-usage) explain more about why it's there).
