### ISSUE TITLE
"Draft" state missing from "MergeableState" enum

### ISSUE THREAD

**Issue by adtakle** [octokit/octokit.net#2339]
We're receiving a payload from a GitHub webhook with `"mergeable_state": "draft"` when a PR is marked as a draft. We're seeing an error when deserializing the JSON payload using the Octokit `MergeableState` enum:
`System.ArgumentException: Value 'draft' is not a valid 'MergeableState' enum value.`

I think the fix should just be to add `draft` as an enum value here: [MergeableState enum](https://github.com/octokit/octokit.net/blob/e9fbe84657976326c8caed7289c0150e38c8adea/Octokit/Models/Response/PullRequest.cs#L263)

**Comment by omelianlevkovych** [comment]
Hi, Is it still relevant?
Can I try to prepare PR to fix it (as my first contribution)?

**Comment by adtakle** [comment]
@omelianlevkovych yes, this is still relevant

**Comment by omelianlevkovych** [comment]
Okay, I will try to prepare PR this/next week. Thanks
