### ISSUE TITLE
Swift Language is missing

### ISSUE THREAD

**Issue by p-brito** [octokit/octokit.net#2341]
SearchRepositoriesRequest.Language does not have Swift. @mislav @anaisbetts  @zeke @mislav @zerowidth Can you please add this language, it's a quick fix I think.

**Comment by p-brito** [comment]
@shiftkey I think this is a quick fix, can you handle it?

**Comment by shiftkey** [comment]
@p-brito please don't at-mention a whole bunch of people - some of whom no longer work at GitHub, none of whom are previous contributors to this project - and ask them to do this work.

I've merged #2344, so this will go out with the next release.

**Comment by p-brito** [comment]
Thank you @shiftkey! Sry for tagging a lot of people.
