### ISSUE TITLE
GitHub IDs have exceeded Int32.MaxValue; Octokit uses int

### ISSUE THREAD

**Issue by SeanKilleen** [octokit/octokit.net#2351]
Spotted in this tweet from @patriksvensson: https://twitter.com/firstdrafthell/status/1429738272574558210?s=19

I'll look into this ASAP but don't mind anyone else doing the same.

**Comment by shiftkey** [comment]
An example PR where we've had to fix this in the past: https://github.com/octokit/octokit.net/pull/1703

Happy to push out a release asap about it if you have a fix.

**Comment by shiftkey** [comment]
@patriksvensson got a sample script that helps us to know where it's overflowing?

**Comment by SeanKilleen** [comment]
For those following along, I am using the following regex search in VS to attempt to find int Ids and knocking them out:

`int [^=]*Id`

**Comment by SeanKilleen** [comment]
@shiftkey I'm not quite sure how the songs are chosen for releases, but this one seems like "For the Long-est Time" would be appropriate.

**Comment by shiftkey** [comment]
Release titles are chosen mostly at random. I endorse this name for the one that fixes this.

**Comment by patriksvensson** [comment]
@shiftkey I don't have a sample script, but encountered this when retrieving notifications.

**Comment by SeanKilleen** [comment]
@patriksvensson question as I go through this: 

You mention that you were having issues when retrieving notifications. It looks like, in a strange turn of events, the API is actually returning the notification ID as a string (and Octokit .NET is complying with that). Thread IDs are integers, but Octokit is currently compliant with that as well.

Are you by any chance casting it to an integer on your end?

The rest of this is still worth addressing, but I wanted to point out that it may not resolve your particular issue.

**Comment by nwf** [comment]
Is there any progress on resolving this?  #2352 appears stalled, but, sadly, this is stymieing any use of octokit.net for handling `workflow_job` events, because the `id` field therein is expressed as a JSON number, not a string, and they are far above 2**32 at this point.
