### ISSUE TITLE
SearchCodeApi show error : Only the first 1000 search results are available

### ISSUE THREAD

**Issue by CancanTang** [octokit/octokit.net#2354]
i want to search more results by SearchCode API . 
For example : search code by key words "net6.0" , it just return 1000 results , but i want to get more than 1000 , May be 10,000 results 
how can i do?

![image](https://user-images.githubusercontent.com/50062380/131452832-fbad01a1-3687-4e90-8417-6c6c7dc1c5f8.png)

**Comment by zgenov** [comment]
This is limitation from GitHub. Check this https://docs.github.com/en/rest/reference/search
