### ISSUE TITLE
Upload to Github releases stopped working

### ISSUE THREAD

**Issue by seebeen** [octokit/octokit.net#2361]
Hello,

We use @semantic-release/github plugin to upload releases to github. This morning, our releases stopped working with the following error.

![image](https://user-images.githubusercontent.com/6689756/134164750-edbcd25b-77eb-42fa-b245-2bbf3aebefcf.png)

Is this something octokit related, or should I direct the issue to semantic-release team.

**Comment by shiftkey** [comment]
Please reach out to the project owners for Semantic Release as a first step.

This is the Octokit C# bindings project, and the JS bindings are handled by a different project. But this may require reaching out to GitHub Support if it doesn't appear to be an intermittent issue.
