### ISSUE TITLE
UpdateFile: Octokit.ApiException: is at xx but expected yy

### ISSUE THREAD

**Issue by rshettybr** [octokit/octokit.net#2365]
I want to create a PR with the few changes on main.

1. Fetch the commitId(sha/reference) on main.
2. Then execute GetAllContentsByRef for the given commitId(reference)
3. Create a new branch against the  main(commitId) using client.Git.Reference.Create
4. Any new changes I have I execute: (For each file : about 20 files)
client.Repository.Content.UpdateFile
where UpdateFileRequest () -> would point to the new branchName(Step 3) and the fileReference Sha which is obtained from Step 2.

Step 4 runs in parallel.
Few files get updated  after which I get:
                               | Octokit.ApiException: is at b9c93a4016dc558ff17122357ff0d92522c6e30a but expected b2d67661f1cf2c1e532bbdb0c9a3ea64a468b3ba
                              |    at Octokit.Connection.HandleErrors(IResponse response) in /actions-runner/_work/octokit.net/octokit.net/Octokit/Http/Connection.cs:line 707
                             |    at Octokit.Connection.RunRequest(IRequest request, CancellationToken cancellationToken) in /actions-runner/_work/octokit.net/octokit.net/Octokit/Http/Connection.cs:line 682
                              |    at Octokit.Connection.Run[T](IRequest request, CancellationToken cancellationToken) in /actions-runner/_work/octokit.net/octokit.net/Octokit/Http/Connection.cs:line 666
                               |    at Octokit.ApiConnection.Put[T](Uri uri, Object data) in /actions-runner/_work/octokit.net/octokit.net/Octokit/Http/ApiConnection.cs:line 400
                               |    at in /all/libs/Roblox.DocumentationToolingCommon/src/Implementation/GitHubClientHelper.cs:line 264
                               | {"message":"is at b9c93a4016dc558ff17122357ff0d92522c6e30a but expected b2d67661f1cf2c1e532bbdb0c9a3ea64a468b3ba","documentation_url":"https://docs.github.com/rest/reference/repos#create-or-update-file-contents"}

How do I go about fixing this. Because I have only 10 to 50 files to update. I have chosen this option. Is this the right way to go about?

Is there a workaround for this?

**Comment by JonruAlveus** [comment]
Hi @rshettybr, sorry for the slow reply. Did you ever find a solution or is this still a problem for you? I wonder if you could share a code sample if possible reproducing the issue?
