### ISSUE TITLE
RepoCollaboratorsClient.Add throws exception with 201 status code (Created)

### ISSUE THREAD

**Issue by marwie** [octokit/octokit.net#2373]
Hello, looks like github changed the return code for adding collaborators

STRP: 
1) check "IsCollaborator"
2) if false call "Add" 
3) observe exception

Using octokit 0.50.0

![image](https://user-images.githubusercontent.com/5083203/142020488-e332a2fd-5130-4d6a-9804-0a6617f16456.png)

**Comment by JonruAlveus** [comment]
@nickfloyd this check is only performed when there is a CollaboratorRequest passed in. This appears to be organisation-owned/enterprise only. Unfortunately I don't have access to test this, do you? RepoCollaboratorsClient.Add methods.

**Comment by nickfloyd** [comment]
@JonruAlveus Thanks for the heads up on this.  I've added it to the board to put some 👀's on it soon to verify and fix.

**Comment by JonruAlveus** [comment]
Hi @marwie, could you confirm if this is still occurring? I can't now reproduce it.
Thanks!
