### ISSUE TITLE
Granting team access for (Enterprise) repositories

### ISSUE THREAD

**Issue by Sam13** [octokit/octokit.net#2374]
Is there a way to add a team with specific access rights to a repository?
I can do this manually in the repository settings -> Collaborators & teams -> Add a team

In the repository client I can add collaborators but I'm not able to add teams.
I can retrieve the list of teams in the repository client.

I'm using Octokit.NET v0.50.0 with GitHub Enterprise Server 3.2.3

**Comment by Jimdandy498** [comment]
add what ever you think

**Comment by Jimdandy498** [comment]
im trying to get connected but says ot of range

**Comment by JonruAlveus** [comment]
Hi @Sam13, sorry for the very slow response! Under the Team client you can assign a repo and change permissions using the AddRepository method.
