### ISSUE TITLE
GetLatest Release takes several minutes

### ISSUE THREAD

**Issue by Codectory** [octokit/octokit.net#2392]
I cannot explain why, but since yesterday, the call "client.repository.Release.GetLatest(...) takes several minutes. The requesttimeout is set to 10 seconds.  Any ideas?

Edit: The strange thing about, when I an exception raises after some minutes, the next call works perfectly.

**Comment by JonruAlveus** [comment]
Hi @Codectory, is this still a problem for you? If so can you share some sample code to help us diagnose the issue?
