### ISSUE TITLE
`seats` and `filled_seats` fields are missed in Plan model

### ISSUE THREAD

**Issue by dmitry-kosar** [octokit/octokit.net#2405]
According to API reference there are `seats` and `filled_seats` fields in Organization response
See https://docs.github.com/en/rest/reference/orgs#get-an-organization--code-samples

But they missed in Plan model
See https://github.com/octokit/octokit.net/blob/main/Octokit/Models/Response/Plan.cs

Is this expected?

**Comment by JonruAlveus** [comment]
Hi @dmitry-kosar, I'm really sorry for the very long time for a response. Those fields are indeed missing, I'll create a PR with the changes in now.
