### ISSUE TITLE
Question: compare branches and get files changed for each commit

### ISSUE THREAD

**Issue by giladv** [octokit/octokit.net#2411]
Hello,

I'm trying to compare 2 branches - so far pretty easy with `/repos/{owner}/{repo}/compare/{basehead}`

but for some reason, the returned result comes with a list of commits and a list of files changed separated,
and i can't seem to be able to connect between them by any identifier. 
i would like for each commit to link the associated file changes. 
is it possible?

the only solution i found is for each commit to have a separate api call like so:
`/repos/{owner}/{repo}/commits/{ref}` but it seems very inefficient.

**Comment by JonruAlveus** [comment]
Hi @giladv, I'm very sorry for the super slow reply! There isn't a nice way of doing it (the commit sha isn't returned as is in the response) however it does appear in the raw/blob urls, so could be parsed out of that. I have created a small PR to add this functionality.

**Comment by JonruAlveus** [comment]
@giladv The only way to find it is by parsing it out of one of the URLs., with something like this based on the RawUrl.

``` csharp
var splitItems = RawUrl.Split(new[] { '/' }, System.StringSplitOptions.RemoveEmptyEntries);

if (splitItems.Length > 2)
{
    return splitItems[splitItems.Length - 2];
}
```
