### ISSUE TITLE
There isn't a clone to desktop button

### ISSUE THREAD

**Issue by Gera-Vera** [octokit/octokit.net#2423]
.

**Comment by nickfloyd** [comment]
Hey @Gera-Vera thanks for reaching out.  I'm making an assumption here but in the GitHub web interface, you should find what you're looking for by navigating to the repo's main [page](https://github.com/octokit/octokit.net) then clicking on code, and then choosing `open with GitHub desktop`

![Screen Shot 2022-04-25 at 2 05 48 PM](https://user-images.githubusercontent.com/139819/165156939-a86bb6f8-b82a-41d2-ae34-00b40289aa43.png)

Let me know if that answers you question.
