### ISSUE TITLE
Support for beta projects

### ISSUE THREAD

**Issue by nkolev92** [octokit/octokit.net#2428]
We're trying to use projects (beta), but the lack of automation around it makes a bit challenging. 

```cs
var projects = await client.Repository.Project.GetAllForOrganization("nuget");
```

Only returns the v1 projects.

**Comment by shiftkey** [comment]
The v3 REST API does not yet support beta projects - GraphQL support is currently available: https://docs.github.com/en/issues/trying-out-the-new-projects-experience/using-the-api-to-manage-projects

**Comment by HouseOfPandas** [comment]
Any updates on this issue?

**Comment by JonruAlveus** [comment]
Hi @HouseOfPandas, unfortunately the GitHub Api itself still only supports classic projects.

**Comment by TluwaniMS** [comment]
@HouseOfPandas and @nkolev92 I was having the same issue and these docs helped me.
https://docs.github.com/en/rest/projects/projects?apiVersion=2022-11-28
https://docs.github.com/en/issues/planning-and-tracking-with-projects/automating-your-project/using-the-api-to-manage-projects

Not sure if you guys might've resolved the issue.

Let me know if you might need any assistance, will be more than willing top help.

You'll need to authenticate with a PAT though.
