### ISSUE TITLE
How to delete a reaction from an issue?

### ISSUE THREAD

**Issue by tschissler** [octokit/octokit.net#2430]
I have been trying to create and delete reactions on an issue. Creating works great, but I'm having issues deleting the issue. It throws an exception with "Not found". I'm guessing it does not find the reaction_id I'm providing.

```csharp
var user = client.User.Current().Result;
var reactions = client.Reaction.Issue.GetAll("myorg", "myrepo", args.RowData.Number).Result;

if (reactions.Any(i => i.User.Login == user.Login))
{
var reaction = reactions.First(i => i.User.Login == user.Login);				
client.Reaction.Delete(reaction.Id).Wait();
}
else
{
client.Reaction.Issue.Create("myorg", "myrepo", args.RowData.Number, new NewReaction(ReactionType.Heart)).Wait();
}
```

What confuses me is that it seems that the API needs the issue Id 

DELETE /repos/{owner}/{repo}/issues/{issue_number}/reactions/{reaction_id}
https://docs.github.com/en/rest/reference/reactions#delete-an-issue-reaction

But the if I understand the actual code correctly, this is operating without the issue 

```csharp
/// <summary>
/// Delete a reaction.
/// </summary>
/// <remarks>https://developer.github.com/v3/reactions/#delete-a-reaction</remarks>
/// <param name="number">The reaction id</param>
/// <returns></returns>
[Preview("squirrel-girl")]
[ManualRoute("DELETE", "/reactions/{reaction_id}")]
public Task Delete(int number)
{
    return ApiConnection.Delete(ApiUrls.Reactions(number), new object(), AcceptHeaders.ReactionsPreview);
}
```

```csharp
/// <summary>
/// Returns the <see cref="Uri"/> for deleting a reaction.
/// </summary>
/// <param name="number">The reaction number</param>
/// <returns>The <see cref="Uri"/> that lists the watched repositories for the authenticated user.</returns>
public static Uri Reactions(int number)
{
    return "reactions/{0}".FormatUri(number);
}
```
How can I delete the reaction?

**Comment by JonruAlveus** [comment]
Hi @tschissler. I've not been here long enough to comment precisely, but I believe that either this is how it used to work, or this was an attempt to standardise deletions for the Observable side.

Code wise, I would say that the below clients need updating to include delete routes, as they are all slightly different:
* ICommitCommentReactionsClient
* IIssueReactionsClient
* IIssueCommentReactionsClient
* IPullRequestReviewCommentReactionsClient

@nickfloyd would you agree?

**Comment by JonruAlveus** [comment]
@timrogers will do.

**Comment by nickfloyd** [comment]
Thank you for adding the issue for this @JonruAlveus! ❤️

**Comment by JonruAlveus** [comment]
@tschissler The fix should now be available, please could you let us know if it’s working for you? 😄

**Comment by tschissler** [comment]
@JonruAlveus, thanks for implementing this. I will look into this in the next couple of days.

**Comment by tschissler** [comment]
Thank you @JonruAlveus 
I just tested it and it works now as expected. Great work!.

I have created a LinqPad sample and can create a PR for this if you think this is helpful.

``` CSharp
async Task Main(string[] args)
{
	var userName = "tschissler";
	var org = "tschissler";
	var repo = "TestIntegration";
	
	GitHubClient client = new GitHubClient(new Octokit.ProductHeaderValue("Octokit.Samples"));
	client.Credentials = new Credentials(Util.GetPassword("github"));

	IIssuesClient issuesclient = client.Issue;

	var allissues = await issuesclient.GetAllForRepository(org, repo);
	allissues.Select(a => new { a.Number, a.Title, a.Body, a.Reactions}).Dump();
	
	client.Reaction.Issue.Create(org, repo, allissues[0].Number, new NewReaction(ReactionType.Heart)).Wait();
	
	allissues = await issuesclient.GetAllForRepository(org, repo);
	allissues.Select(a => new { a.Number, a.Title, a.Body, a.Reactions}).Dump();
	
    var reactions = client.Reaction.Issue.GetAll(org, repo, allissues[0].Number).Result;
    var reaction = reactions.Last(i => i.User.Login == userName);
    await client.Reaction.Issue.Delete(org, repo, allissues[0].Number,reaction.Id);
	
	allissues = await issuesclient.GetAllForRepository(org, repo);
	allissues.Select(a => new { a.Number, a.Title, a.Body, a.Reactions}).Dump();	
}
```

**Comment by JonruAlveus** [comment]
Hi @tschissler, glad it working for you! We’re always happy to receive a PR for improvements, especially to the documentation side if you have time!
