### ISSUE TITLE
Can OctoKit provide a complete tree of raw files?

### ISSUE THREAD

**Issue by urbanistica** [octokit/octokit.net#2460]
There seems to be no way simple way to do this, and neither with GitHub API. Faiing that, a list of the file paths...?

**Comment by nickfloyd** [comment]
Hey @urbanistica,

Apologies, our [documentation](https://octokitnet.readthedocs.io/en/latest/) is a bit out of date - that's something we are actively trying to address. I am guessing you're looking for the equivalent of git's `git ls-tree` - does that sound right?

I'm wondering if you might be looking for the Trees API, specifically GET [Tree](https://docs.github.com/en/rest/git/trees#get-a-tree).  If that's the case then you'll want to look at the [TreesClient](https://github.com/octokit/octokit.net/blob/main/Octokit/Clients/TreesClient.cs) and the [TreeResponse](https://github.com/octokit/octokit.net/blob/main/Octokit/Models/Response/TreeResponse.cs).

Let me know if that's what you might be looking for and thanks for the question!  A

**Comment by urbanistica** [comment]
Hey Nick, yeah the tree is the idea. I'm going to circle back to this, so I may open this up to ask more specific questions. Fro now, I'm grabbing the commits, and then retrieving them, while saving the sha for the most recent. That then becomes the limit for the next retrieval. It all goes in a DB, and the purpose is to get the raw urls.... works as a hack. Thanks for getting back to me.
