### ISSUE TITLE
Support for lazy pagination

### ISSUE THREAD

**Issue by Saalvage** [octokit/octokit.net#2463]
The various `GetAll*` methods automatically paginate through the entire structure, which can be overly expensive both in terms of performance as well as in terms of API calls, the allowed number of which is very limited without an oAuth token.
In many cases you only want to find exactly one entry matching some criteria or similar, for which enumerating the entire structure isn't necessary.

My proposal is introducing an alternative method for all of them, which returns an `IAsyncEnumerable`.

### Version issues
Immediately an issue presents itself: `IAsyncEnumerable` is not introduced until C#8 / .NET Core 3.0. I am not sure whether using it with the current octokit targets of .NET 4.6 / .NET Standard 2.0 is possible, as [this article](https://btburnett.com/csharp/2019/12/01/iasyncenumerable-is-your-friend.html) does state that using it with .NET Standard 2.0 is possible, but it requires .NET 4.6.1.
Either way, since even that would introduce an additional dependency just for this feature I feel like introducing an auxiliary package providing this functionality might be the better options, this package would then target the necessary standard versions to allow for `IAsyncEnumerable`.

### Implementation
Whatever the choice may be, this functionality can easily be implemented using extension methods by relying on the existing overloads that take in an `ApiOptions` object.

Here is an example method that I'm using in one of my projects using octokit:
```cs
public static async IAsyncEnumerable<PullRequest> GetAllForRepositoryAsync(this IPullRequestsClient client,
    string owner, string name, PullRequestRequest request) {
    var pageNum = 1;
    Task<IReadOnlyList<PullRequest>> GetNextPage() =>
        client.GetAllForRepository(owner, name, request, new() {
            StartPage = pageNum++,
        });

    while (await GetNextPage().ConfigureAwait(false) is { Count: > 0 } page) {
        foreach (var pr in page) {
            yield return pr;
        }
    }
}
```

### Related issues:
#1774 - Comments contain discussion about a solution using `IAsyncEnumerable`, but it's not really elaborated on. Furthermore the issue present there is seemingly attributed to something else.
#1799 - Is pretty similar to this issue, but was made at a time when `IAsyncEnumerable` was still in its infancy and without any real concrete goal in mind.

If this is something that the octokit team would be interested in I would personally be interested in realizing this as a feature. :)

**Comment by nickfloyd** [comment]
@Saalvage Thanks for taking the time to put the thought into this.  I like what you're describing.  We're planning on dropping support for .NET 4.6.0 btw, but I feel like what you suggest is the best path forward:
i.e. Introduce this concept as an extension method, then later implement it as a first-class citizen of the `GetAll*` implementations - perhaps after we drop support for 4.6.

**Comment by Saalvage** [comment]
Thank you for getting back to me! I've started cooking up a PR! :)
