### ISSUE TITLE
Missing response properties on the branch protection api

### ISSUE THREAD

**Issue by chris-smith-zocdoc** [octokit/octokit.net#2465]
There are several newer properties on the branch protection api that are missing 

- required_signatures
- required_linear_history
- allow_force_pushes
- allow_deletions
- required_conversation_resolution

Relevant response model https://github.com/octokit/octokit.net/blob/main/Octokit/Models/Response/BranchProtection.cs

Api
https://docs.github.com/en/rest/branches/branch-protection#get-branch-protection

**Comment by timrogers** [comment]
@chris-smith-zocdoc Thanks for reaching out! Would you be open to create a PR to add these fields?

**Comment by chris-smith-zocdoc** [comment]
@timrogers potentially. Could you point me toward something that explains what type of testing / documentation is required for these new properties

**Comment by JonruAlveus** [comment]
@chris-smith-zocdoc It looks like there's some options for integration tests in RepositoryBranchesClientTests.TheGetBranchProtectionMethod where you can test that the properties are pulling back correctly. It doesn't look like there's any unit testing. Documentation is just summary tags on classes & properties.
