### ISSUE TITLE
Unable to fetch Organisations list if membership is private

### ISSUE THREAD

**Issue by JyotstnaDeviChintala** [octokit/octokit.net#2470]
i have an  C# wpf Desktop APP  trying to fetch the organizations list i have access to or i'm a member of

This app has been added to trusted apps to my account and by the organization ( i own) also
Applications ->Authorised OAUth APPs ->MYAPP, its trusted by the Organization too.

Scopes used are : `user` and `read:org`  while fetching access token

But still using this token im unable to fetch full organizations list.

**Organizations in which my membership is Public are being retrieved**.

but for **Organizations in which my membership is Private are not retrieved**.

is this expected?

**Comment by timrogers** [comment]
@JyotstnaDeviChintala Thanks for sharing the code!

According to the API docs, [that API](https://docs.github.com/en/rest/orgs/orgs#list-organizations-for-a-user) "only lists public memberships, regardless of authentication". You'll need to use the "list organizations for the authenticated user" [API](https://docs.github.com/en/rest/orgs/orgs#list-organizations-for-the-authenticated-user) instead.

Can you try using the [`GetAllForCurrent` method](https://github.com/octokit/octokit.net/blob/main/Octokit/Clients/OrganizationsClient.cs#L80) instead?

**Comment by JyotstnaDeviChintala** [comment]
Thanks a lot ! it Worked.

i got confused with the library documentation

        ```
//
        // Summary:
        //     Returns all Octokit.Organizations for the specified user.
        //
        // Returns:
        //     A list of the specified user's Octokit.Organizations.
        //
        // Exceptions:
        //   T:Octokit.ApiException:
        //     Thrown when a general API error occurs.
        Task<IReadOnlyList<Organization>> GetAllForUser(string user);
```

**Comment by timrogers** [comment]
> **Thanks a lot ! it Worked.**
> 
> Doc was not clear and i got confused with the library documentation
> 
> ```
>     ```
> ```
> 
> // // Summary: // Returns all Octokit.Organizations for the specified user. // // Returns: // A list of the specified user's Octokit.Organizations. // // Exceptions: // T:Octokit.ApiException: // Thrown when a general API error occurs. Task<IReadOnlyList> GetAllForUser(string user);

Great! If you have time, it would be awesome if you could make a pull request updating the method description to make the "only lists public memberships, regardless of authentication" limitation clear. That'll help other people in the future I'm sure.
