### ISSUE TITLE
.NET SDK: Remove preview headers

### ISSUE THREAD

**Issue by JonruAlveus** [octokit/octokit.net#2497]
It’s looks like all preview headers have been removed from the api.

This is the latest post:
https://github.blog/changelog/2021-10-14-rest-api-preview-promotions/

The 2 remaining from this page no longer specify the need for the header anywhere on the documentation, so we should remove all trace of preview headers to simplify the code.

**Comment by timrogers** [comment]
Exactly right on this one! ✅

**Comment by nickfloyd** [comment]
Yeah +1 on this for sure... I promoted all of the REST API previews last year so this is long overdue! Thanks for jotting this one down. 

Info: this is the related Octokit.rb issue: https://github.com/octokit/octokit.rb/issues/1447
