### ISSUE TITLE
Calculate Sha locally without Client.Git.Blob.Create()

### ISSUE THREAD

**Issue by krulci** [octokit/octokit.net#2498]
I am currently looping my local directory to compare with remote repository.
What I do not get is that everytime creating a NewBlob, Sha is generated through the Create methods (which uses Rates).
Is it possible to calculate Sha locally?

**Comment by timrogers** [comment]
Hi there! Can you tell me a bit more about what you’re trying to achieve?

**Comment by timrogers** [comment]
Can you tell me a bit more about why you are trying to do that comparison? I’d like to understand your goal so I might be able to suggest a different approach.

**Comment by krulci** [comment]
The project's ultimate goal is to commit these files separately so that each files has specific comment.
Due to this reason, I chose to commit each file separately instead of commit as a single tree.

**Comment by timrogers** [comment]
If you're creating commits using the GitHub REST API, then you will need to make an API call for each commit. An alternative approach would be to use Git locally to build the commits and push them.

**Comment by krulci** [comment]
I was looking for this feature earlier.
The only thinging I was able to figure was that update method.
I don't see something that could push multiple commits with octokit

**Comment by krulci** [comment]
Thanks for your suggestion
I was able to get commit and push.
I understand this might be better to post as an issue in libgit2sharp.
However, does this library you suggested allow Parralel.ForEach loop when staging files?

**Comment by timrogers** [comment]
I don't know I'm afraid - sorry!

**Comment by JonruAlveus** [comment]
Response given

**Comment by tisfeng** [comment]
I found a way to calculate the github sha locally https://stackoverflow.com/a/62612802/8378840 .

This is a Swift example and I verified that it is correct 😃

```swift
import Cocoa
import CryptoSwift

extension Data {
    /// Get github file sha.
    func githubSHA() -> String {
        let header = "blob \(self.count)\0".data(using: .utf8)!
        var store = Data()
        store.append(header)
        store.append(self)
        let sha1 = store.sha1().toHexString()
        return sha1
    }
}
```
