### ISSUE TITLE
Find invalid code owners files

### ISSUE THREAD

**Issue by JonruAlveus** [octokit/octokit.net#2505]
Hi,

Is there an api route for finding repositories with invalid code owner files, or to check the code owners file is valid? I can see it in the UI and I have a feeling we have a few invalid/broken ones hanging around.

Cheers!

**Comment by timrogers** [comment]
Hi @JonruAlveus 👋🏻 Yes - there is. You can find the API in the docs at https://docs.github.com/en/rest/repos/repos#list-codeowners-errors.

**Comment by JonruAlveus** [comment]
Thanks @timrogers! PR created :)
