### ISSUE TITLE
Correct SetRequestTimeout code does to be more descriptive of what it's actually doing 

### ISSUE THREAD

**Issue by nickfloyd** [octokit/octokit.net#2506]
A few spots in the code exist where `SetRequestTimeout` is used and documented. 

The timeout specified in the connection itself is only for the client connecting to the server. All this does is pass through the value you pass into `System.Net.Http.HttpClient` and assigns it to the `Timeout` property - which just sets the timespan to wait before the request itself times out.

We need to correct the code docs for this API on the GitHubClient object. The code comments ("Set the GitHub Api request timeout.") implies that this will set the timeout for the GitHub API itself ([which is capped at 10 seconds](https://docs.github.com/en/rest/overview/troubleshooting#timeouts)) and not the client timeout to the API.

This documentation should better represent what calling this method does - it sets the timeout for the connection between the client and server and does not assign the timeout of the GitHub REST API (it's a client connection timeout and not a deadline propagation).

**Comment by notauserx** [comment]
I would like to work on this issue.

To reiterate, I would be updating the code docs from "Set the GitHub Api request timeout." to "Sets the timeout between the client and the server".

**Comment by notauserx** [comment]
#2520 is my PR

**Comment by nickfloyd** [comment]
Thank you @notauserx for helping us make things better here 🎉
