### ISSUE TITLE
Private repositories no longer have a maximum quota

### ISSUE THREAD

**Issue by snyrting6github** [octokit/octokit.net#2507]
All plans now have unlimited repositories and private repositories. We have a few methods and tests which check for quota exceptions, throwing PrivateRepositoryQuotaExceededException and this should be removed.

See RepositoriesClientTests.ThrowsPrivateRepositoryQuotaExceededExceptionWhenOverQuota

**Comment by JonruAlveus** [comment]
Sorry the above was me, I forgot I was logged in as my test account 🙄
