### ISSUE TITLE
Repository WatchersCount actually refers to Starred

### ISSUE THREAD

**Issue by JonruAlveus** [octokit/octokit.net#2509]
The response for getting a repository contains a watchers_count property. This doesn't actually refer to watchers, but to Stars (unless stars add watchers?). I've created a repository, added a watch via the Activity.Watch client and the property is 0 when retrieved. If I start it, the property becomes 1.

I wonder if there is something wrong in the background as watchers_count seems to follow stargazers.

This shows what I mean, it's watched by 1 and starred by 0, but watchers_count and stargazers are both 0.
![image](https://user-images.githubusercontent.com/15954362/180594311-0eaff6f4-2787-4c24-91f1-3531056f4cd5.png)

**Comment by nickfloyd** [comment]
Interesting, good catch!  I wonder if there is a transposed element in the [OpenAPI descriptions](https://github.com/github/rest-api-description) - given how we dynamically hydrate the response object this is most likely on the GitHub REST API side of things.  

I'll put it on the list of things to look into unless anyone else has time to grok the OpenAPI descriptions.

**Comment by JonruAlveus** [comment]
I'm not sure what the openapi spec is telling us, but here's the bit we're talking about

![image](https://user-images.githubusercontent.com/15954362/181600806-464da518-049b-4ed9-b73b-eec8812cfa48.png)

They both have the same example value, not sure if that's relevant?

**Comment by Brend-Smits** [comment]
This seems like a bug in the GitHub API itself. I just tested it by using the GitHub CLI and Postman and get the same bug as you reported. 
I don't think we can fix this in this repository, needs to be escalated to the GH Team.

**Comment by nickfloyd** [comment]
@Brend-Smits Thanks for tracking this down!  It's not an ideal situation.  Hopefully, in the future, with versioning - this type of thing will be a non-issue as in, fields will be more easily deprecated.
