### ISSUE TITLE
Review/Cleanup DefineConstants in the projects

### ISSUE THREAD

**Issue by nickfloyd** [octokit/octokit.net#2526]
There seems to be a mismatch between what is defined in the `< DefineConstants>` nodes in the csproj files from what is being used in the code. We need to look at the following projects and determine what env constants are still being used:

- [ ] Octokit
- [ ] Octokit.Tests
- [ ] Octokit.Tests.Integration

**Comment by JonruAlveus** [comment]
This is the distinct list of usages (full list of usages further down). Not sure where to go with it though!

GITHUBJWT_HELPER_AVAILABLE
NET_45
NO_SERIALIZABLE
HAS_DEFAULT_ENCODING
HAS_TYPEINFO
HAS_REGEX_COMPILED_OPTIONS
HAS_ENVIRONMENT
HAS_SERVICEPOINTMANAGER
NETFX_CORE
SIMPLE_JSON_NO_LINQ_EXPRESSION
SIMPLE_JSON_DYNAMIC
SIMPLE_JSON_OBJARRAYINTERNAL
SIMPLE_JSON_INTERNAL
SIMPLE_JSON_READONLY_COLLECTIONS
SIMPLE_JSON_REFLECTION_UTILS_PUBLIC
SIMPLE_JSON_TYPEINFO

CsProj usages:
Octokit.Tests - netcoreapp3.1 - NO_SERIALIZABLE; HAS_TYPEINFO
Octokit.Tests.Integration - netcoreapp3.1 - GITHUBJWT_HELPER_AVAILABLE
Octokit - everything - HAS_TYPEINFO; SIMPLE_JSON_INTERNAL; SIMPLE_JSON_OBJARRAYINTERNAL; SIMPLE_JSON_READONLY_COLLECTIONS; SIMPLE_JSON_TYPEINFO

Octokit.Tests.Integration\Helper.cs(78):#if GITHUBJWT_HELPER_AVAILABLE
Octokit.Tests\Clients\UsersClientTests.cs(2):#if NET_45
Octokit.Tests\Exceptions\ApiExceptionTests.cs(5):#if !NO_SERIALIZABLE
Octokit.Tests\Exceptions\ApiExceptionTests.cs(95):#if !NO_SERIALIZABLE
Octokit.Tests\Exceptions\ApiValidationExceptionTests.cs(3):#if !NO_SERIALIZABLE
Octokit.Tests\Exceptions\ApiValidationExceptionTests.cs(41):#if !NO_SERIALIZABLE
Octokit.Tests\Exceptions\RateLimitExceededExceptionTests.cs(8):#if !NO_SERIALIZABLE
Octokit.Tests\Exceptions\RateLimitExceededExceptionTests.cs(89):#if !NO_SERIALIZABLE
Octokit.Tests\Fixtures\EmbeddedResource.cs(24):#if HAS_DEFAULT_ENCODING
Octokit.Tests\Fixtures\Fixtures.cs(1):#if HAS_TYPEINFO
Octokit.Tests\Fixtures\Fixtures.cs(9):#if HAS_TYPEINFO
Octokit.Tests\Http\RateLimitTests.cs(4):#if !NO_SERIALIZABLE
Octokit.Tests\Http\RateLimitTests.cs(74):#if !NO_SERIALIZABLE
Octokit.Tests\SelfTests.cs(1):#if HAS_TYPEINFO
Octokit.Tests\SelfTests.cs(14):#if HAS_TYPEINFO
Octokit\Exceptions\AbuseException.cs(7):#if !NO_SERIALIZABLE
Octokit\Exceptions\AbuseException.cs(18):#if !NO_SERIALIZABLE
Octokit\Exceptions\AbuseException.cs(66):#if !NO_SERIALIZABLE
Octokit\Exceptions\ApiException.cs(4):#if !NO_SERIALIZABLE
Octokit\Exceptions\ApiException.cs(15):#if !NO_SERIALIZABLE
Octokit\Exceptions\ApiException.cs(144):#if !NO_SERIALIZABLE
Octokit\Exceptions\ApiValidationException.cs(5):#if !NO_SERIALIZABLE
Octokit\Exceptions\ApiValidationException.cs(14):#if !NO_SERIALIZABLE
Octokit\Exceptions\ApiValidationException.cs(63):#if !NO_SERIALIZABLE
Octokit\Exceptions\AuthorizationException.cs(5):#if !NO_SERIALIZABLE
Octokit\Exceptions\AuthorizationException.cs(14):#if !NO_SERIALIZABLE
Octokit\Exceptions\AuthorizationException.cs(54):#if !NO_SERIALIZABLE
Octokit\Exceptions\ForbiddenException.cs(5):#if !NO_SERIALIZABLE
Octokit\Exceptions\ForbiddenException.cs(14):#if !NO_SERIALIZABLE
Octokit\Exceptions\ForbiddenException.cs(46):#if !NO_SERIALIZABLE
Octokit\Exceptions\InvalidGitIgnoreTemplateException.cs(3):#if !NO_SERIALIZABLE
Octokit\Exceptions\InvalidGitIgnoreTemplateException.cs(12):#if !NO_SERIALIZABLE
Octokit\Exceptions\InvalidGitIgnoreTemplateException.cs(41):#if !NO_SERIALIZABLE
Octokit\Exceptions\LegalRestrictionException.cs(5):#if !NO_SERIALIZABLE
Octokit\Exceptions\LegalRestrictionException.cs(16):#if !NO_SERIALIZABLE
Octokit\Exceptions\LegalRestrictionException.cs(57):#if !NO_SERIALIZABLE
Octokit\Exceptions\LoginAttemptsExceededException.cs(3):#if !NO_SERIALIZABLE
Octokit\Exceptions\LoginAttemptsExceededException.cs(12):#if !NO_SERIALIZABLE
Octokit\Exceptions\LoginAttemptsExceededException.cs(43):#if !NO_SERIALIZABLE
Octokit\Exceptions\NotFoundException.cs(5):#if !NO_SERIALIZABLE
Octokit\Exceptions\NotFoundException.cs(14):#if !NO_SERIALIZABLE
Octokit\Exceptions\NotFoundException.cs(50):#if !NO_SERIALIZABLE
Octokit\Exceptions\PullRequestMismatchException.cs(5):#if !NO_SERIALIZABLE
Octokit\Exceptions\PullRequestMismatchException.cs(15):#if !NO_SERIALIZABLE
Octokit\Exceptions\PullRequestMismatchException.cs(48):#if !NO_SERIALIZABLE
Octokit\Exceptions\PullRequestNotMergeableException.cs(5):#if !NO_SERIALIZABLE
Octokit\Exceptions\PullRequestNotMergeableException.cs(15):#if !NO_SERIALIZABLE
Octokit\Exceptions\PullRequestNotMergeableException.cs(48):#if !NO_SERIALIZABLE
Octokit\Exceptions\RateLimitExceededException.cs(4):#if !NO_SERIALIZABLE
Octokit\Exceptions\RateLimitExceededException.cs(21):#if !NO_SERIALIZABLE
Octokit\Exceptions\RateLimitExceededException.cs(105):#if !NO_SERIALIZABLE
Octokit\Exceptions\RepositoryExistsException.cs(4):#if !NO_SERIALIZABLE
Octokit\Exceptions\RepositoryExistsException.cs(14):#if !NO_SERIALIZABLE
Octokit\Exceptions\RepositoryExistsException.cs(100):#if !NO_SERIALIZABLE
Octokit\Exceptions\RepositoryFormatException.cs(5):#if !NO_SERIALIZABLE
Octokit\Exceptions\RepositoryFormatException.cs(12):#if !NO_SERIALIZABLE
Octokit\Exceptions\RepositoryFormatException.cs(38):#if !NO_SERIALIZABLE
Octokit\Exceptions\SecondaryRateLimitExceededException.cs(3):#if !NO_SERIALIZABLE
Octokit\Exceptions\SecondaryRateLimitExceededException.cs(19):#if !NO_SERIALIZABLE
Octokit\Exceptions\SecondaryRateLimitExceededException.cs(49):#if !NO_SERIALIZABLE
Octokit\Exceptions\TwoFactorAuthorizationException.cs(5):#if !NO_SERIALIZABLE
Octokit\Exceptions\TwoFactorAuthorizationException.cs(12):#if !NO_SERIALIZABLE
Octokit\Exceptions\TwoFactorAuthorizationException.cs(67):#if !NO_SERIALIZABLE
Octokit\Exceptions\TwoFactorChallengeFailedException.cs(3):#if !NO_SERIALIZABLE
Octokit\Exceptions\TwoFactorChallengeFailedException.cs(10):#if !NO_SERIALIZABLE
Octokit\Exceptions\TwoFactorChallengeFailedException.cs(52):#if !NO_SERIALIZABLE
Octokit\Exceptions\TwoFactorRequiredException.cs(5):#if !NO_SERIALIZABLE
Octokit\Exceptions\TwoFactorRequiredException.cs(14):#if !NO_SERIALIZABLE
Octokit\Exceptions\TwoFactorRequiredException.cs(53):#if !NO_SERIALIZABLE
Octokit\Exceptions\UserIsLastOwnerOfOrganizationException.cs(5):#if !NO_SERIALIZABLE
Octokit\Exceptions\UserIsLastOwnerOfOrganizationException.cs(15):#if !NO_SERIALIZABLE
Octokit\Exceptions\UserIsLastOwnerOfOrganizationException.cs(45):#if !NO_SERIALIZABLE
Octokit\Exceptions\UserIsNotMemberOfOrganizationException.cs(5):#if !NO_SERIALIZABLE
Octokit\Exceptions\UserIsNotMemberOfOrganizationException.cs(15):#if !NO_SERIALIZABLE
Octokit\Exceptions\UserIsNotMemberOfOrganizationException.cs(45):#if !NO_SERIALIZABLE
Octokit\Exceptions\UserIsOrganizationMemberException.cs(5):#if !NO_SERIALIZABLE
Octokit\Exceptions\UserIsOrganizationMemberException.cs(15):#if !NO_SERIALIZABLE
Octokit\Exceptions\UserIsOrganizationMemberException.cs(45):#if !NO_SERIALIZABLE
Octokit\Helpers\ReflectionExtensions.cs(42):#if !HAS_TYPEINFO
Octokit\Helpers\ReflectionExtensions.cs(65):#if HAS_TYPEINFO
Octokit\Helpers\StringExtensions.cs(129):#if HAS_REGEX_COMPILED_OPTIONS
Octokit\Http\ApiInfoParser.cs(14):#if HAS_REGEX_COMPILED_OPTIONS
Octokit\Http\Connection.cs(11):#if !HAS_ENVIRONMENT
Octokit\Http\Connection.cs(793):#if !HAS_ENVIRONMENT
Octokit\Http\HttpClientAdapter.cs(32):#if HAS_SERVICEPOINTMANAGER
Octokit\Http\RateLimit.cs(7):#if !NO_SERIALIZABLE
Octokit\Http\RateLimit.cs(15):#if !NO_SERIALIZABLE
Octokit\Http\RateLimit.cs(20):#if !NO_SERIALIZABLE
Octokit\Http\RateLimit.cs(99):#if !NO_SERIALIZABLE
Octokit\Models\Response\ApiError.cs(11):#if !NO_SERIALIZABLE
Octokit\Models\Response\ApiErrorDetail.cs(7):#if !NO_SERIALIZABLE
Octokit\SimpleJson.cs(48):#if NETFX_CORE
Octokit\SimpleJson.cs(62):#if !NO_SERIALIZABLE
Octokit\SimpleJson.cs(67):#if !SIMPLE_JSON_NO_LINQ_EXPRESSION
Octokit\SimpleJson.cs(70):#if SIMPLE_JSON_DYNAMIC
Octokit\SimpleJson.cs(85):#if SIMPLE_JSON_OBJARRAYINTERNAL
Octokit\SimpleJson.cs(119):#if SIMPLE_JSON_OBJARRAYINTERNAL
Octokit\SimpleJson.cs(125):#if SIMPLE_JSON_DYNAMIC
Octokit\SimpleJson.cs(351):#if SIMPLE_JSON_DYNAMIC
Octokit\SimpleJson.cs(500):#if SIMPLE_JSON_INTERNAL
Octokit\SimpleJson.cs(552):#if !NO_SERIALIZABLE
Octokit\SimpleJson.cs(1226):#if SIMPLE_JSON_DATACONTRACT
Octokit\SimpleJson.cs(1249):#if SIMPLE_JSON_DATACONTRACT
Octokit\SimpleJson.cs(1265):#if SIMPLE_JSON_INTERNAL
Octokit\SimpleJson.cs(1278):#if SIMPLE_JSON_INTERNAL
Octokit\SimpleJson.cs(1468):#if SIMPLE_JSON_READONLY_COLLECTIONS
Octokit\SimpleJson.cs(1583):#if SIMPLE_JSON_DATACONTRACT
Octokit\SimpleJson.cs(1585):#if SIMPLE_JSON_INTERNAL
Octokit\SimpleJson.cs(1667):#if SIMPLE_JSON_REFLECTION_UTILS_PUBLIC
Octokit\SimpleJson.cs(1682):#if SIMPLE_JSON_TYPEINFO
Octokit\SimpleJson.cs(1696):#if SIMPLE_JSON_TYPEINFO
Octokit\SimpleJson.cs(1710):#if SIMPLE_JSON_TYPEINFO
Octokit\SimpleJson.cs(1728):#if SIMPLE_JSON_TYPEINFO
Octokit\SimpleJson.cs(1741):#if SIMPLE_JSON_TYPEINFO
Octokit\SimpleJson.cs(1763):#if SIMPLE_JSON_READONLY_COLLECTIONS
Octokit\SimpleJson.cs(1789):#if SIMPLE_JSON_TYPEINFO
Octokit\SimpleJson.cs(1798):#if !SIMPLE_JSON_TYPEINFO
Octokit\SimpleJson.cs(1809):#if SIMPLE_JSON_READONLY_COLLECTIONS
Octokit\SimpleJson.cs(1825):#if SIMPLE_JSON_READONLY_COLLECTIONS
Octokit\SimpleJson.cs(1855):#if SIMPLE_JSON_TYPEINFO
Octokit\SimpleJson.cs(1893):#if SIMPLE_JSON_TYPEINFO
Octokit\SimpleJson.cs(1902):#if SIMPLE_JSON_TYPEINFO
Octokit\SimpleJson.cs(1911):#if SIMPLE_JSON_TYPEINFO
Octokit\SimpleJson.cs(1920):#if SIMPLE_JSON_TYPEINFO
Octokit\SimpleJson.cs(1929):#if SIMPLE_JSON_NO_LINQ_EXPRESSION
Octokit\SimpleJson.cs(1938):#if SIMPLE_JSON_NO_LINQ_EXPRESSION
Octokit\SimpleJson.cs(1956):#if !SIMPLE_JSON_NO_LINQ_EXPRESSION
Octokit\SimpleJson.cs(1987):#if SIMPLE_JSON_NO_LINQ_EXPRESSION
Octokit\SimpleJson.cs(1996):#if SIMPLE_JSON_NO_LINQ_EXPRESSION
Octokit\SimpleJson.cs(2014):#if !SIMPLE_JSON_NO_LINQ_EXPRESSION
Octokit\SimpleJson.cs(2037):#if SIMPLE_JSON_NO_LINQ_EXPRESSION
Octokit\SimpleJson.cs(2046):#if SIMPLE_JSON_NO_LINQ_EXPRESSION
Octokit\SimpleJson.cs(2064):#if !SIMPLE_JSON_NO_LINQ_EXPRESSION
Octokit\SimpleJson.cs(2088):#if SIMPLE_JSON_TYPEINFO
