### ISSUE TITLE
IssueEvent is missing payload for code review set of events

### ISSUE THREAD

**Issue by extesy** [octokit/octokit.net#2550]
I am writing a review request notification bot and as part of that I need to get information about when somebody was requested to review a PR. As part of `review_requested` event [payload](https://docs.github.com/en/developers/webhooks-and-events/events/issue-event-types#review_requested) there should be `review_requester`, `requested_reviewer` and `requested_team` fields but they are not in the IssueEvent class so I can't get this information using OctoKit. Same problem for other similar events like `reviewed`, `review_request_removed`, etc.

**Comment by timrogers** [comment]
@extesy Thanks for reaching out! Would you be open to create a pull request to add those fields? At the moment, the code here isn't automatically generated based on the API structure, so we rely on humans to keep it up to date with actual payloads.
