### ISSUE TITLE
Ability to specify per_page for PullRequest.Files?

### ISSUE THREAD

**Issue by Gamer025** [octokit/octokit.net#2552]
Is it somehow possible to specify the per_page parameter when calling PullRequest.Files?
By default Github only returns 30 files per page but could return up to 100.
This means when retrieving a list of modified files on a large PR a lot of unneeded API calls are being made.

Apparently other GetAll methods allow you to pass an ApiOptions parameter but it doesn't look like PullRequest.Files has an overload for that.

Alternatively would it be possible for PullRequest.Files to include per_page set to 100 by default?
I don't see any reason why one wouldn't want that method to use as little API calls as possible.

**Comment by timrogers** [comment]
@Gamer025 👋🏻 Hi there! Just to confirm, are you referring to [this method](https://github.com/octokit/octokit.net/blob/595e35d6419e444bbf20f9d02bab5a9749219e83/Octokit/Clients/PullRequestsClient.cs#L419-L446)?

If so, I can see that [that REST API does support the `per_page` parameter](https://docs.github.com/en/rest/pulls/pulls#list-pull-requests-files).

Would you be open to creating a PR to add that? I think it would be better for Octokit.NET not to override the API's default `per_page`, but you could at least make it customisable.

**Comment by Gamer025** [comment]
Hello @timrogers
Yes im referring to the method you linked.
I took a quick look at the code and as far as I can tell one probably only needs to add an overloaded Files method that takes in an ApiOptions object?
That object can then simply be passed on to ApiConnection.GetAll

**Comment by timrogers** [comment]
That sounds like it will work to me! I'd welcome a PR.

**Comment by Gamer025** [comment]
I submitted a PR that adds ApiOptions to the Files method.
I tested it in a local project and everything worked correctly and one could now query up to 100 files per page:
![image](https://user-images.githubusercontent.com/33846895/186719434-177fb485-7a02-452a-a21b-d7bb0ab8f0df.png)
I had to change some of the unit test mocking because calling PullRequestsClient.Files without ApiOptions now calls the overloaded method version with ApiOptions set to None.

**Comment by timrogers** [comment]
Thanks for taking the time to submit the PR, #2553! We'll get that reviewed.
