### ISSUE TITLE
Basic Auth credentials not working

### ISSUE THREAD

**Issue by rkreisel** [octokit/octokit.net#2554]
I am trying to use the API via C# and the OctoKit nuget package.
During development I want to use basic auth, but after configuring it I still get errors indicating I am not authenticated.

var client = new GitHubClient(new ProductHeaderValue("rkreiselsstuff"));
var basicAuth = new Credentials("_myuserid_", "_myid_");
client.Credentials = basicAuth;

var rateLimit = await client.Miscellaneous.GetRateLimits(); - this shows I have exhausted my count but includes the message about credentialed requests have a higher limit

these next two simply return HTTP 500 with the "api limit hit" message
var user = await client.User.Get("randy@rkreisel.com"); 
var projectList = await client.Organization.GetAllForCurrent();

Is there a problem with my code (I used the API doc as an example), or does this simply not work as documented?

**Comment by timrogers** [comment]
Hi there! 👋 Thanks for reaching out. 

Sadly it looks like the documentation is out of date as basic authentication using a username and password is no longer supported in the GitHuh API. 

Can you try creating a personal access token from your GitHub settings, and using that to authenticate with the token option?

If you run into any more issues, let us know. We'll get those docs fixed - or you're welcome to submit a pull request to fix the docs if you like.

**Comment by timrogers** [comment]
There's an example at https://github.com/octokit/octokit.net/blob/main/docs/getting-started.md of how you can use a token. 

Just to add as well, the `User.Get` method expects a username as the argument, not an email address.

**Comment by rkreisel** [comment]
Thanks.  I'll give that a try later tonight. Sent from the bridge of the Enterprise NCC 1701-E.
-------- Original message --------From: Tim Rogers ***@***.***> Date: 8/25/22  16:45  (GMT-06:00) To: "octokit/octokit.net" ***@***.***> Cc: Randy Kreisel ***@***.***>, Author ***@***.***> Subject: Re: [octokit/octokit.net] Basic Auth credentials not working (Issue #2554)
There's an example at https://github.com/octokit/octokit.net/blob/main/docs/getting-started.md of how you can use a token.
Just to add as well, the User.Get method expects a username as the argument, not an email address.

**Comment by rkreisel** [comment]
I implemented the use of a PAT and submitted a pull request to update the document.

**Comment by JonruAlveus** [comment]
Completed 👍
