### ISSUE TITLE
Invalid exception when add-collaborator return 201

### ISSUE THREAD

**Issue by FrediKats** [octokit/octokit.net#2558]
From docs (https://docs.github.com/en/rest/collaborators/collaborators#add-a-repository-collaborator):

![image](https://user-images.githubusercontent.com/22368203/188271559-71a88d6d-8d96-4823-b0f4-9136fb233218.png)

But .Add method has `response.HttpResponse.IsTrue()` and fail on 201. Method should return `RepositoryInvitation` instead of `bool` and do not fail on 201.

**Comment by timrogers** [comment]
Thanks for reporting this issue! Would you be open to creating a PR to fix it? We welcome all contributions ❤️

**Comment by FrediKats** [comment]
We will try to fix it.

**Comment by timrogers** [comment]
If you don't have time or if you run into any issues, let us know and we can try to pick this up on our side. 

I imagine this will end up being a breaking change as the return type will be different.

**Comment by annchous** [comment]
This issue was originally posted in #2373, but the author had lost the confirmation of this problem somehow.

I can try to create a pull request to fix it in a few hours.
