### ISSUE TITLE
Listing all issues in a repo with a Github application

### ISSUE THREAD

**Issue by DrewScoggins** [octokit/octokit.net#2566]
From reading the documentation it seems that Github exposes a rest endpoint to get all issues in a repo as a Github app, https://docs.github.com/en/rest/issues/issues#list-repository-issues. However, it is unclear to me if this endpoint is wrapped in Octokit.

If it is can you please point to the documentation, and if not is there a plan to include this in a future release?

**Comment by timrogers** [comment]
@DrewScoggins Hi there! 👋🏻 The [`GetAllForRepository` method on the `IssuesClient`](https://github.com/octokit/octokit.net/blob/main/Octokit/Clients/IssuesClient.cs#L303) should do what you're looking for. You can see an example in the docs [here](https://octokitnet.readthedocs.io/en/latest/issues/#get-all). If you're using a GitHub App, you will just need to make sure you authenticate with the relevant token.

**Comment by DrewScoggins** [comment]
I found out what my issue was. I was using a custom RepositoryIssueRequest, and by default the Filter on that is set to just assigned issues, not all. Once I changed that it works just like I thought it should.
