### ISSUE TITLE
Split out and retire the MiscellaneousClient

### ISSUE THREAD

**Issue by SeanKilleen** [octokit/octokit.net#2572]
While working on #2571 to support #2474, I noticed the `MiscellaneousClient` had a link to `misc` rest endpoint that had since been separated into their own named endpoints and docs. The Octokit .NET client updated the URLs but didn't update the C# code to reflect them.

My suggestion, which I think can be done in steps:

* Method by method: 
 * Create named clients & methods to support the functionality within MiscellaneousClient 
 * Use those clients from within MiscellaneousClient to ensure no issues.
 * Deprecate methods to ensure users know it's just a redirect.
* Deprecate MiscellaneousClient itself.
* Remove MiscellaneousClient in a future release.

Creating this issue per discussion with @nickfloyd at https://github.com/octokit/octokit.net/pull/2571#issuecomment-1248279480

**Comment by JonruAlveus** [comment]
❤️ I'd be happy to pick this one up.

**Comment by JonruAlveus** [comment]
Clients:

- EmojisClient
  - /emojis
- MarkdownClient
  - /markdown/raw
  - /markdown
- GitIgnoreClient
  - /gitignore/templates
  - /gitignore/templates/{name}
- LicensesClient
  - /licenses
  - /licenses/{key}
- RateLimitClient
  - /rate_limit
- MetaClient
  - /meta
