### ISSUE TITLE
[Octokit.AuthorizationException: Bad credentials] via connection with OAuth token

### ISSUE THREAD

**Issue by Falcion** [octokit/octokit.net#2593]
**Information before issue:**

- .NET Core 6
- Octokit.net v3.0.1

My bot is connecting to Octokit with help of OAuth's client secret (aka token), but in an aswer I got exception about bad credentials.

... there is code of command which uses Octokit connection:

```csharp
            var gitClient = new GitHubClient(new ProductHeaderValue("Octokitty-DISCORD"));
            var authToken = new Credentials(Environment.GetEnvironmentVariable("GITHUB_TOKEN"));

            gitClient.Credentials = authToken;

            var miscRateLimit = await gitClient.RateLimit.GetRateLimits();

            var coreRateLimit = miscRateLimit.Resources.Core;
            var searchRateLimit = miscRateLimit.Resources.Search;

            var coreRequestsPerHour = coreRateLimit.Limit;
            var coreRequestsLeft = coreRateLimit.Remaining;
            var coreRequestsReset = coreRateLimit.Reset;

            var searchRequestsPerHour = searchRateLimit.Limit;
            var searchRequestsLeft = searchRateLimit.Remaining;
            var searchRequestsReset = searchRateLimit.Reset;
```

OAuth token is NOT null either empty string, and client gets it credentials, but when I try to use something, it screams this exception:

```
Octokit.AuthorizationException: Bad credentials
   at Octokit.Connection.HandleErrors(IResponse response) in /home/runner/work/octokit.net/octokit.net/Octokit/Http/Connection.cs:line 704
   at Octokit.Connection.RunRequest(IRequest request, CancellationToken cancellationToken) in /home/runner/work/octokit.net/octokit.net/Octokit/Http/Connection.cs:line 685
   at Octokit.Connection.Run[T](IRequest request, CancellationToken cancellationToken) in /home/runner/work/octokit.net/octokit.net/Octokit/Http/Connection.cs:line 670
   at Octokit.ApiConnection.Get[T](Uri uri, IDictionary`2 parameters) in /home/runner/work/octokit.net/octokit.net/Octokit/Http/ApiConnection.cs:line 72
   at OctokittyBOT.Commands.HandleApisInfo.Execute(SocketSlashCommand command) in E:\Projects\Octokitty's Environment\Octokitty-DISCORD\src\Commands\HandleApisInfo.cs:line 22
   at OctokittyBOT.Program.SlashCommandHandler(SocketSlashCommand command) in E:\Projects\Octokitty's Environment\Octokitty-DISCORD\src\Program.cs:line 55
   at Discord.EventExtensions.InvokeAsync[T](AsyncEvent`1 eventHandler, T arg)
   at Discord.WebSocket.DiscordSocketClient.TimeoutWrap(String name, Func`1 action)
{"message":"Bad credentials","documentation_url":"https://docs.github.com/rest"}
```

Maybe it's about my stupidity or something, because there is a reference to the API, so I really don't understand what my problem is: I even tried different OAuth tokens and I use an example connection from docs, but it doesn't help.

**Comment by nickfloyd** [comment]
Hey @Falcion,

Since there could be a few reasons why you might be hitting this, would you mind attempting to do the following and let us know what type of response you get:

`curl -u my_client_id:my_client_secret 'https://api.github.com/user/repos'`

and 

`curl -i https://api.github.com/user/repos -u VALID_USERNAME:VALID_TOKEN `

**Comment by Falcion** [comment]
Eh~, maybe I'm stupid but in answer on both cURLs I got the same answers, also I hid token, names and ID for obvious reasons:

- **Response on `curl -u my_client_id:my_client_secret 'https://api.github.com/user/repos'`**

```
Invoke-WebRequest : The parameter cannot be processed because the parameter name "u" is ambiguous. Possible matches: -UseBasicParsing -Uri -UseDefaultCredentials -UserAgent.
string:1 char:6
+ curl -u <client_id>:<client_secret> ...
+      ~~
    + CategoryInfo          : InvalidArgument: (:) [Invoke-WebRequest], ParameterBindingException
    + FullyQualifiedErrorId : AmbiguousParameter,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
```

**- Response on `curl -i https://api.github.com/user/repos -u VALID_USERNAME:VALID_TOKEN`**

```
Invoke-WebRequest : The parameter cannot be processed because the parameter name "u" is ambiguous. Possible matches: -UseBasicParsing -Uri -UseDefaultCredentials -UserAgent.
string:1 char:43
+ curl -i https://api.github.com/user/repos -u <client_name>:<client_secret> ...
+                                           ~~
    + CategoryInfo          : InvalidArgument: (:) [Invoke-WebRequest], ParameterBindingException
    + FullyQualifiedErrorId : AmbiguousParameter,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

```

**Comment by nickfloyd** [comment]
Hey @Falcion,

I was expecting the same result sets coming back from the GitHub API.  I see you are using PowerShell/Windows.

Would you mind giving the following a try -  just so that we can eliminate variables, generally they syntax `curl` should work but we can try the more native approach for your given platform:

```
$username = 'username'
$token = 'token'

[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
$base64Auth = [Convert]::ToBase64String([Text.Encoding]::ASCII.GetBytes(("{0}:{1}" -f $username, $token)))
$header = @{Authorization="Basic $base64Auth"}

Invoke-RestMethod -Uri https://api.github.com/user/repos -Method GET -Headers $header
```

**Comment by Falcion** [comment]
Excuse me for the long time without answering, there is an answer in PowerShell:

```
Invoke-RestMethod : {"message":"Bad credentials","documentation_url":"https://docs.github.com/rest"}
string:8 char:1
+ Invoke-RestMethod -Uri https://api.github.com/user/repos -Method GET  ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
```

**Comment by Falcion** [comment]
> Excuse me for the long time without answering, there is an answer in PowerShell:
> 
> ```
> Invoke-RestMethod : {"message":"Bad credentials","documentation_url":"https://docs.github.com/rest"}
> string:8 char:1
> + Invoke-RestMethod -Uri https://api.github.com/user/repos -Method GET  ...
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebExc
>    eption
>     + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
> ```

Maybe there is some problem with .NET packages (distributives), VS version or something else because I don't even see where is case of issue.

**Comment by nickfloyd** [comment]
Hey Falcon,

It looks like either your token does not have access to the specific resource (repos in this case) or your creds are invalid. Using what I posted [here](https://github.com/octokit/octokit.net/issues/2593#issuecomment-1275063224) should work for a personal access token with repo rights.

**Comment by Falcion** [comment]
I checked the PAT and there was permission for `repo`, I recreated PAT with all required permissions and now it works for me: thanks for helping me with this, @nickfloyd, it looks like those were "radiation from the sun" problems.
