### ISSUE TITLE
PullRequest property is always null in issues

### ISSUE THREAD

**Issue by Licho1** [octokit/octokit.net#2603]
PullRequest property is supposed to contain pull request linked to a given issue.
However even when issue is linked to a PR (and for example issue got closed by merging PR), the property is always null.

Note this happens even if Issue is retrieved with direct Issues.Get

**Comment by nickfloyd** [comment]
Hey @Licho1 ,

I am closing this issue given its over a year old.  If you still need some help on this please feel free to reopen the issue. :heart:
