### ISSUE TITLE
[BUG]: Example code for getting all releases doesn't work

### ISSUE THREAD

**Issue by Move2win** [octokit/octokit.net#2618]
### What happened?

https://octokitnet.readthedocs.io/en/latest/releases/#get-all

I added `using Octokit;` into the cs file and copied codes from the document above, then VS said CS0103, the name "client" does not exist in the current context.

Is the example code wrong? or was I using it in the wrong way?

![image](https://user-images.githubusercontent.com/45490638/203464896-6a4b4fea-28b1-483b-a94c-a3e69bf73942.png)
![image](https://user-images.githubusercontent.com/45490638/203464613-a0a1f28b-3a42-446e-8bd5-4be3a3db00ba.png)

### Versions

v4.0.1 from NuGet

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Move2win** [comment]
I tried to delete "client," and then VS said 'Repository' does not contain a definition for 'Release.'

![image](https://user-images.githubusercontent.com/45490638/203465267-b97a02ce-fbcb-40e4-a77c-16bb8400db72.png)

**Comment by nickfloyd** [comment]
Hey @Move2win,

It looks like you'll need to instantiate a `client` first - you can see how that's done in this [doc](https://octokitnet.readthedocs.io/en/latest/getting-started/) - but here's a snip to get you started:

```
var client = new GitHubClient(new ProductHeaderValue("my-cool-app"));
```

I hope this helps.

**Comment by Move2win** [comment]
> Hey @Move2win,
> 
> It looks like you'll need to instantiate a `client` first - you can see how that's done in this [doc](https://octokitnet.readthedocs.io/en/latest/getting-started/) - but here's a snip to get you started:
> 
> ```
> var client = new GitHubClient(new ProductHeaderValue("my-cool-app"));
> ```
> 
> I hope this helps.

Thank you, I didn't realize that the client is a variable. But there is another issue.
`var latest = releases[0]` doesn't work, the [] index can't use on IReadOnlyList releases.
I change that to `var latest = releases.Result.ElementAt(0);` and it works fine.

**Comment by kfcampbell** [comment]
@Move2win is this something you might have interest in opening a PR to fix? It looks like that relevant doc is defined [here](https://github.com/octokit/octokit.net/blob/6c11c1edff539f4538f7aeea3edc22305aea3f79/docs/releases.md?plain=1#L9). If not, I can do it.

**Comment by Move2win** [comment]
@kfcampbell Okay, I'll open a PR for that later.
