### ISSUE TITLE
[BUG]: Intermittent ApiValidationException 

### ISSUE THREAD

**Issue by amaltinsky** [octokit/octokit.net#2619]
### What happened?

An automated GitHub Action job that uses Octokit to manage PRs fails intermittently due to `Octokit.ApiValidationException : Validation Failed`. Example stack trace:

```
at Octokit.Connection.HandleErrors(IResponse response) in /home/runner/work/octokit.net/octokit.net/Octokit/Http/Connection.cs:line 704
at Octokit.Connection.RunRequest(IRequest request, CancellationToken cancellationToken) in /home/runner/work/octokit.net/octokit.net/Octokit/Http/Connection.cs:line 685
at Octokit.Connection.Run[T](IRequest request, CancellationToken cancellationToken) in /home/runner/work/octokit.net/octokit.net/Octokit/Http/Connection.cs:line 670
at Octokit.ApiConnection.Post[T](Uri uri, Object data, String accepts, String contentType, CancellationToken cancellationToken) in /home/runner/work/octokit.net/octokit.net/Octokit/Http/ApiConnection.cs:line 293
...
```

Re-running the job "resolves" the issue without any changes to the code or credentials.

### Versions

Octokit.net 4.0.1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nickfloyd** [comment]
Hey @amaltinsky, thanks for reaching out, and sorry for the trouble here.  This almost feels like a rate-limiting issue or cancellation that is causing the connection to be dropped - though I cannot be certain.

Would you happen to be able to provide the source (or a snip of how the SDK is being used) of the action that you are running, or a link (if it's open source)?

**Comment by amaltinsky** [comment]
I can't provide sources, but generally speaking the code does some sanity checking of our CI by creating some pull requests with changes that should pass/fail various CI stages.

It's implemented as an NUnit test fixture with a few tests. Each test creates a PR, waits until the CI is done processing it, and then checks the results. Octokit is used to manage the PRs in question - open a PR for each test, check the status by polling every 5 seconds, and close it when the test is done.

It might be worth mentioning that we're using GitHub Enterprise, and are currently on v3.6.2.

Regarding rate limiting - first of all, I kinda doubt we're anywhere near the limit. The number of tests is in the low single digits. But would hitting the limit result in a `Validation Failed` error? Because that's what we're seeing.

**Comment by kfcampbell** [comment]
A [rate limit API](https://docs.github.com/en/rest/rate-limit) exists to check to see how close you are to the rate limit. 

If rate limiting is indeed the issue, GitHub App authentication can be used to obtain a [higher rate limit](https://docs.github.com/en/developers/apps/building-github-apps/rate-limits-for-github-apps) in GitHub Enterprise Cloud. If it's GitHub Enterprise Server (the self-hosted version), [rate limiting](https://docs.github.com/en/enterprise-server@3.5/admin/configuration/configuring-your-enterprise/configuring-rate-limits) is not configured by default, is adjustable in the site admin management console, and specific users can be exempted. 

If rate limiting is not the issue, I do not have a ready explanation for that behavior. I have not yet seen it personally.

**Comment by amaltinsky** [comment]
@kfcampbell I'm aware of the existence of the rate limit API. However, the number of API calls is quite small so I don't think that's the problem. Also, I'd expect a different error in case of a rate limit issue - not "Validation Failed".

Is there any way to check whether it's a backend issue? Maybe we have some issues with our local GHE installation.

**Comment by kfcampbell** [comment]
> I'd expect a different error in case of a rate limit issue - not "Validation Failed".

> Is there any way to check whether it's a backend issue? Maybe we have some issues with our local GHE installation.

I'm sorry, I'm not sure! Do you have a GitHub representative or someone you could reach out to? I wish I could be more helpful here.

**Comment by amaltinsky** [comment]
Okay, fair enough.
Thanks anyway.
