### ISSUE TITLE
Add Islocked filter to SearchIssuesRequest API 

### ISSUE THREAD

**Issue by nickfloyd** [octokit/octokit.net#2620]
### Discussed in https://github.com/octokit/octokit.net/discussions/2615

<div type='discussions-op-text'>

<sup>Originally posted by **JimSuplizio** November 18, 2022</sup>
I'm using Octokit.net's SearchIssuesRequest for several things, and it's pretty awesome, one thing I'm having trouble with is figuring out how to search for issues that are locked/unlocked. One of the things I need to do for closed issues older than X days is lock them. We have several thousand closed issues but I haven't been able to figure out how to limit the search for only those issues that haven't been locked and I was wondering if this can be done with SearchIssuesRequest?</div>

- [ ] Filtering issues based on if they are locked or not is possible through the API - [doc](https://docs.github.com/en/search-github/searching-on-github/searching-issues-and-pull-requests#search-based-on-whether-a-conversation-is-locked)
- [ ] Can be implemented here - [source](https://github.com/octokit/octokit.net/blob/main/Octokit/Models/Request/SearchIssuesRequest.cs)
- [ ] Docs will need updating - [here](https://octokitnet.readthedocs.io/en/latest/search/#search-issues)
- [ ] Add tests / integration test

**Comment by notauserx** [comment]
I would like to take this issue. Loving how the issue is broken up with tasks with relevant links.

**Comment by JimSuplizio** [comment]
@nickfloyd - Quick question for you about this fix, what version of Octokit will this be in? I don't know the release cycle and if I should be looking at beta release for testing purposes.

**Comment by nickfloyd** [comment]
Hey @JimSuplizio, So things are fairly streamlined in this project.  Given the Holidays we've slowed things down a bit but I plan on dropping a release of this today.

**Just for clarity, we typically do the following:**
1. A user creates an issue with something that is needed, an idea, or a problem that they may be facing
2. The core maintainers do a little `triage`, prioritize it (this one is a normal) and then if acceptable,  mark it as `up-for-grabs`
3. Depending on priority and availability someone picks up the work (our friend @notauserx has done that here)
4. They will make the changes and add coverage and PR the change
5. Typically, if everything is ✅ and there are no [breaking changes](https://github.com/octokit/.github/blob/master/community/breaking_changes.md) we will merge it in and release/publish it to nuget.

As far as things like betas and release schedule, we generally reserve those for changes such as removing or adding new versions of .NET, breaking changes, etc...

I hope this helps.  Thanks again for the idea/ask, I'm looking forward to seeing it get released shortly ❤️.

**Comment by nickfloyd** [comment]
* octokit.net v4.0.3 - [Nuget release](https://www.nuget.org/packages/Octokit/4.0.3) | [GitHub release](https://github.com/octokit/octokit.net/releases/tag/v4.0.3)
* octokit.Reactive v4.0.3 - [Nuget release](https://www.nuget.org/packages/Octokit.Reactive/4.0.3) | [GitHub release](https://github.com/octokit/octokit.net/releases/tag/v4.0.3)

**Comment by JimSuplizio** [comment]
@nickfloyd, you are truly awesome, thank you!
