### ISSUE TITLE
[BUG]: Accessing renamed repositories from an app installation

### ISSUE THREAD

**Issue by bismip** [octokit/octokit.net#2627]
### What happened?

We're trying to read an issue from a repository, that has previously been renamed.

With the new name:
```
var issue = client.Issue.Get("owner", "newName", 1).Result;
```
This works as expected.

With the old name:
```
var issue = client.Issue.Get("owner", "oldName", 1).Result;
```
The program just hangs at this line (or continues and exits when using async/await).

The docs state, that redirects are followed, but this doesn't seem to be the case here. It is very confusing, as no exceptions are thrown, and it just hangs/exits without any error code.

### Versions

Octokit.NET v4.0.2, .NET Framework v4.8

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by godsonjoseph** [comment]
With the below environment:
Octokit Version 4.0.2 targetting .NET Framework 4.8 
Project with .NET Framework 4.8
and a Console App with the below code

```
internal class Program
    {
        static void Main(string[] args)
        {
            var github = new GitHubClient(new ProductHeaderValue("user"));
            var issue = github.Issue.Get("user", "oldreponame", 2).Result;
            Console.ReadLine();
        }
    }
```

I was able to see that it does not hang and it redirects to the newer repo name correctly. 

Can you try to replicate the issue on a new project? Or tell me is there something I missed in this test case?

**Comment by bismip** [comment]
@godsonjoseph I did replicate it on a new project, back then before I opened this issue. Unfortunately I don't have time to look into it these days, so you can close it. If anyone else hits this, they can comment to reopen.
