### ISSUE TITLE
Possibly wrong status code for ApiValidationException

### ISSUE THREAD

**Issue by CalvinWilkinson** [octokit/octokit.net#2639]
Hello!!

### **Description:**
I was using your library and happen to be searching the code base to verify some things and I noticed a possible issue with the `ApiValidationException` class.

I am not sure if it is an issue, which is why I created a blank issue.

I noticed one of the constructors possibly has some incorrect logic in the `Debug.Assert()` method call.  

### **Here is the issue:**
https://github.com/octokit/octokit.net/blob/450c2a149622592a7aba7ab48744f7ee554f8b7f/Octokit/Exceptions/ApiValidationException.cs#L33-L43

My question is this.  Isn't the HTTP status code for this exception suppose to be [422](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/422)?

The reason I ask is that the debug assertion description states that the exception was created with the _**WRONG**_ status code which means the code should check if it is _**NOT EQUAL**_.  But here it is checking that it is _**EQUAL**_ to 422.  If you look at the constructor at the very top of the code file, it is _**ACCEPTING**_ the value of 422.

**Code Not Allowing 422:**
https://github.com/octokit/octokit.net/blob/450c2a149622592a7aba7ab48744f7ee554f8b7f/Octokit/Exceptions/ApiValidationException.cs#L41-L42

**Constructor Allowing 422:**
https://github.com/octokit/octokit.net/blob/450c2a149622592a7aba7ab48744f7ee554f8b7f/Octokit/Exceptions/ApiValidationException.cs#L17-L22

---

Again, I just wanted to get this into the system and was not sure that this was even a problem.  I would be happy to fix the issue if you want me to.  I will also recreate a new issue of the correct type if you want.

**Comment by kfcampbell** [comment]
Hi @CalvinWilkinson, thank you for the care in submitting! I might be misunderstanding you, but I think this is desired behavior. 

You are correct that the status code for that exception should be 422, absolutely. I think where I get lost is on the Debug.Assert call: the [docs here](https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.debug.assert?view=net-7.0) mention

> Checks for a condition; if the condition is false, outputs messages and displays a message box that shows the call stack.

The Debug.Assert call uses the equality operator, but only to ensure that the condition will be false if equality is false. Does that make sense?

**Comment by CalvinWilkinson** [comment]
@kfcampbell Ah yes.

That makes perfect sense.  🙂
I was definitely thinking about it a little backward!!  That is good news!  Nothing needs to be done then.

Thanks for the quick response though and sorry to waste your time.

**Comment by kfcampbell** [comment]
No worries at all, we appreciate the care!
