### ISSUE TITLE
[FEAT]: Add functionality to check out code from specific branch

### ISSUE THREAD

**Issue by scott-david-walker** [octokit/octokit.net#2641]
### Describe the need

According to the [Github API](https://octokit.github.io/rest.js/v18#repos-get-content), you should be able to checkout code from a specific branch. However, the overload for this appears not to be available.  I can only see the overload for (owner, repo, path).

Could we add this to the library?

### SDK Version

Octokit 4.0.3

**Comment by kfcampbell** [comment]
It does look like the REST API supports downloading [repository content](https://docs.github.com/en/rest/repos/contents?apiVersion=2022-11-28#get-repository-content) from a specific branch: 

![image](https://user-images.githubusercontent.com/9327688/210423174-39144de1-777c-4d8a-97a4-3d9a6e4d9c40.png)

I also am unable to find a way to do this in octokit.net. Is this something you have interest in opening up a PR to fix?

**Comment by scott-david-walker** [comment]
Sure, I can look into adding it.

**Comment by kfcampbell** [comment]
It looks like our RepositoryContent model is [here](https://github.com/octokit/octokit.net/blob/04d2a8724f869b5975b305930bc2e83b46fdd9a9/Octokit/Models/Response/RepositoryContent.cs#L11). I would probably begin by looking at its references and seeing how it's used. There's probably a `GetRepositoryContent` client method(s) somewhere that we can overload and add tests to similarly to how it's already being done.

**Comment by scott-david-walker** [comment]
Dug into the code and found where it was. Closing as not a bug

`client.Repository.Content.GetAllContentsByRef`
