### ISSUE TITLE
Delete a parent team deletes the child teams.

### ISSUE THREAD

**Issue by ajasingh2022** [octokit/octokit.net#2646]
### What happened?

I have written a script to delete team which is unused as **0 members **or **0 repositories**.

But when I run the code to our production it deleted all the child team as well and we lost 1000 of teams.

we are helpless from GitHub as they won't be able to restore back.

Ideally **Octokit** library should not delete any child teams before confirmation as GitHub ui prompts.

Thanks
Ajay singh

### Versions

Octokit 0.51.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kfcampbell** [comment]
@ajasingh2022 that's unfortunate; I'm sorry to hear that! This behavior is not specific to octokit.net and it's documented in our API [here](https://docs.github.com/en/rest/teams/teams?apiVersion=2022-11-28#delete-a-team): 

> If you are an organization owner, deleting a parent team will delete all of its child teams as well.

Have you tried contacting [GitHub Support](https://support.github.com/contact) to create an issue or request an API change that way?
