### ISSUE TITLE
[FEAT]: Support Custom Fields on `Issue` model

### ISSUE THREAD

**Issue by taylorchasewhite** [octokit/octokit.net#2663]
### Describe the need

We’d like to use the new [Custom Fields](https://docs.github.com/en/issues/planning-and-tracking-with-projects/understanding-fields) feature in Octokit. 

Is it possible to add these to the `Issue` model?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by taylorchasewhite** [comment]
@excelkobayashi fyi.

**Comment by nickfloyd** [comment]
Hey @taylorchasewhite, Thanks for reaching out. 

Currently, custom fields are only available via GitHub GraphQL API in the ProjectsV2 resource.  While there are no plans to introduce the ProjectV2 resource in the REST API (the API that octokit.net covers), we do have a [.NET GraphQL SDK](https://github.com/octokit/octokit.graphql.net/tree/main/Octokit.GraphQL/Model) that encapsulates the [resources](https://github.com/octokit/octokit.graphql.net/blob/main/Octokit.GraphQL/Model/ProjectV2.cs) that you might be looking for.

You can also update the query below and run it in the [explorer](https://docs.github.com/en/graphql/overview/explorer) and use that directly in your project.

```
{
  repository(name: "", owner: "") {
    projectV2(number: 10) {
      fields {
        edges {
          node {
            ... on ProjectV2Field {
              id
              name
            }
          }
        }
      }
    }
  }
}
```
I hope this helps!

**Comment by bluedragonknight** [comment]
> Hey @taylorchasewhite, Thanks for reaching out.
> 
> Currently, custom fields are only available via GitHub GraphQL API in the ProjectsV2 resource. While there are no plans to introduce the ProjectV2 resource in the REST API (the API that octokit.net covers), we do have a [.NET GraphQL SDK](https://github.com/octokit/octokit.graphql.net/tree/main/Octokit.GraphQL/Model) that encapsulates the [resources](https://github.com/octokit/octokit.graphql.net/blob/main/Octokit.GraphQL/Model/ProjectV2.cs) that you might be looking for.
> 
> You can also update the query below and run it in the [explorer](https://docs.github.com/en/graphql/overview/explorer) and use that directly in your project.
> 
> ```
> {
>   repository(name: "", owner: "") {
>     projectV2(number: 10) {
>       fields {
>         edges {
>           node {
>             ... on ProjectV2Field {
>               id
>               name
>             }
>           }
>         }
>       }
>     }
>   }
> }
> ```
> 
> I hope this helps!

So is the GraphQL out of early beta or being maintained at all?  I see nothing has been touched in a while and I did see there are .Net core 3.1 references and net standard 2.0 which is not that old.  But yeah is the Octokit.GraphQL.Net out of early beta?

**Comment by kfcampbell** [comment]
octokit.graphql.net is being maintained in the sense that we triage and respond to open issues and PRs as well as merge appropriate dependency updates. GitHub's SDK team is not currently pursuing active feature development on the repository.

**Comment by bluedragonknight** [comment]
Okay…well that kind of stinks because I would prefer to use graphql over the octokit.net rest calls as graphql has more to it.  Does that team have compile instructions as I cloned it updated things to just 2.1 or net 7 over 3.1 but when I pull on the compiled DLL and try to do it the way it says it in the docs two objects never come back as objects.  The Connection and the productheadervalue never come back as objects and I’m a bit confused.

**Comment by kfcampbell** [comment]
I'm going to close this issue for now as the original question has been answered. Should you feel additional responses to the later questions/comments on the thread are needed, please open a new issue(s).
