### ISSUE TITLE
[BUG]: state_reason is not exposed for issues, affects task lists

### ISSUE THREAD

**Issue by heaths** [octokit/octokit.net#2664]
### What happened?

Without `state_reason` that is defined for Issues (see [docs](https://docs.github.com/en/rest/issues/issues?apiVersion=2022-11-28#update-an-issue:~:text=open%2C%20closed-,state_reason,-string%20or%20null), we cannot close stale issues as `not_planned`. This adversely impacts any issues with task lists referencing those issues, showing the linked issue as "completed" when, in fact, it was not and can give a false impression of current project state.

### Versions

Octokit 5.0.0 (and just checked the sources in this repo)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nickfloyd** [comment]
Hey @heaths, 

Thank you for bringing this issue up, and sorry for the trouble that it may have caused you. Is this something that you'd be interested in taking a stab at solving?  If so, we'd be glad to review a PR when ready.  

I've marked this as up-for-grabs as well, just in case anyone else in the community wants to grab it.

**Comment by nickfloyd** [comment]
oof.  Sorry about that.  I literally just found it and merged it in. Apologies for the extra noise.
