### ISSUE TITLE
Rename a folder and a file

### ISSUE THREAD

**Issue by BermudaLamb** [octokit/octokit.net#2672]
### Discussed in https://github.com/octokit/octokit.net/discussions/2670

<div type='discussions-op-text'>

<sup>Originally posted by **BermudaLamb** February 14, 2023</sup>
How do I rename a file and a folder in the repository, while keeping the folder/file history?</div>

**Comment by kfcampbell** [comment]
I've responded on #2670; let's keep the conversation there.
