### ISSUE TITLE
[FEAT]: Stream-alternative for GetRawContentByRef

### ISSUE THREAD

**Issue by hach-que** [octokit/octokit.net#2680]
### Describe the need

This is less than ideal because it has to wait for the entire file to be downloaded and present in the `byte[]` array returned from `GetRawContentByRef`:

```csharp
using (var memory = new MemoryStream(await _client.Repository.Content.GetRawContentByRef(
    _owner,
    _repo,
    destinationPath,
    sha)))
{
    using (var writer = new FileStream(destinationPath, System.IO.FileMode.Create, FileAccess.Write, FileShare.None))
    {
        await memory.CopyToAsync(writer);
    }
}
```

Instead, it'd be more efficient if there was a stream alternative of `GetRawContentByRef`:

```csharp
using (var stream = await _client.Repository.Content.GetRawContentStreamByRef(
    _owner,
    _repo,
    destinationPath,
    sha))
{
    using (var writer = new FileStream(destinationPath, System.IO.FileMode.Create, FileAccess.Write, FileShare.None))
    {
        await stream.CopyToAsync(writer);
    }
}
```

### SDK Version

Octokit 5.0.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nickfloyd** [comment]
Hey @hach-que, thanks for reaching out ❤️ .  This is a solid idea. Would it be something you'd be interested in implementing?  Either way, we'll put this in the backlog to get prioritized - thanks again for putting the idea out there and letting us know!

**Comment by hach-que** [comment]
Hi @nickfloyd, I probably won't get a chance to do a merge request. I did end up getting something working at an API level, but the performance of the GitHub API was just too slow for fetching individual files for my use-case (regularly 300ms+ to fetch a single file). I plan to look at using the Git protocol over SSH directly to fetch arbitrary blobs at some point in the future, since I think that should have lower latency for on-demand data fetching.

What I did end up with is this:

```csharp
using (var client = new HttpClient())
{
    client.DefaultRequestHeaders.Add("User-Agent", $"user-agent");
    client.DefaultRequestHeaders.Add("Authorization", $"Bearer {_client.Credentials.GetToken()}");
    client.DefaultRequestHeaders.Add("Accept", "application/vnd.github.raw");
    client.DefaultRequestHeaders.Add("X-GitHub-Api-Version", "2022-11-28");

    var url = $"https://api.github.com/repos/{_owner}/{_repo}/git/blobs/{sha}";
    var response = await client.GetAsync(url);
    if (!response.IsSuccessStatusCode)
    {
        var message = await response.Content.ReadAsStringAsync();
        response.EnsureSuccessStatusCode();
    }

    using (var stream = await response.Content.ReadAsStreamAsync())
    {
        // ... do stuff with the stream
    }
}
```

so feel free to adapt this for Octokit.

**Comment by nickfloyd** [comment]
Hey @hach-que, thanks for getting back to us, and sorry about the slowness.  We are working to make things better around things such as latency.  

We appreciate you sharing the snip. Hopefully, we can use it to improve things for others in the community. ❤️

**Comment by hach-que** [comment]
@nickfloyd For context, my use case is virtualising Git repos on Windows and making it so that individual files in a Git repository can be fetched as they're accessed for the first time. Because build processes that scan directories might want to iteratively read through files, for it to be practical the latency needs to be fairly low. I don't know if this helps your planning around latency optimisation, but thought I'd mention it.
