### ISSUE TITLE
[FEAT]: PackageVersion has no tag reported for container type

### ISSUE THREAD

**Issue by GaudinValentin** [octokit/octokit.net#2683]
### What happened?

Hi guys,
Just to let you know, when calling for example Packages.PackageVersions.GetAllForOrg(owner, packageType, packageName) for a container type, we are getting the packages (PackageVersion type) but the Metadata is incomplete: Container section is not present and so Tags are also not present... we are getting only the package type as Metadata.
thus, it's not easy to find a container from its tag.
I used the GetAllForOrg method but from what I saw in the code, all methods returning the PackageVersion should produce the same result.
![DebugView](https://user-images.githubusercontent.com/94403552/226032718-6e5e9151-6deb-4685-923f-4d8413335f5b.PNG)
![ApiReponse](https://user-images.githubusercontent.com/94403552/226032806-cd2bba6f-7aa4-4577-ae37-b7af3e03ecdb.PNG)

### Versions

v5.0.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nickfloyd** [comment]
Hey @GaudinValentin, Thanks for reaching out! So from the PackageVersion [model](https://github.com/octokit/octokit.net/blob/7d01bad2971b751f3b6736c57c9349d318a37293/Octokit/Models/Response/PackageVersion.cs#L54) it looks like the only property implemented is `PackageType` just as you said above.

Is this something that you'd be interested in adding to the SDK?  I validated (just as you did) that the API is returning the data so all that would be needed here would be to add the fields and their accessors to `PackageVersion` and the serializer should take care of the rest.

I'll mark this as up for grabs as well just in case another community member would like to add the properties.

Thanks again! ❤️
