### ISSUE TITLE
[BUG]: Missing workflow run conclusions

### ISSUE THREAD

**Issue by ezhevita** [octokit/octokit.net#2684]
### What happened?

Our company has a service that is grabbing GitHub workflow run data and then store it locally for further analysis. However the library was throwing exceptions for some of those workflow runs with the message `Value 'startup_failure' is not a valid 'WorkflowRunConclusion' enum value`. I've checked the source code of Octokit.NET and it wasn't there indeed, so I've checked GitHub API reference to make sure this is properly documented. However, all of the REST API documentation doesn't mention this conclusion anywhere ([Using the REST API to interact with checks](https://docs.github.com/en/rest/guides/using-the-rest-api-to-interact-with-checks), [Check Runs REST API](https://docs.github.com/en/rest/checks/runs), [Workflow runs REST API](https://docs.github.com/en/rest/actions/workflow-runs), [Creating CI tests with the Checks API](https://docs.github.com/en/apps/creating-github-apps/guides/creating-ci-tests-with-the-checks-api)) and the only place this conclusion is mentioned is in [GraphQL reference](https://docs.github.com/en/graphql/reference/enums#checkconclusionstate).

I have prepared a branch with the fix to the library (however the GitHub documentation is still broken), so the pull request should follow shortly after the issue.

also misc: the Code of Conduct link is broken in the issue template and actually is leading [to issues](https://github.com/octokit/octokit.net/issues/CODE_OF_CONDUCT.md) :p

### Versions

Octokit.Net 4.0.2, .NET 6.0.14

### Relevant log output

```shell
System.ArgumentException: Value 'startup_failure' is not a valid 'WorkflowRunConclusion' enum value.
  File "/home/runner/work/octokit.net/octokit.net/Octokit/Models/Response/StringEnum.cs", line 146, col 17, in ParseValue
  File "/home/runner/work/octokit.net/octokit.net/Octokit/Models/Response/StringEnum.cs", line 45, col 19, in get_Value
  ... application stacktrace ...
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nickfloyd** [comment]
Hey @ezhevita, thanks for the double catch and thoroughness and follow-through on checking the API docs.

This is one of those cases where we have to go to the [GitHub OpenAPI definitions](https://github.com/github/rest-api-description) to validate the enum - which `startup_failure` is included in that set.  

It's a great call out that I'll bring up to our OpenAPI working group to see if these types of enums can get better representation in our docs.
