### ISSUE TITLE
[BUG]: Getting Octokit.ApiException while trying to search repositories

### ISSUE THREAD

**Issue by NiharikaNimaje** [octokit/octokit.net#2700]
### What happened?

Hi Team,

We have dot net application which connects to our enterprise Git Hub using Octo Kit api and searches the repositories available over there.
We have code in place which used to work few days back but suddenly it has stopped working for one of our repository. 
It is giving below error:

An internal error occurred: System.AggregateException: One or more errors occurred. ---> Octokit.ApiException: An error occurred with this API request
at Octokit.Connection.HandleErrors(IResponse response) in /home/runner/work/octokit.net/octokit.net/Octokit/Http/Connection.cs:line 705

It is still working for other repositories that we have, but failing for one repo. Kindly help.

### Versions

Octokit 5.0.4.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kfcampbell** [comment]
Can you reproduce this problem on a public repo? I don't think there's enough information as-is to troubleshoot effectively.
