### ISSUE TITLE
[FEAT]: Add the before property to PushEventPayload

### ISSUE THREAD

**Issue by juliangiebel** [octokit/octokit.net#2720]
### Describe the need

The `PushEventPayload` is missing the `before` property described in the github webhook documentation:
https://docs.github.com/en/webhooks-and-events/events/github-event-types#pushevent

![image](https://github.com/octokit/octokit.net/assets/8915246/d878a61c-f968-4c38-9c28-b8827e296508)

### SDK Version

Octokit.net v6.0.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by michaeljolley** [comment]
I submitted a PR for this today. Also, included the missing `push_id` and `distinct_size` properties.
