### ISSUE TITLE
[BUG]: Deserializing WorkflowJob from WorkflowJobEvent webhooks fails

### ISSUE THREAD

**Issue by lineville** [octokit/octokit.net#2724]
### What happened?

I attempted to deserialize a webhook payload that is triggered by a `WorkflowJobEvent` into the Octokit `WorkflowJob` model, and this fails because the `WorkflowJob` model in octokit.net and webhooks.net are a bit out of sync. The error when calling `SimpleJsonSerializer.Deserialize<WorkflowJob>()` fails if the workflow job json has null values for properties that it expects to be non-nullable. However, there are many cases where the WorkflowJob has null values for fields like (`RunnerId, RunnerName, RunnerGroupId, RunnerGroupName`) which causes the deserialization to fail. I have a fix for this that I've tested and will open a PR shortly.

### Versions

Octokit.net version `6.0.0`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vuryleo** [comment]
Similar stuff happens if trying to get a workflowjob via `Octokit.IGitHubClient.Actions.Workflows.Jobs` w/o runnerid etc, it will raise `NullReferenceException` when there's null value.
