### ISSUE TITLE
[FEAT]: Add CreatedAt field to WorkflowJob Model

### ISSUE THREAD

**Issue by lineville** [octokit/octokit.net#2728]
### Describe the need

The current Octokit model for `WorkflowJob` is missing the `CreatedAt` field which was recently added to the [REST API for listing workflow jobs](https://docs.github.com/en/rest/actions/workflow-jobs?apiVersion=2022-11-28#list-jobs-for-a-workflow-run). I would like to contribute a small PR that adds this field to the model.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kfcampbell** [comment]
@lineville I don't see `created_at` in the docs linked above. Has it been publicly released yet?

**Comment by lineville** [comment]
@kfcampbell so oddly enough they don't show that field in the "Example Response" tab but it is shown in the "Response Schema" and listed as non-nullable. In my testing calling the API directly, it is including the field. I believe this is a somewhat recent addition, at least in the somewhat recent past this property wasn't there, so I'm guessing the docs there are just lagging behind a bit (at least in the response example)

**Comment by kfcampbell** [comment]
Interesting! Thanks for the background.

**Comment by lineville** [comment]
@kfcampbell Any plans to cut a release in the near future 😄 ?

**Comment by lineville** [comment]
@kfcampbell Thanks so much, appreciate the quick turnaround 🙏
