### ISSUE TITLE
[BUG]: There's no WorkflowJobStatus.Waiting

### ISSUE THREAD

**Issue by vuryleo** [octokit/octokit.net#2730]
### What happened?

While querying for the workflow job status, suddenly it returns sth other than `queued` `in_progress` nor `completed` but `waiting`.
As it's waiting for some prod approval.

### Versions

octoket v6.1.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kfcampbell** [comment]
Interesting...it seems like that was missed in the specification. The docs [here](https://docs.github.com/en/rest/actions/workflow-jobs?apiVersion=2022-11-28) show the following options:

```json
    "status": {
      "description": "The phase of the lifecycle that the job is currently in.",
      "type": "string",
      "enum": [
        "queued",
        "in_progress",
        "completed"
      ],
      "examples": [
        "queued"
      ]
    },
```

but I do see where the API returns `waiting`.

**Comment by kfcampbell** [comment]
It seems like there's several API schemas that do and do not have "waiting" as a status. The docs linked above also have a "Get a job for a workflow run" endpoint that returns (in part):

```json
    "status": {
      "description": "The phase of the lifecycle that the job is currently in.",
      "type": "string",
      "enum": [
        "queued",
        "in_progress",
        "completed"
      ],
      "examples": [
        "queued"
      ]
    },
```

Since Octokit.net has one model we share across these endpoints, your PR looks reasonable.

**Comment by vuryleo** [comment]
Yes, however, in my case it's just returning as an response from a `get a workflowjob` API. Perhaps the document is kind of outdated.
