### ISSUE TITLE
[FEAT]: Support refreshtokens in OAuth flow

### ISSUE THREAD

**Issue by Kencdk** [octokit/octokit.net#2731]
### Describe the need

While the library currently supports getting access tokens from an OAuth callback, the resulting object doesn't include the refresh token, which allows an application to get a new access token for the user, without having to go through the entire OAuth flow again.

Additionally, the OAuthClient doesn't support a way to get an access token from a refresh token.

The refresh token is returned in the original request to get an access token.
https://docs.github.com/en/apps/creating-github-apps/authenticating-with-a-github-app/generating-a-user-access-token-for-a-github-app
https://docs.github.com/en/apps/creating-github-apps/authenticating-with-a-github-app/refreshing-user-access-tokens

Proposal:
Add RefreshToken as a property on [Octokit/Models/Response/OauthToken.cs](https://github.com/octokit/octokit.net/blob/afac3e0bcfc853a61f0decde6fe1da1b1124f53b/Octokit/Models/Response/OauthToken.cs)
Add RefreshToken as a property on [Octokit/Models/Request/OauthTokenRequest.cs](https://github.com/octokit/octokit.net/blob/afac3e0bcfc853a61f0decde6fe1da1b1124f53b/Octokit/Models/Request/OauthTokenRequest.cs)

If a OauthTokenRequest contains a RefreshToken but the AuthToken is null only the refresh_token property should be added to the request body due to the null check in [RequestParameters.cs::ToParametersDictionary()](https://github.com/octokit/octokit.net/blob/afac3e0bcfc853a61f0decde6fe1da1b1124f53b/Octokit/Models/Request/RequestParameters.cs#L24)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Kencdk** [comment]
if the proposal is accepted, I'd gladly implement it :)

**Comment by kfcampbell** [comment]
@Kencdk that seems reasonable to me! PRs are always appreciated.
