### ISSUE TITLE
[FEAT]: Allow managing Copilot for Business seats with new CopilotClient

### ISSUE THREAD

**Issue by dylan-asos** [octokit/octokit.net#2750]
### Describe the need

A new API is available (in beta) that allows managing Copilot for Business license allocations. 

https://docs.github.com/en/rest/copilot/copilot-for-business?apiVersion=2022-11-28

Implement the API methods in a new `CopilotClient` class, allowing integration opportunities to manage Copilot setup.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dylan-asos** [comment]
I'll probably pick this up as have a vested interest. Let me know if any thoughts around the beta/breaking change element to this. 

Any way to have a vNext/Beta path + publish a pre-release version of the nuget package? e.g. 7.0.1-beta.  Or, trying to keep that overhead out of the process and prefer to keep everything on stable semver?

**Comment by kfcampbell** [comment]
My vote would be to follow the Microsoft [Nuget pre-release guidelines](https://learn.microsoft.com/en-us/nuget/create-packages/prerelease-packages) and then detail the beta changes in our release notes. If we wanted to get more specific, perhaps we could explore using custom attributes to mark specific functions, though I don't think that's necessary at this point.
