### ISSUE TITLE
[FEAT]: Implement variables support

### ISSUE THREAD

**Issue by timheuer** [octokit/octokit.net#2753]
### Describe the need

Repository variables (and environment variables) are not implemented.  This is similar to #2752, but there are environment secrets/variables but also just repository secrets/variables.  Repository secrets are the only thing currently implemented in Octokit

### SDK Version

7.0.1

### API Version

3

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by michaeljolley** [comment]
@timheuer, is this issue specifically for repository variables? Or are you looking for org secrets/variables in this as well?

Happy to take it on regardless, just want to define the scope.

**Comment by timheuer** [comment]
I'd be happy to start with just repository.

**Comment by michaeljolley** [comment]
One more question @timheuer. I'm ready to submit a PR excluding documentation. However, I don't see where any of the repository endpoints associated with Actions are documented. I'm not sure where (or if at this point) I should add them. It seems there needs to be some information architecture decisions on the docs themselves. 

I'll submit the PR in draft mode until I receive direction.

**Comment by timheuer** [comment]
> I don't see where any of the repository endpoints associated with Actions are documented

Yeah, good point, not sure either.  The Environments Secrets are documented: https://docs.github.com/en/rest/actions/secrets?apiVersion=2022-11-28#list-environment-secrets

**Comment by michaeljolley** [comment]
Ah. Misunderstanding. 

I don't see where any of the repository endpoints associated with Actions are documented in the [Octokit.net docs](https://github.com/octokit/octokit.net/tree/main/docs). In fact, I don't see documentation for any of the repository related clients.

**Comment by timheuer** [comment]
> I don't see where any of the repository endpoints associated with Actions are documented in the [Octokit.net docs](https://github.com/octokit/octokit.net/tree/main/docs?rgh-link-date=2023-10-05T17%3A27%3A17Z). In fact, I don't see documentation for any of the repository related clients.

Yeah looks like a gap right now.
