### ISSUE TITLE
[BUG]: The `Labels` in SearchIssuesRequest is flawed

### ISSUE THREAD

**Issue by capdiem** [octokit/octokit.net#2762]
### What happened?

When there is only one label, there is no problem. 
But if there are more than one, like the problem I encountered, I can't do [`label:Label,Label`](https://docs.github.com/en/search-github/searching-on-github/searching-issues-and-pull-requests#search-by-label).

> label:bug,resolved matches issues with the label "bug" or the label "resolved."

```cs
var request = new SearchIssuesRequest();
request.Labels = new[] { "bug,resolved" }; // error
```
Labels would be format to `label:"bug,resolved"`, This means that "bug,resolved" is one label, not two. The right thing should be `label:bug,resolved` or `label:"bug","resolved"`.

#2084 changed it, I can understand. But it also caused the current problem. 

### Versions

7.1.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kfcampbell** [comment]
Agreed that what you describe should be the correct behavior. Do you have the interest/inclination to open up a PR to fix this behavior?
