### ISSUE TITLE
[Feature]: IActionsArtifactsClient is empty and has no methods available to call

### ISSUE THREAD

**Issue by thomhurst** [octokit/octokit.net#2780]
### What happened?

I'm not sure to raise this as a bug or feature, as I'm not sure whether it's just not been developed yet, or it's been overlooked/forgotten about.

The `IActionsArtifactsClient` is empty - So it seems pointless to expose this to the user.

I'd like to be able to download/upload artifacts from Workflows using Octokit, but there's no methods available to call to do this.

```csharp
_gitHubClient.Actions.Artifacts. // No methods other than `object` methods available to call
```

```csharp
namespace Octokit
{
    /// <summary>
    /// A client for GitHub's Actions Artifacts API.
    /// </summary>
    /// <remarks>
    /// See the <a href="https://developer.github.com/v3/actions/artifacts/">Actions Artifacts API documentation</a> for more information.
    /// </remarks>
    public interface IActionsArtifactsClient
    {
    }
}

```

### Versions

Octokit (NuGet) 7.1.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nickfloyd** [comment]
Hey @thomhurst, thanks for this ❤️.  It simply has not been implemented.  But to your point it would be a great addition.  I've labeled it with `up for grabs` and `hacktoberfest` just in case the community (or you 😉) want's to take on the change set for it.

**Comment by thomhurst** [comment]
Thanks @nickfloyd ! I decided to take you up on the offer and gave it a go myself.
