### ISSUE TITLE
RobiniaDocs API Explorer

### ISSUE THREAD

**Issue by NeuroXiq** [octokit/octokit.net#2781]
### Describe the need

Maybe You will be interested in hosting API Explorer online:
https://www.robiniadocs.com/d/octokit/api/Octokit.html

This is ready-to-go, so above link can be added to README.md for other people to see it.
Or using ready shields.io badge:

[![Static Badge](https://img.shields.io/badge/API%20Docs-RobiniaDocs-43bc00?logo=readme&logoColor=white)](https://www.robiniadocs.com/d/octokit/api/Octokit.html)

```
[![Static Badge](https://img.shields.io/badge/API%20Docs-RobiniaDocs-43bc00?logo=readme&logoColor=white)](https://www.robiniadocs.com/d/octokit/api/Octokit.html)
```

https://github.com/NeuroXiq/RobiniaDocs

Regards
NeuroXiq

### API Version

This will apply to newest version (system downloads newest version automatically)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nickfloyd** [comment]
@NeuroXiq Hey thanks for the info and work on [RobiniaDocs](https://github.com/NeuroXiq/RobiniaDocs) - it looks good.  We'll take a look at this in a bit and see what it would look like as far as giving our community a healthy bump in docs...

Thanks again for letting us know about your project! cc: @kfcampbell
