### ISSUE TITLE
[BUG]: Dates are not returned

### ISSUE THREAD

**Issue by aloneguid** [octokit/octokit.net#2784]
### What happened?

```csharp
var stars2 = await client.Activity.Starring.GetAllStargazersWithTimestamps("user", "repo");
```

returns null users and default dates:

![image](https://github.com/octokit/octokit.net/assets/3155189/c08eb2ba-996b-456d-9aab-c3eb6fa2a0e1)

### Versions

8.0.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nickfloyd** [comment]
Hey @aloneguid, it looks like the header value is not being applied in these requests.  According to the docs:

> There is one supported custom media type for these endpoints. When you use this custom media type, you will receive a response with the starred_at timestamp property that indicates the time the star was created. The response also has a second property that includes the resource that is returned when the custom media type is not included. The property that contains the resource will be either user or repo.

`application/vnd.github.star+json`

ex. 
`curl  https://api.github.com/repos/Octokit/octokit.net/stargazers -H 'accept:application/vnd.github.star+json'`

It really should be provided [here](https://github.com/octokit/octokit.net/blob/03e7644f5ec2bbb9299d4531ca17a14c7569af60/Octokit/Clients/StarredClient.cs#L130C60-L130C60) in the base implementation of `GetAllStargazersWithTimestamps` 

I'll put this in our backlog and label it with `up for grabs` - feel free to tackle it if you get a moment and thank you for helping this SDK and community get better at what it does! ❤
