### ISSUE TITLE
[BUG]:  not all releases are being fetched.

### ISSUE THREAD

**Issue by LiorBanai** [octokit/octokit.net#2788]
### What happened?

trying to fetch all my releases from 
https://github.com/Analogy-LogViewer/Analogy.LogViewer/releases

![image](https://github.com/octokit/octokit.net/assets/36262995/072e9b84-46c6-499e-88d0-c64e10c0a162)

it does not fetch latest release:
![image](https://github.com/octokit/octokit.net/assets/36262995/3b1b2a85-0eb4-4c08-bb16-e09ebfc59fe8)

the code:
```cs
 var client = new GitHubClient(new ProductHeaderValue("Analogy.LogViewer.Analogy"));
 IReadOnlyList<Release>? releases = await client.Repository.Release.GetAll("Analogy-LogViewer","Analogy.LogViewer");
 return releases;
```
### Versions
8.0.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nickfloyd** [comment]
Hey @LiorBanai tried a repo case using octokit.net

```
 var client = new GitHubClient(new ProductHeaderValue("Octokit.net-sample-app"));
 IReadOnlyList<Release>? releases = await client.Repository.Release.GetAll("Octokit","octokit.net");
 Console.WriteLine(releases.Count());
```

It returned the correct number of releases (103) (run on Oct 3rd 2023)

As far as your releases go - I see that this [list](https://github.com/Analogy-LogViewer/Analogy.LogViewer/releases) is missing your latest release and the [tags section](https://github.com/Analogy-LogViewer/Analogy.LogViewer/releases/tag/v5.1.0.0) has it.

For whatever reason it appears that v5.1.0.0 is not considered a release in the GitHub UI.  I reviewed the actions runner and your workflow file for releases and everything looked like it ran successful. I couldn't find a doc on how you release so perhaps there is something in the workflow that got missed (that wouldn't make too much sense given you've release 65 other times - why would this one be any different).

It appears that Octokit is returning the data that the GitHub REST API is giving it.  You might consider reaching out to GitHub [support](https://support.github.com/) and drop a request there.

**Comment by LiorBanai** [comment]
@nickfloyd I'll do some checks and try to investigate this. The release was manual like all othe releases..
I'll update..

**Comment by LiorBanai** [comment]
funny. I went inside the release and"edit" it by just pressing the "Update release" button and everything was fixed. I guess it was hiccups on Github side.

closing it now :)
