### ISSUE TITLE
[FEAT]: Move all types to Octokit namespace

### ISSUE THREAD

**Issue by TanukiSharp** [octokit/octokit.net#2845]
### Describe the need

Could you move all types to the `Octokit` namespace please ?

Today I realized (the hard way) that `Artifact` and `ArtifactWorkflowRun` types have no namespace, and it messed up my work since we also have a type named `Artifact`. I recently updated from 7.1 to 9.0 and apparently that's the reason, the type `Artifact` was added in commit 958bc5f1f87cd97cd8520ac74f958c2df12903b3 and broke our code.

While you are at it, please make sure there are no other types without namespace.

Thanks.

### SDK Version

Octokit.net v9.0.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by anjolaoluwaakindipe** [comment]
Is it cool if I could tackle this issue

**Comment by wesdevpro** [comment]
> Is it cool if I could tackle this issue

Absolutely! It's up for grabs. Take a whack at it!
