### ISSUE TITLE
[DOCS]: ScriptCs.OctoKit is Deprecated/Archived

### ISSUE THREAD

**Issue by WesBossPro** [octokit/octokit.net#2851]
### Describe the need

Remove https://github.com/hnrkndrssn/ScriptCs.OctoKit links from the docs or note as an archived repo.

### SDK Version

Octokit.net v9.1.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wesdevpro** [comment]
@kfcampbell I will create a PR sometime this evening to simply remove the link from the readme. Please let me know if you would rather me leave the link and just mention that the project is Deprecated/Archived.

**Comment by kfcampbell** [comment]
@wesdevpro thanks! While you're at it, would you mind removing the "Related Projects" section entirely, with ScriptCs.OctokitLibrary as well? That hasn't been touched in 9 years; I think it's okay to delete it too.

**Comment by wesdevpro** [comment]
@kfcampbell thank you for your quick response⚡
