### ISSUE TITLE
[BUG]: class Artifact is in global namespace

### ISSUE THREAD

**Issue by darthkurak** [octokit/octokit.net#2861]
### What happened?

I am using Nuke. 
I have my custom code to define Build and have defined the Artifact class in my custom code. 
After updating Nuke to the new version 8.0.0 which depends on >= 9.0.0, the Artifact class from Octokit wins with my custom class which breaks usages of my library and I can't fix this without breaking change. 
This is because Artifact from Octokit is in the global namespace. 

Is there any chance that this type could be moved to some namespace? :) 

### Versions

9.0.0 for sure. 

### Relevant log output

```shell
Namespace '<global namespace>' contains a definition conflicting with alias 'Artifact'
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by amis92** [comment]
It seems in general all models have the `namespace Octokit`, except those added in #2782 (see [diff](https://github.com/octokit/octokit.net/commit/958bc5f1f87cd97cd8520ac74f958c2df12903b3#diff-9c7ccb897b1c829bd899598cc978d92c18371daa9a39406f3cf1eabdd8164eed))

@nickfloyd you've approved that PR from @thomhurst any chance for a fix?

**Comment by thomhurst** [comment]
Apologies. Must've had some weird IDE settings on that didn't want to add namespaces.
Have added namespaces in #2862.

**Comment by nickfloyd** [comment]
oof great catch y'all... Thank you @thomhurst for the follow up here - I'll get reviewed and out the door shortly

**Comment by nickfloyd** [comment]
The fix has been [released](https://www.nuget.org/packages/Octokit/9.1.1). Again, apologies for the trouble and thanks @thomhurst for the super quick fix.

**Comment by amis92** [comment]
Thanks so much!
