### ISSUE TITLE
[BUG]: Query DeploymentEnvironments throws exception

### ISSUE THREAD

**Issue by jessehouwing** [octokit/octokit.net#2931]
### What happened?

Same issue as: #2927

But for DeploymentEnvironments

![image](https://github.com/octokit/octokit.net/assets/4173387/9f0e2dd1-5947-47d7-a3e7-cebd8751b589)

### Versions

v12

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jessehouwing** [comment]
It would be my guess that it makes sense to upgrade **ALL** `int id` to `long id`.

**Comment by jessehouwing** [comment]
No time for a PR yet, did a quick patch for only Environments:

https://github.com/globaldevopsexperience/octokit.net/commit/01a26b4026adaa944e20273f8c85a93399f9893a

**Comment by martincostello** [comment]
Looks like a dupe of #2893.

**Comment by jessehouwing** [comment]
Looks like it.
