### ISSUE TITLE
[BUG]: #2747 closed but can't reopen

### ISSUE THREAD

**Issue by mitchcapper** [octokit/octokit.net#2942]
### What happened?

#2747 got automagically closed by the bug bot (and it happily labeled it as done too;0).   To keep it open required adding a label but not sure non members can do so.   I don't know if done items automatically convert to release notes but that also might be awkward;)

### Versions

n/a

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kfcampbell** [comment]
I've reopened #2747 (and pinned it) and I'll now close this issue.
