### ISSUE TITLE
[MAINT]: Release 13.0.1 refers to tag 13.1.0

### ISSUE THREAD

**Issue by lg2de** [octokit/octokit.net#2950]
### Describe the need

The recent release 13.0.1 refers to a tag which is not existing (anymore):
`Full Changelog: https://github.com/octokit/octokit.net/compare/v13.0.0...v13.1.0`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kfcampbell** [comment]
I've now fixed that link!
