### ISSUE TITLE
[BUG]: Octokit.NotFoundException

### ISSUE THREAD

**Issue by ghost** [octokit/octokit.net#2969]
### What happened?

I try octokit for the first time using nuget package 13.0.1

This is my code

async public Task UpdateGithub()
{
    var ghClient = new GitHubClient(new ProductHeaderValue("Octokit"));
    ghClient.Credentials = new Credentials("login", "password");

    // github variables
    var owner = "owner";
    var repo = "repo.github.io";
    var branch = "main";

    var targetFile = "test.txt";

    try
    {
        // try to get the file (and with the file the last commit sha)
        var existingFile = await ghClient.Repository.Content.GetAllContentsByRef(owner, repo, targetFile, branch);

        // update the file
        var updateChangeSet = await ghClient.Repository.Content.UpdateFile(owner, repo, targetFile, new UpdateFileRequest("API File update", "Hello Universe! " + DateTime.UtcNow, existingFile.First().Sha, branch));
    }
    catch (Octokit.NotFoundException)
    {
        // if file is not found, create it
        var createChangeSet = await ghClient.Repository.Content.CreateFile(owner, repo, targetFile, new CreateFileRequest("API File creation", "Hello Universe! " + DateTime.UtcNow, branch));
    }
}

I get 2 times a Octokit.NotFoundException.
Can somebody tell me what's wrong and why?

I replaced "login", "password", "owner", "repo.github.io" and "main" by the correct value for my github repo.

Jessica

### Versions

Octokit nuget  13.0.1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kfcampbell** [comment]
Are you actually using your GitHub password to authenticate? We removed support for that as of August 2021 IIRC. If so, you'll need to generate a Personal Access Token and use that to authenticate instead.

**Comment by ebisarlak** [comment]
Wedeal our not visa cart yo buy original pac game

در تاریخ شنبه ۲۸ سپتامبر ۲۰۲۴،‏ ۲:۱۳ thevirtualarcade <
***@***.***> نوشت:
