### ISSUE TITLE
Implement Organizations Teams API

### ISSUE THREAD

**Issue by alfhenrik** [octokit/octokit.net#331]
http://developer.github.com/v3/orgs/teams

- [x] http://developer.github.com/v3/orgs/teams/#get-team
- [x] http://developer.github.com/v3/orgs/teams/#list-team-members
- [ ] ~~http://developer.github.com/v3/orgs/teams/#get-team-member~~ to be deprecated, use https://developer.github.com/v3/orgs/teams/#get-team-membership
- [ ] ~~http://developer.github.com/v3/orgs/teams/#add-team-member~~ to be deprecated, use https://developer.github.com/v3/orgs/teams/#add-team-membership
- [ ] ~~http://developer.github.com/v3/orgs/teams/#remove-team-member~~ to be deprecated, use https://developer.github.com/v3/orgs/teams/#remove-team-membership
- [x] http://developer.github.com/v3/orgs/teams/#list-team-repos
- [x] http://developer.github.com/v3/orgs/teams/#get-team-repo
- [x] http://developer.github.com/v3/orgs/teams/#add-team-repo
- [x] http://developer.github.com/v3/orgs/teams/#remove-team-repo
- [ ] http://developer.github.com/v3/orgs/teams/#list-user-teams

**Comment by shiftkey** [comment]
Closing this out as #795 completed the missing bits
