### ISSUE TITLE
Implement Repository Contents API

### ISSUE THREAD

**Issue by alfhenrik** [octokit/octokit.net#334]
http://developer.github.com/v3/repos/contents/

- [x] http://developer.github.com/v3/repos/contents/#get-contents
- [x] http://developer.github.com/v3/repos/contents/#create-a-file
- [x] http://developer.github.com/v3/repos/contents/#update-a-file
- [x] http://developer.github.com/v3/repos/contents/#delete-a-file
- ~~[ ] http://developer.github.com/v3/repos/contents/#get-archive-link~~ moved to https://github.com/octokit/octokit.net/issues/748

**Comment by shiftkey** [comment]
This finally landed in #649
