### ISSUE TITLE
Create repository tests fail

### ISSUE THREAD

**Issue by lbargaoanu** [octokit/octokit.net#342]
CreatesANewPublicRepository failed with "404 Not Found", could not reproduce the next day, probably a fluke. CreatesANewPrivateRepository:

POST https://api.github.com/user/repos
{"name":"private-repo-20140124010515796","private":true}
HTTP/1.1 422 Unprocessable Entity
{"message":"Validation Failed","documentation_url":"http://developer.github.com/v3/repos/#create","errors":[{"resource":"Repository","code":"custom","field":"name","message":"name can't be private. You are over your quota."}]}

**Comment by shiftkey** [comment]
`TheCreateMethodForUser.CreateANewPrivateRepository` was moved over to `[PaidAccountTest]` in https://github.com/octokit/octokit.net/pull/656. 

`TheCreateMethodForOrganization.CreateANewPublicRepository` was moved over to `[OrganizationTest]` in https://github.com/octokit/octokit.net/pull/634.

I think that's all that needed to be done here. :hocho:
