### ISSUE TITLE
Should we add overloads that take concrete types?

### ISSUE THREAD

**Issue by Haacked** [octokit/octokit.net#347]
Most of our methods take in string identifiers. For example, to get the list of members for an org, you pass in the org name.

I wonder if we should add overloads that take in the full `Organization` type as well? This would make chaining a bit nicer. For example:

__Before__

```csharp
orgsClient.GetAllForCurrent()
  .SelectMany(org => orgsClient.Member.GetAll(org.Login));
```

__After__

```csharp
orgsClient.GetAllForCurrent()
  .SelectMany(orgsClient.Member.GetAll);
```

It's mostly cosmetic, but kind of nice.

**Comment by shiftkey** [comment]
Looking back on this, I'm kinda neutral on the idea.

Can we think about some other areas here where things can be improved?

**Comment by shiftkey** [comment]
This has been sitting here a while. Please drop a comment in here if someone gets sufficiently caremad enough to tackle this.
