### ISSUE TITLE
Signed Octokit Releases - Yea or Nay?

### ISSUE THREAD

**Issue by shiftkey** [octokit/octokit.net#405]
So #404 landed, and I wanted to have a proper discussion about whether we should do this in an official capacity for Octokit releases. 

So let the fur fly (remember, bonus points for good reasoning and being gentlemanly) and I'll check back in a few days to see who is left standing...

![fight3](https://f.cloud.github.com/assets/359239/2291194/a8aa9d7a-a037-11e3-9621-474b59d9e8c8.gif)
![fight2](https://f.cloud.github.com/assets/359239/2291195/a8ade336-a037-11e3-96f0-4e2083f446cc.gif)
![fight4](https://f.cloud.github.com/assets/359239/2291198/b7b0eb62-a037-11e3-98c3-f9ecbc8c49db.gif)
![fight1](https://f.cloud.github.com/assets/359239/2291196/a8b172e4-a037-11e3-914c-1a6ce3c66fac.gif)

**Comment by nickfloyd** [comment]
Hey Friends,

As a factor of closing the loop on this - we have just shipped the first signed Octokit .NET.  Regardless of where you might've been originally on this approach - after a few years, we have completed what [we set out to do](https://github.com/octokit/octokit.net/blob/main/docs/strong-naming.md) after this conversation.

❤️ Thank you to everyone who contributed to the above and to Octokit .NET itself - we could not do any of this without y'all!

Special hat-tip to @shiftkey for having the courage to begin this discussion and making the [decision](https://github.com/octokit/octokit.net/blob/master/docs/strong-naming.md) and to @AndreyTretyak for [implementing](https://github.com/octokit/octokit.net/pull/2575) it.
