### ISSUE TITLE
Add classes corresponding to webhook payloads

### ISSUE THREAD

**Issue by wwahammy** [octokit/octokit.net#407]
Currently, deserialization of webhook payloads into classes is not included in octokit.net. If these were included, it'd make webhooks easier to create because devs wouldn't have to one-off their own classes for handling webhook payloads.

**Comment by erichexter** [comment]
Would you take implementations for the Create and Delete Payloads ?

If so, what else needs to be done for this? 

- [ ]  implementing the classes in the ActivityPayloads folder.  
- [ ] Add serialization tests to https://github.com/octokit/octokit.net/blob/master/Octokit.Tests/Clients/EventsClientTests.cs

**Comment by JamieMagee** [comment]
Webhook payloads are now supported in the [Octokit .NET webhooks package](https://github.com/octokit/webhooks.net)
