### ISSUE TITLE
Validation checks on NewRepository.GitignoreTemplate

### ISSUE THREAD

**Issue by shiftkey** [octokit/octokit.net#423]
One of our integration tests was failing with this response:

```
{
  "message":"Validation Failed",
  "documentation_url":"http://developer.github.com/v3/repos/#create",
  "errors":
  [{
    "resource":"Repository",
    "code":"custom",
    "field":"gitignore_template",
    "message":"gitignore_template is an unknown gitignore template."
  }]
}
```

This is because we were passing `visualstudio`, rather than `VisualStudio`.

We should surface this as a proper exception message in the future...

**Comment by willsb** [comment]
Will `new InvalidGitignoreTemplateException("gitignore_template is an unknown gitignore template.");` suffice?

**Comment by Haacked** [comment]
Yeah. But obviously use the returned message and not that literal string. :stuck_out_tongue:
