### ISSUE TITLE
File Contents

### ISSUE THREAD

**Issue by Roman1991** [octokit/octokit.net#444]
How can I get the file contents from github repository using octokit.net?

**Comment by shiftkey** [comment]
@Roman1991 this was added in https://github.com/octokit/octokit.net/pull/649 which was released in v0.6.2

@bursteg I'm not sure if you were referring to [Get a Blob](https://developer.github.com/v3/git/blobs/#get-a-blob) - which uses the Git object SHA for lookup, or [Get Contents](https://developer.github.com/v3/repos/contents/#get-contents) which lets you specify the relative path to the file.

If you think there's something that can be improved in the BlobsClient feel free to add some more details here or discuss this in a PR.
