### ISSUE TITLE
The Integration Tests Time out

### ISSUE THREAD

**Issue by haacked** [octokit/octokit.net#456]
![integration-tests](https://cloud.githubusercontent.com/assets/19977/2721758/dcbc4dcc-c57e-11e3-836d-88bc1d32cbe2.jpg)

Rather than increase the QED timeout, how can we make our integration tests faster. Part of the problem is that for many test classes, each test has to set up the "entire world."

What if we did one of the following:
1. Sequence our integration tests (I would never do this for unit tests) so that they build on each other and do not need to create the world for each test. This adds a lot of complexity to our tests.
2. Have each test only create the parts of the world it needs and not clean up the world. We would need a way to clean up at the end of each set of tests (as opposed to after each individual test).

Thoughts?

**Comment by shiftkey** [comment]
I've looked into enabling parallel builds with xUnit 2 but am hitting some issues with the integration tests running in parallel. My psychic debugger thinks this is related to contention with making requests to the same remote server...

**Comment by Haacked** [comment]
We could run the unit tests in parallel, but not the integration tests.

**Comment by shiftkey** [comment]
Just tested this out, and it does shave off a couple of seconds:

### Before

```
=== TEST EXECUTION SUMMARY ===
   Octokit.Tests  Total: 1026, Errors: 0, Failed: 0, Skipped: 0, Time: 8.756s
   Octokit.Tests-NetCore45  Total: 588, Errors: 0, Failed: 0, Skipped: 0, Time: 5.373s
   Octokit.Tests-Portable  Total: 588, Errors: 0, Failed: 0, Skipped: 0, Time: 5.332s

UnitTests   00:00:41.2409233
```

### After

```
=== TEST EXECUTION SUMMARY ===
   Octokit.Tests  Total: 1026, Errors: 0, Failed: 0, Skipped: 0, Time: 5.372s
   Octokit.Tests-NetCore45  Total: 588, Errors: 0, Failed: 0, Skipped: 0, Time: 3.219s
   Octokit.Tests-Portable  Total: 588, Errors: 0, Failed: 0, Skipped: 0, Time: 3.240s

UnitTests   00:00:40.7780810
```

**Comment by shiftkey** [comment]
Running the tests in the new VS test runner suffers the same problem as the command line, so I'd like to get to the bottom of this issue. But I can work around it in the meantime and run batches of tests...
