### ISSUE TITLE
I'd really appreciate some documentation

### ISSUE THREAD

**Issue by JacobCZ** [octokit/octokit.net#463]
Hello, i know that it's hard to create a full documentation of library, but come on, one small example? Really? I'm sorry, but this library is kinda useless without proper documentation, so pelase, anybody, do it...

**Comment by Papalamus** [comment]
Sorry for  intervening, but is there a way to request list of public repositories as in https://developer.github.com/v3/repos/#list-all-public-repositories  ?

**Comment by shiftkey** [comment]
@Papalamus this seems to have been overlooked. I've opened https://github.com/octokit/octokit.net/issues/686 to track adding it to the API

**Comment by hahmed** [comment]
@Haacked @shiftkey why not go with the jekyll option, I do not mind getting the experiment rolling?

That way we can be consistent with our ruby brethren. 

https://github.com/octokit/octokit.rb/tree/gh-pages

Anyhow if you do decide to go down that route, would you mind creating the gh-pages branch and nuking it for me, so I can start from there?

Better than me creating a PR that contains deletions to sooo many files, I can simply start with **jekyll new** when I make my first PR for the documentation.

- Get all documentation on one page (then split them up as we go along into tabs or whatever)
- We need a link to an svg of that octokit logo for octokit.net

Let me know your thoughts on this.

**Comment by Haacked** [comment]
I'm down for that. @shiftkey? If you agree, I'll create the branch.

**Comment by shiftkey** [comment]
Not sure why I didn't raise this sooner, but I like how ReadTheDocs does this. Here's ReactiveUI's as an example: http://reactiveui.readthedocs.org/en/latest/ - and the relevant PR - https://github.com/reactiveui/ReactiveUI/pull/771

This is slightly different from the `gh-pages` approach for a couple of reasons:

 - it's markdown'd already - we've got some docs as a starting point
 - docs are alongside the code - easier to keep things in sync than with Pages
 - docs use tags to represent [versions](https://read-the-docs.readthedocs.org/en/latest/versions.html) - we don't get this for free with a vanilla Pages site

For style and stuff we can work on that after getting something going - I just feel this is a better starting point that a vanilla pages site.

**Comment by M-Zuber** [comment]
I would like to second the notion of not using gh-pages. There is a project I contribute to,  and updating the docs are a pain in ...  ... 

In other news,  there is  a little nifty tool I saw recently : http://classeur.io/.  I wonder if that can be hooked up which might make it easier /simpler to write the docs, which in turn ups the chance of them getting written.

**Comment by hahmed** [comment]
@shiftkey readthedocs is cool too :+1: aspnet vnext is using that. The default styles look really good.

Would we care too much about having documentation for different versions for octokit.net? Seems like an overkill for this library.

**Comment by shiftkey** [comment]
> Would we care too much about having documentation for different versions for octokit.net?

It's something you get "for free" if you're tagging releases (like we are) - so I don't see it as much work for us.  But yeah, it's a minor bonus.

**Comment by hahmed** [comment]
Ok, we will need to create an account for readthedocs and import the markdown files into it I think. 

Shall I let you handle the account creation so admin rights are on your end - assuming that's how it works? (Never used it before but more than willing to help out on this).

**Comment by shiftkey** [comment]
@hahmed yeah, I should have some time to set up the basics tonight.

Ideally it should just keep redeploying off of webhook activity for a certain branch.

**Comment by shiftkey** [comment]
Due to the `.` in the project name :cry: the URL it gave me is http://octokitnet.readthedocs.org/en/latest/.

Gonna set up the other bits now and open a brief PR to get things going.

**Comment by shiftkey** [comment]
@hahmed I've opened up #948 to track this work. There's a whole bunch of details here about the mkdocs format (which we're using here): http://mkdocs.readthedocs.org/en/stable/

Happy to discuss things in PRs targeting the `documentation` branch, and we can just iterate on stuff quickly while we get a feel for what this might look like.

**Comment by Haacked** [comment]
:thumbsup: to whatever @shiftkey says here. :smile:
