### ISSUE TITLE
Request: Include remaing rate-limit in responses

### ISSUE THREAD

**Issue by saguiitay** [octokit/octokit.net#504]
For example, in the SearchCodeResult (and all other Result objects), include a remaining rate limits.

This will allow an extremely simple to implement throttling of my requests

**Comment by shiftkey** [comment]
> I'm currently using the former in some test code - but doesn't feel correct to add to a PR.

I think 1) is going to be a more maintainable solution in the long-term. The other solution means deserializing becomes a two-step operation (read the content, then read the headers). Would love to hear your concerns.

**Comment by Red-Folder** [comment]
Gonna have a go at option 1 and produce a PR for review (hopefully next 24 hours)

Basically just going to provide a property on the client which calls through to connection which calls through the HTTPClientAdaptor (which will store the last ApiInfo during the Send).

Putting the chained calls all the way through the stack avoids having to keep a reference to the HttpClientAdaptor - which makes it easier for the user.

**Comment by shiftkey** [comment]
As this requires significant thought - and likely significant changes to the API responses - as well as there exists the ability to get this data using `IGitHubClient.GetLastApiInfo()` I'm happy to close this out for now.

I've opened https://github.com/octokit/octokit.net/issues/1142 to add some documentation for this feature before I forget.
