### ISSUE TITLE
LINQPad samples

### ISSUE THREAD

**Issue by shiftkey** [octokit/octokit.net#505]
http://www.linqpad.net/nugetsamples.aspx

cc @distantcam

**Comment by shiftkey** [comment]
Taking this off my radar for the foreseeable future.

**Comment by naveensrinivasan** [comment]
@Haacked  I wanted to check if this something that we want to do now.

IMHO having samples would greatly improve people using this for their needs. I think linqpad is a great tool for doing that without much of ceremony. I use it very often to try out new API's. 

Based on this I forked  @shiftkey https://github.com/naveensrinivasan/octokit-linqpad-samples and updated with some more samples.  

I updated the octokit's Nuspec locally with the linqpad-samples 
![linqpad-samples](https://cloud.githubusercontent.com/assets/172697/10124817/33d7626e-652d-11e5-9819-f4a14c5ba7bd.JPG)

and when I use this nuget package it comes up with the samples in linqpad
![samples](https://cloud.githubusercontent.com/assets/172697/10124822/94352984-652d-11e5-9a00-f64a13e64fc5.JPG)

![samples-treeview](https://cloud.githubusercontent.com/assets/172697/10124828/c7097f40-652d-11e5-82c1-fe54cd60bef8.JPG)

If it is interesting, then I could a do a PR with 
* the samples, 
* updated the build to include the linqpad samples and
* also include a test to make sure any changes don't break the samples.

**Comment by Haacked** [comment]
Should this go in the main Octokit package or perhaps a special samples package? For example, we may want to create Octokit.Linqpad and Octokit.Reactive.Linqpad.

**Comment by naveensrinivasan** [comment]
I agree it could more of like `Octokit.Samples` where we could use one of the options as Linqpad and we could use the same samples for XS/VS project sample.

**Comment by alfhenrik** [comment]
:+1: for it to be it's own package

**Comment by M-Zuber** [comment]
I would also prefer to have a separate package

**Comment by shiftkey** [comment]
> Should this go in the main Octokit package or perhaps a special samples package?

The general guidance from the [Linqpad site](https://www.linqpad.net/nugetsamples.aspx) is to contain them in the main package:

> 2. Update your NuGet packing script to copy your samples into a folder called linqpad-samples.
> 3. Add the linqpad-samples tag to your NuGet submission to ensure free access.

I gather this means the user will have them automagically after installing (rather than digging around for a second package).

Also, I'm not sure what that last step means.

**Comment by naveensrinivasan** [comment]
Here is a sample  [Octokit.samples.0.0.1.nupkg]  (https://www.dropbox.com/s/pgsrtcijjs5pp2d/Octokit.samples.0.0.1.nupkg?dl=0) which would automatically show up in the linqpad samples.

Should it be original nuget package or should be a separate nuget package?

**Comment by alfhenrik** [comment]
> Also, I'm not sure what that last step means.

From the nuget.org [docs](https://docs.nuget.org/create/nuspec-reference)

**tags**
_A space-delimited list of tags and keywords that describe the package. This information is used to help make sure users can find the package using searches in the Add Package Reference dialog box or filtering in the Package Manager Console window._

**Comment by alfhenrik** [comment]
And after thinking about this a bit more, I'd like to revise my vote for it to be in it's own package...as if I'm interested in the LINQPad samples, I'm obviously wanting to do something with octokit and then I'd have to install both the samples package AND the actual package...

**Comment by Haacked** [comment]
I think the issues for me is I have no idea how many people use LINQPad. I don't use it so this feature doesn't really matter much to me. Will there be other tools that want their own proprietary formats in our packages?

If a lot of you DO use LINQPad, I will relent and go with it because I don't feel too strongly about it.

**Comment by Haacked** [comment]
could someone post what an example might look like? Perhaps if we could link to the examples in the README and make sure they're human readable as well as LINQPad readable, I'd be more favorable. That way they're useful to folks who don't have LINQPad installed.

Also, I'm concerned about the maintenance cost of these samples over time. If they're not compiled and run as part of our CI, then they'll bit rot over time. Would someone sign up and figure out a way to do that? (Roslyn to the rescue?)

**Comment by distantcam** [comment]
`.linq` files have a little bit of XML header, and then the actual code. They are very human readable.

For example https://github.com/naveensrinivasan/octokit-linqpad-samples/blob/master/1-introducing-octokit.linq

LinqPad can run scripts on the command line (https://www.linqpad.net/lprun.aspx) and output them. Then you could use approval tests on the output.

And if I have any sway over it, I'd like to see the samples in the main package. That way if you use LinqPad to experiment with nugets (which is a common use case of LinqPad) the samples are right there. Con is the package has some extra text files if you don't use LinqPad.

**Comment by Haacked** [comment]
> Con is the package has some extra text files if you don't use LinqPad.

So I'm :+1: for adding these to the main package if we:

- [ ] Write useful samples that we can link to in the README and can be read nicely online.
- [ ] Make sure our CI validates the samples somehow.

**Comment by naveensrinivasan** [comment]
The linqpad has compilation options for compile check.  https://www.linqpad.net/lprun.aspx
>The -compileonly switch tells lprun to check that the query will compile, without actually running anything.

I was planning to use that feature in the CI build to make sure the commits don't break the samples.

**Comment by Haacked** [comment]
> I was planning to use that feature in the CI build to make sure the commits don't break the samples.

:+1:

**Comment by naveensrinivasan** [comment]
Implemented this in https://github.com/octokit/octokit.net/pull/921
