### ISSUE TITLE
a better caching experience for Octokit

### ISSUE THREAD

**Issue by shiftkey** [octokit/octokit.net#530]
After discussions in #369 about WinInet I'm leaning towards a different approach for a couple of reasons:
- it's unclear if the WinInet issues will be fixed, let alone when 
- what about platforms where WinInet isn't available?
- HttpClient has support for doing this "Russian Doll"-style of behaviour using `DelegatingHandler`

[Tavis.PrivateCache](https://github.com/tavis-software/Tavis.PrivateCache) has been proposed as a implementation of this, so I'm leaning towards one of two options around this:
### Make Tavis.PrivateCache an development dependency, and bake it in

**Pros:**
- easier for users to get benefits of it
- less fiddling around with ctors

**Cons:**
- harder to debug (perhaps make this opt-out for those who are feeling brave)
### Expose `DelegatingHandler` in `GitHubClient` and let others do the work wiring it up

**Pros:**
- more future-proof
- others might want to do their own stuff with HttpClient

**Cons:**
- harder to get benefits for new users
- probably some more IoC pain

The work required is probably about the same, but I'm leaning toward option 1 because it'll be simpler for users of the library.

cc @paulcbetts @darrelmiller @niik

**Comment by nigel-sampson** [comment]
I created a naive implementation of the latter solution by creating a custom http client https://github.com/nigel-sampson/octokit.caching

**Comment by paulcbetts** [comment]
![](http://i.ytimg.com/vi/vqgSO8_cRio/hqdefault.jpg)

**Comment by shiftkey** [comment]
![](http://i.imgur.com/5nfca5U.gif)

**Comment by paulcbetts** [comment]
Hubot img me Jonny Lee Miller 2015

![](http://upload.wikimedia.org/wikipedia/commons/thumb/d/df/Jonny_Lee_Miller_Comic-Con_2012_%28cropped%29.jpg/330px-Jonny_Lee_Miller_Comic-Con_2012_%28cropped%29.jpg)

**Comment by darrelmiller** [comment]
Oh, where oh where are the other 48 hours I need in a day.

**Comment by shiftkey** [comment]
Status update: I'm ranting and raving over in #781 about first class support for `HttpClient/HttpMessageHandler` - once I get that right I think this will be trivial to add - and I already have crazy ideas in my head about how to do it...

**Comment by darrelmiller** [comment]
Yesterday I did a major update to my [HTTPCache](https://github.com/tavis-software/Tavis.httpcache) to fix the problems with the way the vary header is handled.  I also renamed it because how it can handle being a shared cache too!  This also caused a change to the storage interface.  Next step is to produce a persistent storage mechanism.

**Comment by shiftkey** [comment]
@darrelmiller so if I head down the road towards something like [this](https://github.com/octokit/octokit.net/issues/781#issuecomment-112392389) does that make your life easier or harder?

**Comment by darrelmiller** [comment]
@shiftkey Much easier.  Adding my cache would look pretty much exactly like you showed it in the example.
