### ISSUE TITLE
Consider to set the default proxy

### ISSUE THREAD

**Issue by forki** [octokit/octokit.net#594]
In https://github.com/fsprojects/FSharp.Configuration/pull/38 @shiftkey told us that Octokit has overloads for proxies. I suggest you set a default proxy for all your http connections. This helps people like @vasily-kirichenko to release software with octokit.

We applied the following (strange) pattern successfully to https://github.com/fsprojects/Paket.

1.) Detect the default proxy:

```
    static IWebProxy GetDefaultWebProxy()
    {
        IWebProxy result = WebRequest.GetSystemWebProxy();
        Uri irrelevantDestination = new Uri(@"http://google.com");
        Uri address = result.GetProxy(irrelevantDestination);

        if (address == irrelevantDestination)
            return null;

        return new WebProxy(address) { Credentials = CredentialCache.DefaultCredentials };
    }
```

2) Set this default proxy to every occurence of WebClient and WebRequest.

**Comment by schlamar** [comment]
Octokit is already using the system web proxy on .NET per default, only authentication is not enabled. To enable proxy authentication (against the current Windows user) you can just set `WebRequest.DefaultWebProxy.Credentials = CredentialCache.DefaultCredentials;`, no need to configure something in Octokit...

**Comment by Haacked** [comment]
> To enable proxy authentication (against the current Windows user) you can just set `WebRequest.DefaultWebProxy.Credentials = CredentialCache.DefaultCredentials;`, no need to configure something in Octokit...

I assume you mean that the app developer who is using Octokit just needs to set that code, right? What are the implications of doing that?

**Comment by schlamar** [comment]
> I assume you mean that the app developer who is using Octokit just needs to set that code, right?

Yes that would be probably the correct way (or update the app.config, see link below).

> What are the implications of doing that?

This should have no bad implications at all. Please note that this does only NTLM/Kerberos style authentication and never Basic/Digest, so your credentials are never exposed to a rogue proxy.

I'm not sure why this isn't enabled per default in .Net. See here for additionally comments: https://visualstudio.uservoice.com/forums/121579-visual-studio-2015/suggestions/2397357-fix-it-so-that-net-apps-can-access-http-thru-auth
