### ISSUE TITLE
How can I get the last n commits?

### ISSUE THREAD

**Issue by omidkrad** [octokit/octokit.net#619]
I've been playing with the API, and I couldn't find a way to get the last _n_ commits. I'm looking for something similar to `git log -5` The following didn't work:

```
gitDb.Commit.Get("octokit", "octokit.net", "HEAD")
```

Thanks!

**Comment by RedlineTriad** [comment]
> Our Rx-based clients have paging built in, so you could do something like this:
> 
> ```
> var client = new ObservableGitHubClient("OctokitTests");
> var commits = await client.Repository.Commits.Get("octokit", "octokit.net", "HEAD").Take(5).ToArray();
> ```
I tried this but it gave an `Observable<GitHubCommit[]>` and for some reason it only ever has one commit even though the repository has over 5000.
```cs

client.Repository.Commit
    .Get("unitystation","unitystation", "develop")
    .Take(10)
    .ToArray()
    .ObserveOn(SynchronizationContext.Current)
    .Subscribe(commits =>{
        foreach(var com in commits){
            Commits.Add(com.Commit.Message);
        }
    });
```

**Comment by shiftkey** [comment]
@RedlineTriad please open a fresh issue with details about your setup, as this discussion is over 4 years old and a lot has changed since then...
