### ISSUE TITLE
Events pagination

### ISSUE THREAD

**Issue by Odonno** [octokit/octokit.net#625]
I can see on the GitHub API that the Events API (https://developer.github.com/v3/activity/events/) can be based on pagination (only page property, no per_page property).

Currently, the octokit framework let us get events with a simply collection (no paging system).

Could you fix it ?

**Comment by dampir** [comment]
@ryangribble, @shiftkey could this one be closed as solved because Octokit.NET in one little step from release with pagination support?

**Comment by shiftkey** [comment]
Fixed in https://github.com/octokit/octokit.net/pull/1240 and will be available in the next Octokit release...
