### ISSUE TITLE
TheCreateMethodForUser.ThrowsRepositoryExistsExceptionForExistingRepository is failing

### ISSUE THREAD

**Issue by gabrielweyer** [octokit/octokit.net#633]
It is failing because `RepositoriesClient.Create` is calling its overload with `null` as the value for `organizationLogin` argument. This value is then used to instantiate the `RepositoryExistsException`.

**Comment by shiftkey** [comment]
I'm contemplating burning that exception to the ground (or just using the original URL rather than tying it to the login details).

**Comment by Haacked** [comment]
Yeah, that parameter is not named correctly. I think the way I'd prefer we fix this is to have two `RepositoryExistsException ` constructors.

```csharp
public RepositoryExistsException(
            string organization,
            string name,
            Uri baseAddress,
            ApiValidationException innerException);

and

public RepositoryExistsException(
            string name,
            Uri baseAddress,
            ApiValidationException innerException)
```

The first one is called if the exception is for an organization. It should not allow a null `organization` value. The second one is called if the exception is for the current user.

It's up to the caller to determine which ctor to call.

**Comment by shiftkey** [comment]
I *really* think we should just pass in the repository URL to the exception - whether it's an org or a user repo doesn't really matter here, right?

**Comment by Haacked** [comment]
We use it in GHfW to provide a clear and useful error message to the user.

**Comment by gabrielweyer** [comment]
Let me do a quick PR to see how this would like :smile:
