### ISSUE TITLE
ForbiddenException still thrown when rate limit NOT exceeded

### ISSUE THREAD

**Issue by sbohlen** [octokit/octokit.net#638]
I have a simple program that reads issues from a CSV file, inserts (creates) them in github, and then updates the status, lables, etc. of each one of them.  There are only 57 issues, so I would assume this would equate to ~114 API calls (57 calls to CREATE and 57 calls to UPDATE).

I am using basic auth with a personal API token, which is expected to provide me 5000 API calls per day (more than sufficient for my needs).  However, each time I run my code I am always receiving a ForbiddenException with the following message, always after the initial 20 insert (CREATE) operations have been completed:

`You have triggered an abuse detection mechanism and have been temporarily blocked from content creation. Please retry your request again later.`

In an attempt to ensure that my understanding of the behavior of my code is what is being seen by GitHub, I added a simple Debug.WriteLine(...) call around each of the operations that interact with the API to display the API's response to my query re: the remaining number of API calls I should have available both before and after each of my operations against the API.

Following is a sample of the output that I'm seeing from a typical run...

Before Adding New Issue [GitHub API Queries Remaining: 4888]
Beginning Process [GitHub API Queries Remaining: 4888]
After Adding New Issue [GitHub API Queries Remaining: 4887]
Before Adding New Issue [GitHub API Queries Remaining: 4887]
After Adding New Issue [GitHub API Queries Remaining: 4886]
Before Adding New Issue [GitHub API Queries Remaining: 4886]
After Adding New Issue [GitHub API Queries Remaining: 4885]
Before Adding New Issue [GitHub API Queries Remaining: 4885]
After Adding New Issue [GitHub API Queries Remaining: 4884]
Before Adding New Issue [GitHub API Queries Remaining: 4884]
Before Adding New Issue [GitHub API Queries Remaining: 4883]
After Adding New Issue [GitHub API Queries Remaining: 4883]
After Adding New Issue [GitHub API Queries Remaining: 4882]
Before Adding New Issue [GitHub API Queries Remaining: 4882]
Before Adding New Issue [GitHub API Queries Remaining: 4881]
After Adding New Issue [GitHub API Queries Remaining: 4881]
Before Adding New Issue [GitHub API Queries Remaining: 4880]
After Adding New Issue [GitHub API Queries Remaining: 4880]
Before Adding New Issue [GitHub API Queries Remaining: 4879]
After Adding New Issue [GitHub API Queries Remaining: 4879]
Before Adding New Issue [GitHub API Queries Remaining: 4878]
After Adding New Issue [GitHub API Queries Remaining: 4878]
After Adding New Issue [GitHub API Queries Remaining: 4877]
Before Adding New Issue [GitHub API Queries Remaining: 4877]
Before Adding New Issue [GitHub API Queries Remaining: 4876]
After Adding New Issue [GitHub API Queries Remaining: 4876]
Before Adding New Issue [GitHub API Queries Remaining: 4875]
After Adding New Issue [GitHub API Queries Remaining: 4875]
After Adding New Issue [GitHub API Queries Remaining: 4874]
Before Adding New Issue [GitHub API Queries Remaining: 4874]
Before Adding New Issue [GitHub API Queries Remaining: 4873]
After Adding New Issue [GitHub API Queries Remaining: 4873]
Before Adding New Issue [GitHub API Queries Remaining: 4872]
After Adding New Issue [GitHub API Queries Remaining: 4872]
Before Adding New Issue [GitHub API Queries Remaining: 4871]
After Adding New Issue [GitHub API Queries Remaining: 4871]
After Adding New Issue [GitHub API Queries Remaining: 4870]
Before Adding New Issue [GitHub API Queries Remaining: 4870]
Before Adding New Issue [GitHub API Queries Remaining: 4869]
After Adding New Issue [GitHub API Queries Remaining: 4869]
Before Adding New Issue [GitHub API Queries Remaining: 4868]
After Adding New Issue [GitHub API Queries Remaining: 4868]
Test 'IssuesImporter.Test.WhenWritingGithubIssues.CanAddIssueToGitHub' failed: Octokit.ForbiddenException : You have triggered an abuse detection mechanism and have been temporarily blocked from content creation. Please retry your request again later.

Note that since I've run my code several times recently, the 'countdown' doesn't begin at exactly 5000, but you can (hopefully) see from the values reported from the GitHub API querying my rate limit both that I am indeed decrementing my available calls by '1' each time I do an operation _and_ that I should seemingly have more than sufficient API calls remaining to complete my additional work.

Clearly I must be bumping into one of a few possible causes here:
1. There is a bug in the OctoKit.net library that erroneously throws this exception for the wrong reasons (frankly unlikely as this would presumably be a blocker for a lot more people than just myself and I cannot find any evidence of this elsewhere on the internet, whether here or elsewhere on blogs, etc.)
2. There's a flaw in the GitHub API such that it is returning whatever error code indicates an API throttling action for reasons _other_ than my having exceeded it (also seemingly unlikely as I'd again expect that to turn up elsewhere on the web)
3. I'm bumping into some sort of _additional_ API abuse-related detection method _other_ than the 5000-calls-per-day rate limit that is resulting in this exception being raised.

Any thoughts re: what I might be doing wrong --?  Since the Oktokit.net `response.ApiInfo.RateLimit.Remaining` value clearly seems to indicate that I've more than enough API calls remaining for the code to continue, I'm betting that its number 3 and I'm bumping into some other API limit that's (perhaps) not as well-advertised (?)  This is (perhaps) further reinforced by the part of the error message `...and have been temporarily blocked from content creation.`

Is it possible that there is a cannot-create-more-than-20-items-in-a-short-duration API limit that I'm somehow hitting here? Any ideas appreciated -- my processing code _always_ halts after 20 API calls.

Since 20 API calls seems to be the magic number, as an experiment I trimmed my CSV source file down to just 10 records (which should equate to 10 CREATE calls and 10 UPDATE calls = 20 total).  In this case, the entirety of my process functions just fine (both the CREATE and the UPDATE calls) so I know (think!) my code is right but I'm stymied by this unexpected ForbiddenException I receive when attempting to process the entirety of my data set.

Thanks in advance for any suggestions -- if it helps, I can share the entirety of my simple code, though as mentioned since it works 100% fine on a smaller data set (<= 20 API calls) I'm skeptical that the issue is in my logic per se.

Cheers,

-Steve B.
.

**Comment by thiagobustamante** [comment]
Thanks a lot. It was very useful to me.
