### ISSUE TITLE
Enums Prevent New Server-Side State

### ISSUE THREAD

**Issue by thedillonb** [octokit/octokit.net#643]
Philosophical discussion:

Enums on response objects are a blessing and a curse. Becides the obvious advantages, there is a looming disadvantage that I think needs to be addressed. Lets take the possible values for an issue event type: closed, reopened, merged, mentioned, etc... If all these are programmed into the client as enumerable values then everything works as expected. However, if the server adds a new value, say 'Foo', and a query of the events of an issue has that type then Octokit will currently blow up with an exception that the value 'Foo' was not found in the possible enumerations. 

Now, this is not a problem if we are guarenteed that upon 1.0.0 no new states will appear under v3. However, if that is not the case then we indeed have a problem. Upon an unknown state for an enumeration should we choose a default? Should we not populate it? What to do?

**Comment by M-Zuber** [comment]
## This is not an attempt to give an answer to OPs question, but to try and get a handle on what would be affected
What enums would this apply for?
Some points before your eyes glaze over as you read the list:
- Quite a number of the enums use the `ParameterAttribute` to set the actual value as needed by/from the server
- Some of the enums are not part of the client/server traffic
- The list may be moot as there is a high probability that a fix will only be in `SimpleJson`

We have the following:  (links are from my fork as I am pulling from Visual Studio)
- [AuthenticationType](https://github.com/M-Zuber/octokit.net/blob/4072a6f5929eacdf0784d212c3c631026871cdf3/Octokit/Authentication/AuthenticationType.cs#L6)
- [ArchiveFormat](https://github.com/M-Zuber/octokit.net/blob/4072a6f5929eacdf0784d212c3c631026871cdf3/Octokit/Clients/IRepositoryContentsClient.cs#L271)
- [OrganizationMembersFilter](https://github.com/M-Zuber/octokit.net/blob/4072a6f5929eacdf0784d212c3c631026871cdf3/Octokit/Clients/OrganizationMembersClient.cs#L14)
- [OrganizationMembersRole](https://github.com/M-Zuber/octokit.net/blob/4072a6f5929eacdf0784d212c3c631026871cdf3/Octokit/Clients/OrganizationMembersClient.cs#L28)
- [TwoFactorType](https://github.com/M-Zuber/octokit.net/blob/4072a6f5929eacdf0784d212c3c631026871cdf3/Octokit/Exceptions/TwoFactorAuthorizationException.cs#L95)
- [IssueFilter](https://github.com/M-Zuber/octokit.net/blob/4072a6f5929eacdf0784d212c3c631026871cdf3/Octokit/Models/Request/IssueRequest.cs#L95)
- [ItemStateFilter](https://github.com/M-Zuber/octokit.net/blob/4072a6f5929eacdf0784d212c3c631026871cdf3/Octokit/Models/Request/IssueRequest.cs#L126)
- [ItemState](https://github.com/M-Zuber/octokit.net/blob/4072a6f5929eacdf0784d212c3c631026871cdf3/Octokit/Models/Request/IssueRequest.cs#L147)
- [IssueSort](https://github.com/M-Zuber/octokit.net/blob/4072a6f5929eacdf0784d212c3c631026871cdf3/Octokit/Models/Request/IssueRequest.cs#L163)
- [SortDirection](https://github.com/M-Zuber/octokit.net/blob/4072a6f5929eacdf0784d212c3c631026871cdf3/Octokit/Models/Request/IssueRequest.cs#L184)
- [MilestoneSort](https://github.com/M-Zuber/octokit.net/blob/4072a6f5929eacdf0784d212c3c631026871cdf3/Octokit/Models/Request/MilestoneRequest.cs#L40)
- [DeployTask](https://github.com/M-Zuber/octokit.net/blob/4072a6f5929eacdf0784d212c3c631026871cdf3/Octokit/Models/Request/NewDeployment.cs#L101)
- [WebHookContentType](https://github.com/M-Zuber/octokit.net/blob/4072a6f5929eacdf0784d212c3c631026871cdf3/Octokit/Models/Request/NewRepositoryWebHook.cs#L141)
- [Permission](https://github.com/M-Zuber/octokit.net/blob/4072a6f5929eacdf0784d212c3c631026871cdf3/Octokit/Models/Request/Permission.cs#L9)
- [PullRequestSort](https://github.com/M-Zuber/octokit.net/blob/4072a6f5929eacdf0784d212c3c631026871cdf3/Octokit/Models/Request/PullRequestRequest.cs#L56)
- [Sort](https://github.com/M-Zuber/octokit.net/blob/4072a6f5929eacdf0784d212c3c631026871cdf3/Octokit/Models/Request/RepositoryForksListRequest.cs#L40)
- [RepositoryType](https://github.com/M-Zuber/octokit.net/blob/4072a6f5929eacdf0784d212c3c631026871cdf3/Octokit/Models/Request/RepositoryRequest.cs#L80)
- [RepositorySort](https://github.com/M-Zuber/octokit.net/blob/4072a6f5929eacdf0784d212c3c631026871cdf3/Octokit/Models/Request/RepositoryRequest.cs#L111)
- [RepositoryVisibility](https://github.com/M-Zuber/octokit.net/blob/4072a6f5929eacdf0784d212c3c631026871cdf3/Octokit/Models/Request/RepositoryRequest.cs#L138)
- [RepositoryAffiliation](https://github.com/M-Zuber/octokit.net/blob/4072a6f5929eacdf0784d212c3c631026871cdf3/Octokit/Models/Request/RepositoryRequest.cs#L159)
- [CodeSearchSort](https://github.com/M-Zuber/octokit.net/blob/4072a6f5929eacdf0784d212c3c631026871cdf3/Octokit/Models/Request/SearchCodeRequest.cs#L223)
- [CodeInQualifier](https://github.com/M-Zuber/octokit.net/blob/4072a6f5929eacdf0784d212c3c631026871cdf3/Octokit/Models/Request/SearchCodeRequest.cs#L229)
- [IssueSearchSort](https://github.com/M-Zuber/octokit.net/blob/4072a6f5929eacdf0784d212c3c631026871cdf3/Octokit/Models/Request/SearchIssuesRequest.cs#L412)
- [IssueTypeQualifier](https://github.com/M-Zuber/octokit.net/blob/4072a6f5929eacdf0784d212c3c631026871cdf3/Octokit/Models/Request/SearchIssuesRequest.cs#L436)
- [IssueInQualifier](https://github.com/M-Zuber/octokit.net/blob/4072a6f5929eacdf0784d212c3c631026871cdf3/Octokit/Models/Request/SearchIssuesRequest.cs#L447)
- [IssueIsQualifier](https://github.com/M-Zuber/octokit.net/blob/4072a6f5929eacdf0784d212c3c631026871cdf3/Octokit/Models/Request/SearchIssuesRequest.cs#L457)
- [IssueNoMetadataQualifier](https://github.com/M-Zuber/octokit.net/blob/4072a6f5929eacdf0784d212c3c631026871cdf3/Octokit/Models/Request/SearchIssuesRequest.cs#L477)
- [SearchQualifierOperator](https://github.com/M-Zuber/octokit.net/blob/4072a6f5929eacdf0784d212c3c631026871cdf3/Octokit/Models/Request/SearchQualifierOperator.cs#L6)
- [InQualifier](https://github.com/M-Zuber/octokit.net/blob/4072a6f5929eacdf0784d212c3c631026871cdf3/Octokit/Models/Request/SearchRepositoriesRequest.cs#L180)
- [Language](https://github.com/M-Zuber/octokit.net/blob/4072a6f5929eacdf0784d212c3c631026871cdf3/Octokit/Models/Request/SearchRepositoriesRequest.cs#L389)
- [RepoSearchSort](https://github.com/M-Zuber/octokit.net/blob/4072a6f5929eacdf0784d212c3c631026871cdf3/Octokit/Models/Request/SearchRepositoriesRequest.cs#L758)
- [ForkQualifier](https://github.com/M-Zuber/octokit.net/blob/4072a6f5929eacdf0784d212c3c631026871cdf3/Octokit/Models/Request/SearchRepositoriesRequest.cs#L781)
- [AccountSearchType](https://github.com/M-Zuber/octokit.net/blob/4072a6f5929eacdf0784d212c3c631026871cdf3/Octokit/Models/Request/SearchUsersRequest.cs#L147)
- [UserInQualifier](https://github.com/M-Zuber/octokit.net/blob/4072a6f5929eacdf0784d212c3c631026871cdf3/Octokit/Models/Request/SearchUsersRequest.cs#L162)
- [UsersSearchSort](https://github.com/M-Zuber/octokit.net/blob/4072a6f5929eacdf0784d212c3c631026871cdf3/Octokit/Models/Request/SearchUsersRequest.cs#L183)
- [StarredSort](https://github.com/M-Zuber/octokit.net/blob/4072a6f5929eacdf0784d212c3c631026871cdf3/Octokit/Models/Request/StarredRequest.cs#L52)
- [AccountType](https://github.com/M-Zuber/octokit.net/blob/4072a6f5929eacdf0784d212c3c631026871cdf3/Octokit/Models/Response/AccountType.cs#L3)
- [EncodingType](https://github.com/M-Zuber/octokit.net/blob/4072a6f5929eacdf0784d212c3c631026871cdf3/Octokit/Models/Response/Blob.cs#L48)
- [EnforcementLevel](https://github.com/M-Zuber/octokit.net/blob/4072a6f5929eacdf0784d212c3c631026871cdf3/Octokit/Models/Response/BranchProtection.cs#L80)
- [CommitState](https://github.com/M-Zuber/octokit.net/blob/4072a6f5929eacdf0784d212c3c631026871cdf3/Octokit/Models/Response/CommitStatus.cs#L83)
- [ContentType](https://github.com/M-Zuber/octokit.net/blob/4072a6f5929eacdf0784d212c3c631026871cdf3/Octokit/Models/Response/ContentType.cs#L8)
- [DeploymentState](https://github.com/M-Zuber/octokit.net/blob/4072a6f5929eacdf0784d212c3c631026871cdf3/Octokit/Models/Response/DeploymentStatus.cs#L94)
- [EventInfoState](https://github.com/M-Zuber/octokit.net/blob/4072a6f5929eacdf0784d212c3c631026871cdf3/Octokit/Models/Response/EventInfo.cs#L74)
- [MigrationState](https://github.com/M-Zuber/octokit.net/blob/4072a6f5929eacdf0784d212c3c631026871cdf3/Octokit/Models/Response/Migration.cs#L104)
- [PagesBuildStatus](https://github.com/M-Zuber/octokit.net/blob/4072a6f5929eacdf0784d212c3c631026871cdf3/Octokit/Models/Response/Page.cs#L7)
- [PullRequestReviewCommentSort](https://github.com/M-Zuber/octokit.net/blob/4072a6f5929eacdf0784d212c3c631026871cdf3/Octokit/Models/Response/PullRequestReviewComment.cs#L113)
- [ReactionType](https://github.com/M-Zuber/octokit.net/blob/4072a6f5929eacdf0784d212c3c631026871cdf3/Octokit/Models/Response/Reaction.cs#L8)
- [InvitationPermissionType](https://github.com/M-Zuber/octokit.net/blob/4072a6f5929eacdf0784d212c3c631026871cdf3/Octokit/Models/Response/RepositoryInvitation.cs#L7)
- [TaggedType](https://github.com/M-Zuber/octokit.net/blob/4072a6f5929eacdf0784d212c3c631026871cdf3/Octokit/Models/Response/TagObject.cs#L25)
- [TeamMembership](https://github.com/M-Zuber/octokit.net/blob/4072a6f5929eacdf0784d212c3c631026871cdf3/Octokit/Models/Response/TeamMembership.cs#L3)
- [TreeType](https://github.com/M-Zuber/octokit.net/blob/4072a6f5929eacdf0784d212c3c631026871cdf3/Octokit/Models/Response/TreeItem.cs#L60)
- [VerificationReason](https://github.com/M-Zuber/octokit.net/blob/4072a6f5929eacdf0784d212c3c631026871cdf3/Octokit/Models/Response/Verification.cs#L49)

**Comment by khellang** [comment]
Wasn't this fixed with https://github.com/octokit/octokit.net/pull/1595?

**Comment by M-Zuber** [comment]
It would seem so
(thanks btw for all the work on that)
