### ISSUE TITLE
Consistent way to create and teardown test repositories

### ISSUE THREAD

**Issue by shiftkey** [octokit/octokit.net#655]
We have a consistent way to create a test repository for the purpose of integration tests:

```
var repoName = Helper.MakeNameWithTimestamp("source-repo");
var repository = await client.Repository.Create(new NewRepository { Name = repoName, AutoInit = true });
```

And a couple of different ways to cleanup this repository:

```
finally
{
    if (repository != null)
       client.Repository.Delete(repository.Owner.Login, repository.Name);
}
```
OR
```
finally
{
    Helper.DeleteRepo(createdRepository);
}
```
OR 
```
finally
{
    Helper.DeleteRepo("owner", "name");
}
```

We also have a couple of places where we use `IDisposable` to signal to xUnit to run some disposal code outside the scope of the test.

So basically, everything is terrible.

There's a couple of constraints to be wary of here:

 - the repository should be deleted when the test completes (or an exception occurs)
 - `IDisposable.Dispose` isn't `await`-able :cry:
 - The [Delete Repository](https://developer.github.com/v3/repos/#delete-a-repository) API is a network call, we should probably wait for it to complete.

Ideally, I'd like some sort of wrapper which we can use:

```
using (var repository = gitClient.CreateTestRepository("source-repo"))
{


}
```

Where `CreateTestRepository` is an extension method that takes care of generating the unique name for the repository and calling the necessary APIs. There might be some ickyness inside `Dispose` to workaround the blocking/non-blocking problem, but hopefully this makes it easier to scaffold new integration tests...

**Comment by Haacked** [comment]
I like the `using` approach. :+1:

**Comment by willsb** [comment]
What's the current status of this one? Are any bits of [this closed PR](https://github.com/octokit/octokit.net/pull/680) relevant? May I start working on it?

**Comment by Haacked** [comment]
Nobody's working on this currently. Feel free.

**Comment by devkhan** [comment]
Should be closed?
