### ISSUE TITLE
Convention test to ensure all response models use IReadOnlyList<T>

### ISSUE THREAD

**Issue by shiftkey** [octokit/octokit.net#660]
See discussion in https://github.com/octokit/octokit.net/pull/658

**Comment by khellang** [comment]
Maybe also expand this to check that properties have protected setters? I can take this after #658 is in :smile:

**Comment by shiftkey** [comment]
Let's divide and conquer on it - they're not exactly coupled together.

**Comment by khellang** [comment]
LOL. Doesn't look like the convention test that checks for `DebuggerDisplayAttribute` checks response models at all. It gets the method return types from the client interfaces, but those are `Task<T>` and `Task<IReadOnlyList<T>>` etc. I think we need to unwrap those types first... See https://github.com/octokit/octokit.net/blob/master/Octokit.Tests.Conventions/DebuggerDisplayOnModels.cs#L29

**Comment by shiftkey** [comment]
@khellang herp derp. Yeah, that's Definitely An Issue...

**Comment by khellang** [comment]
OK, the reason there's all this stuff going on is because it's hard to identify request/response models (everything is same assembly, same namespace etc.).

Here are some suggestions:
 1. Introduce namespaces (breaking, ugly)
 2. Add marker interfaces, `IRequestModel` and `IResponseModel`.
   - This could further be enforced by adding generic constraints on `IApiConnection`'s methods.
 3. Add attributes, `RequestModelAttribute` and `ResponseModelAttribute`.
 4. Keep scraping client interfaces for parameter- and return types to determine request- and response models.

What do you think?

**Comment by Haacked** [comment]
> Keep scraping client interfaces for parameter- and return types to determine request- and response models.

I like this option. It's harder, but gives a better result. Who's afraid of hard?

**Comment by shiftkey** [comment]
- Namespaces: we've tried to avoid avoided namespaces below `Octokit` for everything public.
- Marker Interfaces: I'm Not A Fan
- Attributes: pass

Yeah, the test infrastructure bit us in the rear this time - we should have added a check here to fail the test if the collection of models discovered was empty.

**Comment by khellang** [comment]
Alright. I'll just check if the return type is generic, get the generic parameter(s), check if the its assembly is Octokit, if it is, return, otherwise, recurse. Sounds like a plan?

**Comment by Haacked** [comment]
Sounds good.

**Comment by khellang** [comment]
Soooo... There are 89 files in the response model folder, but I only detect 59 types in the tests. I guess this is because many of the models isn't top-level and thus isn't exposed through an interface. Do you want me to walk the tree to pick up non-top-level models as well? ¯\(°_o)/¯

**Comment by Haacked** [comment]
I'm not sure I understand. Walk what tree?

**Comment by khellang** [comment]
The tree of type dependencies :smile: A `RepositoryTag` has a property with type `GitReference`, which again has a property with type `User` etc.

**Comment by Haacked** [comment]
Oh wait, I understand now. Yeah, we have to iterate the properties of the returned models looking for types we haven't seen yet.

**Comment by Haacked** [comment]
Fun, right?! :laughing:

**Comment by khellang** [comment]
Yeah :smile:

**Comment by khellang** [comment]
There has to be a circular reference in there somewhere as well :grin:

**Comment by Haacked** [comment]
Well definitely keep track of the types you've already seen.

**Comment by khellang** [comment]
Now I got up to 71 :stuck_out_tongue: Looks like 8 of the files are enums, which are filtered out. Wonder what the remaining 10 files are... could they be unused?

**Comment by shiftkey** [comment]
@khellang could be unused - i'd love some more details!

**Comment by khellang** [comment]
Hey! Collections! Same problems as earlier. Forgot to unwrap generic types :smile: Now I got 'em all.
