### ISSUE TITLE
Add default constructors to response models.

### ISSUE THREAD

**Issue by Zoltu** [octokit/octokit.net#677]
As a user, I would like to be able to easily test my code that utilizes Octokit.  One of the things that I may want to do is mock library calls (particularly calls that normally would hit network/disk) to return mocked objects.  This allows me to unit test my business logic without needing to deeply understand the internal workings of Octokit.

A recent change (https://github.com/octokit/octokit.net/commit/21ca33817d96725391c7705f62d2eeb4de298531) altered many of the models to be read-only.  The problem here is that if I mock a call like `IReferencesClient.Get(...)`, I cannot easily construct a `Reference` to return from that mocked function.  In theory, I could derive a class from Reference and create a constructor that uses the protected setters to populate the objects, but I would have to do that for every model.  I can't use a traditional mocking library because the getters are not virtual.

Suggestions (in order of least work to most work):

1. Make the properties virtual.  This will at least allow me to leverage a mocking library.
1. Provide a constructor that can populate the object.
1. Don't directly use the models, instead use interfaces everywhere.  The models as they are now would just become private implementations of those interfaces.

**Comment by Haacked** [comment]
These models are basically data objects so I don't like 1 or 3 for that reason. They aren't meant to have any behavior.

I like 2. Each object should have a default constructor (so we can deserialize them) and a constructor that fully populates it.

Would you be interested in submitting a PR to introduce those ctors? :smile:

**Comment by Zoltu** [comment]
I'll get a PR put together for this.
