### ISSUE TITLE
Check an authorization

### ISSUE THREAD

**Issue by alfhenrik** [octokit/octokit.net#682]
https://developer.github.com/v3/oauth_authorizations/#check-an-authorization

**Comment by shiftkey** [comment]
If I haven't covered this in #647 I definitely should

**Comment by alfhenrik** [comment]
Sorry, totally missed that PR...

**Comment by alfhenrik** [comment]
@shiftkey you want to implement it in your PR above, or should I keep it in with mine?

**Comment by shiftkey** [comment]
If you need it urgently, open a PR against `master` for it. #683 is about some upcoming breaking changes, and I've been pulled off that for the moment so it's somewhat stalled...

**Comment by alfhenrik** [comment]
No urgency here :) was just looking to start contributing again :cake:

**Comment by shiftkey** [comment]
The Authorization API changes will go out in the next release (0.7.1), if you're looking for something to pick up again :trollface:

**Comment by alfhenrik** [comment]
:+1:

**Comment by alfhenrik** [comment]
I'll pick up this one plus #652, #653 and #654 as they're all in the same area
