### ISSUE TITLE
Add build badge to Readme.

### ISSUE THREAD

**Issue by Zoltu** [octokit/octokit.net#685]
It would be nice if the readme had a build badge.  Not because I expect master to ever go red but rather so I can have a quick link to the project on AppVeyor.  Plus, all the cool kids have badges in their Readme!

http://www.appveyor.com/docs/status-badges

I would submit a PR, but I don't have the necessary access to your AppVeyor account to get the badge link.

**Comment by shiftkey** [comment]
We've been meaning to setup an official account on AppVeyor for Octokit - currently it's just using one of our personal accounts.
