### ISSUE TITLE
Pull Request

### ISSUE THREAD

**Issue by needlina** [octokit/octokit.net#688]
hi i have some problem about using pull request with octokit.net

my code is first pic...

is just for test, anyway i tried to create pull request, and then  tried to merge,
but as you seeing second pic, "The Pull Request is not mergeable"
and i checked github, pull request is created well....
why the error came out?
and more, can i merge without button clicking in github if i use 'Merge' method??

please help me ;(( 
and thank you in advance

![merge1](https://cloud.githubusercontent.com/assets/6994028/5971819/66124c34-a891-11e4-889e-607eb69644b9.png)
![merge2](https://cloud.githubusercontent.com/assets/6994028/5971818/66124072-a891-11e4-9a3e-cb21ee07c750.png)
![merge3](https://cloud.githubusercontent.com/assets/6994028/5971820/6615cda0-a891-11e4-987b-e4f16d50e16c.png)

**Comment by shiftkey** [comment]
From what I can tell, the rejection is due to the branch not being in a mergeable state:

https://developer.github.com/v3/pulls/#response-if-merge-cannot-be-performed

If you view the PR on the website, do you see a green "Merge" button or a greyed out button?

**Comment by needlina** [comment]
@shiftkey is Green...

![20150130_152200](https://cloud.githubusercontent.com/assets/6994028/5971942/c67ab3b6-a893-11e4-98c4-5e9563acb46d.png)
