### ISSUE TITLE
Add team membership issue

### ISSUE THREAD

**Issue by aneville** [octokit/octokit.net#689]
First I'd like to say almost every other endpoint I've tried to use has worked fine and octokit seems to be doing quite well, but I'm having an issue with how the client.Organization.Team.AddMember function is setup. 

According to the github api documentation (https://developer.github.com/v3/orgs/teams/#add-team-membership) this endpoint should send an email to the user trying to be added that invites them to the organization. However, when I attempt to add a user through octokit via Organization.Team.AddMember I receive an error stating: "User isn't a member of this organization. Please invite them first." and an email is not sent to my test account inviting it to the organization.

I'm currently working on github integration into a custom development environment that would allow users to log into github and connect their projects to an organization and automatically create Teams with proper permissions. I have the setup working I'm just running into this issue. If there's anything specific you need from me to further investigate just let me know. 

EDIT: Also from further investigation into the octokit code I believe it could be a small change. Seems as though the old Add team member setup used: PUT /teams/:id/members/:username (https://developer.github.com/v3/orgs/teams/#add-team-member) however this is deprecated and scheduled to be removed in the next API version. It should probably be replaced with PUT /teams/:id/memberships/:username whenever there's a chance to modify and test.

Thanks

**Comment by Haacked** [comment]
Could you post the request and response from a Fiddler trace (with private details ommitted of course) in here?

**Comment by aneville** [comment]
I haven't used that before but I'll figure it out shortly. In the meantime I can tell you that I have tried this several times with multiple organizations and have not received any emails from github. After searching through the octokit code I found this function in Helpers/ApiUrls:

/// <summary>
        /// returns the <see cref="Uri"/> for team member
        /// </summary>
        /// <param name="id">The team id</param>
        /// <param name="login">The user login.</param>
        public static Uri TeamMember(int id, string login)
        {
            return "teams/{0}/members/{1}".FormatUri(id, login);
        }

which uses the deprecated api endpoint and is used in this function inside /Clients/TeamClients:

/// <summary>
        /// Add a member to the team
        /// </summary>
        /// <exception cref="ApiException">Thrown when a general API error occurs.</exception>
        /// <returns></returns>
        public Task AddMember(int id, string login)
        {
            Ensure.ArgumentNotNullOrEmptyString(login, "login");

            var endpoint = ApiUrls.TeamMember(id, login);
            return ApiConnection.Put(endpoint);
        }
. So we can start from there while I figure out how to use Fiddler trace.

**Comment by Haacked** [comment]
Ah! That's almost certainly it. If you clone the repo, apply that fix, and try it out, it'll probably work.

Would you be interested in fixing it and submitting a pull request? If you need help with that process, I'm happy to help. :smile:

**Comment by aneville** [comment]
I would be very interested in fixing it however I would need a bit of assistance on that part. I have only been using GIT for about 2 weeks but it's very interesting and I've always found helpful code here. I'll start by cloning and seeing if I can get it to work for me. Then I'll ask about the pull request process once I'm ready. I appreciate the quick replies!

**Comment by aneville** [comment]
So I've got the project cloned locally and the fix is done but I'm a bit stuck on the testing part. I'm a little unclear on how to generate the DLL so I can use it in my main project, unless there's a better way to test.

**Comment by Haacked** [comment]
@aneville probably the easiest way to test with your app is to compile your app, then replace the Octokit.dll with the patched version and then run your app.

**Comment by aneville** [comment]
@Haacked I must have been having a friday afternoon brain fart cause I got it working first thing this morning. So I've made the change to teh TeamMember function but I left eh TeamMembers function the same because that endpoint seems to still be current. I have the windows GIT client now so I'll attempt to commit to master and I think that's all I'll have to do. If there's anything I should know about pull requests in general just let me know!

**Comment by Haacked** [comment]
@aneville in general, it's best not to commit to `master`. Create a branch for your work and commit it there. The reason for this is if there are new changes to `master` upstream (aka new changes to `master` in `octokit/octokit.net`), it's easier to update `master` on your fork with those changes from upstream and then either merge them into your branch or rebase your branch against them.

When you create a pull request, it'll do the right thing and create the pull request against the upstream `master`. Does that make sense?

**Comment by aneville** [comment]
@Haacked I think so, so I'll make a separate branch for myself and then make a pull request. Still new to this whole process but I think I'm getting the hang of it. Apparently I've setup my current system to only commit to the master branch. Maybe I should restructure things. Thanks for the tip!

**Comment by Haacked** [comment]
@aneville Cool! We're happy to help. We follow something we call [The GitHub Flow](https://guides.github.com/introduction/flow/index.html). There's a lot of good guides if you need more background info here: https://guides.github.com/

And of course, the Octokit maintainers are happy to help when we can, though we get :arrow_down: :droplet: at times.

**Comment by aneville** [comment]
@Haacked Ha I was literally just reading over GitHub Flow as I saw the email get here. I've got the Github for windows client running and I'm trying to figure out how to do a pull request on there. I made a branch but I can't figure out the UI so I'll keep reading. Thanks for the guides! I'll be reviewing them next!

**Comment by aneville** [comment]
So I've created a pull request and updated the test cases that I missed. Nothing really compares to actually doing a pull request for understanding how it works so thanks for the opportunity! Feeling a lot more confident in how this works now. If there's anything else I need to do just let me know.

@Haacked Thanks for the help!

**Comment by shiftkey** [comment]
Fixed in #695
