### ISSUE TITLE
RepositoriesClientTests - Wrong Method Names

### ISSUE THREAD

**Issue by rms81** [octokit/octokit.net#692]
Some **RepositoriesClientTests** test methods have the names wrong. According to the method name the method under test would return **organizations** and not **repositories**. 
_RequestsTheCorrectUrlAndReturnsOrganizations()_
_RequestsTheCorrectUrlAndReturnsOrganizations()_
_RequestsTheCorrectUrlAndReturnsOrganizations()_

**Comment by shiftkey** [comment]
Yeah, those tests names could be so much better.

If you'd like to have a go at updating these, I'd be more than happy to review it and suggest changes.
