### ISSUE TITLE
i think i found some missing in CompareResult.Class check it please...

### ISSUE THREAD

**Issue by needlina** [octokit/octokit.net#694]
hi!
in this website, https://developer.github.com/v3/repos/commits/
section 'Compare two commits', you explained about comparing between commits,
so to use it with Octokit and to get result, i found CompareResult(class) (if i'm wrong please let me know)
in result with JSON type, last of webpage, there is "files":[{ "sha":"........", "filename":"......"}]
but i couldnt find 'files' field at CompareResult in Octokit. i think you forgot adding "files" field,,,

![20150202_095730](https://cloud.githubusercontent.com/assets/6994028/5994725/13be39a6-aac2-11e4-90bd-2ea0b939b8fe.png)
![20150202_095627](https://cloud.githubusercontent.com/assets/6994028/5994724/13bc0366-aac2-11e4-9f44-229a7d11c2a0.png)

check this below class in Octokit.Net please.
---------------------------------------------------------------------------------------------------------------------------

--

    public class CompareResult
    {
        public string Url { get; protected set; }
        public string HtmlUrl { get; protected set; }
        public string PermalinkUrl { get; protected set; }
        public string DiffUrl { get; protected set; }
        public string PatchUrl { get; protected set; }
        public GitHubCommit BaseCommit { get; protected set; }
        public GitHubCommit MergedBaseCommit { get; protected set; }
        public string Status { get; protected set; }
        public int AheadBy { get; protected set; }
        public int BehindBy { get; protected set; }
        public int TotalCommits { get; protected set; }
        public IReadOnlyList<GitHubCommit> Commits { get; protected set; }

        internal string DebuggerDisplay
        {
            get
            {
                return String.Format(CultureInfo.InvariantCulture, "Status: {0} Ahead By: {1}, Behind By: {2}", Status, AheadBy, BehindBy);
            }
        }
    }
-----------------------------------------------------------------------------------------------------------------------------

i would like to receive your reply asap
have a good day :) and thank you in advance!

**Comment by Haacked** [comment]
Yes, it looks like we're missing that property. Want to submit a pull request that adds it in?

**Comment by alfhenrik** [comment]
This can be closed...fixed in 68c4c98270517fabd1bcd3de7f5fe4d68c97ba8d :smile:

**Comment by shiftkey** [comment]
![](http://www.troll.me/images/compliment-bender/indeed-well-played-good-sir.jpg)
