### ISSUE TITLE
Forking a repository to current user

### ISSUE THREAD

**Issue by kbilsted** [octokit/octokit.net#698]
how do i fork a repository? the #313 supposedly fixed this, but I'm not able to find the api that has been implemented. Neither from the nuget package nor when i download the source for browsning.

**Comment by johnduhart** [comment]
That PR was never completed. If you want you can pick up where I left off at #495

**Comment by kbilsted** [comment]
I would require serious amounts of support to pull that off. I can't even open the csproj under windows 7 which I'm currently using.

Also it's a bit unclear to me what the outstanding issues are and why the PR was closed in the first place

**Comment by shiftkey** [comment]
@kbilsted you'll need VS2013 to open the solution locally

**Comment by kbilsted** [comment]
I have VS2013, it opens a window telling me windows 8.1 is required.

**Comment by shiftkey** [comment]
> I have VS2013, it opens a window telling me windows 8.1 is required.

That's just for some specific projects which use NetCore. Don't worry about it!

**Comment by kbilsted** [comment]
Sure I can ignore that, but when I then build from within VS all hell breaks loose. Hundreds of warnings and errors.

**Comment by Haacked** [comment]
Hmm, try unloading that project.

**Comment by kristianhald** [comment]
I'll look at the pull request to determine if I can make the necessary changes so that it can be merged.

**Comment by DavidStrickland0** [comment]
Anyone get anywhere on this one? Is pr 495 still the best spot to start from?

**Comment by shiftkey** [comment]
@DavidStrickland0 #776 is almost wrapped up and ready to merge, so forking a repository should go out in the next release!

**Comment by shiftkey** [comment]
I'll drop a note in here when it's been released, but #776 has been merged into `master`

**Comment by DavidStrickland0** [comment]
Appreciate the work. Thanks

**Comment by shiftkey** [comment]
@DavidStrickland0 @kbilsted this is now available in v0.12 on NuGet.

**Comment by kbilsted** [comment]
Cheers
