### ISSUE TITLE
WatchersCount on repository incorrect

### ISSUE THREAD

**Issue by DaveWM** [octokit/octokit.net#699]
It looks like the WatchersCount property is set incorrectly on the repository object, it's always the same as the StargazersCount property. For example, it is showing as 605 for this repo when it should be 80. Will submit a PR for this when I have time :).

**Comment by shiftkey** [comment]
@DaveWM I think this is actually a bug in the GitHub API - https://api.github.com/repos/octokit/octokit.net

cc @pengwynn

**Comment by pengwynn** [comment]
It's confusing but that's expected, [because history][post].

You'll find what the UI calls "Watchers" in the `subscribers_count` field for API resources.

[post]: https://developer.github.com/changes/2012-9-5-watcher-api/

**Comment by shiftkey** [comment]
@pengwynn thanks for the details

**Comment by DaveWM** [comment]
@shiftkey @pengwynn Thanks guys :)

**Comment by Haacked** [comment]
@shiftkey @DaveWM if I understand this correctly, it seems like we should remove the deprecated property from our client API. I'm guessing `WatchersCount` can go away as long as we have a `SubscribersCount` property?

**Comment by shiftkey** [comment]
@haacked gah, you're right - we can still fix this.

We could map `subscribers_count` to `WatchersCount` instead of deprecating the property altogether. How does that feel?

**Comment by Haacked** [comment]
I'd rather have the property name match the api field name as much as possible. We're not 1.0 yet, we can do whatever the hell we want. :stuck_out_tongue:  Let's just match the API canonical names.

**Comment by shiftkey** [comment]
Fiiiiine :stuck_out_tongue:

**Comment by Haacked** [comment]
:stuck_out_tongue: It's just my preference. I think it's a good rule of thumb. But I'm open to strong arguments to the contrary in specific cases. :smile:

**Comment by Haacked** [comment]
Also, if we're all in agreement, would you like to submit a PR with this change @DaveWM?

**Comment by shiftkey** [comment]
> It's just my preference. I think it's a good rule of thumb. 

I'm just being pre-caffeine silly here. As the behaviour isn't going to change for the lifetime of v3, I'm :thumbsup: with hiding away this incorrect field.

**Comment by DaveWM** [comment]
@Haacked @shiftkey I've made a PR (#701), just removed the `WatchersCount` property. Probably a good idea to remove this even though it's still on the api, just to avoid confusion
