### ISSUE TITLE
Payload for Activity

### ISSUE THREAD

**Issue by DaveWM** [octokit/octokit.net#703]
The `Activity` class currently doesn't have a payload property ([which they do in the api](https://developer.github.com/v3/activity/events/)), which would be really useful. I couldn't find any existing issues for this, is it something you guys have talked about in the past? 

I'd be happy to implement the payload for some of the most common [event types](https://developer.github.com/v3/activity/events/types/), but doing it for all types would be a big job (there are 25 types in total).

**Comment by Haacked** [comment]
We just haven't gotten around to it. Would love a PR that implements as many as you feel like. And then open a new issue with a list of the remaining for others to implement?

**Comment by DaveWM** [comment]
Cool, I'll spend some time on it over the weekend

**Comment by DaveWM** [comment]
Hey guys, I've made a PR for this (#737). I've implemented 9 of the 25 types of event payload. It may need cleaning up a bit, see the comments on the PR
