### ISSUE TITLE
A related project I am working on

### ISSUE THREAD

**Issue by BrisingrAerowing** [octokit/octokit.net#704]
I am working on a Powershell wrapper for Octokit, called Posh-Octokit. When I get a good base going I will upload it to a repository on my account. I am just starting out with it, and it is getting late where I am, so I will continue working on it tomorrow.

If this is not the right place to post this, I will gladly take a pointer to the place this should go.

**Comment by shiftkey** [comment]
@BrisingrAerowing sounds interesting! I can't wait to see what you make! 

I can add a note to the README about related projects once you have something to show off - there's also a [ScriptCs.Octokit](https://github.com/alfhenrik/ScriptCs.OctoKit) project which I should point people to cc @alfhenrik.

I'll leave this open until I can do that.

**Comment by alfhenrik** [comment]
![image](https://cloud.githubusercontent.com/assets/1035315/6224840/581233e2-b6ce-11e4-9737-ea9ab446f475.png)

**Comment by Haacked** [comment]
:cool: Personally, I think it should be called "Poshtokit" :stuck_out_tongue:  :octocat:

**Comment by shiftkey** [comment]
@BrisingrAerowing feel free to submit a PR once you've got something cool to show off!
