### ISSUE TITLE
Retrieving batch IssueEvents : is there a more efficient way?

### ISSUE THREAD

**Issue by erichexter** [octokit/octokit.net#706]
Sorry for posing a question rather then an Issue. 

I am trying to determine if there is a more efficient way for querying all the label and unlabeled Issue events from the api. Currently I have an N+1 algorithm, where I get all the events, then I call this for each issue.

```Csharp
client.Issue.Events.GetForIssue(user, repository, issue.Number)
                                .Result.Where(
                                    a => a.Event == EventInfoState.Labeled || a.Event == EventInfoState.Unlabeled)
                                .ToList()
```

Is there a better way to accomplish this?

**Comment by shiftkey** [comment]
A quick thought: perhaps get all events for the repository?

```
var events = await client.Issue.Events.GetForRepository(user, repository);
var filteredEvents = events.Where(a => a => a.Event == EventInfoState.Labeled || a.Event == EventInfoState.Unlabeled).ToList();
```

This will handle the pagination work, however it has an upper limit on the data you can retrieve (I forget how high this goes, but unfortunately it's not configurable currently) so some old data might not be available.

**Comment by erichexter** [comment]
I saw that method, I just assumed, it would not include the issue events in that repo, looking at the api docs, it made me think, it would just include team member adds, and other repo level events.  I will try that out and see I was just being an ID10T.

**Comment by erichexter** [comment]
That seems to be working for me.  It would be nice if the rest endpoint supported some filtering, so that I could just pull down the event types I am looking for, but this seems to do the jop  Thanks @shiftkey
