### ISSUE TITLE
Revisit Mono/MonoTouch/MonoDroid Support

### ISSUE THREAD

**Issue by shiftkey** [octokit/octokit.net#719]
As we found out in https://github.com/octokit/octokit.net/pull/717, out Mono\* support has been lacking recently (mostly due to neglect on our part).

It was suggested in https://github.com/octokit/octokit.net/issues/684#issuecomment-75685924 that the Portable Class Library version of Octokit could be used for Mono platforms, as it's only dependency is on the `Microsoft.Net.Http` package.

There's lots of things I'd love to do here to give this first-class support, but first I'd like to understand what the value is for us to maintain separate projects for the Mono\* builds. Any resources I should be reading on this?

Feel free to pull in any Xamarin experts you can think of.

**Comment by thedillonb** [comment]
I'd also be pretty interested to hear what any experts have to suggest. I've been using the portable version and having had any issue.

**Comment by shiftkey** [comment]
Closing this out as we target .NET Standard 1.1 which I believe is Good Enough™.

Please open a fresh issue if there's additional work we could do here.
