### ISSUE TITLE
ReleaseAssetUpload is a request object, not a response object

### ISSUE THREAD

**Issue by shiftkey** [octokit/octokit.net#721]
See https://github.com/fsharp/FAKE/commit/7fcbd023443c20bacaf658548334b5e19b48c5ed

This was incorrectly cleaned up to be a `readonly` object in https://github.com/octokit/octokit.net/pull/679/ because it was in the wrong folder.

https://github.com/octokit/octokit.net/pull/679/files#diff-ab14db36e8c16d064dcf820ede18e2c6

What should be done:

- move it under the `Request` folder (no namespace changes)
- put the setters back to public
- leave the ctor for now but mark it as obsolete

**Comment by forki** [comment]
please keep me updated about this. I need to update https://github.com/fsharp/FAKE/blob/master/modules/Octokit/Octokit.fsx when change it again.

**Comment by shiftkey** [comment]
@forki :thumbsup:

**Comment by shiftkey** [comment]
Fixed in #724 and shipped in v0.7.1
