### ISSUE TITLE
Feature Request: Append to file

### ISSUE THREAD

**Issue by omidkrad** [octokit/octokit.net#728]
This is probably a Git API issue, but I didn't find a better place to post it.

Please support appending to a file without having to [Update](https://developer.github.com/v3/repos/contents/#update-a-file) the whole file. This is especially useful for data-like files that you want to append a line to them but don't want to update the whole thing over the network.

**Comment by omidkrad** [comment]
See these for examples of data hosted on GitHub:

- http://data.okfn.org/data
- http://dataprotocols.org/

**Comment by shiftkey** [comment]
Thanks for the feedback @omidkrad, however this is just the repository for managing the .NET wrapper around the GitHub API. 

You can contact the API developers directly by using support@github.com to discuss this further.
