### ISSUE TITLE
Implementing a IHttpClient leads to lots of code copy

### ISSUE THREAD

**Issue by thedillonb** [octokit/octokit.net#729]
I'm currently working to implement a IHttpClient so that I can use @paulcbetts ModernHttpClient as the message handler. So far it's not pretty as I basically have to copy a lot of the code in the `HttpClientAdapter.cs`'s message construction methods. It then gets worse because `Response` is an internal object - ok what ever, that's easy to work around, I'll just create my own - however the problem then becomes that within `Response` is the `ApiInfoParser` which is also internal. So I end up copying a lot of code just to rebuild that functionaility just so I can swap out the Http handler. This is obviously not a huge deal but I think this can be avoided by maybe moving `BuildResponse` and `BuildRequestMessage` out of `HttpClientAdapter` and into a helper class or just swaping `internal` -> `public` on the `Response` or `ApiInfoParser`

**Comment by shiftkey** [comment]
cc @haacked

**Comment by thedillonb** [comment]
Prepare to laugh as I found an easy way around this by abusing some objects. Basically just inherited the HttpClientAdapter, made those methods public so I could build the request/response, and referenced that.

```
    public class OctokitModernHttpClient : IHttpClient
    {
        private readonly MessageBuilder _messageBuilder = new MessageBuilder();

        /// <summary>
        /// Sends the specified request and returns a response.
        /// </summary>
        /// <param name="request">A <see cref="IRequest"/> that represents the HTTP request</param>
        /// <param name="cancellationToken">Used to cancel the request</param>
        /// <returns>A <see cref="Task" /> of <see cref="IResponse"/></returns>
        public async Task<IResponse> Send(IRequest request, CancellationToken cancellationToken)
        {
            if (request == null)
                throw new ArgumentNullException("request");

            var httpOptions = new NativeMessageHandler
            {
                AllowAutoRedirect = request.AllowAutoRedirect
            };
            if (httpOptions.SupportsAutomaticDecompression)
            {
                httpOptions.AutomaticDecompression = DecompressionMethods.GZip | DecompressionMethods.Deflate;
            }

            var http = new HttpClient(httpOptions)
            {
                BaseAddress = request.BaseAddress,
                Timeout = request.Timeout
            };
            using (var requestMessage = _messageBuilder.BuildRequestMessage(request))
            {
                // Make the request
                var responseMessage = await http.SendAsync(requestMessage, HttpCompletionOption.ResponseContentRead, cancellationToken)
                    .ConfigureAwait(false);
                return await _messageBuilder.BuildResponse(responseMessage).ConfigureAwait(false);
            }
        }

        /// <summary>
        /// This class' only purpose is so I can call the helper methods.
        /// </summary>
        private class MessageBuilder : HttpClientAdapter
        {
            public new HttpRequestMessage BuildRequestMessage(IRequest request)
            {
                return base.BuildRequestMessage(request);
            }

            public new Task<IResponse> BuildResponse(HttpResponseMessage responseMessage)
            {
                return base.BuildResponse(responseMessage);
            }
        }
    }
```

**Comment by shiftkey** [comment]
![](http://i0.kym-cdn.com/photos/images/newsfeed/000/154/596/fb0.jpg)

But more seriously, this is something we've kicked around a bunch in the past - I've not settled on a design I'm personally happy with, but https://github.com/octokit/octokit.net/issues/352  https://github.com/octokit/octokit.net/pull/369 and https://github.com/nigel-sampson/octokit.caching are interesting discussions to follow.

I definitely think our recent changes has made this harder - thanks for the specifics on issues you're encountering...

**Comment by Haacked** [comment]
You may well be the first person we've run into who's tried to implement our `IHttpClient`! :smile:

Would welcome some PRs that improve the API.

**Comment by thedillonb** [comment]
I can definitely come up with a PR. My two big use cases for toying around with the IHttpClient are:

* Instantiate a different HttpClient Handler (in this cause it's the ModernHttpClient)
* Utilize an on-disk caching via Akavache which means the IResponse object should be in one way shape or form available for serialization and if not, it should be easy to parsist the object in another class and then reform the IResponse object after deserialization.

I think this will be relatively easy as much of the logic is all right there but just needs a visability change or  adjustment to make it slightly more flexable. Either way, I'll post a PR soon.

**Comment by darrelmiller** [comment]
@thedillonb Should be straightforward to use a different HttpClientHandler with the changes in https://github.com/octokit/octokit.net/pull/808

**Comment by marin-bratanov** [comment]
I also need to swap out the HttpClient for a different implementation. In my case it's because Blazor nuked its SendAsync() method, so now nothing from Octokit works under Blazor. Reference:

* [https://github.com/aspnet/AspNetCore/issues/9125](https://github.com/aspnet/AspNetCore/issues/9125)
* [https://github.com/aspnet/Blazor/issues/1484](https://github.com/aspnet/Blazor/issues/1484) 

So far I've been unable to figure out how to use the overload for a Connection class that will let me use my own. This feels like it has to be the approach to go in Blazor: [https://github.com/aspnet/Blazor/issues/1484#issuecomment-424738744](https://github.com/aspnet/Blazor/issues/1484#issuecomment-424738744)
