### ISSUE TITLE
Search in repositories without term

### ISSUE THREAD

**Issue by alisabzevari** [octokit/octokit.net#732]
I have tested api with this request:
https://api.github.com/search/repositories?q=language:assembly&sort=stars&order=desc
It returns the correct result. I wanted to get all repositories with assembly language.

The problem is Octokit.net does not allow creating SearchRepositoriesRequest with empty term in constructor.

**Comment by Haacked** [comment]
Ah. Ok. Mind sending a pull request? We should just make that ctor empty and allow setting the term property.

**Comment by alisabzevari** [comment]
I tried to fix the issue but I found something else:

This is not a valid request:
https://api.github.com/search/code?q=in:file+repo:jquery/jquery
In the error message it says "Searches that use qualifiers only are not allowed." but this request is valid:
https://api.github.com/search/code?q=language:js+repo:jquery/jquery
I think there is a misconception in API.

**Comment by alexandrugyori** [comment]
I added a pull request adding no-args constructor since I needed the feature.

**Comment by raffaeler** [comment]
Can someone tell me why I still can't search without a term?
Am I doing something wrong?
*  throws: `new SearchCodeRequest(null, owner, repositoryName)`
* can't specify the owner/repository with the default ctor

Thanks!
