### ISSUE TITLE
Repository.GetAllForCurrent is getting all *not* for current

### ISSUE THREAD

**Issue by distantcam** [octokit/octokit.net#733]
var githubClient = new GitHubClient(new ProductHeaderValue("ListRepoTest"));
    githubClient.Credentials = new Credentials("[TOKEN]");
    var repos = await githubClient.Repository.GetAllForCurrent();

This seems to return all the repos not just the ones for the "current" user. Is that because I'm using a token instead of user/password? If so, how do I provide user/password credentials when I'm also using 2fa?

**Comment by shiftkey** [comment]
If you're testing this in 0.7.x this might involve the changes to the `/user/repos` endpoint documented [here](https://developer.github.com/changes/2014-12-08-organization-permissions-api-preview/#whats-happening-to-the-list-your-repositories-api) - are you seeing organization repositories in the API response?

**Comment by distantcam** [comment]
Yes it was 0.7.1.

I don't know if I'm seeing my organizations or not because after about 100 pages I tend to stop debugging. It's downloading *all* the repos, not just mine.

**Comment by shiftkey** [comment]
Yeah, that doesn't sound good at all. I thought I might have messed something up recently but #691 is the only one I can think of - and it's not merged yet.

Can you grab a sample repsonse from Fiddler (just one, not all 100 :grinning:) and send it to me over email or Skype?
