### ISSUE TITLE
missing unsubscribed value from EventInfo enum

### ISSUE THREAD

**Issue by erichexter** [octokit/octokit.net#738]
Requested value 'unsubscribed' was not found. For an Issue Event.  When calling the following api: client.Issue.Events.GetForRepository(user, repository);

Here is the enum, that is missing the value.
https://github.com/octokit/octokit.net/blob/master/Octokit/Models/Response/EventInfo.cs#L75

Looking at the docs, I don't see unsubscribed as a documented event, but I do see a subscribed event. 
https://developer.github.com/v3/issues/events/

Exception Stack Trace Below.
Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.ArgumentException: Requested value 'unsubscribed' was not found.

Source Error: 

Line 93:                         // remove '-' from values coming in to be able to enum utf-8
Line 94:                         stringValue = RemoveHyphenAndUnderscore(stringValue);
Line 95:                         return Enum.Parse(type, stringValue, ignoreCase: true);
Line 96:                     }

**Comment by shiftkey** [comment]
@erichexter perhaps this is something missing from the docs - is this a public repository I could run a test against to confirm this behaviour?

**Comment by erichexter** [comment]
It is a public repository. I got the error running the command on
https://github.com/waffleio/waffle.io


Eric Hexter

blog | http://Hex.LosTechies.com
info | http://www.linkedin.com/in/erichexter

**Comment by shiftkey** [comment]
@erichexter :heart:

**Comment by shiftkey** [comment]
Weird, I couldn't trigger the issue using this test harness (against b3859cf6eecc510d484d7f846e855fd07952a0b0):

```
[IntegrationTest]
public async Task ReturnsACollection()
{
    var github = Helper.GetAuthenticatedClient();
    var events = await github.Activity.Events.GetAllForRepository("waffleio", "waffle.io");
    Assert.NotEmpty(events);
} 
```

@erichexter am I missing something?

**Comment by erichexter** [comment]
So I was using client.Issue not client.Activity 
``` 
client.Issue.Events.GetForRepository(user, repository);
```

**Comment by shiftkey** [comment]
Found it: https://api.github.com/repos/waffleio/waffle.io/issues/events/142230057

**Comment by darrencamp** [comment]
I'm going to have a go at fixing this one.

**Comment by shiftkey** [comment]
@darrencamp thanks!

I'll follow up with the team whether this should be documented, but for now I think we should just Fix The Bug.

**Comment by shiftkey** [comment]
This will go out in the next release

**Comment by shiftkey** [comment]
This has been deployed in v0.8.0
