### ISSUE TITLE
list-your-authorizations in AuthorizationsClient

### ISSUE THREAD

**Issue by needlina** [octokit/octokit.net#745]
about Authorization : 

i tried to get GitHub API with Token, so i took AuthorizationClient, in detail, i wanna take token from AuthorizationClient's GetAll() and Get(id). but the problem is 'Authorization' Class, the 'ApplicationAuthorization' Class has token Property but Authorization has not.. is there any reason why like that?
if is not good idea, is there any way to using GitHub API with Personal access tokens
or taking token with basic authorization?

GitHub API is really helps me i really appreciate you guys 
thanks in advance! :)

**Comment by shiftkey** [comment]
This is a recent change as the API team wanted to close the security hole around letting third party integrations read the tokens that a user has:

https://developer.github.com/changes/2015-02-20-migration-period-removing-authorizations-token/

If you still want to access the `Token` you can use the `GetOrCreateApplicationAuthentication` method without setting `NewAuthorization.Fingerprint`. It won't return you all the authorizations, but for specific cases it should be a good enough workaround.

I've written a test here which demonstrates this behaviour:

https://github.com/octokit/octokit.net/blob/master/Octokit.Tests.Integration/Clients/AuthorizationClientTests.cs#L10-L53

Let me know if anything is unclear here and I'll reopen the issue.

> is there any way to using GitHub API with Personal access tokens. or taking token with basic authorization?

I'm not sure I understand the question. Could you expand on what you're trying to do here?

**Comment by needlina** [comment]
@shiftkey 

i think my explain was not enough,, sorry
actually i'm using github enterprise, so i dont wanna create "Developer application" that their own.
so i dont use ClientId, ClientSecret properties,,,,
thats why i wanna use Personal access tokens. i want 'Users' can take GitHub API with their own token... of course, they has id and password but is just only the way to get Autorization to get token,,

simply, process that i want is,, user id and password "basic authorization" -> getting personal token -> create GitHubClients with 'the token'

i want this process ^^ can i do process with Octokit? 

i hope you could get it! sorry for my poor explain! thank you :))
