### ISSUE TITLE
 List pull requests files

### ISSUE THREAD

**Issue by shiftkey** [octokit/octokit.net#747]
Reference: https://developer.github.com/v3/pulls/#list-pull-requests-files

This should live inside `IPullRequestsClient`.

This endpoint should return a `Task<IReadOnlyList<PullRequestFile>>` - you can basically C#-ify the hash properties returned from the endpoint and it should largely work as-is.

Tests would be great, use an old Octokit PR to ensure you're testing against live data :trollface:

**Comment by alfhenrik** [comment]
I'll take this one, and #746 as it's in the same area

**Comment by shiftkey** [comment]
:thumbsup:
