### ISSUE TITLE
Get Archive Link for Repository Contents

### ISSUE THREAD

**Issue by shiftkey** [octokit/octokit.net#748]
Reference: https://developer.github.com/v3/repos/contents/#get-archive-link

This should belong under `IRepositoryContentsClient` but the workflow for turning a `302` into actual content might need a bit of thought.

**Comment by alfhenrik** [comment]
I'll take a :athletic_shoe: :football: at this one

**Comment by alfhenrik** [comment]
Looking at Octokit.rb the `Get Archive Link` method just returns the URL returned in the `Location` header, so I started thinking and thought I'd ask, for Octokit.net should we provide **two** methods:
- one that just returns the URL in the `Location` header, and 
- one that (somehow) follows the redirect and returns the contents of the archive?

**Comment by shiftkey** [comment]
Definitely have the first option. If the second option is easy enough to add in, I'd happily accept it as well...

**Comment by alfhenrik** [comment]
First option is the easy one :grinning: It's the second one that will take some :thought_balloon:

**Comment by shiftkey** [comment]
Note: #808 will complete this feature (by introducing `GetArchive` which follows the received `302`) and the old `GetArchiveLink` will be obsoleted in a future release.
