### ISSUE TITLE
Issue.ToUpdate forgets Labels

### ISSUE THREAD

**Issue by nigel-sampson** [octokit/octokit.net#762]
Unsure whether this is a bug or intended but `Issue.ToUpdate` doesn't copy over the Labels to `IssueUpdate`. There is a test that asserts the default value to be null which I assume means no change. However that property then behaves differently to the other properties of `IssueUpdate`.

I came across this when I wanted to remove a Label, this then entrails copying over the Labels and then removing the one I don't want.

Can submit a PR if wanted.

**Comment by shiftkey** [comment]
Heh, was waiting to see when I'd be back in this code. Removing *one* label isn't a scenario I'd thought about when I was in https://github.com/octokit/octokit.net/pull/718.

Perhaps an overload to `Add` that takes a range of labels? Would that make you happier?

cc @thedillonb

**Comment by nigel-sampson** [comment]
Given my code the new overload wouldn't matter but I imagine it could be helpful to other people. It's enough for me to know this intended behaviour.

Am curious why we treat Labels different and leave as (null / no change) but don't do the same for the others such as Body? (unless that behaviour has changed as well).

**Comment by shiftkey** [comment]
> Am curious why we treat Labels different and leave as (null / no change) but don't do the same for the others such as Body? 

The milestone and labels are handled slightly differently to the other fields in the API on PATCH: https://developer.github.com/v3/issues/#edit-an-issue

I know I can make this clearer in our API, this feedback is great :sparkles:

**Comment by nigel-sampson** [comment]
Yeah I just discovered the `IssueUpdate.Milestone` `null` vs `new int?()`.

Thanks
