### ISSUE TITLE
exception: attempt was made to access a socket in a way forbidden

### ISSUE THREAD

**Issue by erichexter** [octokit/octokit.net#775]
Using Octokit v 0.8 

I got the strangest exception running in an azure website, the same code executes without an error locally, and this error seems to occur on a repo with a large amount of issue >2k. (Waffleio/waffle.io)

The call into octokit which is throwing this exception is.
IReadOnlyList<Octokit.IssueEvent> events = await client.Issue.Events.GetForRepository(user, repository);

exception message

An attempt was made to access a socket in a way forbidden by its access permissions

stack trace
===

An attempt was made to access a socket in a way forbidden by its access permissions

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.Net.Sockets.SocketException: An attempt was made to access a socket in a way forbidden by its access permissions

Source Error: 

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.

SocketException (0x271d): An attempt was made to access a socket in a way forbidden by its access permissions]
   System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress) +6641636
   System.Net.Sockets.Socket.InternalBind(EndPoint localEP) +80
   System.Net.Sockets.Socket.BeginConnectEx(EndPoint remoteEP, Boolean flowContext, AsyncCallback callback, Object state) +171
   System.Net.Sockets.Socket.UnsafeBeginConnect(EndPoint remoteEP, AsyncCallback callback, Object state) +50
   System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception) +414

[WebException: Unable to connect to the remote server]
   System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult) +6462362
   System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar) +64

[HttpRequestException: An error occurred while sending the request.]
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +93
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +52
   Octokit.Internal.<Send>d__2.MoveNext() in c:\Users\shiftkey\Documents\GitHub\octokit.net\Octokit\Http\HttpClientAdapter.cs:61
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +93
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +52
   Octokit.<RunRequest>d__23.MoveNext() in c:\Users\shiftkey\Documents\GitHub\octokit.net\Octokit\Http\Connection.cs:445
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +93
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +52
   Octokit.<Run>d__1f`1.MoveNext() in c:\Users\shiftkey\Documents\GitHub\octokit.net\Octokit\Http\Connection.cs:436
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +93
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +52
   Octokit.Internal.<GetNextPage>d__0.MoveNext() in c:\Users\shiftkey\Documents\GitHub\octokit.net\Octokit\Http\ReadOnlyPagedCollection.cs:0
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +93
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +52
   Octokit.<GetAllPages>d__0`1.MoveNext() in c:\Users\shiftkey\Documents\GitHub\octokit.net\Octokit\Clients\ApiPagination.cs:0
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +93
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +52
   System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() +24
   OctokitDemo.Controllers.<Create>d__3b.MoveNext() in c:\Users\Eric\Documents\Github\octokit-oauth-demo\OctokitDemo\Controllers\Cfd.cs:44
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +93
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +52
   System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() +24
   OctokitDemo.Controllers.<Report>d__1b.MoveNext() in c:\Users\Eric\Documents\Github\octokit-oauth-demo\OctokitDemo\Controllers\HomeController.cs:127
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +93
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +52
   System.Web.Mvc.Async.TaskAsyncActionDescriptor.EndExecute(IAsyncResult asyncResult) +84
   System.Web.Mvc.Async.<>c__DisplayClass37.<BeginInvokeAsynchronousActionMethod>b__36(IAsyncResult asyncResult) +17
   System.Web.Mvc.Async.WrappedAsyncResult`1.CallEndDelegate(IAsyncResult asyncResult) +10
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +48
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult) +32
   System.Web.Mvc.Async.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d() +50
   System.Web.Mvc.Async.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f() +225
   System.Web.Mvc.Async.<>c__DisplayClass33.<BeginInvokeActionMethodWithFilters>b__32(IAsyncResult asyncResult) +10
   System.Web.Mvc.Async.WrappedAsyncResult`1.CallEndDelegate(IAsyncResult asyncResult) +10
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +48
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult) +34
   System.Web.Mvc.Async.<>c__DisplayClass2b.<BeginInvokeAction>b__1c() +26
   System.Web.Mvc.Async.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult) +100
   System.Web.Mvc.Async.WrappedAsyncResult`1.CallEndDelegate(IAsyncResult asyncResult) +10
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +48
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult) +27
   System.Web.Mvc.Controller.<BeginExecuteCore>b__1d(IAsyncResult asyncResult, ExecuteCoreState innerState) +13
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +36
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +53
   System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult) +39
   System.Web.Mvc.Controller.<BeginExecute>b__15(IAsyncResult asyncResult, Controller controller) +12
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +28
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +53
   System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult) +29
   System.Web.Mvc.Controller.System.Web.Mvc.Async.IAsyncController.EndExecute(IAsyncResult asyncResult) +10
   System.Web.Mvc.MvcHandler.<BeginProcessRequest>b__5(IAsyncResult asyncResult, ProcessRequestState innerState) +21
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +36
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +53
   System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult) +31
   System.Web.Mvc.MvcHandler.System.Web.IHttpAsyncHandler.EndProcessRequest(IAsyncResult result) +9
   System.Web.CallHandlerExecutionStep.OnAsyncHandlerCompletion(IAsyncResult ar) +129

**Comment by shiftkey** [comment]
> SocketException (0x271d): An attempt was made to access a socket in a way forbidden by its access permissions]

Is this consistently occurring on Azure?

This looks like it's an environment-specific problem, not quite sure what I can do from Octokit itself to address this...

**Comment by erichexter** [comment]
It is consistent on azure, not super critical for me as this is just a
large repo I use to test my app (and the api). I will contact some of my
azure friends to see if they can shed some light on this and maybe this
would go into some sort of FAQ on the wiki (?)

Eric Hexter

blog | http://Hex.LosTechies.com
info | http://www.linkedin.com/in/erichexter

**Comment by shiftkey** [comment]
@erichexter that'd be great. if you have any extra details I can reopen this issue.

**Comment by jbkielis** [comment]
Were you ever able to find out the cause of this issue?  Thanks.

**Comment by erichexter** [comment]
I did not, I was able to reproduce it but I ended up moving my project to a
virtual machine and I never had this problem. If you have a simple test
case to reproduce it I can connect you with a azure architect who said he
would troubleshoot it.

On Thursday, May 21, 2015, jbkielis <notifications@github.com> wrote:

> Were you ever able to find out the cause of this issue? Thanks.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/octokit/octokit.net/issues/775#issuecomment-104395632>
> .
>


-- 
Eric Hexter

blog | http://Hex.LosTechies.com
info | http://www.linkedin.com/in/erichexter
