### ISSUE TITLE
[Question] Get the commit and commit date of specific folder/file

### ISSUE THREAD

**Issue by NitroXenon** [octokit/octokit.net#778]
I can get the commit and commit date using Github API : 
`https://api.github.com/repos/User/Repo/commits?path=Filename`

But how can I get those data using octokit.net? There is no detailed document and sample so I dont know how to do it...

**Comment by shiftkey** [comment]
I've not documented it, but I've adapted one of our integration tests to illustrate this API:

```csharp
[IntegrationTest]
public async Task CanGetListOfCommitsByPath()
{
    var client = new GitHubClient(new ProductHeaderValue("my-cool-app"));
    var request = new CommitRequest { Path = "Octokit.Reactive/IObservableGitHubClient.cs" };
    var list = await client.Repository.Commits.GetAll("octokit", "octokit.net", request);
}
```

**Comment by alfhenrik** [comment]
Hi!

The following should do what you need:

```
var client = new GitHubClient(new ProductHeaderValue("MyAwesomeGitHubClient");
var repoCommits = client.Repository.Commits;
var request = new CommitRequest { Path = "Octokit.Reactive/IObservableGitHubClient.cs" };
var commits = await repoCommits.GetAll("octokit", "octokit.net", request);
```

Other examples can also be found here https://github.com/octokit/octokit.net/blob/ede59d18de13355e557bfa8207e7c63d00fb18d0/Octokit.Tests.Integration/Clients/RepositoryCommitsClientTests.cs

Hope that helps! :smile:

**Comment by alfhenrik** [comment]
D'oh, too slow :hurtrealbad:
