### ISSUE TITLE
GitHubCommit.Author/Committer should be a simple object, not Author type 

### ISSUE THREAD

**Issue by shiftkey** [octokit/octokit.net#779]
Currently when you retrieve a commit from `{user}/{repo]/commits` you get this payload for the `Author` and `Committer`:

```json
      "author": {
        "name": "Gabriel Weyer",
        "email": "gabrielweyer@gmail.com",
        "date": "2014-05-04T00:46:35Z"
      },
      "committer": {
        "name": "Gabriel Weyer",
        "email": "gabrielweyer@gmail.com",
        "date": "2014-05-04T00:46:35Z"
      },
```

This doesn't align with what we have defined in `GitHubCommit.Author` and `GitHubCommit.Committer` - we should introduce a specify type which contains just these properties.

**Comment by khellang** [comment]
Sounds like... `CommitCommitter` :trollface:

**Comment by willsb** [comment]
I really wanna get my feet wet on OSS, and this bug seems like a good start. Can I call it mine and fix it? 

Also, I can't think of a name other than CommitCommitter lol

**Comment by shiftkey** [comment]
@willsb I think `CommitEntity` is a better term :grinning: - and you're more than welcome to make a start on it

**Comment by willsb** [comment]
@shiftkey Okay, I'll take a look at it this weekend. Just commenting here to let everyone aware :)

**Comment by shiftkey** [comment]
![cantwait](https://cloud.githubusercontent.com/assets/359239/7882424/a3a87370-064c-11e5-97c7-f5ef7f216279.gif)

**Comment by Haacked** [comment]
> Currently when you retrieve a commit from `{user}/{repo]/commits` you get this payload for the `Author` and `Committer`:

@shiftkey that's not exactly correct.

If you look at https://developer.github.com/v3/repos/commits/#get-a-single-commit you'll see the payload looks more like (bunch of stuff cut out):

```js
{
  "commit": {
    "author": {
      "name": "Monalisa Octocat",
      "email": "support@github.com",
      "date": "2011-04-14T16:00:49Z"
    },
    "committer": {
      "name": "Monalisa Octocat",
      "email": "support@github.com",
      "date": "2011-04-14T16:00:49Z"
    },
    "author": {
      "login": "octocat",
      "id": 1,...
    }
    "committer": {
      "login": "octocat",
      "id": 1,...
    }
}
```

So note that `GitHubCommit` has `Author` and `Committer` properties. But it also has an inner `Commit` property that also has an `Author` and `Committer`.

`GitHubCommit` represents a commit database record which includes things like comments etc. The `Author` and `Committer` properties of `GitHubCommit` represents GitHub accounts _if it could match one up_. The inner `Commit` property of `GitHubCommit` represents the raw Git commit and its `Author` and `Committer` properties represent the basic information that Git has for the commit.

The one thing I haven't had time to determine is what happens on the `GitHubCommit` response if it couldn't match up the `Author` with an account. I assume it just returns the simple form. @pengwynn @jasonrudolph do you know what happens for sure? I'd love a pointer to the code. :smile:

**Comment by jasonrudolph** [comment]
> The one thing I haven't had time to determine is what happens on the `GitHubCommit` response if it couldn't match up the `Author` with an account. I assume it just returns the simple form. @pengwynn @jasonrudolph do you know what happens for sure? I'd love a pointer to the code. :smile:

If the author doesn't map to a GitHub account, then the top-level `author` attribute has a `null` value. The same goes for the committer. Example:

```
curl https://api.github.com/repos/android/platform_system_core/commits/8731d30085b02012487552d8ad6d95c0ac9a8d4d
```

```js
{
  "sha": "8731d30085b02012487552d8ad6d95c0ac9a8d4d",
  "commit": {
    "author": {
      "name": "Sami Tolvanen",
      "email": "samitolvanen@google.com",
      "date": "2015-09-28T15:43:43Z"
    },
    "committer": {
      "name": "Sami Tolvanen",
      "email": "samitolvanen@google.com",
      "date": "2015-09-28T15:52:38Z"
    },
    // ...
  },
  // ...
  "author": null,
  "committer": null,
  // ...
}
```

**Comment by Haacked** [comment]
@jasonrudolph That's kind of what I hoped would happen. :smile: Makes it easier for us connoisseurs of statically typed languages.

**Comment by shiftkey** [comment]
> @shiftkey that's not exactly correct.

@Haacked this issue was so long ago that I suspect you're right (I probably didn't make it clear).

:thumbsup: to the work in #916
