### ISSUE TITLE
Obsolete AssertEx.Throws test helper 

### ISSUE THREAD

**Issue by shiftkey** [octokit/octokit.net#782]
This was written before the support for testing asynchronous tasks was added in xUnit 2.0 (because we pre-dated it).

Here's a rough task list:

 - mark `AssertEx.Throws` as obsolete
 - :eyes: and :fire: all usages - they should be `Assert.ThrowsAsync` now, and it'll drop the need for an inner `async/await` block.
 - :fire: the `AssertEx.Throws` helper
 - dance party

**Comment by M-Zuber** [comment]
Shouldn't `Assert.TaskThrows` be `Assert.ThrowsAsync`?

**Comment by shiftkey** [comment]
@M-Zuber yuuup, I typed it up in a rush. I'll update it.

**Comment by M-Zuber** [comment]
I am having some issues with getting this to work. Should I open a PR to discuss or have it here?

**Comment by shiftkey** [comment]
Fixed in #799
