### ISSUE TITLE
Getting zipball with Octokit is returning me null or invalid zip file

### ISSUE THREAD

**Issue by NikolayIT** [octokit/octokit.net#784]
I have the following code:

    // ... client = new Client(...);
    // some authentication logic...
    // some other queries to GitHub that work correctly
    var url = "https://api.github.com/repos/SomeOrg/SomePrivateRepo/zipball";
    var response = await this.client.Connection.Get<byte[]>(new Uri(url),
                                                            new Dictionary<string, string>(),
                                                            null);
    var data = response.Body;
    var responseData = response.HttpResponse.Body;

Three problems:

1. `data` is `null`
2. `responseData` is of type `string`
3. when I try `Encoding.ASCII.GetBytes(response.HttpResponse.Body.ToString());` I get invalid zip file

![untitled](https://cloud.githubusercontent.com/assets/3106986/7248361/cb813c2e-e81a-11e4-854e-6cf47d55d995.png)

Am I doing something wrong or is it a bug?

**Comment by shiftkey** [comment]
Fixed in #792
