### ISSUE TITLE
Colors

### ISSUE THREAD

**Issue by M-Zuber** [octokit/octokit.net#790]
I know that the official api returns colors without the leading `#` but what do you think about adding it in? In most use cases in `C#` it is useful to necessary to have it

**Comment by shiftkey** [comment]
I'm indifferent on this as it's not something I use day-to-day. But if there's sufficient interest in this use case I would be happy to review a contribution about it....

**Comment by M-Zuber** [comment]
I've been thinking about this some more and am starting to lean towards just providing a warning in the doc - comments. 
But I will leave this open in case a discussion develops

**Comment by shiftkey** [comment]
@M-Zuber :thumbsup: to clarifying the docs as a good first step

**Comment by M-Zuber** [comment]
is [this](https://github.com/octokit/octokit.net/blob/master/docs/labels.md) the correct spot to put it in?

**Comment by SeanKilleen** [comment]
I took a quick stab at this in #1530.
