### ISSUE TITLE
Issue and IssueComment don't feel related to each other

### ISSUE THREAD

**Issue by M-Zuber** [octokit/octokit.net#791]
While I understand that the main object fits in with the body of the `api` response, it would be nice to be able to get a list of issues -with their corresponding comments without jumping through hoops.
As an example is some code I wrote to try and do this:
```c#
public async Task<IReadOnlyList<IssueWithComments>> GetAllForCurrent()
{
  var issues = await base.GetAllForCurrent();          
  List<IssueWithComments> all = new List<IssueWithComments>();
  var groupedIssues = issues.GroupBy(i => i.Url);
  foreach (var group in groupedIssues)
  {
    var owner = group.Key.Segments[2];
    var repo = group.Key.Segments[3];
    foreach (var i in group)
    {
      all.Add(new IssueWithComments { Issue = i, Comments = await base.Comment.GetAllForIssue(owner, repo, i.Number) });
     }
   }
   return all.AsReadOnly();
}
```
It feels like in order to navigate based on issues I will have to write wrappers for almost the whole library (or some really fancy code loops).

**Comment by M-Zuber** [comment]
Crazy idea, but maybe make the model classes partial which then lets people make extensions (or ship an official opt-in extensions library) to the models and clients accordingly.
Any thoughts?

**Comment by Haacked** [comment]
> Crazy idea, but maybe make the model classes partial which then lets people make extensions (or ship an official opt-in extensions library) to the models and clients accordingly.
Any thoughts?

Partial classes are a compilation hack. They have no meaning once the binary has been produced. In other words, you can only extend a partial class with your partial class if you're compiled to the same assembly.

**Comment by M-Zuber** [comment]
forgot that..., can we hide this under a rock so no one ever finds it? :scream: 
**Is there** a solution that exists for extending the models in a simple way?

The goal I have in my head is that a consumer that wants to stick to the _official_ `API` they can, but they can also access objects that are a little easier to navigate through.

**Comment by Haacked** [comment]
Well the root problem is that our API doesn't support this. You'll have to email support@github.com for that. So your code has to create a request per issue and that's going to be slow. It might be possible to do this with our search endpoint, but I haven't tried that out.

If you don't mind the N+1 problem, I think the approach you took is fine. We want to keep Octokit.net closely aligned with the API. If there's a strong demand for it, we could consider an Octokit.Extensions package with these meta types, but this is the first we've heard of it.

**Comment by M-Zuber** [comment]
Understood.  Thanks for listening.  Only the future can tell what will become of this.
