### ISSUE TITLE
Not Found when creating issue in org repository

### ISSUE THREAD

**Issue by dennisan** [octokit/octokit.net#801]
I'm using Octokiet nuget package version 0.11.0

When I try to create an new issue in a repo like "mspnp/textrepo" I get a NotFoundException.

```
var newIssue = new NewIssue(guidance);
if (description.Length > 0) newIssue.Body = description;
if (owner.Length > 0) newIssue.Assignee = owner;
if (category.Length > 0) newIssue.Labels.Add(category);
var issue = await issuesClient.Create("dennisan", "mspnp/roadmaptest", newIssue);
```

throws a NotFoundException.

I can create the issue successfully if i use a repo such as "myrepo" but when I try using an org repo I get the exception.  I'm using basic username/password authentication.   I do have access to the repo and I am able to see the repo when I call Client.Repository.GetAllForOrg("mspnp")

**Comment by shiftkey** [comment]
@dennisan the first parameter to `Create` should be owner of the repository, not your account:

```
var issue = await issuesClient.Create("mspnp", "roadmaptest", newIssue);
```

That should get you back to a happy place.

As a sanity check, do you think we should warn the user if they try and specify more than just the repo name in that second parameter?

**Comment by dennisan** [comment]
yes, I would recommend a warning if the repo name contains delimiters such as / or \.   It looks like native GIT api takes "owner/repo" from what I read so that was throwing me off.  Also, I suggest that the exception message mentions that its the named repo that could not be found.

**Comment by dennisan** [comment]
Thanks for the quick reply also
