### ISSUE TITLE
 FollowersClientTests.ReturnsUsersTheUserIsFollowing setup seems to be faulty

### ISSUE THREAD

**Issue by M-Zuber** [octokit/octokit.net#803]
```c#
public async Task ReturnsUsersTheUserIsFollowing()
{
    var following = await _github.User.Followers.GetAllFollowing("alfhenrik");
    
    Assert.NotNull(following);
    Assert.NotEmpty(following);
}
```
I still have a lot to learn about the code base but it seems that there needs to be code that sets up the test user as a follower of `"alfhenrik"`?

**Comment by shiftkey** [comment]
I think this test is more to see if `alfhenrik` is following anyone. It shouldn't depend on the user account running the tests. Do you agree @alfhenrik?

**Comment by alfhenrik** [comment]
Yes, the test is to return all the users a specific user (`alfhenrik` in this case) is following.

I must admit though that it is a bit confusing due to the namings here..perhaps it should be `GetAllFollowers` instead of `GetAllFollowing`...

**Comment by alfhenrik** [comment]
And I may have actually broken the test as I cleared all users I was following..._oops_

**Comment by M-Zuber** [comment]
Closed as @alfhenrik is now following an account
