### ISSUE TITLE
Rate Information

### ISSUE THREAD

**Issue by cdaapi** [octokit/octokit.net#811]
Is it possible to access the rate information via the .NET library as per https://developer.github.com/v3/rate_limit/

**Comment by shiftkey** [comment]
Not currently, but it's been raised previously: #504

**Comment by Red-Folder** [comment]
Is this not different to #504?  #504 asked to get the rate limits per API call (included in the headers)

This request asked for the rate limits as part of the MiscellaneousClient - a discrete API request.

I'm currently having a play at both.  Hopefully produce a PR for the MiscellaneousClient some point next week.

**Comment by shiftkey** [comment]
@Red-Folder you're right. I was thinking about it from the "i need this info" side rather than the fact you can get it in either place.

> I'm currently having a play at both. Hopefully produce a PR for the MiscellaneousClient some point next week.

I think this is going to be easier to knock out than the details in #504, but I suspect we'll need both eventually. Thanks for looking into it!

**Comment by Red-Folder** [comment]
Functionality added in commit #848 

Believe this can now be closed
