### ISSUE TITLE
GitHubClient.Repository.Create left hanging

### ISSUE THREAD

**Issue by Nodios** [octokit/octokit.net#813]
Hello,

I'm using octokit to create a new repository. When GitHubClient.Repository.Create is called, method is waiting, no exception is thrown and execution lasts forever, and no repository is created.

This is my code

            string name = "testRepo";
            NewRepository newRepo = new NewRepository(name);
            newRepo.AutoInit = true;

            var accessToken = Session["OAuthToken"] as string;
            if (accessToken != null)
            {
                client.Credentials = new Credentials(accessToken);
            }

            try
            {
                var kita = client.Repository.Create(newRepo);
            }
            catch
            {
             //catch exception
            }

the same client is used to fetch list of repositories, and this works perfectly, however this example doesn't. Could you please help me? Tnx

**Comment by M-Zuber** [comment]
You need to `await` the call to `Create` as it is `Task` based.

**Comment by shiftkey** [comment]
Alternatively, you can block on the result (but this makes me sad whenever I have to write this code) so `await` is definitely The Recommended Way™:

```
var kita = client.Repository.Create(newRepo).Result;
```
