### ISSUE TITLE
StatisticsClient isn't Enterprise-friendly

### ISSUE THREAD

**Issue by shiftkey** [octokit/octokit.net#822]
The URLs created internally need to respect Enterprise environments, and the `/api/v3/` prefix seems to be skipped based on some testing...

**Comment by smathilakath** [comment]
I am interested.

**Comment by shiftkey** [comment]
So I think this is a rather straight-forward fix for someone who wants to grab it cc @smathilakath

Inside `StatisticsClient` we define the URLs with a leading `/`

https://github.com/octokit/octokit.net/blob/master/Octokit/Clients/StatisticsClient.cs#L46

```
var endpoint = "/repos/{0}/{1}/stats/contributors".FormatUri(owner, repositoryName);
```

This means the `HttpClient` ignores the `/api/v3/` prefix when interacting with an Enterprise server, generating a 404...

**Comment by khellang** [comment]
@shiftkey Why do you define the endpoints inline and not in `ApiUrls`? Going away from it?

**Comment by shiftkey** [comment]
@khellang I think it was just an unintentional oversight at the time.
