### ISSUE TITLE
WebHook - Decode Security SHA1 token

### ISSUE THREAD

**Issue by warrenbuckley** [octokit/octokit.net#826]
Hello,
I was wondering if there is any helper method I can use in the library to help decode the SHA1 token that is sent as a HTTP header on the WebHook POST of the JSON payload data to my WebAPI controller please?

If not does anyone have any sample code at all for this please?

**Comment by warrenbuckley** [comment]
Closing this, but if anyone searched for this & needs to know here is some sample code thanks to Chris Klug blog post - http://chris.59north.com/post/Integrating-with-Github-Webhooks-using-OWIN

```csharp
/// <summary>
/// http://chris.59north.com/post/Integrating-with-Github-Webhooks-using-OWIN
/// </summary>
/// <param name="body"></param>
/// <param name="signature"></param>sB
/// <returns></returns>
private bool IsValidToken(string payloadToken, HttpRequestMessage request)
{
    //Get token stored on enviroment
    var serverToken = Environment.GetEnvironmentVariable("githubToken");
    //var serverToken = "superSecretFOO";

    //Need to get the actual content of the request - JSON payload
    //As this payload is signed/encoded with our key
    var jsonPayload = request.Content.ReadAsStringAsync().Result;

    //Verify the payloadToken starts with sha1
    var vals = payloadToken.Split('=');
    if (vals[0] != "sha1")
    {
        return false;
    }
                

    var encoding = new System.Text.ASCIIEncoding();
    var keyByte = encoding.GetBytes(serverToken);

    var hmacsha1 = new HMACSHA1(keyByte);

    var messageBytes = encoding.GetBytes(jsonPayload);
    var hashmessage = hmacsha1.ComputeHash(messageBytes);
    var hash = hashmessage.Aggregate("", (current, t) => current + t.ToString("X2"));

    return hash.Equals(vals[1], StringComparison.OrdinalIgnoreCase);
}
```

**Comment by GMouron** [comment]
In case someone comes here (like I did) and is not, let's say, American :)
The code is actually incorrect.
You should use the UTF-8 encoding and nt the Ascii Encoding.
So the line `var encoding = new System.Text.ASCIIEncoding();` should be `var encoding = new System.Text.UTF8Encoding();`
At first, it worked fine for me but then it started to "randomly" fail, the reason was I had accented characters in the content of the payload.
