### ISSUE TITLE
Should we make all Observables cold?

### ISSUE THREAD

**Issue by haacked** [octokit/octokit.net#83]
Recall, a `cold observable` is:

> a stream that is passive and starts publishing on request.

And a `hot observable` is:

> a stream that is active and publishes regardless of subscriptions.

A great example of this is connecting to a mouse event stream. It wouldn't really make sense to make that cold.

I'm starting to come to the conclusion that for APIs where any method is kicking off an observable (as opposed to connecting to a hot observable), it should be cold.

For example, today, when you call a method to make an HTTP request, it's actually a `warm observable`. It's `hot` in the sense that the request occurs whether or not you `Subscribe`. But it's `cold` in that the result of the request is published when you subscribe. That makes sense because the `Subscribe` call could happen after the request completes and you wouldn't want to miss it.

However, having three types of observable makes this shit hard to reason about. Also, certain methods like `Retry` don't work with warm observables but could work with cold ones.

So the proposal is that we don't make an API request until a `Subscribe` call happens. What do you think?

/cc @paulcbetts @jspahrsummers

**Comment by shiftkey** [comment]
This issue has sat inactive for a long while, and given I'm currently seeing the downloads for Octokit.Reactive are 2% of the downloads for the main Octokit library for the most recent release I'm going to close this out. There's plenty of other things I need to invest my time in currently.
