### ISSUE TITLE
Unable to Open Solution in VS2015

### ISSUE THREAD

**Issue by whoisj** [octokit/octokit.net#830]
When I attempt to open the solution, in VS2015, I'm greeted with the following error message, in the Output window: 
> C:\Src\octokit.net\Octokit\Octokit-NetCore45.csproj : error  : This project requires a Visual Studio update to load. Right-click on the project and choose "Download Update".

Right-clicking on the project gives me a few options, but none of them are "Download Update".

All of the projects seem to load except for Octokit-NetCore45.

![image](https://cloud.githubusercontent.com/assets/11578325/8488486/c48db11e-20c7-11e5-8f40-a6ffc54fe5ca.png)

Builds of course fail with:

> 1>------ Build started: Project: Octokit.Tests-NetCore45, Configuration: Debug Any CPU ------
> 1>CSC : error CS0006: Metadata file 'C:\Src\octokit.net\Octokit\bin\Debug\NetCore45\Octokit.dll' could not be found
> ========== Build: 0 succeeded, 1 failed, 9 up-to-date, 0 skipped ==========

/CC @shiftkey

**Comment by shiftkey** [comment]
Oh cool, the Win8 project. You're running Windows 10?

**Comment by whoisj** [comment]
Windows 8.1 + patches

**Comment by shiftkey** [comment]
Oh, interesting. I'm not sure what the story is with Windows Store Apps + VS2015 but that gives me enough to reproduce it at least.

**Comment by whoisj** [comment]
> Oh, interesting. I'm not sure what the story is with Windows Store Apps + VS2015 but that gives me enough to reproduce it at least.

Is that the issue? I likely mucked something up installing, uninstalling, reinstalling, edit, reinstalling, etc... various Windows Kits and versions of Visual Studio.

Very unfortunate, but not something I can easily recover from. Luckily it sounds like it is mostly my problem... is that correct?

**Comment by shiftkey** [comment]
> I likely mucked something up installing, uninstalling, reinstalling, edit, reinstalling, etc... various Windows Kits and versions of Visual Studio.

Possibly. But this is something I can verify without too much hassle.

My only concern is that the IDE doesn't let you download the bits you need...

**Comment by whoisj** [comment]
Do you have a URL for the "bits [I] need"? If so, I could try to grab them... some how.

**Comment by shiftkey** [comment]
Just tested this out on my version of VS2015RC, and I get this error too:

> C:\Users\shifkey\Documents\GitHub\octokit.net\Octokit\Octokit-NetCore45.csproj : error  : The imported project "C:\Program Files (x86)\MSBuild\Microsoft\WindowsXaml\v12.0\Microsoft.Windows.UI.Xaml.CSharp.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  C:\Users\shifkey\Documents\GitHub\octokit.net\Octokit\Octokit-NetCore45.csproj

I this [this section](https://msdn.microsoft.com/en-us/library/windows/apps/dn263114.aspx#step5) where you enable the "Tools for Maintaining Store apps for Windows 8" bits is the way out of this - testing to confirm it...

**Comment by shiftkey** [comment]
Nope, that didn't change anything. I'll leave this open until [July 20](http://blogs.windows.com/buildingapps/2015/06/29/release-dates-and-compatibility-visual-studio-2015-and-windows-10-sdk/) and revisit it then.

**Comment by whoisj** [comment]
@shiftkey any luck? :smirk:

**Comment by shiftkey** [comment]
@whoisj I had to fix some CI issues with MSBuild v14 - see #846 - however transitioning to VS2015 completely is something I'm still mulling over - it likely means I can't support VS2013 due to MSBuild migrations for the Store Apps projects, so I need to do it carefully.

Hang tight.

**Comment by whoisj** [comment]
Hanging. :-) In the meantime, do you have any time to assist/advise on a separate but related project?

**Comment by shiftkey** [comment]
Asynchronously, perhaps.

Not sure how much time I can dedicate directly, but happy to give feedback on stuff.

**Comment by shiftkey** [comment]
We did this in #956
