### ISSUE TITLE
Support for DNX platform

### ISSUE THREAD

**Issue by shiftkey** [octokit/octokit.net#832]
I've some code lying around thanks to @glennc which helps target this new platform (and simplifies a bunch of cross-platform headaches). With #830 indicating that VS2015 requires re-targeting MSBuild to v14.0 and VS2015 close to shipping, I think we should look at simplifying things.

I also have a side-project which would love to use Octokit - but can't in it's current form...

**Comment by Eilon** [comment]
@shiftkey I'm using Octokit in a DNX app on .NET Framework 4.5 just fine. Are you trying to use it on .NET Core (dnxcore)?

**Comment by Haacked** [comment]
> Are you trying to use it on .NET Core (dnxcore)?

I haven't tried this yet, but we'd like to make sure it works on this platform. Any tips?

**Comment by alfhenrik** [comment]
I've just tried to get my little vNext app running on dnxcore50 (on OSX) and there's a couple of kinks with the HttpClient support on *nix systems at the moment [dotnet/corefx#2155](https://github.com/dotnet/corefx/issues/2155), now I haven't tried it on a Windows machine so can't say if it'll work or not there, but it seems that it should...might have some time next week to test it out if no one else beats me to it.

**Comment by Eilon** [comment]
Yeah I'm using `dnx451` only right now. For `dnxcore50` it's a matter of compiling against that target framework and making all the tests run. We're (Microsoft) working on that guidance right now, but there are a few bits and pieces that aren't quite in place to make it a super smooth story across the board.

**Comment by naveensrinivasan** [comment]
With the latest release of beta8 I was able to get the Octokit working on the `dnxcore50`.

I had to make changes to the nuspec to include the `System.Net.Http` instead of `Microsoft.Net.Http` for coreclr because coreclr does not have `Microsoft.Net.Http`. Here are the changes https://github.com/octokit/octokit.net/commit/0f23ff9f4a12990453ad72836885030a98dd81c3.

And here is sample of Octokit that is working on the coreclr.

https://github.com/naveensrinivasan/OctokitCoreClrSample

The sample also has the beta nuget package which could be used directly to test it.

**Comment by shiftkey** [comment]
@naveensrinivasan :sparkles::sparkles::sparkles::sparkles::sparkles: thanks for looking into this and getting it working.

**Comment by naveensrinivasan** [comment]
When are planning to support dnxcore? Could we have a beta branch?

**Comment by shiftkey** [comment]
@naveensrinivasan there's some VS2015 changes I need to handle (obsoleting Win8.0 support in particular) - I'd like to tackle this after I've got that in place and addressed some of the outstanding build/deployment issues.

**Comment by naveensrinivasan** [comment]
Thanks! Is there a VS2015 branch that I could clone?

**Comment by shiftkey** [comment]
@naveensrinivasan the VS2015 support is here https://github.com/octokit/octokit.net/pull/956 going to let it sit for a couple of days before closing. I might have a chance to play around with DNX support in the meantime, but feel free to target that branch if you've got stuff to share!

**Comment by naveensrinivasan** [comment]
@shiftkey Cool! will do that. Thanks!

**Comment by naveensrinivasan** [comment]
@shiftkey  When are planning to move to C# 6.0?

**Comment by shiftkey** [comment]
@naveensrinivasan it's not something I'm looking into - I'd like to ensure that contributors are happy with the VS2015 migration before I look at new language features...

**Comment by shiftkey** [comment]
Let's put the C# 6 discussions aside for now, but I'm keen to see us get DNX builds out now we're on VS2015. If someone is keen (or more familiar) with porting existing projects to the new platform I'm happy to jam with them on this.

You can see my previous attempt in #960 - it's close, but PCL support continues to torment me (as well as CI).

**Comment by khellang** [comment]
I can take a stab at this. Been porting quite a few projects lately. I probably won't have time until the new year arrives, though.

**Comment by khellang** [comment]
> but PCL support continues to torment me

What does this mean? Do you still want to target a PCL profile?

**Comment by shiftkey** [comment]
@khellang as part of this change I wanted to replace the existing csproj files that Octokit is currently building (it's nice that MSBuild now tells me via errors).

However the one that I can never get right is `Profile259`. I've had various other people show me how they got it to work for their projects but it's never really mapped to how we've configured things with Octokit - I'm probably missing something, and would love to be shown how easy it actually is.

**Comment by khellang** [comment]
> However the one that I can never get right is Profile259.

What do you mean by "get right"?

I think we should just ditch

 - Octokit-Mono.csproj	
 - Octokit-MonoAndroid.csproj
 - Octokit-Monotouch.csproj
 - Octokit-Portable.csproj
 - Octokit-netcore45.csproj
 - Octokit.csproj

And aim for a single project.json with `dotnet5.1`, which is roughly the same as Profile259 (it has the same targets). That should also be Future-Proof™, until `netstandard1.0` takes over.

**Comment by khellang** [comment]
Like this; https://github.com/khellang/serilog/commit/15eaf8c9b97617d8a840d88d0c6db10146064849

**Comment by naveensrinivasan** [comment]
>And aim for a single project.json with dotnet5.1, which is roughly the same as Profile259 (it has the > same targets). That should also be Future-Proof™, until netstandard1.0 takes over.

:+1:

**Comment by shiftkey** [comment]
> What do you mean by "get right"?

Basically, I'd love a framework inside `project.json` for `".NETPortable,Version=v4.5,Profile=Profile259"` to Just Work. 

> I think we should just ditch ...

Fair, but one of the reasons I was bashing my head against having all the currently supported platforms inside a `project.json` file is that it'll then generate the correct NuGet package - and I'd like to drop the hand-crafted work that we do there.

I've also not thought about how transitioning to `project.json` impacts the MonoDevelop/Xamarin Studio side - @naveensrinivasan anything we should be keep in mind?

> And aim for a single project.json with dotnet5.1, which is roughly the same as `Profile259` (it has the same targets). 

This seems fine. I just want to ensure we continue to support our existing platforms alongside the new `dotnet/netstandard` stuff...

**Comment by shiftkey** [comment]
Closing this out in favour of #1115
