### ISSUE TITLE
OauthTokenRequest constructor that takes in parameters as SecureStrings

### ISSUE THREAD

**Issue by SplitInfinity** [octokit/octokit.net#833]
Can an OauthTokenRequest constructor be added that takes all parameters as SecureStrings (System.Security.SecureString) instead of just normal strings?

**Comment by shiftkey** [comment]
That seems reasonable. I'm not sure if it's available in the PCL target we've chosen, but we can find that out easily enough.

Thoughts @Haacked?

**Comment by Haacked** [comment]
:+1: to the idea.

**Comment by Haacked** [comment]
> Can an OauthTokenRequest constructor be added that takes all parameters as SecureStrings (System.Security.SecureString) instead of just normal strings?

Hmm, as I think about it more, help me understand why you'd want this? After all, the information in the token request is going to be sent as part of the HTTP request. So if you're trying to hide it from the caller, they can just use Fiddler to see the information.

**Comment by willsb** [comment]
May I? Should I?

**Comment by Haacked** [comment]
I feel like this provides a false sense of security. Convince me otherwise. :smile:

**Comment by willsb** [comment]
I just wanted something to work on while I travel :disappointed:

**Comment by khellang** [comment]
Also, `SecureString` is being removed/internalized with .NET Core. https://github.com/dotnet/apireviews/tree/master/2015-07-14-securestring
