### ISSUE TITLE
search across multiple repositories

### ISSUE THREAD

**Issue by shiftkey** [octokit/octokit.net#834]
it's currently impossible to do something like this:

> https://api.github.com/search/issues?q=repo:aspnet/dnx+repo:aspnet/logging+type:pr+state:open&sort=created&order=desc&per_page=100

with Octokit. The syntax is valid, but we constrain things currently to one repository.

cc @damianedwards

**Comment by shiftkey** [comment]
An even better example: https://api.github.com/search/issues?q=repo:aspnet/dnx+repo:aspnet/dnvm+repo:aspnet/Hosting+repo:aspnet/DependencyInjection+repo:aspnet/HttpAbstractions+repo:aspnet/KestrelHttpServer+repo:aspnet/WebListner+repo:aspnet/Helios+repo:aspnet/Logging+repo:aspnet/Configuration+repo:aspnet/Options+repo:aspnet/BasicMiddleware+repo:aspnet/CORS+repo:aspnet/WebSockets+repo:aspnet/Localization+repo:aspnet/ResponseCaching+repo:aspnet/Session+repo:aspnet/FileSystem+repo:aspnet/DataProtection+repo:aspnet/Caching+repo:aspnet/HttpClient+repo:aspnet/UserSecrets+repo:aspnet/homebrew-dnx+repo:aspnet/benchmarks+type:pr+state:open&sort=created&order=desc&per_page=100

**Comment by M-Zuber** [comment]
:thumbs-up: to this.  I need it for a project I am building, and was planning to either call the api myself or loop the requests
