### ISSUE TITLE
ASP.NET Web Forms

### ISSUE THREAD

**Issue by williamhodges** [octokit/octokit.net#837]
I've  been searching and searching but I can't find out how to use this package to implement into an ASP.NET web form. Am I missing something? I'm trying to figure out where some tutorials are. I'm teaching my self this with no formal coding education. Any help, much appreciated.

**Comment by shiftkey** [comment]
@wdhodges to be honest, WebForms isn't something I've used for many years - so it's not something I've had in mind. If you're using .NET 4.5 it should all just work, and [here's](https://github.com/octokit/octokit.net/blob/master/docs/getting-started.md) a good intro for testing that it all works. 

The rest of the docs are here

https://github.com/octokit/octokit.net/tree/master/docs

but if there's specific things you're interested in that aren't documented, let me know and I can add those to my backlog...

**Comment by Eilon** [comment]
@wdhodges what exactly are you looking for? Ultimately Octokit is mostly a bunch of async API calls - you could bind the results to a GridView or whatever you want.
