### ISSUE TITLE
DocPlagiarizer not working on VS2015

### ISSUE THREAD

**Issue by shiftkey** [octokit/octokit.net#849]
This occurs during a build step, but I'm not seeing it work in VS2015.

**Comment by naveensrinivasan** [comment]
DocPlagiarizer has a bug on mono also which make's hard to compile on non-windows platform.  The repo hasn't been updated since Feb 2014 https://github.com/pmacn/DocPlagiarizer. Do we fork this and fix it or do you want to move away form this?

**Comment by shiftkey** [comment]
Yeah, I'm not surprised it's largely unchanged from then. Given it's value is in extracting docs from interfaces, we could switch it off to help support the x-plat experience.

Given it was built ontop of earlier builds of Roslyn, I'd like to see if we can port it over to the now-RTM analyzers that are in the box. I've not had a look at how this would work outside of VS2015, so any knowledge or war stories would be great to help us decide the transition.

**Comment by shiftkey** [comment]
We're tracking #971 to bring this functionality back, so I'm closing this out as #995 removed this.
