### ISSUE TITLE
Downloading ReleaseAsset zip File - NullReferenceException

### ISSUE THREAD

**Issue by kdolan** [octokit/octokit.net#854]
I am trying to download a zip file that is an asset in a release. 

```c#
var request = client.Release.GetAll("username", "repo");
var releases = await request;
var latest = releases[0];
var assets = await client.Release.GetAllAssets("username", "repo", latest.Id);
var myAsset_zipFile = assets[0];

var resp= await client.Connection.Get<byte[]>(new Uri(myAsset_zipFile.Url),
          new Dictionary<string, string>(),
          null); //NullReference Here

var data = resp.Body;
var responseData = resp.HttpResponse.Body;
System.IO.File.WriteAllBytes("myZip.zip", (byte[])responseData);
```

I am getting a NullReferenceException in SimpleJson.cs in the DeserializeObject function at the line that reads obj = ConstructorCache\[type\](); when I call client.Connection.Get.

If I have trying to get this to work without success for some time and have tried several different methods. 

It is worth mentioning that I am trying to download from a private repo.

Potentially Related #792

**Comment by shiftkey** [comment]
There's definitely something unclear about this API - you can see a test I've written to download an asset here:

https://github.com/octokit/octokit.net/blob/master/Octokit.Tests.Integration/Clients/ReleasesClientTests.cs#L186-L206

In this case, I've done the download slightly different:

```
var response = await client.Connection.Get<object>(new Uri(asset.Url), new Dictionary<string, string>(), "application/octet-stream");
```

I think something weird is happening with the deserialization if you don't specify the appropriate `Accepts` header (probably defaulting to JSON, which would explain something `null`-ing out.

**Comment by kdolan** [comment]
Unsupported "application/octet-stream"

{Octokit.ApiException: Unsupported 'Accept' header: ["application/octet-stream"]. Must accept 'application/json'.
   at Octokit.Connection.HandleErrors(IResponse response) in octokit.net\Octokit\Http\Connection.cs:line 550}

**Comment by shiftkey** [comment]
@kdolan well that's not great!

Is this a repository I can test out (even privately?) - perhaps there's some edge case here I haven't seen before while working on this area...

**Comment by kdolan** [comment]
I just made a public repo for what I am trying to do. Basically an auto updater that downloads a zip file and then extracts it. In the repo I used the Nuget package but I've also used the project source with the same result.

https://github.com/kdolan/AutoUpdater

**Comment by shiftkey** [comment]
@kdolan thanks, I'll check it out

**Comment by kdolan** [comment]
@shiftkey After some more trouble shooting this appears to be an issue with the API/request. The error above is from the API not from this codebase. I verified this using postman. It would appear then that maybe the BrowserDownloadUrl is what needs to be used, however, whenever I try to download the file using postman I get a 404 (because it is a private repo) and token authentication does not appear to work for the browser download URL.

![cap1](https://cloud.githubusercontent.com/assets/2603056/9087483/f8b530f6-3b58-11e5-955d-bb116f3bca07.png)
![cap2](https://cloud.githubusercontent.com/assets/2603056/9087484/f8b6c786-3b58-11e5-8ebc-77f1d1831932.png)

**Comment by shiftkey** [comment]
I'm pretty sure that `/:user/:repo/releases/:id` needs to be called with `Accept: application/json` as this is returning the payload of release assets:

https://developer.github.com/v3/repos/releases/#get-a-single-release

> It would appear then that maybe the BrowserDownloadUrl is what needs to be used

Correct

> however, whenever I try to download the file using postman I get a 404 (because it is a private repo) and token authentication does not appear to work for the browser download URL.

Okay, this definitely sounds interesting. Do you see the `Authorization` header being set when you use the `BrowserDownloadUrl` value?

**Comment by kdolan** [comment]
```c#
var request = client.Release.GetAll("kdolan", "AutoUpdater");
var releases = await request;
var latest = releases[0];
var latestAsset = await client.Release.GetAllAssets("kdolan", "AutoUpdater", latest.Id);
            
//Download Release.zip here
var response = await client.Connection.Get<object>(new Uri(latestAsset[0].Url), new Dictionary<string, string>(), "application/octet-stream");

byte[] bytes = Encoding.ASCII.GetBytes(response.HttpResponse.Body.ToString()); ;
File.WriteAllBytes("Release.zip", bytes);
```

This code is working for me; I was targeting the wrong API Endpoint. However, the actual writing of the zip file to disk does not seem to always work. The release for AutoUpdater just has a small text file in it and this code works fine, however, when I try other repos with larger Release Zips then the Zip file written is corrupt/incomplete.

**Comment by naveensrinivasan** [comment]
I figure out the reason for this It is because  `content-type` is `application/octet-stream` on the response and the code does not handle that.  It handles `image`,`zip`,`x-gzip`. 

https://github.com/octokit/octokit.net/blob/1266ac0f3a366f033061d0c1cc0785bc3c9f5bd3/Octokit/Http/HttpClientAdapter.cs#L80

Because it is binary type and we read as string in the `else` block that is what is causing the corruption. And that is why it does not fail for text files.

I tried including that and it works. I am able to download the release and the file isn't corrupted.

@shiftkey  let me know if you want me to do PR on this?

**Comment by shiftkey** [comment]
@naveensrinivasan 

> let me know if you want me to do PR on this?

That'd be great!

**Comment by naveensrinivasan** [comment]
:+1:
