### ISSUE TITLE
Consider making RepositoryContent.EncodedContent public

### ISSUE THREAD

**Issue by yufeih** [octokit/octokit.net#861]
Please consider making `RepositoryContent.EncodedContent` public or provide an alternative to get the raw bytes of a file, this is useful when working with binary files.

**Comment by naveensrinivasan** [comment]
I guess this could be security reason so that you don't extract a malware.

https://github.com/octokit/octokit.net/blob/e6e7c3d393160fabe4cc48dd6c410db2a19b7e72/Octokit/Models/Response/RepositoryContent.cs#L34-48

@Haacked

**Comment by Haacked** [comment]
I'm ok with either making it public or maybe adding a method to read it as a binary stream/array.

**Comment by yufeih** [comment]
Thanks, you guys rocks.
