### ISSUE TITLE
Reading an assets raw file?

### ISSUE THREAD

**Issue by RandomlyKnighted** [octokit/octokit.net#863]
In each release that I make for one of my projects I add the release notes as an asset. I noticed in the API that there is a download link for each asset. However, while I could use that if necessary I'd like to be able to read the raw file so that I can display the information on the project website. Is there a way to that I can do this with Octokit?

**Comment by Haacked** [comment]
>  I noticed in the API that there is a download link for each asset. However, while I could use that if necessary I'd like to be able to read the raw file so that I can display the information on the project website.

On `IGitHubClient` there's a `Connection` property. You can use that for making arbitrary requests. If the content is HTML, you can call `GetHtml`. If the content is binary, you might want to use `System.Net.HttpClient` directly as Octokit isn't designed for requesting arbitrary binary files.

**Comment by RandomlyKnighted** [comment]
I used the GetHtml method to pull the HTMl file from GitHub like so.

```csharp
private async Task<string> DownloadReleaseNotes()
        {
            var request = client.Release.GetAll("ligershark", "side-waffle");


            var releases = await request;
            var latestRelease = releases[0];

            var assets = await client.Release.GetAllAssets("ligershark", "side-waffle", latestRelease.Id);
            string assetURL = "";

            foreach (var asset in assets)
            {
                if (asset.Name.Equals("release-notes.html"))
                {
                    assetURL = asset.Url;
                }
            }

            var response = await client.Connection.GetHtml(new Uri(assetURL, UriKind.Absolute));
            
            return response.ToString();
        }
```

I then created a separate function in order to pull the string out of the Task.

```csharp
public string GetReleaseNotes()
        {
            return DownloadReleaseNotes().Result;
        }
```

However, when I loaded the string on to the webpage all that displayed was ```Octokit.Internal.ApiResponse`1[System.String];``` What am I missing? Am I forgetting to do something in order to get that HTML string?

**Comment by Haacked** [comment]
The default implementation of `ToString` for most objects is to return the type name. So what you're seeing is the type name of the response object which is [`ApiResponse<string>`](https://github.com/octokit/octokit.net/blob/master/Octokit/Http/ApiResponse.cs).

That type has a `Body` property. You need to look at that.

So in `DownloadReleaseNotes` change that last line with the `return` statement to return the body:

```csharp
return response.Body;
```

**Comment by RandomlyKnighted** [comment]
It's returning a json string for the file. I thought getHTML would return the HTML of the actual file uploaded?

**Comment by RandomlyKnighted** [comment]
@Haacked did I misunderstand the use of the getHTML method?

**Comment by shiftkey** [comment]
@RandomlyKnighted `GetHTML` is just a shortcut to set the `Accepts` headers when making a request. The server is free to ignore this or just give us something else, and that's what's happening here.

The problem is with this section:

```csharp
foreach (var asset in assets)
{
    if (asset.Name.Equals("release-notes.html"))
    {
        assetURL = asset.Url; // this line
    }
}
```

`asset.Url` points to the JSON payload for the file - here's an example from the docs https://developer.github.com/v3/repos/releases/#get-a-single-release-asset

If you want the contents of this file, you'll need to use the `asset.BrowserDownloadUrl` instead.

**Comment by RandomlyKnighted** [comment]
@shiftkey so just to be clear ```asset.BrowserDownloadUrl``` will get me the URL of the file itself so that i can download it and just read the file directly from the disk?

**Comment by shiftkey** [comment]
@RandomlyKnighted correct
