### ISSUE TITLE
use Issue.GetAllForRepository to find issues with labels

### ISSUE THREAD

**Issue by lucamorelli** [octokit/octokit.net#866]
I'm using Octokit.net to filter issues in a repository using the **Issue.GetAllForRepository(owner,name,request)**.  
In the request I set the property **Since** to set the time filter and the Property _Labels_ to filter for a set of labels: I would like to find all the issues that have at least one of these labels, but from the results I think that are selected only the issues have all these labels.
Is possible to configure the request so every issue that has at least one label is found? At the moment I have to do a single request for every label.

**Comment by shiftkey** [comment]
> I would like to find all the issues that have at least one of these labels, but from the results I think that are selected only the issues have all these labels.

Currently this is a limitation of how the upstream API works, so we're stuck at "find issues tagged with all labels" or "request per label".

I'm not sure how clever we should be on the client about this to hide away this limit, but I'm open to suggestions.

**Comment by lucamorelli** [comment]
I supposed was an API problem. I don't think is very necessary to implement this inside the library, the mail point is that in this scenario I have do multiple calls to the server, implement this at API level could be a way to optimize the calls.

**Comment by shiftkey** [comment]
@lucamorelli fair point. However it'd change the behaviour of the API, which existing consumers might be reliant upon.
