### ISSUE TITLE
Merged is always false in Pull Request list

### ISSUE THREAD

**Issue by lucamorelli** [octokit/octokit.net#867]
I'm reading the list of the Pull Request list of a repository looking for all the merge, but I noticed the property **Merged** is always false, although the pull request in the site is merged and also in the request object the property **MergedAt** is not null.
Another thing: How can I find the final commit generated at the end of the merge?

**Comment by shiftkey** [comment]
> I'm reading the list of the Pull Request list of a repository looking for all the merge, but I noticed the property **Merged** is always false, 

I think this is a serialization issue - there's no `merged` field sent by the server, so it should be marked as obsolete in favour of using `MergedAt`. See an earlier discussion on this (at least I think it's the right thing I was ranting about) https://github.com/octokit/octokit.net/issues/502

> Another thing: How can I find the final commit generated at the end of the merge?

The `MergeCommitSha` property should be set when the pull request has been merged, but a quick scan of the codebase indicates that it doesn't match the expected Git commit. 

@pengwynn I'm looking at https://github.com/octokit/octokit.net/pull/857 and I see a comment about https://github.com/octokit/octokit.net/commit/1776ca1086a861b81bd499aaf8a0dd9da76ca4ce being the merge commit.

<img width="749" alt="screen shot 2015-08-24 at 2 24 52 pm" src="https://cloud.githubusercontent.com/assets/359239/9433073/205e9670-4a6c-11e5-93f8-a669c5473e52.png">

However when I retrieve it from the API I get a different value: https://api.github.com/repos/octokit/octokit.net/pulls/587

`merge_commit_sha=e27e3c3c9fafe3b69b238b478981587837fd62f0` appears to be a server-side commit (possibly the merge after it was last pushed).

There's another issue which I'm poking into about how a different value appears when this PR is listed in `/pulls?state=closed` which I still need to dig into, but let me know if I'm missing something obvious...

**Comment by chenjiaming93** [comment]
See https://developer.github.com/v3/pulls/#get-a-single-pull-request
"The merge_commit_sha attribute holds the SHA of the test merge commit; however, this attribute is deprecated and is scheduled for removal in the next version of the API. The Boolean mergeable attribute will remain to indicate whether the pull request can be automatically merged."  
I think we need to set Merged to MergedAt.HasValue? or any other ideas?

**Comment by Haacked** [comment]
I commented on the PR.

**Comment by shiftkey** [comment]
The `MergedAt` change is now available in v0.18. I think we're good here.

I've got a side project which depends on whether a pull request is mergeable (rather than past-tense merged), so once I've updated that I'll come back to this to see if there's any extra work to do here.
