### ISSUE TITLE
How can I find the changed files in a commit?

### ISSUE THREAD

**Issue by lucamorelli** [octokit/octokit.net#869]
As in the subject, I'm looking for a way to detect which are the documents are changed in a commit. I tried expanding the tree, but I obtain I think all the files of the repository.
Looks like the library doesn't expose the files section

**Comment by shiftkey** [comment]
Looks like `CommitsClient.Get` should return the `files` element from the server, however the typed `Commit` response doesn't have the property.

**Comment by lucamorelli** [comment]
do you have any suggestion on how can I solve this problem?

**Comment by shiftkey** [comment]
@lucamorelli I think this new property needs to be added to `Commit` -  see https://github.com/octokit/octokit.net/pull/696 for a similar scenario

**Comment by lucamorelli** [comment]
thanks for the info, in the end I seen that comparing commit I can obtain the informations I need. May be nice to have this info directly in the commit, just to avoid another server call, but at the moment using compare is fine for me.

**Comment by shiftkey** [comment]
I'll leave this open as an opportunity for someone to add it in.

**Comment by alfhenrik** [comment]
I can take this one, ease my way back into Octokit again :laughing:

**Comment by alfhenrik** [comment]
OK, so it seems that the `CommitsClient.Get` function isn't returning any `Files` property in the response and according to the [API docs](https://developer.github.com/v3/git/commits/#get-a-commit) it isn't expected to be returned.

So, perhaps you're looking for the `RepositoryCommitsClient.Get` as this returns all files changed in a commit of the specified SHA, and this is also specified in the [API Docs](https://developer.github.com/v3/repos/commits/#get-a-single-commit).

**Comment by shiftkey** [comment]
This works for me on the latest Octokit release (v0.18):

```
[IntegrationTest]
public async Task CanGetFilesInCommit()
{
    var commit = await client.Repository.Commit.Get("octokit", "octokit.net", "65a22f4d2cff94a286ac3e96440c810c5509196f");
    Assert.NotEmpty(commit.Files);
}
```

Closing this out as I'm not sure what else we need to do here.

**Comment by dimitrisTim** [comment]
I am trying to use the client.Repository.Commit.Get method, to get every file that a commit has changed. But if the commits are too many (let's say more that 1000), this method of obtaining the info is very slow. Any thoughts?

**Comment by shiftkey** [comment]
@dimitrisTim can you please open a new issue with more information and/or a code sample of what you're trying to achieve? Thanks!
