### ISSUE TITLE
Doc comments on Issue.Url and Issue.HtmlUrl are wrong/missing

### ISSUE THREAD

**Issue by Eilon** [octokit/octokit.net#875]
This one is wrong (it says milestone instead of issue): https://github.com/octokit/octokit.net/blob/master/Octokit/Models/Response/Issue.cs#L34-L37

And this one is missing: https://github.com/octokit/octokit.net/blob/master/Octokit/Models/Response/Issue.cs#L39

**Comment by mikeparker** [comment]
If the related PR is merged can this issue be closed? @Eilon

**Comment by shiftkey** [comment]
:shipit:
