### ISSUE TITLE
Creating pull request throws "no commits between"..

### ISSUE THREAD

**Issue by mikeparker** [octokit/octokit.net#879]
I've been investigating this error for 3+ hours now and I can't see any bugs in my code. (famous last words! :))

                // Authenticate
            var gitHubClient = new GitHubClient(new ProductHeaderValue("mikeparker-testapp"));
            var authToken = new Credentials(personalAccessToken); // ask user to enter this from ui
            gitHubClient.Credentials = authToken;
 
            // Get current username
            var user = await gitHubClient.User.Current();
            var username = user.Login;
 
            // Make the Pull Request
            var newPR = new NewPullRequest("The PR title", username + ":prcreator-testing/branch-to-merge", "next");
            newPR.Body = "This is my PR body..";
            var pullRequest = await gitHubClient.Repository.PullRequest.Create("mikeparker", "prcreator-testing", newPR);

Throws an ApiValidationException:

"{\"message\":\"Validation Failed\",\"errors\":[{\"resource\":\"PullRequest\",\"code\":\"missing_field\",\"field\":\"head_sha\"},{\"resource\":\"PullRequest\",\"code\":\"missing_field\",\"field\":\"base_sha\"},{\"resource\":\"PullRequest\",\"code\":\"custom\",\"message\":\"No commits between next and prcreator-testing/branch-to-merge\"}],\"documentation_url\":\"https://developer.github.com/v3/pulls/#create-a-pull-request\"}"

This lists 3 errors, which I think is probably wrong, but interesting. At first I thought I was missing a parameter but i've checked and both branches are successfully getting through to Octokit.

You can see the branches on my public repo here
https://github.com/mikeparker/prcreator-testing/compare/next...branch-to-merge

I've stepped into Octokit.ApiConnection.Post and it looks OK to me: 

uri : "repos/mikeparker/prcreator-testing/pulls"
data: 
- Base: "next"
- Body: "This is my PR body.."
- Head: "mikeparker:prcreator-testing/branch-to-merge"
- Title: "The PR title"

I've even added commits to both branches and tried reversing the order. I've also tried using a head branch from a different repo.

**Comment by mikeparker** [comment]
Finally figured this out. You must not insert the repository name into the Head string... I've opened a separate issue to clarify the docs to prevent anyone else struggling for hours with the same thing.

**Comment by shiftkey** [comment]
> You must not insert the repository name into the Head string... I've opened a separate issue to clarify the docs to prevent anyone else struggling for hours with the same thing.

Correct. The only time you need to specify more than the branch name for the `Head` is when you're creating a pull request against another repository (fork -> upstream is the most common scenario).
