### ISSUE TITLE
Please clarify docs on head vs base ref in NewPullRequest

### ISSUE THREAD

**Issue by mikeparker** [octokit/octokit.net#880]
NewPullRequest:

```
/// <summary>
/// The branch (or git ref) you want your changes pulled into (required).
/// 
/// </summary>
public string Base { get; }
/// <summary>
/// The branch (or git ref) where your changes are implemented (required).
/// 
/// </summary>
public string Head { get; }
```

This should make it clear that Base and Head accept different formats of strings. It should also make it clear that this only accepts strings of the forms:

username:branch

and not

username:repo/branch

The GitHub API returns a most unhelpful error message if you get this wrong!

**Comment by khellang** [comment]
In addition, Octokit should validate the format and throw if it's invalid.

**Comment by shiftkey** [comment]
> In addition, Octokit should validate the format and throw if it's invalid.

Thinking out loud here, the scenario we had in #879 was that this was an invalid ref `mikeparker:prcreator-testing/branch-to-merge`. Refs can be namespaced, e.g: `shiftkey/my-cool-feature` - and as edge-case as it might be, `prcreator-testing/branch-to-merge` could also be a valid ref. Without hitting the API, we can't verify it.

Perhaps a better error message here (it's pretty easy to test this against the real API) with a reference to the docs page for creating a PR to help diagnose?

I don't want to make this area too clever, but I empathise with the lack of docs in general.

**Comment by mikeparker** [comment]
I think at minimum emphasising the format of the base and head refs in the docs is good enough. In particular, the base ref doesn't include the username, but the head ref does (I havent checked what happens if you specify the username in the base ref too, maybe it works?)

Am I right in saying that the GitHub API could return a more helpful error message here, if the branch doesn't exist, because its returning 3 confusing error messages simply because the caller is specifying an invalid branch? It says "base sha" and "head sha" empty or not specified, and "No commits between [the specified branches]". If this is the case then perhaps this is an issue for the main github API, but it would super awesome if Octokit could fix up the error message but perhaps "nice to have".
