### ISSUE TITLE
How to get the Repo from the Issue Object?

### ISSUE THREAD

**Issue by naveensrinivasan** [octokit/octokit.net#882]
I would like to the get the Repo the issue belongs to get  the comments. How do I get Repo the issue belongs to? 

Here is an example of my code which gets all the Issue for the user
```
var result = await GitHub.Issue.GetAllForCurrent ();

```  
For each of these issues I want the comments on them. 

Thanks

**Comment by shiftkey** [comment]
> How do I get Repo the issue belongs to?

Unfortunately the [raw JSON](https://developer.github.com/v3/issues/#list-issues) doesn't contain anything related to the repository. I'd recommend parsing the `HtmlUrl` property on the issue (you *could* look at everything before `/issues` in the URL).

> For each of these issues I want the comments on them.

There's a `comments_url` property on the raw JSON which we're not surfacing. We should do that.

**Comment by shiftkey** [comment]
Opened https://github.com/octokit/octokit.net/issues/883 to address the missing property

**Comment by naveensrinivasan** [comment]
Thanks!
