### ISSUE TITLE
Setting up CI for the Xamarin projects

### ISSUE THREAD

**Issue by naveensrinivasan** [octokit/octokit.net#891]
By default the appveyor  builds don't run the xamarin projects build. These two recent PR https://github.com/octokit/octokit.net/pull/888 https://github.com/octokit/octokit.net/pull/889 could have been avoided if we had xamarin as part of the CI.  AppVeyor does have Xamarin msbuilds http://www.appveyor.com/docs/lang/xamarin. 

The requirement to run xamarin builds is license which IMO can be  requested for a open source project https://resources.xamarin.com/open-source-contributor.html

**Comment by Haacked** [comment]
Interesting. Want to help us do all that?

**Comment by naveensrinivasan** [comment]
Yes, I can do PR for this.

**Comment by naveensrinivasan** [comment]
Here is the response from Xamarin. The author of the project would have to apply for the license. 


>Hi Naveen,
>
>Thanks for letting me know!
>
>The author of the project needs to apply for the subscription and if it is a group open source project, 
>all will need to apply separately with a note of who else is working on the project.
>
>Best,
>Andrey

@Haacked Could you apply for this? https://resources.xamarin.com/open-source-contributor.html

**Comment by Haacked** [comment]
Done! I'll let you know when I get it approved.

**Comment by Haacked** [comment]
@naveensrinivasan ok, I have the subscription, but not sure what I need to do next.

**Comment by naveensrinivasan** [comment]
Did you get the license for yourself ? If you have the email can you forward it I could apply for the 
>all will need to apply separately with a note of who else is working on the project. 

and then use that specific license to supply in build server

**Comment by shiftkey** [comment]
I think this is not something worth tackling given we target .NET Standard 1.1 these days.

Please open a new issue if this is something you still care about.
