### ISSUE TITLE
Retrieving contributors for an empty repo throws an ANE

### ISSUE THREAD

**Issue by adamralph** [octokit/octokit.net#893]
In this case the response of the body is `null` and the call to https://github.com/octokit/octokit.net/blob/c6c332f5de4038be275d7e99649b8eb6ec668cf2/Octokit/Http/ApiConnection.cs#L467-L469 and then https://github.com/octokit/octokit.net/blob/c6c332f5de4038be275d7e99649b8eb6ec668cf2/Octokit/Http/ReadOnlyPagedCollection.cs#L13-L14 passes that `null` into the `ReadOnlyCollection` constructor.

**Comment by Haacked** [comment]
Doh! Seems like low hanging fruit. Interested in sending a PR?

**Comment by naveensrinivasan** [comment]
I will send a PR on this.

**Comment by Haacked** [comment]
I think @adamralph was already planning to.

**Comment by naveensrinivasan** [comment]
Sure. Thanks!
