### ISSUE TITLE
Locked and Locking Issues

### ISSUE THREAD

**Issue by Eonasdan** [octokit/octokit.net#896]
Unless I missed it, there doesn't seem to be a way to filter out locked issue nor does there seem to be a way to lock an issue.

Actually, I can't find anything in the API the suggests I can do this.

Please let me know if I over looked something.

**Comment by Haacked** [comment]
Hmm, I don't see it either. Perhaps @pengwynn would know.

**Comment by Eonasdan** [comment]
slightly related https://github.com/twbs/no-carrier/issues/3

**Comment by pengwynn** [comment]
@Haacked: Locking isn't currently available via the API. I've referenced this issue on the internal feature request for that one.

**Comment by Eonasdan** [comment]
![image](https://cloud.githubusercontent.com/assets/1006516/11187944/8b8b6820-8c56-11e5-8993-e091464aaad3.png)

**Comment by shiftkey** [comment]
As this is related to the GitHub product itself, rather than the API clients, I'm going to close it out.

For reference, the API is now returning `locked` properties for issues in Octokit (but not Pull Requests, so https://github.com/octokit/octokit.net/issues/1084 is that task). When the other stuff becomes available, we'll expose it in Octokit.

**Comment by Haacked** [comment]
Guess what?! There's [a way to [lock issues via the API now](https://developer.github.com/changes/2016-02-11-issue-locking-api/)! It's in preview mode, but if someone wants to tackle it, that would be great!

**Comment by shiftkey** [comment]
The relevant docs:

 - https://developer.github.com/v3/issues/#lock-an-issue
 - https://developer.github.com/v3/issues/#unlock-an-issue

**Comment by cvrebert** [comment]
Finally! :smile:

**Comment by prayankmathur** [comment]
@shiftkey 
@cvrebert 
I have added the function in the **IssueClients** class.
Could you please tell me what all unit and integration tests to add ?

**Comment by shiftkey** [comment]
@prayankmathur which branch is this for? If you could open a pull request it will run against our CI infrastructure - and let us see what the failures might be about...

**Comment by dampir** [comment]
@shiftkey I think this could be closed for now :+1:
