### ISSUE TITLE
Polish up the NuGet Package Publishing or Deployment Story

### ISSUE THREAD

**Issue by haacked** [octokit/octokit.net#899]
Our guidelines for publishing packages are outdated. Also, when you try and do it manually, we run into [this bug](https://github.com/ctaggart/SourceLink/issues/58) which tells you to clone Octokit.net like so: `git clone https://github.com/octokit/octokit.net.git -c core.autocrlf=input`.

We should figure out an approach that is more automated and actually works. :smile:

**Comment by shiftkey** [comment]
![agree](https://cloud.githubusercontent.com/assets/359239/10264661/17a49d2e-6a13-11e5-9e78-c754e076027a.gif)

xref https://github.com/octokit/octokit.net/issues/756

**Comment by shiftkey** [comment]
I don't mind putting together a proper packaging script ([these conventions](http://githubengineering.com/scripts-to-rule-them-all/) seem nice) - it'll just need some checks before to ensure everything is setup correctly.

**Comment by ghuntley** [comment]
![](https://cloud.githubusercontent.com/assets/359239/10264661/17a49d2e-6a13-11e5-9e78-c754e076027a.gif)

Indeed, I was in the middle of stealing your fsharp `build.fsx|build.cmd|build.sh` for ReactiveUI and ran into the same SourceLink error.

`script/*` seems like a good convention, will check out what you have done up in #924 for inspiration.
