### ISSUE TITLE
Investigate and fix the `StopsMakingNewRequestsWhenTakeIsFulfilled` test

### ISSUE THREAD

**Issue by haacked** [octokit/octokit.net#904]
The test [StopsMakingNewRequestsWhenTakeIsFulfilled](https://github.com/octokit/octokit.net/blob/e6e7c3d393160fabe4cc48dd6c410db2a19b7e72/Octokit.Tests/Reactive/ObservableRepositoriesClientTests.cs#L93-L158) fails consistently now. We need to figure out why and fix the code or the test.

**Comment by alfhenrik** [comment]
I'm unable to replicate this error locally, even running the same commands that AppVeyor runs (i.e. the git commands to get the code) yields a successful unit test run :cry: Could it perhaps be something environmental to AppVeyor...

**Comment by naveensrinivasan** [comment]
Even I couldn't replicate it locally.

**Comment by alfhenrik** [comment]
I'm installing VS2013 on my Server 2012 R2 dev machine and will test it on there as well

**Comment by alfhenrik** [comment]
Everything works fine on my 2012R2 dev machine as well...so I'm quite stump as to why it would be failing on AppVeyor...

**Comment by chenjiaming93** [comment]
it only appears on AppVeyor... Even though I am committing the same content, I cannot duplicate it
