### ISSUE TITLE
Deploying new releases - Eating your own dog food

### ISSUE THREAD

**Issue by naveensrinivasan** [octokit/octokit.net#905]
The octokit deployments of new releases are based on this document https://github.com/octokit/octokit.net/blob/master/DEPLOYMENT.md which  does not use octokit to deploy to github.

Why can't this be more automated like [Paket's](https://github.com/fsprojects/Paket/) `ReleaseGitHub` and `PublishNuGet`? https://github.com/fsprojects/Paket/blob/master/build.fsx .Paket uses octokit to release to github. Why not use octokit to release to github?

**Comment by Haacked** [comment]
> Why not use octokit to release to github?

We just haven't gotten around to it. But if you want to set that up, I'd be eternally grateful.

**Comment by naveensrinivasan** [comment]
I will take this one! Thanks
