### ISSUE TITLE
Assignee is missing from PullRequest class

### ISSUE THREAD

**Issue by Eilon** [octokit/octokit.net#910]
This type: https://github.com/octokit/octokit.net/blob/master/Octokit/Models/Response/PullRequest.cs

The [GitHub API response for PRs](https://developer.github.com/v3/pulls/#response) returns `user` (who submitted the PR) and `assignee` (who the PR is assigned to).

Seems like it just involves adding an `Assignee` property and ctor param to the `PullRequest` class?

**Comment by Eilon** [comment]
If that's all it takes I can send a PR.

**Comment by Eilon** [comment]
@Haacked because reasons.

**Comment by alfhenrik** [comment]
Yes, it should just be as easy as adding that property to the class and a ctor parameter.

**Comment by Haacked** [comment]
@eilon do eeet!

**Comment by Eilon** [comment]
Yessir!

**Comment by Eilon** [comment]
Sweet, I didn't even have to write any code :smile:
