### ISSUE TITLE
Add helper class for creating web hooks

### ISSUE THREAD

**Issue by Haacked** [octokit/octokit.net#914]
The [`NewRepositoryHook`](https://github.com/octokit/octokit.net/blob/master/Octokit/Models/Request/NewRepositoryHook.cs) class is used to create new repository hooks. This class takes in a dictionary of config values.

According to the [documentation for creating repository hooks](https://developer.github.com/v3/repos/hooks/#create-a-hook), if you want to create web hooks, there's some required and optional values that should be in that dictionary. We should provide a strongly typed class specifically for web hooks.

My thought is to add `NewRepositoryWebHook` that derives from `NewRepositoryHook` and adds these properties. It then merges those properties with the supplied `config` dictionary.

**Comment by alfhenrik** [comment]
I'll take this one :)
