### ISSUE TITLE
Use interfaces for response models

### ISSUE THREAD

**Issue by haacked** [octokit/octokit.net#920]
So you're going to laugh because the idea of using interfaces was proposed before but I rejected it because the response models were simple value types with no behavior and it seemed overkill.

Well, I've had a 180 and let me tell you the story of my woe.

The other day I decided to shave the yak of documenting _all the code_ and in doing so, I found a lot of discrepancies with the response models and what was actually returned by the API.

It's not really the fault of the Octokit contributors. To be fair, GitHub.com is a long running Ruby on Rails app and as such, it's response types tend to be dynamic, meet many scenarios, and even collect the occasional cruft.

We don't have comprehensive schema documentation and to really understand what the API returns, it requires reading through a lot of Ruby code that's not publicly accessible.

We tried modeling the response types with an inheritance model, but it just doesn't end up working out well. We get too many types. For example, when you request a repository, the `Organization` property on the back end is actually a `SimpleUser`, but some of the organization fields are omitted. Likewise, we also have organization types on the server.

So instead, what I'd like to do is have monolithic concrete `User`, `Organization` and `Repository` types that we use for responses that return such things, but use interfaces to scope the set of properties returned.

For example, if you call /user (to get the current authenticated user) there's more data returned than a user returned as the owner property of a repository. So in that case the client method will return something like `IUser` vs `IUserSimple`. That way, you still get the benefits of Intellisense etc to find out which properties are available in a response, and we keep things simple in the code and don't have to try and create and maintain a complex inheritance hierarchy that doesn't match the real world.

I'll have to think through how we handle the fact that the monolith may have nullable properties that should not be nullable on the interface. We'll figure something out.

Thoughts? Feedback? /cc @shiftkey @pengwynn

**Comment by pengwynn** [comment]
> I'll have to think through how we handle the fact that the monolith may have nullable properties that should not be nullable on the interface. We'll figure something out.

Are you talking nullable or present? Is there more or less pain for a field to be present and null vs absent altogether?

Either way, the :imp: might be in the details, but I think interfaces could be a pragmatic approach.

**Comment by Haacked** [comment]
> Are you talking nullable or present? Is there more or less pain for a field to be present and null vs absent altogether?

They're more or less equivalent in our case.

The situation I'm thinking about is there are cases where the concrete type might have an int property that can be missing or null, in which case it needs to be a `Nullable<int>` property. But there may be other API endpoints where that same property cannot be null and I'd like to have the property be an `int` that cannot be null. I might run into problems implementing that interface with the same concrete type.

**Comment by khellang** [comment]
> I might run into problems implementing that interface with the same concrete type.

Explicit implementations might be your friend here :smile:
