### ISSUE TITLE
Created/updated binary files are not recognized as binary data

### ISSUE THREAD

**Issue by aaron-comyn** [octokit/octokit.net#925]
Unless I'm missing something obvious: it seems that binary files uploaded through CreateFile/UpdateFile methods in Octokit.net cannot be flagged as binary data and are interpreted server-side as text.

Judging from other Octokit libraries there *may* be an encoding option not being passed through the API when creating and updating new files (isBase64 or isBinary, [more info](https://github.com/philschatz/octokit.js/issues/44)).  

The low-level API handles this properly (with TreeType.Blob and EncodingType.Base64), but it takes a lot more Git knowhow and 6 calls to the API instead of 1 :)
 
----

Examples to show the difference:  

[A file checked in through repository](https://github.com/hrrno/metadata/blob/master/test/binary_reference.xls) vs [a file added through the API](https://github.com/hrrno/metadata/blob/master/test/test_creation_334.xls)
The RepositoryContent returned through Octokit.net for both objects shows no appreciable difference.

Calling code (F#):

        let update = new UpdateFileRequest("[Automatic] update", 
                                           encodedFileContents, 
                                           targetFileInfo.Sha, 
                                           Committer = new SignatureResponse(name, email, date)

        let updatedContent =  
            async { return repo.UpdateFile(repoOwner, repoName, filePath, update).Result } 
            |> Async.RunSynchronously

**Comment by chenjiaming93** [comment]
Cannot find a parameter in Created/Updated API that can clarify the type of the file.

**Comment by aaron-comyn** [comment]
The Github API documentation makes no reference to any kind of binary parameter on CreateFile or UpdateFile, but it looks like they accept an 'encoding' parameter.  Octokit.net seems to be using the default of UTF-8 even for base64 text - supposedly the same issue can be resolved in Octokit.js by properly set the encoding to 'base64'.

[Same issue](https://github.com/philschatz/octokit.js/issues/69) with a [pull request showing a 'working' solution](https://github.com/philschatz/octokit.js/pull/72/files).  Relevant update:

```javascript
               content =
                content: content,
                encoding: 'base64'
```

----

From poking around the code it looks like adding a new property to the CreateFileRequest object (CreateFileRequest.cs), that mapped to the appropriate encoding parameter (or a prop called "IsBinary" that would serialize properly), would do the trick. That parameter would propagate all the way through to the API through the ApiConnection, it's just a matter of finding the correct structure for the encoding values :)

**Comment by naveensrinivasan** [comment]
When the API dose not  officially support it then why build a hack around it?

**Comment by aaron-comyn** [comment]
The API does not list the "encoding" parameter in its Repository Content docs, but it returns an encoding, accepts an encoding, uses a specific 'base64' encoding parameter elsewhere for binary operations and therefore requires a binary encoding for consistency with the rest of the API...  

All other file operations seem to work as expected with binary files except CreateFile and UpdateFile.

As a matter of definition: arguably this is a pure API inconsistency, or a documentation oversight... Perhaps updating the docs would be better, either making the encoding parameter official, or clarifying that the RepositoryContent API doesn't handle binary data.  No hacks needed ;)

---

Feel free to close the issue - I opened it primarily to provide a path for any other people stuck on the API inconsistency.  Dropping into the BLOB DB for a simple file upload requires some GIT knowhow and isn't obvious from the documentation.

**Comment by shiftkey** [comment]
@aaron-comyn oops, totally missed that last message. 

Thanks for the details, and there's actually some things we do under the hood to take the control away from you here - the `Content` property is a .NET string and we decorate it with a `[SerializeAsBase64]` attribute so that the user doesn't need to remember to do that. That's clearly not what you're looking for here, and I'm grateful for that example using the Git Data API.

I've opened https://github.com/octokit/octokit.net/issues/1143 to track this feature as a parity item.

**Comment by ariyuan** [comment]
meet similar issue and fixed with the following c# code, the same idea as the code provided by @aaron-comyn 

`

        // read file stream
        using var memoryStream = new MemoryStream();
        await fileStream.CopyToAsync(memoryStream);
        var fileBytes = memoryStream.ToArray();
        var base64Content = Convert.ToBase64String(fileBytes);

        // create Blob
        var newBlob = new NewBlob
        {
            Encoding = EncodingType.Base64,
            Content = base64Content
        };
        var blob = await github.Git.Blob.Create(_owner, _repo, newBlob);

        // get branch reference
        var reference = await github.Git.Reference.Get(_owner, _repo, $"heads/{branchName}");
        var latestCommit = await github.Git.Commit.Get(_owner, _repo, reference.Object.Sha);

        // create Tree
        var newTree = new NewTree { BaseTree = latestCommit.Tree.Sha };
        newTree.Tree.Add(new NewTreeItem
        {
            Path = pathToTheFile,
            Mode = "100644", // regular file, binary
            Type = TreeType.Blob,
            Sha = blob.Sha
        });

        var createdTree = await github.Git.Tree.Create(_owner, _repo, newTree);

        // create Commit
        var newCommit = new NewCommit(_commitMessage, createdTree.Sha, new[] { latestCommit.Sha });
        var createdCommit = await github.Git.Commit.Create(_owner, _repo, newCommit);

        // update reference
        var updatedRef = new ReferenceUpdate(createdCommit.Sha);
        await github.Git.Reference.Update(_owner, _repo, $"heads/{_branch}", updatedRef);

        return new GitHubFileUploadResult
        {
            Success = true,
            CommitUrl = createdCommit.Url
        };



`
