### ISSUE TITLE
Creating a cross-repository pull request returns "NotFoundException"

### ISSUE THREAD

**Issue by RonnChyran** [octokit/octokit.net#932]
I'm trying to create a pull request using Octokit.net like so.
            
```c#
    string branchName = "MyBranch";
    var pr = new NewPullRequest("Some Pull Request", $"{user.Login}:{branchName}", "master")       
    await gh.PullRequest.Create("SnowflakePowered-Packages", "snowball-packages", pr);
```

And I get the following exception
```c#
    Octokit.NotFoundException: Not Found
```
However, the pull request works if I'm working on my fork
```c#
    string branchName = "MyBranch";
    var pr = new NewPullRequest("Some Pull Request", $"{user.Login}:{branchName}", "master")       
    await gh.PullRequest.Create(user.Login, "snowball-packages", pr);
```
I can't get it to work at all to create the PR on the upstream repository. I'm trying to create the PR on https://github.com/SnowflakePowered-Packages/snowball-packages, but it's not working.

**Comment by Haacked** [comment]
Could you use Fiddler2 to post the request and response you get? Be sure to remove the line of the request header that contains your authorization token. It's the line that starts with "Authorization:".

**Comment by RonnChyran** [comment]
Sure, here is the request

```
POST https://api.github.com/repos/SnowflakePowered-Packages/snowball-packages/pulls HTTP/1.1
Accept: application/vnd.github.quicksilver-preview+json; charset=utf-8, application/vnd.github.v3+json; charset=utf-8
User-Agent: snowball (Win32NT 6.2.9200; amd64; en-CA; Octokit 0.16.0)
Authorization: Token [Redacted]
Content-Type: application/x-www-form-urlencoded; charset=utf-8
Host: api.github.com
Content-Length: 134
Expect: 100-continue
Accept-Encoding: gzip, deflate

{"title":"Add Plugin StandardAjax v0.1.2","base":"master","head":"RonnChyran:StandardAjaxv0.1.2-df225a37-acb9-4e02-acc6-a517a88956d2"}
```

And here is the response

```
HTTP/1.1 404 Not Found
Server: GitHub.com
Date: Sat, 10 Oct 2015 01:02:21 GMT
Content-Type: application/json; charset=utf-8
Status: 404 Not Found
X-RateLimit-Limit: 5000
X-RateLimit-Remaining: 4964
X-RateLimit-Reset: 1444439859
X-OAuth-Scopes: public_repo, repo:status, repo, user, repo_deployment
X-Accepted-OAuth-Scopes: 
X-OAuth-Client-Id: [Redacted]
X-GitHub-Media-Type: github.v3; param=quicksilver-preview; format=json
X-XSS-Protection: 1; mode=block
X-Frame-Options: deny
Content-Security-Policy: default-src 'none'
Access-Control-Allow-Credentials: true
Access-Control-Expose-Headers: ETag, Link, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval
Access-Control-Allow-Origin: *
X-GitHub-Request-Id: D83A5B09:161C9:31899DC:5618639D
Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
X-Content-Type-Options: nosniff
Content-Length: 106

{"message":"Not Found","documentation_url":"https://developer.github.com/v3/pulls/#create-a-pull-request"}
```
Source code for what I'm trying to do is [here](https://github.com/RonnChyran/snowflake/blob/4baaacd0b223965c59a2299aada8005862a2d9f7/Snowflake.Packaging/Publishing/PublishActions.cs#L116)

**Comment by elbaloo** [comment]
Could it be that StandardAjaxv0.1.2-df225a37-acb9-4e02-acc6-a517a88956d2 is
private? If so, does the token have that scope?

--
vrce

**Comment by elbaloo** [comment]
Disregard my previous comment. That's a branch not a repo and scopes are in the request anyway... It's late, I'm going to bed xD

**Comment by RonnChyran** [comment]
Anyone have an idea of what's going on?

**Comment by Haacked** [comment]
@pengwynn do you have any ideas on this?

**Comment by shiftkey** [comment]
> Could it be that StandardAjaxv0.1.2-df225a37-acb9-4e02-acc6-a517a88956d2 is private? If so, does the token have that scope?

I can see this branch on the repo, so I don't believe it's that.

Thanks for the repro, and sorry for the delay. I'll have a look at recreating the issue on my end.

**Comment by shiftkey** [comment]
So I took the same parameters from above and ran the same steps from the repro:

```
POST https://api.github.com/repos/SnowflakePowered-Packages/snowball-packages/pulls HTTP/1.1
Accept: application/vnd.github.quicksilver-preview+json; charset=utf-8, application/vnd.github.v3+json; charset=utf-8
User-Agent: Octokit-Test-Bench (Win32NT 6.2.9200; amd64; en-US; Octokit 0.16.0)
Authorization: Token [redacted]
Content-Type: application/x-www-form-urlencoded; charset=utf-8
Host: api.github.com
Content-Length: 123
Expect: 100-continue
Accept-Encoding: gzip, deflate
Connection: Keep-Alive

{"title":"This is just a test","base":"master","head":"RonnChyran:StandardAjaxv0.1.2-df225a37-acb9-4e02-acc6-a517a88956d2"}
```

And the PR was created successfully - https://github.com/SnowflakePowered-Packages/snowball-packages/pull/2:

```
HTTP/1.1 201 Created
Server: GitHub.com
Date: Mon, 12 Oct 2015 10:05:26 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 16484
Status: 201 Created
X-RateLimit-Limit: 5000
X-RateLimit-Remaining: 4999
X-RateLimit-Reset: 1444647926
Cache-Control: private, max-age=60, s-maxage=60
ETag: "bc7e3d03794f3beeb32704dda5bf1cd0"
X-OAuth-Scopes: gist, repo, user
X-Accepted-OAuth-Scopes: 
Location: https://api.github.com/repos/SnowflakePowered-Packages/snowball-packages/pulls/2
Vary: Accept, Authorization, Cookie, X-GitHub-OTP
X-GitHub-Media-Type: github.v3; param=quicksilver-preview; format=json
X-XSS-Protection: 1; mode=block
X-Frame-Options: deny
Content-Security-Policy: default-src 'none'
Access-Control-Allow-Credentials: true
Access-Control-Expose-Headers: ETag, Link, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval
Access-Control-Allow-Origin: *
X-GitHub-Request-Id: 5883D9F2:AB2E:592639E:561B85E5
Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
X-Content-Type-Options: nosniff
Vary: Accept-Encoding
X-Served-By: 593010132f82159af0ded24b4932e109

{
  "url":"https://api.github.com/repos/SnowflakePowered-Packages/snowball-packages/pulls/2",
  ...
}
```

So what I believe might be happening here is that the is published, but the delay between that occurring and creating the PR is too short (so the PR isn't created because it can't "find" the branch).

@RonnChyran if you were to run through the steps again, could you note the delay between creating the reference [here](https://github.com/RonnChyran/snowflake/blob/4baaacd0b223965c59a2299aada8005862a2d9f7/Snowflake.Packaging/Publishing/PublishActions.cs#L91) and then creating the pull request in Fiddler?

**Comment by pengwynn** [comment]
@RonnChyran @Haacked: Looks like this one is blocked by [third-party application restrictions][doc]. 

[doc]: https://help.github.com/articles/about-third-party-application-restrictions/

**Comment by RonnChyran** [comment]
@pengwynn I've disabled the restrictions on the target repository and it seems to [working now.](https://github.com/SnowflakePowered-Packages/snowball-packages/pull/3)

Thanks for all the help, may I suggest adding a note about that to the API docs?

**Comment by pengwynn** [comment]
> may I suggest adding a note about that to the API docs?

Thanks for suggesting, @RonnChyran. I've added that scenario to [the troubleshooting guide][guide].

[guide]: https://developer.github.com/v3/troubleshooting/#why-am-i-getting-a-404-error-on-a-repository-that-exists
