### ISSUE TITLE
Unit tests that interact with issues on a repository are failing as issues are disabled

### ISSUE THREAD

**Issue by alfhenrik** [octokit/octokit.net#941]
Example: `IssuesEventsClientTests.CanListEventInfoForAnIssue` throws `Octokit.ApiException : Issues are disabled for this repo`

**Comment by alfhenrik** [comment]
This guy https://github.com/octokit/octokit.net/blob/master/Octokit/Models/Request/NewRepository.cs#L43 should be `bool?` as it's an optional parameter...

**Comment by shiftkey** [comment]
@alfhenrik yeah, that should be a `bool?`.

I'll leave it up to you, but if I spot it during my next test run I'll address it then.
