### ISSUE TITLE
Editor config

### ISSUE THREAD

**Issue by naveensrinivasan** [octokit/octokit.net#946]
Why not have http://editorconfig.org/ maintain consistent coding styles. I noticed OSS projects have started embracing it. Any thoughts?

**Comment by shiftkey** [comment]
I think I had problems with the VS extension for this when I last looked at it, but I'm not opposed to taking in something if others would like it.

I'm also leaning towards using a code formatter ala golang (see #807) to automate this.

**Comment by naveensrinivasan** [comment]
Code formatter :+1:
