### ISSUE TITLE
Add AppVeyor builds to its NuGet feed

### ISSUE THREAD

**Issue by naveensrinivasan** [octokit/octokit.net#953]
How about adding Nuget Feeds for the AppVeyor builds similar to this  https://github.com/nunit/nunit/pull/932? 

This would make

>  appveyour nuget packages are really good wayt to try latest master or a specific pr without the need to build from source. Is like a nightly release, only each commit.

**Comment by shiftkey** [comment]
Making pre-release builds of `master` available is something I'd like to do, but there's various other infrastructure needs that I need to address first (VS2015, scriptable releases, x-plat).

I'll leave this open to remind me.

**Comment by naveensrinivasan** [comment]
Do you want to do it just for `master`?

**Comment by shiftkey** [comment]
I think so - once we've merged a PR, it's an indicator that `master` should be in a usable state.

**Comment by shiftkey** [comment]
We're already creating these packages as part of the CI build, but there's a few enhancements we need before we can complete this:

 - implement versioning scheme for pre-release packages - see what [libgit2sharp](https://github.com/libgit2/libgit2sharp/blob/master/appveyor.yml#L33-L40) has done here for example
 - [detect whether build should be packaged](https://github.com/libgit2/libgit2sharp/blob/master/appveyor.yml#L61-L63) and [do this after the build is completed](https://github.com/libgit2/libgit2sharp/blob/master/appveyor.yml#L129-L146).

We've already added notes about the pre-release feed in the README, not sure what else we've missed.

**Comment by shiftkey** [comment]
Opening this up as up-for-grabs for someone who wants to dive into Appveyor customizations...

**Comment by eriawan** [comment]
@shiftkey 
> I think so - once we've merged a PR, it's an indicator that `master` should be in a usable state.

Are we going to have a specific daily LKG as well?

**Comment by shiftkey** [comment]
@eriawan I'm not sure what "daily LKG" stands for

**Comment by eriawan** [comment]
I mean a daily build but it can be considered as build that meets the passing unit tests and integration tests (if any), hence it's called Last Known Good build.

**Comment by ryangribble** [comment]
I do want to get master merges automatically releasing pre release to nuget (but they are currently available on the appveyor feed so if people really want to use them they can). 

In terms of running nightly integration tests, that's a cool idea but we actually have so many integration tests they can't be easily run in one go due to github API rate limits... There are also some tests that seem sensitive to timings and can fail one time but succeed on a rerun...  

some work/thought would be needed to figure out a solution to these issues before we can run integration tests automatically

**Comment by shiftkey** [comment]
I'm going to close this out as we are using the AppVeyor feed to publish pre-release packages https://github.com/octokit/octokit.net#beta-packages, and we have #118 which is tracking the question about running integration tests against the GitHub API.
