### ISSUE TITLE
Creating file on a specific branch.

### ISSUE THREAD

**Issue by ostruk** [octokit/octokit.net#958]
In the [github api](https://developer.github.com/v3/repos/contents/#create-a-file) I can see that I should be able to create files on non-master branches by specifying an optional "branch" parameter.

Is there a way to do this in octokit.net?

Thanks!

**Comment by chenjiaming93** [comment]
I'm gonna do that if possible.

**Comment by shiftkey** [comment]
This work is still outstanding.

For reference, here's the documentation: https://developer.github.com/v3/repos/contents/#create-a-file

I think extending `CreateFileRequest` to provide this new parameter is the best way to go about it.

I'd also have a look at `UpdateFileRequest` (and the docs https://developer.github.com/v3/repos/contents/#update-a-file) as the changes should be similar for both action.

**Comment by M-Zuber** [comment]
The property already exists [here](https://github.com/octokit/octokit.net/blob/master/Octokit%2FModels%2FRequest%2FCreateFileRequest.cs#L32)
Do you want a PR to add it to the constructor?

**Comment by shiftkey** [comment]
@M-Zuber I think a new `ctor` taking the branch name is good enough here

**Comment by shiftkey** [comment]
@M-Zuber also, thanks for noticing the base class before it was too late :grin:

**Comment by M-Zuber** [comment]
:grinning: 
I'll send a PR in the morning.

>I think a new ctor taking the branch name is good enough here

I assume in addition?
Every class in the inheritance chain should get such an overload added?
