### ISSUE TITLE
a doc to list api coverage?

### ISSUE THREAD

**Issue by chenjiaming93** [octokit/octokit.net#968]
recently I am reading through GitHub API references and trying to report unimplemented or incomplete APIs. Do we have a document to list API coverage in Octokit.net?

**Comment by shiftkey** [comment]
Literally just discussing this headache with @haacked. Contemplating scraping the website to get this list.

**Comment by shiftkey** [comment]
Nevermind, looks like @naveensrinivasan might have already cracked this:

https://twitter.com/snaveen/status/674384982803136513

![](https://pbs.twimg.com/media/CVvlkXxVAAEmtT3.png)

**Comment by naveensrinivasan** [comment]
https://gist.github.com/naveensrinivasan/58fa8eb57e61535f10db

**Comment by shiftkey** [comment]
@naveensrinivasan this is so good! I'm kinda buried in work-related stuff this week but I'll try and make time to look into this...

**Comment by naveensrinivasan** [comment]
Cool :+1:

**Comment by chenjiaming93** [comment]
awesome

**Comment by shiftkey** [comment]
Closing this out in favour of #1038 - will spin more work out from that.
