### ISSUE TITLE
Create a new authorization

### ISSUE THREAD

**Issue by dail8859** [octokit/octokit.net#969]
I'm needing to [create a new authorization](https://developer.github.com/v3/oauth_authorizations/#create-a-new-authorization) using basic authentication (without using the web flow) to create a token. I am not wanting to provide a client id and secret (read: can't provide). The closest thing I could find was [AuthorizationsClient.Create()](https://github.com/octokit/octokit.net/blob/master/Octokit/Clients/AuthorizationsClient.cs#L78) but it requires an id and string.

**Comment by Haacked** [comment]
I don't believe there's any way to do that. Why can't you provide the client id and secret?

**Comment by shiftkey** [comment]
Authorizations need an application id and secret, so that the user knows the context of why the token was created, and can revoke them at a later date.

**Comment by dail8859** [comment]
With everything I've read the id and secret need to be kept (not surprisingly) secret, but that's not possible if the code is open source. 

Reading the API docs and using curl it's quite easy to create a new authorization without an id or secret, and I was just wanting to be able to do that from the library.

**Comment by shiftkey** [comment]
> With everything I've read the id and secret need to be kept (not surprisingly) secret, but that's not possible if the code is open source.

Totally agree, but there's many ways to do this - for example, we use environment variables we manage the credentials for the integration test suite:

https://github.com/octokit/octokit.net/blob/master/Octokit.Tests.Integration/Helper.cs

**Comment by dail8859** [comment]
So...then anyone wanting to develop the code would have to create their own id and secret just to build it?

**Comment by shiftkey** [comment]
@dail8859 correct

**Comment by dail8859** [comment]
Hmm OK. Sounds like a pain. Thanks for the info though.

**Comment by dail8859** [comment]
Not sure why I closed this, would still like to see the aforementioned API implemented eventually :)

**Comment by Haacked** [comment]
> Not sure why I closed this, would still like to see the aforementioned API implemented eventually :)

Unfortunately, this is not the repository to log that request. I think an API that doesn't require those things and doesn't use the Web Flow would have major security concerns. You could email support@github.com to make such a request and provide more context on what goals you're trying to accomplish.

**Comment by dail8859** [comment]
Just to clarify, I'm not requesting any changes to the web API, only for the library to support that API call to create a personal access token. 

It's how the (previously supported) Github android app did it.

**Comment by Haacked** [comment]
> only for the library to support that API call to create a personal access token.

Hmm, I'm confused. Do you want the library to support the web flow? If the web API doesn't have an endpoint for us to create an authorization token without the client secret, how would we implement that in the client library.

**Comment by dail8859** [comment]
I apologize, it is very possible I'm just using some wrong terminology, so here's an example. 

Referencing [this](https://developer.github.com/v3/oauth_authorizations/#create-a-new-authorization) document, and using curl, you can see I can create a new personal access token. 

![test](https://cloud.githubusercontent.com/assets/3694843/11596125/42d9b3b4-9a81-11e5-859a-c53ac6000352.png)

**Comment by Haacked** [comment]
Ah! Got it. Want to submit a pull request implementing that change? I think we just need to add an overload to [`AuthorizationsClient`](https://github.com/octokit/octokit.net/blob/master/Octokit/Clients/AuthorizationsClient.cs).

**Comment by dail8859** [comment]
I'll have to pass :)

**Comment by alfhenrik** [comment]
I can take this if no one else has started it
