### ISSUE TITLE
Port DocPlagiarizer to Roslyn Analyzer so we can keep it around

### ISSUE THREAD

**Issue by naveensrinivasan** [octokit/octokit.net#971]
The DocPlagiarizer https://github.com/pmacn/DocPlagiarizer hasn't been maintained in the last 2 years. 

DocPlagiarizer fails to compile in XamarinStudio https://github.com/pmacn/DocPlagiarizer/issues/3 . 

Do we still need to have dependency on this?

**Comment by shiftkey** [comment]
Nope. I'd like to port these rules over to Roslyn analyzers and code fixes so they Just Work Wherever™.

I'd be fine with disabling those when running outside of VS, or just :fire: it as things are relatively stable right now - it was a great help in the early days as the codebase was being built up.

**Comment by naveensrinivasan** [comment]
OK Cool!  I like to use XS on mac to code and this is a bottle neck.

**Comment by shiftkey** [comment]
Now that #995 has been merged (removing this dependency) I'd like to see if we can bring it over as an analyzer - DocPlagiarizer was built using old versions of the Roslyn API, so I'm sure there's some way to port it.
