### ISSUE TITLE
Update Linqpad examples reference to local dll instead of nuget repo

### ISSUE THREAD

**Issue by naveensrinivasan** [octokit/octokit.net#983]
The linqpad references are pointing to nuget packages. It should be pointing to local dll to avoid build failures on release. https://github.com/octokit/octokit.net/releases/tag/v0.17.0

```
/tools/LINQPad\lprun.exe  -compileonly C:\projects\octokit-net\samples\linqpad-samples\6-create-repository.linq 
C:\projects\octokit-net\samples\linqpad-samples\6-create-repository.linq(62,17): error CS0246: The type or namespace name 'SignatureResponse' could not be found (are you missing a using directive or an assembly reference?)
Running build failed.
Error:
System.Exception: lprun.exe returned with a non-zero exit code for C:\projects\octokit-net\samples\linqpad-samples\6-create-repository.linq
   at Microsoft.FSharp.Core.Operators.FailWith[T](String message)
   at Microsoft.FSharp.Collections.SeqModule.Iterate[T](FSharpFunc`2 action, IEnumerable`1 source)
   at FSI_0001.Build.clo@145-25.Invoke(Unit _arg7) in C:\projects\octokit-net\build.fsx:line 148
   at Fake.TargetHelper.runSingleTarget(TargetTemplate`1 target) in C:\code\fake\src\app\FakeLib\TargetHelper.fs:line 483
```

**Comment by shiftkey** [comment]
Had a look at this and found it to be a larger yak than previously anticipated. Problems to address:

 - `lprun` doesn't have an easy way to install certain packages - it's probably using `%APPDATA%\NuGet\NuGet.Config`
 - `nuget.exe` has a way to manage these sources from the CLI so we could script it, but perhaps we're not allowed to do this on AppVeyor. I gather this will be the same thing for TravisCI.
 - if we can do this, we should clean up after it done
 - what about if the build fails - does FAKE have a good way to run cleanup scripts?

**Comment by naveensrinivasan** [comment]
I am going to fix the specific example to get it working and open another issue to address this for every check-in.

**Comment by shiftkey** [comment]
@naveensrinivasan :thumbsup:

**Comment by shiftkey** [comment]
A thought based on re-reading [the docs](https://www.linqpad.net/lprun.aspx) just now:

> LINQPad also supports the ref directive for referencing additional assemblies. You can specify the assembly either via its filename (including the directory if it's outside the .NET Framework) or its fully qualified name (if it's in the GAC): 

For the purposes of CI, could we reference local packages (and the just-compiled assemblies) - rather than fighting with all the conventions of NuGet packaging?

It could work like this:

 - take the file from version control and read it into memory: 

```
<Query Kind="Program">
  <NuGetReference>Octokit</NuGetReference>
  <NuGetReference>Octokit.Reactive</NuGetReference>
  <NuGetReference>Rx-Main</NuGetReference>
  <Namespace>Octokit</Namespace>
  <Namespace>System.Reactive.Linq</Namespace>
  <Namespace>System.Threading.Tasks</Namespace>
</Query>

async Task Main(string[] args)
{
    ...
```

 - replace the XML element with a new payload referencing local files:

```
// replaces "<NuGetReference>Octokit</NuGetReference>"
ref C:\users\shiftkey\code\Octokit\Octokit\bin\Release\net45\Octokit.dll;
// replaces "<NuGetReference>Octokit.Reactive</NuGetReference>"
ref C:\users\shiftkey\code\Octokit\Octokit.Reactive\bin\Release\net45\Octokit.Reactive.dll;
// or we could just reference all the Rx-Main packages here, because we're lazy
ref C:\users\shiftkey\code\Octokit\packages\System.Reactive.Linq\lib\net45\System.Reactive.Linq.dll;

// extract these namespaces from the XML
using Octokit;
using System.Reactive.Linq;
using System.Threading.Tasks;
	
async Task Main(string[] args)
{
    ...
```

 - pass this new file to `lprun.exe` and verify the current code works

**Comment by shiftkey** [comment]
Bumping this as the API changes we're doing here won't be caught by the `lprun` changes...

**Comment by naveensrinivasan** [comment]
@shiftkey  Will look into this next week.

**Comment by shiftkey** [comment]
I wanted to be sure our stuff was working fine before shipping this latest release, so I ended up writing the code I needed for the above steps into an integration test:

https://github.com/octokit/octokit.net/blob/b4476f173944c93a9500949a467c4bd91a474639/Octokit.Tests.Integration/SelfTests.cs

I've muted the previous `ValidateLINQPadSamples` with a note if someone wants to get involved with porting that back to F# so you can run it inline - it's not hard, just XML parsing and writing files and checking process output for messages :trollface:

**Comment by shiftkey** [comment]
As this issue has changed a lot since first reporting, I've opened a fresh issue #1081 with the remaining work to close this out.
